### ISSUE TITLE
where are the values from sjp.glmer(..., type = "fe.pc", ..., show.ci = TRUE)

### ISSUE THREAD

**Issue by julietyd** [strengejacke/sjPlot#130]
Hello, 
I really love the package, so flexible, and such pretty plots. 

I am using the sjp.glmer option to plot predicted probability values from a mixed effect model, and was very excited to see the option for confidence intervals around the fit line (e.g. myplot<-sjp.glmer(mymodel, type = "fe.pc", facet.grid = FALSE, show.ci = TRUE). 

I stepped through the code to try to see (1) how the predicted probability values are computed and (2) the upper and lower limits for the confidence interval, but can't step through fully to see it, I think because of the way the stat-smooth is embedded with the ggplotting functions. 

It would be useful to store or output the predicted values and the CI-upper and -lower values that ggplot uses - is this a feature that could be added? Or perhaps these values are output, and if so I am just having some trouble finding them in the existing output?

Thanks!!

**Comment by sjPlot** [comment]
I'm referring to the latest package version, **sjPlot 2.0** - the `fe.pc` type is now called `fe.slope` resp. `ri.slope` for random intercepts.

There's an explanation in the docs `?sjp.glmer` about each plot type:

**type = "fe.slope"**
> the predicted values are based on the fixed effects intercept's estimate and each specific fixed term's estimate. All other fixed effects are set to zero (i.e. ignored), which corresponds to `family(fit)$linkinv(eta = b0 + bi * xi)` (where `xi` is the estimate of fixed effects and b0 is the intercept of the fixed effects; the inverse link-function is used). This plot type may give similar results as `type = "pred"`, however, `type = "fe.slope"` does not adjust for other predictors.

The sub-routine responsible for the plot is [here](https://github.com/sjPlot/devel/blob/master/R/sjPlotLinreg.R#L588). The function - as every plotting function in **sjPlot** - returns the ggplot-object and the data frame used for plotting, so you can build the plot by yourself. You can access the data like this:

```
dummy <- sjp.glmer(fit, type = "fe.slope")
# for multiple plots, we have multiple data frames
dummy$data.list
# for single plot, just one
dummy$data
```

**Comment by sjPlot** [comment]
I have found [this approach](http://stackoverflow.com/questions/9789871/method-to-extract-stat-smooth-line-fit), however, it does not work inside sjp-functions. Maybe I can find a way to access the data produced by `geom_smooth()`.

**Comment by CJustice77** [comment]
Hi there. I am also interested in extracting the confidence intervals from the sjp.glmer object I created, but it is not stored in the $data component of the sjp object. Did you have any luck finding a way to access the data produced by geom_smooth()?

**Comment by strengejacke** [comment]
[ggeffects](https://github.com/strengejacke/ggeffects) will be used in the forthcoming update to compute marginal effects. The ggeffects-package returns a data frame with predicted values and CI, also for merMod-models. I suggest using that package, and soon this will be available in sjPlot as well. See also [this blog-post](https://strengejacke.wordpress.com/2017/08/27/marginal-effects-for-negative-binomial-mixed-effects-models-glmer-nb-and-glmmtmb-rstats/).
