### ISSUE TITLE
Treat numerical predictor as ordinal

### ISSUE THREAD

**Issue by JMJofficial** [strengejacke/sjPlot#138]
Is there a way to force the sjp.glmer(..., type = "pred",...) function to treat a numerical predictor in the model as an (ordinal) predictor with just a few discrete levels? The problem is that I've self-contrast coded my predictors, rather than inputting them into the mode as factors. As things stand I'm only able to get a graph continuously spanning the whole range of my 'block' predictor (-1.5 to 1.5), whereas what I really want is something like a bar chart with the four levels of the predictor (-1.5, -0.5, 0.5, 1.5) as separate bars, given that the interpolations between them aren't really meaningful.

Many thanks!

**Comment by strengejacke** [comment]
One solution might be using the [ggeffects-package](https://cran.r-project.org/package=ggeffects), and build your own ggplot based on the returned tidy data frame. Else, you have to coerce your variable to factor.
