### ISSUE TITLE
view_df weight.by empty category problem

### ISSUE THREAD

**Issue by piotrbekas** [strengejacke/sjPlot#143]
Dear Dev,

I got data taken from .sav with sjmisc::read_spss (love that!). 
In view_df() I found, that if weighted data has variable with empty categories, the nonweighted % shows 0%, but the weighted % has offset so it becomes (in term of lines of summary) the first category which has n=0.

Examples:
A.) 
I got 9 values labes, 2 of them are empty (the first and last are n = 0). So when nonweighted % shows 0.00 on first category, weighted % shows at the first row value for the second category (which is not empty). And third weighted category becomes second, and so on (2 -> 1, 3 -> 2, 4 -> 3, ...).

B.)
I got variable with 5 value labels, but there's only 1 with n > 0. Unweighted % shows zeros on empty ones, but on weighted % shows only one value (which is 100) and doesn't show zeros on empty categories (but 100 is at the first line, where should be zero from empty category).

Best regards,
Peter

**Comment by sjPlot** [comment]
Do you have any reproducible data/example?

**Comment by strengejacke** [comment]
_bump_
