### ISSUE TITLE
sjt.lm hide Observations

### ISSUE THREAD

**Issue by DanielRandles** [strengejacke/sjPlot#145]
Currently show.obs = FALSE is not available. There are cases where you would want to hide this column, e.g. if using weighted summarized data the reported N will be much lower than the actual N.

**Comment by kjklauder** [comment]
+1 This would be handy.

**Comment by strengejacke** [comment]
No, you can't set the line height for the summary part. But the generic `tab_model()` is under intensive development, I want to submit the update soon. Then you can easily hide intercept or specific parts of the summary.
