### ISSUE TITLE
afex, lsmeans, phia- anova table support

### ISSUE THREAD

**Issue by b1azk0** [strengejacke/sjPlot#156]
Hi,
first of all I'm not sure if this is the correct place to ask this (if not, let me know, and i'll delete this question), secondly please note i'm an R/Coding in general newbie.

Is there any chance sjPlot could support results from the afex packadge (along with lsmeans and testInteractions (from phia)) for a smoother table genaration for repeated measure data handled in Anovas?
I'm testing multiple 3way interactions (within and between subjects) and been desperatly looking for a tool that would easly summarize data but with respect to simple effects and means as well.

Best regards

**Comment by sjPlot** [comment]
Do you have a reproducible example, for example a fitted model, or a plot using a `plot()`-function?

**Comment by b1azk0** [comment]
Hello Daniel,
I hope that this example can clarify what I was looking for.
I almost sure there is a simpler way but i'm no coder and a newbie R user coming from SPSS.

Code from below is also here https://github.com/b1azk0/reprod.examples/blob/master/sjPlot.R

```
#Libraries
library(afex); library(phia)

#Generate data 
set.seed(111)
Nj     <- 10
P      <- 2
Q      <- 3
R      <- 2
DV_t11 <- rnorm(P*Nj,  8, 2)
DV_t21 <- rnorm(P*Nj, 13, 2)
DV_t31 <- rnorm(P*Nj, 13, 2)
DV_t12 <- rnorm(P*Nj, 10, 2)
DV_t22 <- rnorm(P*Nj, 15, 2)
DV_t32 <- rnorm(P*Nj, 15, 2)
df <- data.frame(id=factor(rep(1:(P*Nj), times=Q*R)),
                         IVbtw=factor(rep(LETTERS[1:P], times=Q*R*Nj)),
                         IVwth1=factor(rep(1:Q, each=P*R*Nj)),
                         IVwth2=factor(rep(rep(1:R, each=P*Nj), times=Q)),
                         DV=c(DV_t11, DV_t12, DV_t21, DV_t22, DV_t31, DV_t32))

#1. Omnibus mixed anova with afex
anovaSJTable<- aov_ez("id", "DV", df, within = c("IVwth1", "IVwth2")
       , between = "IVbtw", anova_table=list(correction="none", es="pes"))

#Results passed do sjt
anovaSJTable

#2. Simple effects means and tests with lsmeans
#compute and save tests and means for every effect of interest
btw<- lsmeans(anovaSJTable, ~IVbtw)
wth1<- lsmeans(anovaSJTable, ~IVwth1)
wth1.wth2<- lsmeans(anovaSJTable, ~IVwth1 | IVwth2)
btw.wth1.wth2<- lsmeans(anovaSJTable, ~IVbtw |IVwth1 | IVwth2)

#Means passed to sjt
btw.wth1.wth2

#Contrast results passed to sjt
pairs(wth1.wth2)

#3. Use testInteractions from "phia" to test simple effects

testInteractions(anovaSJTable$lm, 
                 fixed=c("IVwth1", "IVwth2"), 
                 across="IVbtw", 
                 adjustment = "holm", 
                 idata=anovaSJTable$Anova$idata)

testInteractions(anovaSJTable$lm, 
                 fixed="IVwth1", 
                 across="IVwth2", 
                 adjustment = "holm", 
                 idata=anovaSJTable$Anova$idata)

#4. Join results in one table

wth1.wth2 #means for 2x2 interaction
testInteractions(anovaSJTable$lm, 
                 fixed="IVwth2", 
                 across="IVwth1", 
                 adjustment = "holm", 
                 idata=anovaSJTable$Anova$idata) #F and p values for simple effects

```
Thank you for your interest.
Best regards

**Comment by b1azk0** [comment]
Hello,
is there any chance for anova's result support in sjTables or should I close this issue?
best regards
blazej

**Comment by sjPlot** [comment]
No, no need to close this issue. I'll investigate open issues later when I find some time to work on it.

**Comment by b1azk0** [comment]
Thank you.

**Comment by strengejacke** [comment]
Closing in favor of https://github.com/easystats/parameters/issues/247
