### ISSUE TITLE
Suggestion: separate.se.col parameter for sjt regression tables and automatice note update

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjPlot#169]
Hi, 

I would like to suggest adding a boolean paramater ```separate.se.col``` to ```sjt``` functions for regression models, which would work similar to ``separate.ci.col``. In some disciplines it is quite common to display standard errors in brackets in the same column as coefficients.

Related to this it woudld also be super useful if a corresponding note gets added automatically. So for example if one would use  ```separate.se.col=T``` there would be a note "Standard Errors in parentheses" and the same could be applied for ```separate.ci.col```.

Edit: Similar to the notes update, if one chooses ``exp.coef=F`` for ``sjt.glm``, column headers are still named *OR* although raw coefficients are displayed.

**Comment by strengejacke** [comment]
Implemented in the current draft of `tab_model()`.
