### ISSUE TITLE
Theme Updates and palettes

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjPlot#178]
Hi,

is there a reason why you [didn't document](http://www.strengejacke.de/sjPlot/custplot/#using-the-ggthemes-packages) that ``ggthemes`` can also be loaded in ``sjp.setTheme()``? For me this works: ``sjp.setTheme(ggthemes::theme_wsj())``
But it sometimes produces strange outputs, why I thought you didn't document it for a reason:
![image](https://cloud.githubusercontent.com/assets/7460499/21272343/1942fbce-c3bf-11e6-9eac-4179e919f7cc.png)

Related to this I would like to suggest to please add two things:
-  Enable to adjust the default color palette (brewer or vector of colors) in ``sjp.setTheme()``. It would be nice if this would not have to be done for plots manually. 
- Enable continuous confidence intervals (which I think are ``geom_ribbon``) to be in the same color as the corresponding lines, but with a much lower alpha (like 0.2 or whatever). This would look like this:
![pegida10_demosvsislamization](https://cloud.githubusercontent.com/assets/7460499/21272660/8b6d7eb2-c3c0-11e6-9f89-73f1139b51e4.png)

Edit: Is it possible to also include a publication ready greyscale theme via ``sjp.setTheme()``? A nice example with ggthemes is given [here](https://www.r-bloggers.com/how-to-format-plots-for-publication-using-ggplot2-with-some-help-from-inkscape/).

**Comment by sjPlot** [comment]
Actually, I did not know that ggthemes also work with sjp.setThemes. And I'm not sure how to set the color palette, that it's "globally" defined like a theme. I have to look at some other packages' source code to find out how this could work.

And the same coloured CI bands: I have already implemented this in sjp.int, and could also do this for other functions with CI bands as well.

**Comment by methodds** [comment]
That would be nice, thanks. At while your at it: an option for [removing space between the axis and area plot](http://stackoverflow.com/questions/22945651/how-to-remove-space-between-axis-area-plot-in-ggplot2) is not possible in an automated way right?

**Comment by sjPlot** [comment]
> an option for removing space between the axis and area plot is not possible in an automated way right?

No, only for frequency plots, where you find the `expand.grid`-argument.

I have added same colour for CI regions in some plot types, maybe not in all yet - if you anything I forgot, post here, please.

> Enable to adjust the default color palette (brewer or vector of colors) in sjp.setTheme(). It would be nice if this would not have to be done for plots manually.

I'll keep this issue open, to see what I can do.

**Comment by methodds** [comment]
Did you test the latest update? Installing throws an error for me:

``
`Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'blme'
ERROR: lazy loading failed for package 'sjPlot'
* removing 'C:/Users/kasus/Documents/R/win-library/3.3/sjPlot'
* restoring previous 'C:/Users/kasus/Documents/R/win-library/3.3/sjPlot'
Error: Command failed (1)
``

**Comment by sjPlot** [comment]
`blme` is a dependency from `merTools`, so you might not have install that package properly...

**Comment by methodds** [comment]
Thanks, I reinstalled ``blme```and it worked. I wonder what might have gone wrong during the installation of it though.

**Comment by strengejacke** [comment]
Themes will be handled slightly different in the forthcoming update, since functions now directly return the ggplot object.
