### ISSUE TITLE
No CI's in sjp.lm

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjPlot#183]
Hi,

when using the efc example data I have no problem with CI's in a prediction plot:
````
data(efc)
fit <- lm(barthtot ~ c160age + e17age + c12hour + e16sex + c161sex + c172code,
          data = efc)

sjp.lm(fit, type='pred', vars = c('e17age', 'e16sex'), facet.grid =F)
````
![image](https://cloud.githubusercontent.com/assets/7460499/21296267/327034e0-c568-11e6-9d00-fe07a312ce48.png)

Trying the same with a Stata dataset and a similar setting (continuous variable + dummy) does not return confidence intervals (this does not change if I include ``show.ci=T``:
````
d <- read_stata('GLES_Vorwahlquerschnitt_ZA5700_v1-0-0.dta')
d$lire <- set_na(d$q62, -99:-97)
d$skalocdu <- set_na(d$q21a, -99:-98)
d$cdupid <- rec(d$q119a, '1:3 = 1 [PID CDU/CSU]; 4:808 = 0 [keine PID CDU/CSU]',
                var.label='Parteiidentifikation CDU/CSU')

reg2 <-  lm(skalocdu ~ lire + cdupid, data=d)
summary(reg2)
sjp.lm(reg2, type='pred', vars=c("lire", "cdupid"), facet.grid = F)
````

![image](https://cloud.githubusercontent.com/assets/7460499/21296287/9e6d025e-c568-11e6-96fb-9d21df3edba6.png)

A side question: How can I stop the points to be plotted in the corresponding colors, e.g. just drawing them black? Do I have to use ggplot code for this or can it be done "within" sjp?

**Comment by sjPlot** [comment]
Very strange. Currently, I have no idea why CI-region is not plotted. Since the predicted CI are returned as well, you can use a workaround:

```
p <- sjp.lm(reg2, type='pred', vars=c("lire", "cdupid"), facet.grid = F, show.ci = T)
p$plot + geom_ribbon(aes(ymin = ci.low, ymax = ci.high, colour = NULL), alpha =.15)
```

**Comment by methodds** [comment]
Thanks for the workaround, I'll see whether I can find a pattern for the CI's not being included in plots.

**Comment by strengejacke** [comment]
Could you try `plot_model (reg2, type = "pred")` with the current Dev version?

**Comment by methodds** [comment]
I'd love to try it, but upgrading my sjverse and as recommended starting with sjlabelled leads to an installation error:
``ERROR: dependency 'snakecase' is not available for package 'sjlabelled'``

**Comment by strengejacke** [comment]
Ok, you need to install that pkg as well. Or update all from CRAN, and just update sjplot from GitHub.

**Comment by methodds** [comment]
Uff.. snakecase has a R 3.3.3 requirement... ok, will update everything

**Comment by methodds** [comment]
![image](https://user-images.githubusercontent.com/7460499/30522508-4e48d506-9bd1-11e7-83fc-33c7a81bdcfb.png)

looks good! :)

**Comment by strengejacke** [comment]
ok, great! I have submitted an issue because of the R-dependency of snakecase...

**Comment by methodds** [comment]
thanks :)
