### ISSUE TITLE
Suggestion: Change default return values of sjPlots

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjPlot#200]
Hi,

This is from issue #199:

> No, not yet. sjp.setTheme() was more or less an attempt to implement a theming-options with convenient defaults, and to include own theme-presets. Actually, if you want to change details in themes, sjp.setTheme() is not much easier or faster than directly using ggplot2::theme(). That's why I did not spend much time on this function...

How often do you actually need the ``data`` from sjPlots? I'm only using the package for a few months now but had not one case yet where I needed the data. On the other hand, what I wanted very often was to simply use further ggplot() arguments to style the plots without ``$plot``.

I don't know whether this would potentially break a lot of code in sjPlot, but from my perspective, it would be preferable for the default return object of sjPlots to be  ```ggplot``` objects and only if one specifies it with a parameter like ```data=TRUE``` the underlying data would be returned as well. 
At the end, I think this would be a more user friendly solution. I also see it as being better suited for teaching purposes than the current design, as newcomers will probably get confused about plots opening which they cannot directly manipulate with the syntax they learned in the first place. 

I think this is also kind of relevant for ```sjp.setTheme()```, because if it is getting easier to adjust sjPlots directly, the need for a very sophisticated theme function with dozens of parameters becomes less important. But I'll open a separate issue for that.

**Comment by sjPlot** [comment]
It would not break massive code, I would say. It's just the question how to deal with those functions that return multiple plots?

**Comment by methodds** [comment]
which functions would return multiple plot? Because for facet grid types, there is still only one plot object returned right?

**Comment by sjPlot** [comment]
Typically, facet-plots, where you set `facet.grid = FALSE`, or `sjp.int()` etc. There are quite a lot plot-types where you can get a plot-list instead of a single plot-object (or even both - the faceted as one plot, and the single "facets" each as own plot).

**Comment by methodds** [comment]
Argh.. that's unfortunate. Well one way would of course to not alter the current state for these specific plot(s) / parameters, but this also a little unfortunate as the default behavior would not be consistent across all plots anymore.

**Comment by strengejacke** [comment]
Data will no longer be returned, as it is part of the returned plot-object. The revised functions like `plot_models()` or `plot_model()` will only return the plot-object.
