### ISSUE TITLE
Suggestion: sjp.setTheme improvements

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjPlot#201]
Hi,

it would be useful (if this is at all possible) if sjp.setTheme could accept additional arguments, e.g.

-  scaling functions/color schemes passed.

```

scale_colour_Publication <- function(...){
  library(scales)
  discrete_scale("colour","Publication",
           manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c",
"#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ... 
}
sjp.setTheme(scale = scale_colour_Publication())
```
- gridline feature adjustments with ```panel.grid``` and others

**Comment by strengejacke** [comment]
`sjp.setTheme()` will be removed next update.
