### ISSUE TITLE
Can you display the random slope variance in a table from sjt.glmer or sjt.lmer?

### ISSUE THREAD

**Issue by bbachilles** [strengejacke/sjPlot#209]
Hello,

Thanks so much for writing the sjPlot package. It is wonderful!

I am wondering if it is possible to show random slope variances in the html tables one can build using the sjt.glmer/sjt.lmer tool. I see the option to show.re.var (default set to TRUE), but it does not list what is labeled "tau.11" in get_re_var.

If you are building a table containing 2 or more models, do both of the models have to have the random slope?

Thank you,
Erik

**Comment by sjPlot** [comment]
> If you are building a table containing 2 or more models, do both of the models have to have the random slope?

No, currently, "tau.11" (random-slope-variance) is currently not reported at all. I could add this information to the table output as well, if the model has random slope. At the moment, only Slope-Intercept-correlation (rho 01) is shown for models with random slope.

**Comment by bbachilles** [comment]
That would be great. It's very common in my field (education research) to display those random slope variance estimates in the random part of the table. Thanks!

**Comment by strengejacke** [comment]
Possible duplicate of https://github.com/strengejacke/sjPlot/issues/279, so I'll close this one.
