### ISSUE TITLE
Suggestion: Separate model diagnostic plots

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjPlot#215]
Hi,

I'd like to suggest to create a new, separate function that works for testing model assumptions. It would basically be a graphical equivalent to ```check_assumptions()``` in sjstats. Right now, the vif is obtained by using ````sjp.glm/lm```` and I couldn't find other assumption plots. I think it would make more sense to have a specific *diagnostics* function.

In addition to VIF base R already has a nice suite of diagnostic plots if one just calls ````plot()```` on a regression object. Even nicer is that ````ggfortify```` offers a way to convert these into the ggplot world with:

````
library(sjmisc)
library(ggfortify)

data(efc)


fit1 <- lm(barthtot ~ c160age + c12hour, data = efc)
autoplot(fit1, which = 1:6)
````

![image](https://cloud.githubusercontent.com/assets/7460499/23374472/b9760746-fd24-11e6-9e68-c8264e1c3705.png)

**Comment by sjPlot** [comment]
I'm not quite sure what you are missing and might want to add?

**Comment by methodds** [comment]
```check_assumptions()``` are basically tests. What I would like to add are graphical model diagnostics, so that users can inspect both the tests and the visualizations. This could for example be a function like ```sjp.check_assumptions()```, which would then return e.g. plots for
-  multicollinearity -> VIF
- heteroscedasticity -> Scale-Location or Residual vs fitted
- Outliers -> Residuals vs Leverage or Leverage vs Cook's D
- Non-linearity -> Residual vs fitted
- Residual distribution -> Q-Q Plot

[This overview](http://data.library.virginia.edu/diagnostic-plots/) is directly related to the plots from above.

**Comment by methodds** [comment]
After I just tried ```sjp.lm()``` again, I realized that many of these plots are already available, they were just hiding behind the coefficient estimates plot! =D. So maybe you could just remove the estimates plot there and add a plot for outliers?
In addition, user might want to use ``facet.grid``, to show all the plots at once.

**Comment by the-Trees** [comment]
It would be nice to have sjp.lmer(x, type = "ma") play nicely with random intercept models:

```
mlm <- lmer(riskp ~ 
              (1|age2) + 
              (1|sex) + 
              (1|race) + 
              (1|income) + 
              (1|edu) + 
              (1|work) + 
              (1|hhsize) + 
              (1|work:race) + 
              (1|hhsize:work) + 
              (1|sex:race:edu) +
              (1|State_name) + 
              (1|reg4), r, REML = FALSE)
```

```
> sjp.lmer(mlm, type = "ma")
Error: Model is not of class `lm` or `glm`.
```

**Comment by strengejacke** [comment]
Model assumptions for Mixed Models are not as straightforward as for simple linear models. I'm not sure if there are many serious approaches?
