### ISSUE TITLE
Suggestion: factor analysis support

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjPlot#220]
Hi,

I was attending a structural equation modeling workshop by a psychometrician last week which further strengthened my belief that factor analysis would be another useful addition to sjPlot. This could be a wrapper around ```psych::fa``` and create a plot similar to ``sjp.pca()``. In addition, it would support parallel analysis ```psych::fa.parallel``` to determine the number of factors, which seems to be the way to go these days.
I'd like to try a first draft of the function, so you could assign me to this issue if you are in for factor analysis support =)

**Comment by sjPlot** [comment]
Yes, I'm happy with any contribution from other users, so feel free to draft a function for this issue!

**Comment by strengejacke** [comment]
As far as I see, fa-support works, right?

**Comment by methodds** [comment]
Yap still works for me. Did you update the PCA codebase lately? Because I mostly copy pasted code from there and if you improved anything it might be easy to apply this for FA as well.

**Comment by strengejacke** [comment]
No, at least I can't remember ;-)
And the plotting- (and table-)functions will be revised, so I'll have a closer look at all functions, anyway.

**Comment by methodds** [comment]
OK. Do you have a time schedule for the revisions? Is this likely to be on CRAN for the semester start at October 17th?

**Comment by strengejacke** [comment]
The first update is `plot_model()`, as replacement for sjp.lm(), sjp.lmer(), sjp.glm() and sjp.glmer(). This will be submitted shortly, probably until 17th Oct.

Other functions will be revised in the following month. Currently, my plan is to start with the model-table-functions, that will be replaced by a single `tab_model()`. After that, the frequency plots like sjp.frq(), sjp.grpfrq() and sjp.xtab() will be replaced, probably by a more generic function as well. I think, the next submission will be around Dec 17 / Jan 18.

All former functions will still be there, I think I'll remove them later, to have a longer transition period.
