### ISSUE TITLE
sjp.glmer - type="eff" no longer available? 

### ISSUE THREAD

**Issue by s4176123** [strengejacke/sjPlot#225]
Hi there, 

Love sjPlot. Thanks for all you hard work on it. 

I'm trying to produce marginal effects plots for covariates in a GLMM (negative binomial error distribution with log links). The command: sjp.glmer(fit, type="eff") returns an error msg stating that "eff" is not an accepted type, and the plot defaults to a "fe" type. Is there any way to still produce marginal effects plots for a NB GLMM in sjPlot? 

Best regards, 
Sean

**Comment by strengejacke** [comment]
I can't reproduce this issue, for me it works.

**Comment by s4176123** [comment]
Thanks for the quick response. I'll try installing the package again - may be an issue with the version I'm using?

**Comment by strengejacke** [comment]
Could you solve this issue?
