### ISSUE TITLE
Question about binding labeled dataframes

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjPlot#226]
Hi,

I have two large, labeled  spssdatasets (> 40.000 columns) that I'd link to combine with ``bind_rows()`` from dplyr. When reading them in one by one with ``read_spss``, it takes a while but at the end all labels are correctly assigned to the two datasets. After I combined them however, the labels are gone, as dplyr does not seem to include the label attributes for the new coḿbined dataset.

My approach to solve this issue was to take the labels from one of the datasets and append it to the combined version afterwards:
```
labels <- get_labels(d1)
d <- set_labels(d, labels=labels)
```
This however results in several thousands of warnings. Some of these are:

```
More values in "v_58" than length of "labels". Additional values were added to labels.
More values in "v_63" than length of "labels". Additional values were added to labels.
..

Character vectors can only get labels of same type.no non-missing arguments to min; returning Infno non-missing arguments to max; returning -InfCan't set value labels for "quality". Infinite value range.More values in "duration" than length of "labels". Additional values were added to labels.


```

And at the end the process did not work:
```
> frq(d1$v_40)
# Geschlecht

 val    label frq raw.prc valid.prc cum.prc
   1 weiblich 386   53.84     57.10   57.10
   2 männlich 283   39.47     41.86   98.96
   3  anderes   7    0.98      1.04  100.00
   4       NA  41    5.72        NA      NA

> frq(d2$v_40)
# Geschlecht

 val    label frq raw.prc valid.prc cum.prc
   0        0   2    0.23      0.24    0.24
   1 weiblich 479   55.70     57.92   58.16
   2 männlich 344   40.00     41.60   99.76
   3  anderes   2    0.23      0.24  100.00
   4       NA  33    3.84        NA      NA


> frq(d$v_40)
 val label frq raw.prc valid.prc cum.prc
   0     0   2    0.13      0.13    0.13
   1    NA 865   54.85     57.55   57.68
   2    NA 627   39.76     41.72   99.40
   3    NA   9    0.57      0.60  100.00
   4    NA   0    0.00      0.00  100.00
   5    NA  74    4.69        NA      NA
```
Can you help me out here? I'm not sure whats going on.

**Comment by methodds** [comment]
Sorry I just noticed that this question should be issues for sjmisc and not sjplot

**Comment by strengejacke** [comment]
Though I moved the repo to my new GitHub acc, I see notifications only when I log in with my old acc... :-/

**Comment by strengejacke** [comment]
Usually, `dplyr::bind_*()` should copy the attributes. However, you could also try `sjmisc::merge_df()` - does this work for you?

**Comment by strengejacke** [comment]
btw, to copy labels from a labelled data frame to an unlabelled data frame, use `sjmisc::copy_labels()`

**Comment by methodds** [comment]
````merge_df()```` worked perfectly, thank you :)

**Comment by methodds** [comment]
Argh, what I actually didn't check was reading in the data after saving it with ```save_spss```. This unfortunately always raises an error ```File did not contain the expected number of rows```.


Could you please check whether you can reproduce this error? The zipped dataset is available [here](https://www.dropbox.com/s/kjymntsqnb7g8k6/blablasurvey_combined.sav.zip?dl=1).

**Comment by strengejacke** [comment]
Seems to be a _haven_-issue. I have to check whether the file can be opened with SPSS tomorrow. But, 523MB filesize? I thought writing data back to SPSS results in smaller files because of shorter character veariabes?

**Comment by methodds** [comment]
Ye.. It's a file with a a loooot of columns, but also a lot of missing values. Neither SPSS nor Stata a very good at compressing data and Excel does compress but is too stupid to work with more than 30.000 columns and has other annoying limitations. "Big Data" issues for Social Scientists that want labels... =(
