### ISSUE TITLE
suggestion:  sjp.xtab automatic show.values = FALSE when this happend.

### ISSUE THREAD

**Issue by espher1987** [strengejacke/sjPlot#227]
First, Thanks for your job, is amazing. A couple of days ago i have a little problem using de sjp.xtab command of your package, i actually resolve it. But it make me feel that is not how it should work. i explain:

i use this command:
```
sjp.xtab(x     = efc$e42dep, 
             grp = efc$c82cop1)
```

but when i want to create a "clean" plot (without any legends), i try to do this:

```
sjp.xtab(x    = efc$e42dep,
             grp = efc$c82cop1,show.total = F, show.n = F,show.prc = F)

```

what give me this error:

> Error in sjp.xtab(x = efc$e42dep, grp = efc$c82cop1, show.total = F, show.n = F, : objeto 'ggvaluelabels' no encontrado

I look for help and i found out: [here a made my question](https://stackoverflow.com/questions/42878060/error-in-sjplot-sjp-xtab-command-used-to-get-cleanest-graphic)

So now, i know how to do it.

But the point is that i think this error massage doesnt help to undestand why is not drawing a  plot. i suppose that there is a way to make something like:
if
show.total = F, show.n = F,show.prc = F 
then
show.values = FALSE

Something like this. I dont know is just a suggestion. Again, thanks for your amazing job.

**Comment by strengejacke** [comment]
Thanks, you're right with your points. If showing all annotations are set to `FALSE`, show.values = FALSE` should be automatically set to avoid this error.

**Comment by strengejacke** [comment]
Fixed! (will commit later)
