### ISSUE TITLE
Suggestion: change robust-method in sjt.lm

### ISSUE THREAD

**Issue by Zirys1** [strengejacke/sjPlot#228]
sjt.lm uses the robust function of the sjstats package.
Is it possible, when using sjt.lm, to specify the method (e.g. "HC3", "HC0", etc.) used to compute robust standard errors?

**Comment by thoughtsnippet** [comment]
I have the same issue with the sjt.lm function.

I would like to specify the method to HC1 (Stata-Standard).
It seems that sjt.lm uses a differnt default and that I can't change it.

Current - only - option is robust = TRUE right?

**Comment by strengejacke** [comment]
Yes, that's correct. I plan revising the table-output functions completely, and then I will change the robust-argument to accept different specific methods.

**Comment by strengejacke** [comment]
Implemented in the current draft of `tab_model()`.
