### ISSUE TITLE
sjt.df error

### ISSUE THREAD

**Issue by shellyc26** [strengejacke/sjPlot#229]
I'm having the same problem as [this](https://github.com/strengejacke/sjPlot/issues/91) person.

The function 'describe' is found in both Hmisc and psych. I'm not sure it's calling the psych function correctly. Especially because the function works when `describe = FALSE`

I'm using the following versions on Mac Sierra (10.12.3):
sjPlot and sjmisc - 2.3.1
psych - 1.7.3.21 (released March 22, 2017)
RStudio - 1.0.44
R - 3.3.2

For example:
`data(efc)`
`sjt.df(efc)`
`Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ""describe"" to a data.frame`

Thanks!

**Comment by sjPlot** [comment]
I can't reproduce this bug:

```
> library(strengejacke)
Loading sj!-packages: sjmisc
Loading sj!-packages: sjstats
Loading sj!-packages: sjPlot
Visit http://strengejacke.de/sjPlot for package-vignettes.
> data(efc)
> sjt.df(efc)
  |=======================================================================================================| 100%
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.4

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sjPlot_2.3.1.9000  sjstats_0.9.0.9000 sjmisc_2.3.1.9000  strengejacke_0.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10       stringdist_0.9.4.4 mvtnorm_1.0-6      lattice_0.20-35    tidyr_0.6.1       
 [6] zoo_1.7-14         assertthat_0.1     digest_0.6.12      lmtest_0.9-35      psych_1.7.3.21    
[11] mime_0.5           R6_2.2.0           plyr_1.8.4         stats4_3.3.3       coda_0.19-1       
[16] ggplot2_2.2.1      lazyeval_0.2.0     multcomp_1.4-6     minqa_1.2.4        nloptr_1.0.4      
[21] Matrix_1.2-8       DT_0.2             splines_3.3.3      lme4_1.1-12        stringr_1.2.0     
[26] foreign_0.8-67     htmlwidgets_0.8    munsell_0.4.3      shiny_1.0.0        broom_0.4.2       
[31] httpuv_1.3.3       modelr_0.1.0       mnormt_1.5-5       htmltools_0.3.5    nnet_7.3-12       
[36] tibble_1.2         coin_1.1-3         codetools_0.2-15   dplyr_0.5.0        MASS_7.3-45       
[41] grid_3.3.3         xtable_1.8-2       nlme_3.1-131       arm_1.9-3          gtable_0.2.0      
[46] DBI_0.6            magrittr_1.5       scales_0.4.1       stringi_1.1.3      reshape2_1.4.2    
[51] effects_3.1-2      sandwich_2.3-4     blme_1.0-4         TH.data_1.0-8      tools_3.3.3       
[56] purrr_0.2.2        abind_1.4-5        parallel_3.3.3     survival_2.41-2    colorspace_1.3-2  
[61] knitr_1.15.1       haven_1.0.0        merTools_0.3.0     modeltools_0.2-21 
```

**Comment by techxorcist** [comment]
I encountered the same error during a session in which I had loaded the Hmisc library and then subsequently installed sjPlot. When I initiated a new session and did not load Hmisc, I was able to execute sjt.df without an error.

Loading Hmisc yields the following output, after which the error reoccurs:

> library(Hmisc)
> Loading required package: lattice
> Loading required package: survival
> Loading required package: Formula
> Loading required package: ggplot2
> 
> Attaching package: ‘Hmisc’
> 
> The following object is masked from ‘package:sjmisc’:
> 
>     %nin%
> 
> The following object is masked from ‘package:sjstats’:
> 
>     deff
> 
> The following objects are masked from ‘package:base’:
> 
>     format.pval, round.POSIXt, trunc.POSIXt, units

My entire sessionInfo() after loading Hmisc:

> R version 3.4.0 (2017-04-21)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.10
> 
> Matrix products: default
> BLAS: /usr/lib/libblas/libblas.so.3.6.1
> LAPACK: /usr/lib/lapack/liblapack.so.3.6.1
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods  
> [7] base     
> 
> other attached packages:
> [1] Hmisc_4.0-3     ggplot2_2.2.1   Formula_1.2-1   survival_2.41-3
> [5] lattice_0.20-35 sjmisc_2.4.0    sjstats_0.10.0  sjPlot_2.3.1   
> 
> loaded via a namespace (and not attached):
>  [1] tidyr_0.6.3         splines_3.4.0       merTools_0.3.0     
>  [4] modelr_0.1.0        shiny_1.0.3         assertthat_0.2.0   
>  [7] stats4_3.4.0        latticeExtra_0.6-28 coin_1.1-3         
> [10] backports_1.1.0     digest_0.6.12       checkmate_1.8.2    
> [13] RColorBrewer_1.1-2  minqa_1.2.4         colorspace_1.3-2   
> [16] sandwich_2.3-4      htmltools_0.3.6     httpuv_1.3.3       
> [19] Matrix_1.2-10       plyr_1.8.4          psych_1.7.5        
> [22] broom_0.4.2         haven_1.0.0         purrr_0.2.2.2      
> [25] xtable_1.8-2        mvtnorm_1.0-6       scales_0.4.1       
> [28] stringdist_0.9.4.4  lme4_1.1-13         htmlTable_1.9      
> [31] arm_1.9-3           tibble_1.3.1        effects_3.1-2      
> [34] DT_0.2              TH.data_1.0-8       nnet_7.3-12        
> [37] lazyeval_0.2.0      mnormt_1.5-5        magrittr_1.5       
> [40] mime_0.5            nlme_3.1-131        MASS_7.3-47        
> [43] foreign_0.8-67      data.table_1.10.4   tools_3.4.0        
> [46] multcomp_1.4-6      stringr_1.2.0       munsell_0.4.3      
> [49] cluster_2.0.6       compiler_3.4.0      rlang_0.1.1        
> [52] blme_1.0-4          grid_3.4.0          RCurl_1.95-4.8     
> [55] nloptr_1.0.4        htmlwidgets_0.8     bitops_1.0-6       
> [58] base64enc_0.1-3     gtable_0.2.0        codetools_0.2-14   
> [61] abind_1.4-5         DBI_0.6-1           reshape2_1.4.2     
> [64] R6_2.2.1            gridExtra_2.2.1     zoo_1.8-0          
> [67] knitr_1.16          dplyr_0.5.0         modeltools_0.2-21  
> [70] stringi_1.1.5       parallel_3.4.0      Rcpp_0.12.11       
> [73] rpart_4.1-11        acepack_1.4.1       coda_0.19-1        
> [76] lmtest_0.9-35

**Comment by strengejacke** [comment]
I think this is a (Namespace) issue between *psych* and *Hmisc*. Hmisc first masks the class `describe`, which has no `data.frame`-class-attribute, while psych returns an object with both `describe` and `data.frame`-attribute. Since Hmisc was loaded first, R tries to find a "as.data.frame"-method for Hmisc's describe, but fails.

**Comment by isaactpetersen** [comment]
I have this issue as well. The diagnosis by @strengejacke seems correct. However, detaching the `Hmisc` package and unloading its namespace does not solve the problem. How can I use the `describe()` function from the `psych` package after having loaded the `Hmisc` package?

**Comment by strengejacke** [comment]
Please open a new issue, if possible with a small reproducible example. I tried the initial examples and could not reproduce the error.
