### ISSUE TITLE
Error in sjp.grpfrq and sjt.grpmean command in sjPlot package. Different result.

### ISSUE THREAD

**Issue by espher1987** [strengejacke/sjPlot#230]
I am trying to create different kind of variables to teach basic statistic, i am doing analysis considering a numeric variable and a categorical variable. i start creating my variables:

f is the factor and x is numeric.

```
f <- c(1,1,1,2,2,2,3,3,3,5,5,6,6,6,6,7,7,NA)
x <- rnorm(18,2302,230)
```
Apply the variable labels to the factor

```
l.familiaridad <- c("Muy poco familiarizado",
                    "Poco familiarizado",
                    "Escasamente familiarizado",
                    "familiarizado",
                    "Algo familiarizado",
                    "Bastante familiarizado",
                    "Muy familiarizado")
```

`f <- factor(x = f,levels = 1:7,labels = l.familiaridad)`

I always use the table() command to do an early review, to check everything is ok.

`table(f)`

Then i use the sjPlot to create the html output

`sjt.frq(f)`

At this point, everything looks ok. But then i use:

`sjp.grpfrq(x,f,type="boxplot")`

As you can see in the plot, "familiarizado" level is showed, but the table() and sjt.frq() command doesnt show anything in that level. And "muy familiarizado" is no showed.

The second error i get is when i use:

`sjt.grpmean(x,f)`

i get this error

> Error in row.names<-.data.frame(*tmp*, value = value) : invalid 'row.names' length

**Comment by strengejacke** [comment]
The labels for the boxplot are incorrectly set, I'll look at this.
For the 2nd issue (grpmean), I must see whether the missing label is also problematic here as well...

**Comment by strengejacke** [comment]
For the 2nd issue, please use `sjstats::grpmean()` in the future. Onc, _sjstats_ and _sjPlot_ are updated on CRAN, `sjstats::grpmean(out = "viewer")` will create a HTML table.
