### ISSUE TITLE
sjt.pca html output quibble

### ISSUE THREAD

**Issue by skrackow** [strengejacke/sjPlot#231]
The script below produces a file if run, but not if sourced (using R-studio and R3.3.3).
"canmod" is a prcomp object from mixOmics::pca. 
The code worked with prior sjPlot package version under R3.3.2.

sjt.pca(canmod, nmbr.fctr = 4,
          file = "PCA.html",
          wrap.labels = 40, digits = 2, 
          show.msa = FALSE, show.var = TRUE, altr.row.col = TRUE, show.cronb = FALSE,
          use.viewer = FALSE, no.output = FALSE, remove.spaces = TRUE)
 
There might be a bug involved, as the PCA.html code seems corrupted at its end:

<td style="padding:0.2cm; text-align:right; font-style:italic; font-size:0.9em;" colspan="5">varimax-font-style:italic; font-size:0.9em;</td>

**Comment by strengejacke** [comment]
Thanks, fixed! (will commit later)
