### ISSUE TITLE
sjt.xtab displays unused labels

### ISSUE THREAD

**Issue by cschwem2er** [strengejacke/sjPlot#232]
Hi,

by default, `sjt.xtab()` (and probably all related functions) do not drop unused value labels:

```
library(sjmisc)
library(sjPlot)
data(efc)

efc2 <- efc %>% filter(e42dep %in% c(3,4))
sjt.xtab(efc2$e16sex, efc2$e42dep)
```

![image](https://cloud.githubusercontent.com/assets/7460499/25187722/2fe8679e-2524-11e7-8ecc-97f0f2af72d3.png)

Is this behavior intended by you? I would assume that in the majority of such cases, the analyst would not be interested in these unobserved categories and thus prefer the output to not display them by default. From what I understand this would be as sample as an automated ``drop_labels()`` within ``sjt.xtab()``.

**Comment by strengejacke** [comment]
Actually, I spend a lot of work to get the zero-categories being displayed. ;-) I could probably add an option to remove them from the output.

**Comment by methodds** [comment]
An option for this really would be handy as it enables sparse output when needed :)

**Comment by lidingruc** [comment]
An option for this really would be handy for the sjp.frq() function too.

**Comment by strengejacke** [comment]
The question is, which behaviour should be the default?

**Comment by cschwem2er** [comment]
hmm.. I'd personally prefer to drop unused labels by default, but I guess there is no optimal decision here.
