### ISSUE TITLE
labels incorrect in sjt.lm when effects (sum) coding is used with a categorical variable

### ISSUE THREAD

**Issue by svannoy** [strengejacke/sjPlot#233]
When formatting the output of a linear model that has a categorical predictor, sjt.lm appears to only/always use the labeling appropriate for dummy coding of that variable (i.e. the first level/label in the factor is not printed out and the subsequent levels are). This is not correct for many/most alternative coding schemes, such as effects coding. What base R (and stargazer) do when the contrast attribute is set, is to print out generic labels based on the name of the factor and the ordering within the factor (see below).

    ccwaDf <- structure(list(subject_id = 1:10, religion = structure(c(1L, 
    3L, 4L, 1L, 1L, 3L, 4L, 1L, 3L, 3L), .Label = c("Catholic", "Jewish", 
    "Other", "Protestant"), class = "factor"), attitude = c(61L, 
    78L, 47L, 65L, 45L, 106L, 120L, 49L, 45L, 62L)), .Names = c("subject_id", 
    "religion", "attitude"), row.names = c(NA, 10L), class = "data.frame")
    
    # Typical dummy coding, predictors are concatenated factor_name:level
    lmFit1 <- lm(attitude~religion, data=ccwaDf)
    summary(lmFit1)`
    
    # Explicitly specify dummy (treatment) coding, predictors are concatenated           
    lmFit1 <- lm(attitude~religion, contrasts=list(religion=contr.treatment(n=4)), data=ccwaDf)
    summary(lmFit1)
    
    # Explicitly specify effects coding, predictors are correctly concatenated         
    factor_name:numeric_level_position
    lmFit3 <- lm(attitude~religion, contrasts=list(religion=contr.sum), data=ccwaDf)
    summary(lmFit3)
    
One solution to this is to manually specify the pred.labels, which does solve the problem. However, I was thrown of for some time as I was learning about contrast coding in R because I was using sjt.lm as my primary output (it's so great to look at compared to base R!) and I was very confused by the incorrect labels. Perhaps you could do the same as base R and notice when contrasts have been set?

**Comment by strengejacke** [comment]
I'm not sure if I understand right. This is what `sjt.lm()` gives me as output for your two models:

![sjtlm](https://cloud.githubusercontent.com/assets/26301769/25237824/01a45730-25ec-11e7-90cb-fcf29a6ebaa2.png)

It looks exactly like the base R summary output, or am I missing something?

**Comment by svannoy** [comment]
Hi Daniel,

Thanks for the quick response!

Your results below are what I get for model 1, and they are correct. With dummy coding, the reference is the first level of the factor, in this case “Catholic”. The Intercept is the mean of Catholics on the outcome measure (attitude), and the remaining coefficients are the difference between the group mean (mean of “Other” and mean of “Protestant”) and the mean of Catholics.

But for model 3, I have specified effects coding "contrasts = list(religion=contr.sum)”. Now the intercept should be the grand mean and b1 = coefficient for Catholics; b2 = coefficient for Other. (Not Other and Protestant as in dummy coding). The coefficients represent the difference between the category (religion) mean and the grand mean.

The output I get for for model 3 from base R and from sjt.lm match in all respects, except in base r the predictor variables are labeled “religion1 and religion2” (whereas in model one, they are labeled “religion2” and religion3”. All of these values are different than in model 1 (both base R and sjt.lm)

So sjt.lm is matching everything except the lables for the predictor variables.


See my output below:


Call:
lm(formula = attitude ~ religion, data = ccwaDf, contrasts = list(religion = contr.sum))

Residuals:
    Min      1Q  Median      3Q     Max 
-36.500 -10.562  -0.375   9.000  36.500 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)   70.417      8.869   7.940 9.56e-05 ***
religion1    -15.417     11.732  -1.314    0.230    
religion2      2.333     11.732   0.199    0.848    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 26.61 on 7 degrees of freedom
Multiple R-squared:  0.201,	Adjusted R-squared:  -0.02732 
F-statistic: 0.8803 on 2 and 7 DF,  p-value: 0.456

attitude
 	 	B	CI	p
(Intercept)	 	70.42	49.45 – 91.39	<.001
religion
Other	 	-15.42	-43.16 – 12.33	.230
Protestant	 	2.33	-25.41 – 30.08	.848
Observations	 	10
R2 / adj. R2	 	.201 / -.027


*****************************

**Comment by strengejacke** [comment]
In the example you provided, the predictor variables are labelled `religion1` and `religion2` as well, when I use `sjt.lm()` - see my screenshot above. That's why I'm not sure where the source for this error could come from.

**Comment by svannoy** [comment]
Hmmm, sorry about that, I didn’t notice that you had printed out both models side-by-side (another very nice feature).

Now, when I print out only the second model by itself, I have the error, but when I print them both out I don’t; see below:

Here is exactly what I’m running

ccwaDf <- structure(list(subject_id = 1:10, religion = structure(c(1L, 
3L, 4L, 1L, 1L, 3L, 4L, 1L, 3L, 3L), .Label = c("Catholic", "Jewish", 
"Other", "Protestant"), class = "factor"), attitude = c(61L, 
78L, 47L, 65L, 45L, 106L, 120L, 49L, 45L, 62L)), .Names = c("subject_id", 
"religion", "attitude"), row.names = c(NA, 10L), class = "data.frame")

table(ccwaDf$religion)

# Typical dummy coding, predictors are concatenated factor_name:level
lmFit1 <- lm(attitude~religion, data=ccwaDf)
summary(lmFit1)

# Explicitly specify dummy (treatment) coding, predictors are concatenated factor_name:numeric_level_position
lmFit1 <- lm(attitude~religion, contrasts=list(religion=contr.treatment(n=4)), data=ccwaDf)
summary(lmFit1)
sjt.lm(lmFit1)

# Explicitly specify effects coding, predictors are correctly concatenated         
lmFit3 <- lm(attitude~religion, contrasts=list(religion=contr.sum), data=ccwaDf)
summary(lmFit3)
sjt.lm(lmFit3)

sjt.lm(lmFit1, lmFit3)


Thanks
S


*****************************

**Comment by strengejacke** [comment]
ok, I haven't checked that, but will do this. Strange, anyway.

**Comment by strengejacke** [comment]
Your example code doesn't work for me:

```
lmFit1 <- lm(attitude~religion, contrasts=list(religion=contr.treatment(n=4)), data=ccwaDf)
#> Error in `contrasts<-`(`*tmp*`, ncol(ca), value = ca) : 
#>  wrong number of contrast matrix rows
```

**Comment by svannoy** [comment]
Sorry, the reduced data I sent ended up not having any entries for one of the religious categories and that was causing the error you are getting. Here is corrected code:

ccwaDf <- structure(list(subject_id = 1:10, religion = structure(c(1L, 2L,
3L, 4L, 1L, 1L, 3L, 4L, 1L, 3L, 3L), .Label = c("Catholic", "Jewish", 
"Other", "Protestant"), class = "factor"), attitude = c(61L, 
78L, 47L, 65L, 45L, 106L, 120L, 49L, 45L, 62L, 50L)), .Names = c("subject_id", 
"religion", "attitude"), row.names = c(NA, 10L), class = "data.frame")

table(ccwaDf$religion)

# Typical dummy coding, predictors are concatenated factor_name:level
lmFit1 <- lm(attitude~religion, data=ccwaDf)
attr(lmFit1, "contrasts")
summary(lmFit1)

# Explicitly specify dummy (treatment) coding, predictors are concatenated factor_name:numeric_level_position
lmFit1 <- lm(attitude~religion, contrasts=list(religion=contr.treatment(n=4)), data=ccwaDf)
summary(lmFit1)
sjt.lm(lmFit1)

# Explicitly specify effects coding, predictors are correctly concatenated         
lmFit3 <- lm(attitude~religion, contrasts=list(religion=contr.sum), data=ccwaDf)
summary(lmFit3)
sjt.lm(lmFit3)

sjt.lm(lmFit1, lmFit3)


*****************************
