### ISSUE TITLE
sjp.likert throws deprecation warning

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjPlot#234]
Hi, when `cat.neutral` is used with `sjp.likert()` a deprecation warning for `rec` is raised, as the code for the functions still seems to use the old parameter names,  for instance in line 94:
`    items <- sjmisc::rec(items, recodes = recode.pattern)`

**Comment by sjPlot** [comment]
This should already be fixed in the current Dev-version.

**Comment by strengejacke** [comment]
https://github.com/strengejacke/sjPlot/commit/2d04859156b144da1de3bfb0824ad6337519dade
