### ISSUE TITLE
Suggestion Add number of cases in subgroups in sjt.glm

### ISSUE THREAD

**Issue by gabrakadabra** [strengejacke/sjPlot#235]
When looking at the output from a model (glm) I find it useful to get the number of cases for the different subgroups in the coefficent output. This makes it easier to check the number of missing values for each variable and gives me a tool for diagnostics of the model.

I suggest that you add the option to include a N column as in sjt.frq.

I can provide some code for extracting this from the glm-objects modelmatrix if it is useful for you.

**Comment by strengejacke** [comment]
Yes, some code would be nice! I'll look at it and see how to implement this feature.

**Comment by strengejacke** [comment]
I think this is not possible to implement in a way that the output is intuitive to the user. As you can see [in this vignette](https://cran.r-project.org/web/packages/sjPlot/vignettes/sjtlm.html), one row - i.e. one predictor - applies to different models with different numbers of observations. Having just one N would be misleading...
