### ISSUE TITLE
Bug with sjtab using character columns?

### ISSUE THREAD

**Issue by dannyparsons** [strengejacke/sjPlot#238]
I think there's a bug doing frequency tables for character columns using `sjtab`. It works well for other column types I tried but I get an error with character columns.
Example:
```
dat <- data.frame(x = letters, stringsAsFactors = FALSE)
sjtab(dat, fun = "frq")
# Error in sjt.frq(x) : object 'page.content' not found
```

**Comment by dannyparsons** [comment]
Sorry, not a bug, realised this can be done using other parameters:
`sjtab(dat, fun = "frq", ignore.strings = FALSE, auto.grp.strings = FALSE)`

Possibly a more useful error message could be displayed in this case?

**Comment by strengejacke** [comment]
The error message was more useful (stating that strings are not displayed, and vector only contains string), but due to another bug, this msg is not shown currently. I keep this issue open to make sure I will address it.
