### ISSUE TITLE
pca bug

### ISSUE THREAD

**Issue by RandomCriticalAnalysis** [strengejacke/sjPlot#239]
If I pass data to sjp.pca() where your kaiser criteria formula determines the optimal number of factors for the data is one, the following error will be returned:

> Error in if (nc < 2) return(x) : argument is of length zero

This happens within varimaxrota function.  This also happens if I pass the equivalent prcomp object with same data.

I can kind of work around this by passing nmbr.fctr=2 to the function, but I'd like to see output for 1 (if this makes sense to you).  Failing that a more informative error message would probably help other users in the future.

Thanks,
RCA 

P.S., I recently stumbled across your sjPlot library and I have found it very useful.  Thank you!

**Comment by strengejacke** [comment]
With less than 2 principal components, rotation of the loadings matrices is not possible. `sjp.pca()` now gives a more informative error msg if just one component is extracted.
