### ISSUE TITLE
plm model

### ISSUE THREAD

**Issue by fandreacci** [strengejacke/sjPlot#240]
Hi,

I'm trying to plot a fixed effects model from plm package.

```
Y <- cbind(dataxls$RATE)

X <- cbind(dataxls$PIBAGRO,
           dataxls$PIBIND,
           dataxls$PIBSERV,
           dataxls$PIBPCAPTA,
           dataxls$DENSIDADE )

pdata <- plm.data(dataxls, index = c("CDMUN", "ANO"))
fixed <- plm(Y ~ X, data=pdata, model = "within")
```

The model is ok. I'm using the following code in order to plot:
`
sjp.int(fixed)`

And I'm getting the following result:

**Error in mod.matrix[, !is.na(coef(mod))] : 
  (subscript) logical subscript too long**

Any suggestions?

Thanks

**Comment by strengejacke** [comment]
`sjp.int()` only plots interaction terms. Your model does not have any interactions specified. Else, plm should work with `plot_model()`, which will be available in the next update.
