### ISSUE TITLE
Error when using sjPlot::sjtlmer()

### ISSUE THREAD

**Issue by jrosen48** [strengejacke/sjPlot#241]
Thanks for a great package!

When using `sjPlot::sjtlmer()` on a model fitted using `lmer`, an error is returned.

Here is the model:

```
model <- lmer(learning ~ 1 + 
                  (1|program_ID) + (1|participant_ID) + (1|beep_ID),
              data = df)
```

Here also is the data:

> select(df, learning, program_ID, participant_ID, beep_ID)

```
# A tibble: 2,970 × 4
   learning program_ID participant_ID        beep_ID
      <dbl>     <fctr>         <fctr>         <fctr>
1         4          1           1001 1-2015-07-14-1
2         3          1           1001 1-2015-07-14-2
3         3          1           1001 1-2015-07-15-1
4         3          1           1001 1-2015-07-15-2
5         3          1           1001 1-2015-07-21-1
6         3          1           1001 1-2015-07-21-2
7         3          1           1001 1-2015-07-21-4
8         3          1           1001 1-2015-07-22-1
9         3          1           1001 1-2015-07-22-4
10        3          1           1001 1-2015-07-28-1
```

Here is the error:

```
> sjPlot::sjt.lmer(model)
Error in apply(all.coefs, 1, function(x) length(unique(x))) : 
  dim(X) must have a positive length
```

**Comment by strengejacke** [comment]
This might because it's an intercept-only model. I'll see how to address this issue.

**Comment by the-Trees** [comment]
Checking in to see if anyone has found a work-around for this. 

SjPlot creates the most beautiful model parameter tables & I would hate to not use sjt.lmer() for one model  (the random intercept only model) when I've used sjt.lmer() for all the rest in my paper! Thank you for all your work!

**Comment by ssarraf1234** [comment]
I am a huge fan of this package so wanted to check for any solutions to this issue as well. Thank you for developing this!

**Comment by strengejacke** [comment]
I'm on holiday at the moment, and will address the issues in September.

**Comment by RPanczak** [comment]
Hi both,

Has this issue been resolved? I also get an error with intercept only model. Any work around it?

**Comment by strengejacke** [comment]
I guess this one is solved in the current draft of `tab_model()`.
