### ISSUE TITLE
Question about confidence intervals in sjp.frq()

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjPlot#242]
Hi,
when using the sjp.frq() default, I can't find any use for the parameter ``show.ci``. For any of the following commands, the parameter either has no effect, or no useful effect:

````
sjp.frq(efc$c82cop1, show.ci=T, type='bar')
sjp.frq(efc$c82cop1, show.ci=T, type='dot')
sjp.frq(efc$c82cop1, show.ci=T, type='histogram')
sjp.frq(efc$c82cop1, show.ci=T, type='line')
sjp.frq(efc$c82cop1, show.ci=T, type='density')
sjp.frq(efc$c82cop1, show.ci=T, type='boxplot')
sjp.frq(efc$c82cop1, show.ci=T, type='violin')
````
For the default type 'bar', confidence intervals are drawn around the y-axis values, which for these frequency plots will be the observation counts. Why would we want an uncertainty estimate about the number of observations in the dataset? We would rather have CI's for point estimates, e.g. the mean of one or several variables.

**Comment by strengejacke** [comment]
It the CI for the relative frequency of values, so you must relate this CI to the percentage values:

```
sjp.frq(efc$e42dep, show.ci = T)
```

![rplot](https://cloud.githubusercontent.com/assets/26301769/26158034/f959c102-3b1a-11e7-92c6-09e1625ce013.png)

```
REdaS::freqCI(efc$e42dep)
#>       2.5% Estimate    97.5%
#> 1     5.62     7.33     9.03
#> 2    22.15    24.97    27.80
#> 3    30.87    33.96    37.05
#> 4    30.65    33.74    36.83
```

**Comment by methodds** [comment]
ok, thanks for the clarification, this can be closed.
