### ISSUE TITLE
error calculating mean value in sjt.frq using auto.group.

### ISSUE THREAD

**Issue by espher1987** [strengejacke/sjPlot#243]
i create my numeric variable
`x <- 1:100`

i calculate the mean
`mean(x)`

i get : 
[1] 50.5

then using sjplot:
```
library(sjPlot)
sjt.frq(x)
```
in this point there is no problem but when i use the auto.group argument:
`
sjt.frq(x,auto.group = 4)`

i get a mean = 2.50

Why? Total N is = 100, which is ok, valid is 100. So what is happening? skew and kurtosis are wrong, because if i change the value in auto.group all change, e.g.:
```
sjt.frq(x,auto.group = 3, show.kurtosis = T, show.skew = T)
sjt.frq(x,auto.group = 4, show.kurtosis = T, show.skew = T)
sjt.frq(x,auto.group = 5, show.kurtosis = T, show.skew = T)
```
Values for mean, skew and kurtosis change for every command before.

Please check it, and again thanks for your amazing package. it's really good.

**Comment by espher1987** [comment]
Actually in your own documentation:
http://www.strengejacke.de/sjPlot/sjt.frq/

In "auto.group" section you say:
"Note that, although we have less rows now because categories are grouped, the mean and standard deviation is still computed correctly (compare with above table)."

I can see the same error. Please check this.

**Comment by strengejacke** [comment]
It's a bug introduced with some code-revision the last time. I know how to address this issue, I'll do this when revising the table functions.
