### ISSUE TITLE
sjp.setTheme can cause problems for plot_grid 

### ISSUE THREAD

**Issue by LeiSun2017** [strengejacke/sjPlot#244]
I am plotting the results of linear mixed models by using sjp.lmer. 
p1<-sjp.lmer(m1,type="fe", show.intercept=T, geom.size= 0.5) 
p2<-sjp.lmer(m2,type="fe", show.intercept=T, geom.size= 0.5)
p3<-plot_grid(p1,p2)
When I tried to change the size of the values in the plot by using sjp.setTheme (geom.label.size=4). I didn't get the plot but the error message like the following: 
Error in if (debug) { :argument is of length zero

**Comment by strengejacke** [comment]
`sjp.setTheme()` will be removed in the next update.
