### ISSUE TITLE
Issue with showing estimated values for a variable in sjt.glmer different from the model

### ISSUE THREAD

**Issue by diogoprov** [strengejacke/sjPlot#246]
I´m having an apparent inconsistency in the estimates for the predictor variables in model as shown in the table made with sjt.glmer and in the model as in summary().

![qq](https://cloud.githubusercontent.com/assets/5214836/26632577/f4711380-45e6-11e7-8e84-f94d53efe466.png)

**Comment by strengejacke** [comment]
Yes, by default, the estimates are exponentiated - I plan to revise the functions to use the link-inverse function, which should print the correct back-transformed estimates for all family/link-functions.

**Comment by strengejacke** [comment]
You can use `exp.coef = FALSE` to show untransformed estimates in the table output.

**Comment by diogoprov** [comment]
That clears up everything. Thank you for the quick response and for the great package
