### ISSUE TITLE
Bug for grouped boxplot

### ISSUE THREAD

**Issue by cschwem2er** [strengejacke/sjPlot#252]
Hi,

when working at home or on some PCs in the lab many students experienced a bug when calling ``sjp.grpfrq()``. The result is that they can only see the two points for the additionally included mean values, but not the actual boxplots.

Unfortunately I cannot reproduce this behavior on any of my machines. Do you have an idea what could be the problem here? I'm sorry for not being able to show you an example, but the bug definitely still exists for the latest CRAN versions of the sjverse.

**Comment by strengejacke** [comment]
Have you tried resizing the plot-area in our workspace? Sometimes, when the panel is too small, parts of the graphical output are not shown.

**Comment by methodds** [comment]
No matter how I resize the plot-area I unfortunately cannot reproduce this. I think there is something else going on.

**Comment by strengejacke** [comment]
Have you ever encountered this issue again? I'm not sure how to address this bug...

**Comment by cschwem2er** [comment]
Nope I haven't. Feel free to close this and I come back to you if either me or my colleagues experience it again. Hopefully, we will be able to provide more info for replicability then.
