### ISSUE TITLE
 sjp.lmer(fit2, type = "ri.slope") prints several plots at once?

### ISSUE THREAD

**Issue by NikFord** [strengejacke/sjPlot#254]
This package is incredible.  Thank you!

When running # plot fixed effects depending on group levels
sjp.lmer(fit2, type = "ri.slope"), several plots post but I can only see the last one.  Is there a way to see the others?

**Comment by strengejacke** [comment]
This depends on your IDE. In RStudio, for instance, you can "browse" through the history of plots in the plot panel.

See https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf and search for "Navigate recent plots".

**Comment by strengejacke** [comment]
Is this issue solved? I guess it's not package-related, so I'll close it. For multiple plots, see also `plot_grid()` and the `facet.grid`-argument.
