### ISSUE TITLE
Feature request: Display intercept in forest plots of sjp.lm()

### ISSUE THREAD

**Issue by hplieninger** [strengejacke/sjPlot#256]
The intercept of a linear model is removed from the forest plot produced by `sjp.lm()`. I can't find an option to turn this off but would really like to have it (to display the intercept in cases where it has a meaningful interpretation).
Apart from that, thanks for an awesome package.

**Comment by strengejacke** [comment]
Will be possible with the revised functions, e.g. `plot_model()`.
