### ISSUE TITLE
sjp.int linetype only in legend, not in graph

### ISSUE THREAD

**Issue by LisaRosenberger** [strengejacke/sjPlot#258]
I am trying to change the linetype of an interaction plot (with a factor and a continuous predictor) into a solid line and a dashed line by changing the linetype in sjp.setTheme():
`sjp.setTheme(panel.bordercol = "white",axis.linecolor = "black",panel.gridcol="white",geom.linetype = c(1,3),base=theme_bw())`
`sjp.int(m10b,type="eff",int.term = "multiplication_factor:pleasantness",show.ci = TRUE)`

![interaction plot](https://user-images.githubusercontent.com/30463502/28614216-474cc34e-71f5-11e7-951f-6bd227d98de1.png)

However the linetype only changes in my legend, and not in the plot itself. Any idea why that is the case?

**Comment by strengejacke** [comment]
If you use `geom.colors = "bw"`, the line type is applied to the plot, however, it uses black colors (see pkg vignette).

Do you want coloured geoms and different line types?

**Comment by LisaRosenberger** [comment]
Ah, I didn´t see the vignette, sorry. So using the `geom.colors = "bw"` does the trick:
![interaction plot2](https://user-images.githubusercontent.com/30463502/28662117-4c5b0ac0-72b9-11e7-9923-9ee0df7b315a.png)

However, what I was actually trying to make is a grey scale plot so that the CI´s are more distinguishable, like this: 
![interaction plot3](https://user-images.githubusercontent.com/30463502/28662197-95dbe232-72b9-11e7-98cd-6d9182a8eafa.png)
 and there the linetypes didn´t change either. But now I know that it only works with black-and-white plots. And (like in colored plots) there is no actual need for different linetypes with greyscale plots. 
Thanks for your quick reply!

**Comment by strengejacke** [comment]
There is a workaround, by using the returned plot object. `sjp.int()` returns a list of plots. You can then simply add another fill-scale:

```
library(ggplot2)
library(RColorBrewer)
library(sjPlot)

fit <- lm(weight ~ Diet * Time, data = ChickWeight)
p <- sjp.int(fit, type = "eff", geom.colors = "bw", show.ci = T)
# 4 colours for 4 CI-bands
p$plot.list[[1]] + scale_fill_manual(values = RColorBrewer::brewer.pal(4, "Greys"))
```

**Comment by LisaRosenberger** [comment]
This works perfectly, thanks!

**Comment by cathytao** [comment]
How to solve the same problem, if using plot_model? I am using the following code and hope to have line dashed/solided across different levels. I did not find a proper solution!

> plot_model(p8, type = "int",  transform = "exp", terms = "x", geom.colors = "bw", pred.type = "fe", mdrt.values = "meansd")

**Comment by cathytao** [comment]
Sorry, wrong code -

> plot_model(p8, type = "int", transform = "exp", terms = "x", colors = "bw", pred.type = "fe", mdrt.values = "meansd")

**Comment by strengejacke** [comment]
Either use _ggeffects_

```r
library(ggeffects)
data(efc)
fit <- lm(neg_c_7 ~ c12hour * barthtot, data = efc)
ggpredict(fit, terms = c("c12hour", "barthtot")) %>% plot(colors = "bw")
```
or `plot_model()` with `type = "pred"` or `type = "eff"`:

```r
plot_model(fit, type = "pred", terms = c("c12hour", "barthtot"), colors = "bw")
plot_model(fit, type = "eff", terms = c("c12hour", "barthtot"), colors = "bw")
```

For `type = "int"`, it looks like the color-argument is currently not passed down to `plot()`.
