### ISSUE TITLE
Automatically generate human readable labels (derived from input column names)

### ISSUE THREAD

**Issue by Tazinho** [strengejacke/sjPlot#259]
Maybe a (logical) `pretty.print` argument, that turns on conversion from annotation of the axis, legend and (maybe) other graphical elements into human readable output.

For example: `"Sepal.Length"` to `"Sepal Length"`, `"income_per_country"` to `"income per country"`, ...

In R this could look somehow like this:

```r
p <- ggplot(iris, aes(x = Sepal.Width, y = Sepal.Length)) + geom_point() + labs(title = "Test")

if(!is.null(p$labels$x)){
  p$labels$x <- to_any_case(p$labels$x, case = "parsed", preprocess = "\\.", postprocess = " ")
}

if(!is.null(p$labels$y)){
  p$labels$y <- to_any_case(p$labels$y, case = "parsed", preprocess = "\\.", postprocess = " ")
}

if(!is.null(p$labels$y)){
  p$labels$title <- to_any_case(p$labels$title, case = "parsed", preprocess = "\\.", postprocess = " ")
}
```

**Comment by strengejacke** [comment]
I wouldn't use a logical, rather a character for different parsing options.

**Comment by Tazinho** [comment]
Ok, I would start with x-axis, y-axis, x-ticks, y-ticks, and legend labels 
and try to provide good defaults:

```r
case = "parsed",
preprocess = "(?<!\\d)\\.", # dots, which are not behind numbers will be translated to "_"
postprocess = " " # underscores will be replaced with spaces
```

**Comment by strengejacke** [comment]
I think, there are three useful `case`-options:

  * `parsed`
  * `big_camel`
  * `screaming_snake`

```
strings <- c("Sepa.Width", "Species", "c16sex", "YBOCS.total.score")
to_any_case(strings, case = "parsed", preprocess = "(?<!\\d)\\.", postprocess = " ")
to_any_case(strings, case = "big_camel", preprocess = "(?<!\\d)\\.", postprocess = " ")
to_any_case(strings, case = "screaming_snake", preprocess = "(?<!\\d)\\.", postprocess = " ")
```

However, you need to deal with variable names like "c16sex" in the upper example, which should not be separated with white space.

**Comment by Tazinho** [comment]
Yes, we should definitely make usage of the `protect` argument. I could try a pull request (or a code snippet here) with a good general setting, before the next rusergroup (1.8.17) and we could discuss there a bit? BTW: I think also the `mixed_case` could be useful. In this case only the first letters of each substring stay as in parsed case and the rest becomes lower case.

```r
> to_any_case(strings, case = "parsed", preprocess = "(?<!\\d)\\.", postprocess = " ", protect = "\\d")
[1] "Sepa Width"        "Species"           "c16sex"            "YBOCS total score"
> to_any_case(strings, case = "big_camel", preprocess = "(?<!\\d)\\.", postprocess = " ", protect = "\\d")
[1] "Sepa Width"        "Species"           "C16Sex"            "Ybocs Total Score"
> to_any_case(strings, case = "screaming_snake", preprocess = "(?<!\\d)\\.", postprocess = " ", protect = "\\d")
[1] "SEPA WIDTH"        "SPECIES"           "C16SEX"            "YBOCS TOTAL SCORE"
```

**Comment by strengejacke** [comment]
I won't attend the next Hamburg RUG meeting (remember my post on Slack?)...

Ok, the `protect`-argument looks good!

**Comment by strengejacke** [comment]
I have removed the plot_model.R file and related from the current branch, because I was contacted by the tidyr-maintainer to release a fix for sjPlot that is compatible with the new tidyr-release, however, there's probably a bug in tidyr (see https://github.com/tidyverse/tidyr/issues/337).

Once this "in-between" release is commited to CRAN, I'll add back the plot_model-files, and you can organize your pull request (probably best when the `plot_model()`-fnc is completed).

**Comment by strengejacke** [comment]
Ok, sjPlot-update fixing tidyr issues is on the way. Then I will work on `plot_model()`, and you could then submit your PR. If you like, you could do something similar for the ggeffects-package, where you can already start with your work.

**Comment by strengejacke** [comment]
I think this can be closed, as I will include case conversion for other functions as well, once I revise them.
