### ISSUE TITLE
When using sjt.lmer, warning about sjmisc appears

### ISSUE THREAD

**Issue by jrosen48** [strengejacke/sjPlot#260]
Thank you for creating such a useful package.

When I use `sjp.lmer()` on an object of class `lmerMod`, the following warning appears:

> This function will be removed in future versions of sjmisc and has been moved to package 'sjlabelled'. Please use sjlabelled::get_label() instead.This function will be removed in future versions of sjmisc and has been moved to package 'sjlabelled'. Please use sjlabelled::get_label() instead.

Should this appear when using `sjp.lmer` directly from `sjPlot` (not `sjmisc` nor `sjlabelled`)?

**Comment by strengejacke** [comment]
It's just a warning about method being deprecated soon. The labelling functions moved from pkg sjmisc to pkg sjlabelled. I'm planning an intermediate update for sjPlot this week, where pkg dependencies are updated and these warnings disappear.
