### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mj1987** [strengejacke/sjPlot#261]
Hello - I had installed the packages previously and everything worked out great. Upon restarting R, I ran into Error: Command Failure (1). I installed all the packages as you had suggested to avoid any dependencies, to no avail - what's going on? I only need to use the sjPlot and sjmisc packages for sjt.glmer - Thank you!

library(devtools)
library(multcomp)
devtools::install_github("strengejacke/sjlabelled")
devtools::install_github("strengejacke/sjstats")
devtools::install_github("strengejacke/sjmisc")
devtools::install_github("strengejacke/ggeffects")
devtools::install_github("strengejacke/sjPlot")

The command I had run, and it worked, but is now not running at all due to above package errors:
sjt.glmer(fit5,fit6,
         depvar.labels = c("UG",
                                     "Lack of Knowledge"),
         remove.estimates = c(2:7),
         pred.labels = c("Monthly Expenditure",
                             "Total Households",
                             "Higher Education",
                             "Scheduled",
                             "Distance"),
         string.pred= "Predictors",
string.dv="Dependent Variables",
string.interc="Bihar", 
         group.pred=TRUE,
         exp.coef=TRUE,
         p.numeric=FALSE,
         emph.p=TRUE,
         separate.ci.col=FALSE,
         newline.ci=TRUE,
         show.se=TRUE,
         show.icc=TRUE,
         show.re.var=TRUE,
        show.loglik=FALSE,
         show.aic = FALSE,
         show.aicc = FALSE,
         show.dev=TRUE)

**Comment by strengejacke** [comment]
I'm not sure about the origin of this error. You could try to remove the packages and reinstall all from CRAN, the CRAN versions are pretty up to date.

**Comment by strengejacke** [comment]
Any news on this issue?
