### ISSUE TITLE
Error when installing sjplot

### ISSUE THREAD

**Issue by esp112** [strengejacke/sjPlot#262]
Hi, I have used successfully sjplot at work , but trying to do so at home I got this error. I am a beginner in R, so I just copied the same commands. I have tried previous issues, but I did not get any solution to this:

> library(sjPlot)
Error: package or namespace load failed for ‘sjPlot’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘TMB’

**Comment by strengejacke** [comment]
Try to install `glmmTMB` with dependencies (`install.packages("glmmTMB", dependencies = TRUE)`).

**Comment by esp112** [comment]
Great, that solved it, thanks a lot!!
