### ISSUE TITLE
make sjt.glmer() or have sjt.lmer() support objects from lme4::glmer

### ISSUE THREAD

**Issue by DHLocke** [strengejacke/sjPlot#263]
When applying sjt.lmer() to a glmer() object this error is returned

"Error in apply(all.coefs, 1, function(x) length(unique(x))) : 
  dim(X) must have a positive length"

When applying sjt.glmer() [is this a function?] to a glmer() object this error is returned

Error in UseMethod("fixef") : 
  no applicable method for 'fixef' applied to an object of class "logical"

sjt.lmer() is such a useful function, I wish I could do the same with glmer model.s

**Comment by strengejacke** [comment]
It usually works with glmer as well. Could you provide a reproducible example?

**Comment by DHLocke** [comment]
Thanks Daniel.

How does the below look?

- Dexter

I've worked up this repex:

# repex for sjt.plot
# more or less replicates my data
testDF <- data.frame(site = rep(1:51, each=2),
                     city = c(rep("A", times = 42), rep("B", times = 60)),
                     trx  = rep(c("X", "Y")),
                     rich = rpois(102, 12.28))

# maybe rpois is incorrect? My actually data has this distribution:
# Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
# 1.00   11.00   18.00   22.12   28.00  116.00

# looks like my bassic set up
head(testDF)

# I have count data, this specifies a model implicitly assuming normal dist
wrongTest <- lmer(log(rich + 1) ~ trx*city + (1 | site),
            data=testDF, REML=FALSE)

# here is the actual model I'm interested in
Test <- glmer(rich ~ trx*city + (1 | site),
              data=testDF, family=poisson)

sjt.lmer(Test)                       # returns error, as reported earlier
sjt.lmer(Test, wrongTest)     # same here

**Comment by DHLocke** [comment]
Sorry, the toy example does work when "stj.lmer" is replaced with
"stj.glmer".

Apologies, and thanks again for a great package!
Dexter

**Comment by strengejacke** [comment]
So is this issue solved?

**Comment by DHLocke** [comment]
Yes. Thank you for looking into this, and sorry to raise a moot point.

- Dexter
