### ISSUE TITLE
Add white background for rstudio 1.1.331

### ISSUE THREAD

**Issue by robsalasco** [strengejacke/sjPlot#264]
The new dark interface for rstudio rocks! but sjt.* needs a white background to works well with it
Thank you!

<img width="475" alt="captura de pantalla 2017-08-14 a la s 14 44 48" src="https://user-images.githubusercontent.com/2642107/29283941-3ba3cf24-80ff-11e7-9cce-6cb409503126.png">

**Comment by strengejacke** [comment]
Ok, I must see if I can overwrite the black bg in the viewer pane.
