### ISSUE TITLE
sjPlot package gives error after upgrading tidyr from 0.6.3 to 0.7

### ISSUE THREAD

**Issue by atrpie** [strengejacke/sjPlot#265]
After upgrading tidyr from 0.6.3 to 0.7 functions like sjp.xtab produce error: Error in grpcount + 1 : could not find function "+".  Reverting to tidyr 0.6.3 fixes the problem

**Comment by strengejacke** [comment]
Yes, I know. I was in contact with the maintainer, it's related to [this issue](https://github.com/tidyverse/tidyr/issues/337). I know how to fix it, but was in holiday. An sjPlot-update is in preparation.
