### ISSUE TITLE
Support for glmmTMB

### ISSUE THREAD

**Issue by knomoto** [strengejacke/sjPlot#267]
Hello,
First of all, thank you for developing such a nice package. It is beautiful and very useful!
Do you have any plan to support for the output of glmmTMB (sjp and sjt)?
Best,
Kensaku

**Comment by strengejacke** [comment]
Yes, glmmTMB will be supported. Output of estimates is based on `broom`, and I will add own tidyers for models not available in broom yet.

For marginal effects, glmmTMB is already supported (via `ggeffects`-package, which will be used by sjPlot in a forthcoming update).

The timeline is:
- submit sjPlot to CRAN today or tomorrow, to fix tidyr issues
- finish the generic `plot_model`-function, which is a replacement for "sjp.lm", "sjp.glm", "sjp.glmer" and so on -> release on CRAN in September
- Revise table functions, to create a generic table function as well (release probably October or so).

**Comment by knomoto** [comment]
Cool! Looking forward to using it! Thanks! Kensaku
