### ISSUE TITLE
PLM not working

### ISSUE THREAD

**Issue by adamlauretig** [strengejacke/sjPlot#268]
Hi, this package is really cool! 

I'm running into a small problem, though.  When I run the following code:
`srun.fe3 <- plm(formula = bsa ~ usbilateralinvtreaty + trips + bsa_break + 
  ustr + copyrighttreaty + prefusa_exp + log(gdpc2010) + yr_sch_i + ustr*prefusa_exp +
  spatial.gdpsim + spatial.regionalsim  + time.linear, 
  data = inuse.pruned.bsaonly.imputed.rda, effect = "individual", model = "within", 
  index = tscs)
summary(srun.fe3)

sjp.int(srun.fe3, type = "cond", plevel = .95)`

I get the following error:
`
Error in UseMethod("family") : 
  no applicable method for 'family' applied to an object of class "c('plm', 'panelmodel')"
`

I saw this had been an issue in the past. Any idea why it might be cropping up again?  Everything here is up to date.

**Comment by adamlauretig** [comment]
Additionally, this may help diagnostics, when I run: `sjPlot:::sjp.eff.int(srun.fe3, type = "eff", plevel = .95)
`
it returns `Error in mod.matrix %*% mod$coefficients[!is.na(coef(mod))] : 
  non-conformable arguments
In addition: Warning messages:
1: In factor.cols & stranger.cols :
  longer object length is not a multiple of shorter object length
2: In (!factor.cols) & stranger.cols :
  longer object length is not a multiple of shorter object length`

**Comment by strengejacke** [comment]
Could you try [ggeffects](https://github.com/strengejacke/ggeffects)? I have tested some plm models, and they should work with ggeffects. ggeffects will be the workhorse for all marginal effects and interaction plots in the next sjPlot-update.

**Comment by strengejacke** [comment]
should work with `plot_model()`.

**Comment by yl17124** [comment]
Hi Daniel  
I also have an issue to compute marginal effects when I use plm package. It pop ups an error me indicating the term was not found in model terms. 
For example, 
when I regressed this:
model_noneffects <- log(GrantPerCapita)  ~  ProportionMayorsAsMinister + ProportionMayorsAsMembers  + Unemplyed + LargeMunicipalities 
pooled <- plm(model_noneffects, data=tidy_data_plm, index =  c("ID", "year"), model='pooling')

and take `pooled` in to  ggeffects 
ggpredict(pooled, terms = "ProportionMayorsAsMinister") %>% plot()
It show this:
 `ProportionMayorsAsMinister` was not found in model terms. Maybe misspelled?
Error in eval(predvars, data, env) : 
  object 'ProportionMayorsAsMembers' not found
a couple of days, it worked perfectly but now I am not able to run it. 
However, it still works perfectly with lm() function 

Thanks
David

**Comment by strengejacke** [comment]
do you have a reproducible example?
