### ISSUE TITLE
pred.labels not working after sjt.glmer

### ISSUE THREAD

**Issue by trcm0** [strengejacke/sjPlot#270]
I'm attempting to print the output from my mixed-effects logistic regression. And I am running into two issues with the syntax. 

The first is that I cannot seem to label my independent variables.  I am using pred.labels=c("NAME", "NAME"). While I have no issues running the code, the output in the viewer does not reflect the labels I put in.  What am I doing wrong?

The second challenge is that one of my independent variables ("session") is a factor variable comprising of multiple levels. This variable is a "nuissance variable" so to speak. I am not interested in it. I would like my regression table NOT to show all the different levels of this factor, but rather to include the effects of the factor itself (overall). How do I do this? 

Code here:
sjt.glmer(model, pred.labels = c("CDT",
                          "LCT", 
                          "Age",
                          "Sex", 
                          "AF History",
                          "Session",
                          "Region") )

**Comment by strengejacke** [comment]
I need some more information. Could you send me the data and R code to fit the model?

Or maybe this example here helps:
http://strengejacke.de/sjPlot/sjt.lm/
See example at the very bottom, where custom labels are provided for independent variables. Note that each "estimates" needs an own label.

**Comment by trcm0** [comment]
Hi Daniel,
Thanks for the quick reply!

Here is the R code for the table:

sjt.glmer(m1, p.numeric = FALSE, show.dev=FALSE, digits.est=3,
          digits.ci=3, string.est = "OR", show.re.var=TRUE,
          show.family=TRUE, group.pred=TRUE,
          pred.labels = c("CDT",
                          "LCT",
                          "Age",
                          "Sex",
                          "AF History",
                          "Session",
                          "Region") )

I can't send you the data for confidentiality/security reasons. What else
can I provide for context?
Also, is my reply here a direct email to you or is it an automatic posting
on the forum?

Tracey

**Comment by strengejacke** [comment]
The reply is automatically posted on GitHub.
Have you followed my suggestion in my previous answer? I guess that might solve your problem.
