### ISSUE TITLE
Error in b * sx : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by jameshogan** [strengejacke/sjPlot#272]
I'm reporting on an error when I try to run sjt.lmer() on a negative binomial glmm.  

the error message is: Error in b * sx : non-numeric argument to binary operator

not sure what that means or how to interpret it.  
I would like to run that function, which is very useful.
Thanks for sharing your code & nice package!  GO R!

**Comment by strengejacke** [comment]
Have you tried `sjt.glmer()`?

**Comment by jameshogan** [comment]
yes.  that is the error returned when I run sjt.glmer on a glmer.nb() model.  the model has 11 fixed effects, 6 of which are interactions, and 3 random intercept terms.
