### ISSUE TITLE
Save temporary html file

### ISSUE THREAD

**Issue by lingchuding** [strengejacke/sjPlot#273]
@strengejacke Hi, I am a novice of R. These days I am using your package "sjPlot" and I find it is really useful. It improves my efficiency to obtain the results from analyses in R, especially when I am running multilevel models. Thanks for your genius work, which makes my research life easier! However, for the time being, I encounter two questions and hope to get suggestions from you:
 
1. How to save the HTML file to a specific directory when using sjt.lmer ()? In the options of this function, FILE is set as NULL by default. But if I want to save this temporary HTML file, what should I do?
 
2. For some reasons, I want to convert the temporary HTML file into plain text file (.txt) and save it to a specific directory. Maybe this question is not directly related to your package, but I hope to get some suggestions from you. Do you have any ideas about how to realize it?
 
I am looking forward to your reply. Thanks!

**Comment by strengejacke** [comment]
For 1), simply specifiy a filename: 

```
library(sjmisc)
data(efc)
sjt.frq(efc$e42dep, file = "test.html")
```

For 2), I would either save the HTML as txt, but that's manually. Or use a web-scraper-package that allows you to save HTML content as text, maybe rvest?

**Comment by lingchuding** [comment]
Thanks!
