### ISSUE TITLE
Displayed estimates of fixed effects in sjp.glmer are different from the model summary

### ISSUE THREAD

**Issue by AliceBaniel** [strengejacke/sjPlot#275]
I was thinking of using sjp.glmer to do a forest plot of the fixed effects of a glmm model that I'm running with a Poisson error. However, the estimates of the fixed effects displayed in the forest plot (when using sjp.glmer and type="fe") are not the same that the ones displayed by the summary of my model. In the help of the sjp.glmer function, it's indeed written that type="fe" give "odds or incidents ratios of fixed effects" so I guess the estimates are transformed. 

Is there a way to show the raw estimates (as shown in the summary)? 

see example:
library(lme4)
library(sjmisc)
data(efc)
efc$hi_qol <- dicho(efc$quol_5)
efc$grp = as.factor(efc$e15relat)
levels(x = efc$grp) <- get_labels(efc$e15relat)
mydf <- data.frame(hi_qol = efc$hi_qol,
                   sex = to_factor(efc$c161sex),
                   c12hour = efc$c12hour,
                   neg_c_7 = efc$neg_c_7,
                   grp = efc$grp)
# fit glmer
fit2 <- glmer(hi_qol ~ sex + c12hour + neg_c_7 + (1 | grp),
              data = mydf, family = binomial("logit"))

summary(fit2) **#here the estimate of neg_c_7 is  -0.22**
sjp.glmer(fit2, type = "fe") **#here the estimate of neg_c_7 is 0.80**

Many thanks!

**Comment by strengejacke** [comment]
For models with log-link, the exponentiated estimates (odds ratios) are displayed. In the forthcoming update, there's a generic [plot_model()](https://github.com/strengejacke/sjPlot/blob/master/R/plot_model.R) function, where you have an argument `exponentiate`, which allows you to plot the log-odds.
