### ISSUE TITLE
rounding of p values

### ISSUE THREAD

**Issue by ianhussey** [strengejacke/sjPlot#278]
I think the rounding of p values might not meet APA formatting advice. For my data:

`sjt.lmer(model_1)`

- returns "p < .001"

`sjt.lmer(model_1, digits.p = 4)`

- returns "p = .001498", which is only < .001 if you're rounding down. 

Rounding is sometimes seen as on the p hacking spectrum (e.g., counting p = .054 as p < .05). I could be mistaken of course.

**Comment by strengejacke** [comment]
hm, strange. What does `sjstats::p_value(model_1)` return?
The code explicitly checks if the p-value is < 0.001. Do you have a reproducible example?
