### ISSUE TITLE
sjt.lmer does not seem to output variance for random slopes

### ISSUE THREAD

**Issue by jrosen48** [strengejacke/sjPlot#279]
Hi, thanks for this package, which makes my research life so much better!

I am using `sjt.lmer()` to display model summary output, but the function does not seem to output variance estimates for random slopes. For example (below), the `summary()` method prints a varying `age` by `Subject` variance of `0.05`, but this does not appear in the `sjt.lmer()` output. Is it possible to do so using `sjt.lmer()`? Thank you.
``` r
library(lme4)
#> Warning: package 'lme4' was built under R version 3.4.2
#> Loading required package: Matrix
library(sjPlot)
#> Warning in checkMatrixPackageVersion(): Package version inconsistency detected.
#> TMB was built with Matrix version 1.2.10
#> Current Matrix version is 1.2.11
#> Please re-install 'TMB' from source or restore original 'Matrix' package
#> #refugeeswelcome

data(Orthodont,package="nlme")

m <- lmer(distance ~ age + (age|Subject), data = Orthodont)

summary(m)
#> Linear mixed model fit by REML ['lmerMod']
#> Formula: distance ~ age + (age | Subject)
#>    Data: Orthodont
#> 
#> REML criterion at convergence: 442.6
#> 
#> Scaled residuals: 
#>     Min      1Q  Median      3Q     Max 
#> -3.2231 -0.4938  0.0073  0.4722  3.9160 
#> 
#> Random effects:
#>  Groups   Name        Variance Std.Dev. Corr 
#>  Subject  (Intercept) 5.41509  2.3270        
#>           age         0.05127  0.2264   -0.61
#>  Residual             1.71620  1.3100        
#> Number of obs: 108, groups:  Subject, 27
#> 
#> Fixed effects:
#>             Estimate Std. Error t value
#> (Intercept) 16.76111    0.77525  21.620
#> age          0.66019    0.07125   9.265
#> 
#> Correlation of Fixed Effects:
#>     (Intr)
#> age -0.848

sjt.lmer(m)
#> Computing p-values via Kenward-Roger approximation. Use `p.kr = FALSE` if computation takes too long.
```

<table style="border-collapse:collapse; border:none;border-bottom:double;">
<td style="padding:0.2cm; border-top:double;">
 
</td>
<td style="border-bottom:1px solid; padding-left:0.5em; padding-right:0.5em; border-top:double;">
 
</td>
<td style="padding:0.2cm; text-align:center; border-bottom:1px solid; border-top:double;" colspan="3">
distance
</td>
</tr>
<tr>
<td style="padding:0.2cm; font-style:italic;">
 
</td>
<td style="padding-left:0.5em; padding-right:0.5em; font-style:italic;">
 
</td>
<td style="padding:0.2cm; text-align:center; font-style:italic; ">
B
</td>
<td style="padding:0.2cm; text-align:center; font-style:italic; ">
CI
</td>
<td style="padding:0.2cm; text-align:center; font-style:italic; ">
p
</td>
</tr>
<tr>
<td colspan="5" style="padding:0.2cm; text-align:left; border-top:1px solid; font-weight:bold; text-align:left;">
Fixed Parts
</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left;">
(Intercept)
</td>
<td style="padding-left:0.5em; padding-right:0.5em; ">
 
</td>
<td style="padding:0.2cm; text-align:center; ">
16.76
</td>
<td style="padding:0.2cm; text-align:center; ">
15.24 – 18.28
</td>
<td style="padding:0.2cm; text-align:center; ">
&lt;.001
</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left;">
age
</td>
<td style="padding-left:0.5em; padding-right:0.5em;">
 
</td>
<td style="padding:0.2cm; text-align:center; ">
0.66
</td>
<td style="padding:0.2cm; text-align:center; ">
0.52 – 0.80
</td>
<td style="padding:0.2cm; text-align:center; ">
&lt;.001
</td>
</tr>
<tr>
<td colspan="5" style="padding:0.2cm; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; font-weight:bold; text-align:left; padding-top:0.5em;">
Random Parts
</td>
</tr>
<tr>
<td style="padding:0.2cm; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;">
σ<sup>2</sup>
</td>
<td style="padding-left:0.5em; padding-right:0.5em;">
 
</td>
<td style="padding:0.2cm; text-align:center; padding-top:0.1cm; padding-bottom:0.1cm;" colspan="3">
1.716
</td>
</tr>
<tr>
<td style="padding:0.2cm; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;">
τ<sub>00, Subject</sub>
</td>
<td style="padding-left:0.5em; padding-right:0.5em;">
 
</td>
<td style="padding:0.2cm; text-align:center; padding-top:0.1cm; padding-bottom:0.1cm;" colspan="3">
5.415
</td>
</tr>
<tr>
<td style="padding:0.2cm; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;">
ρ<sub>01</sub>
</td>
<td style="padding-left:0.5em; padding-right:0.5em;">
 
</td>
<td style="padding:0.2cm; text-align:center; padding-top:0.1cm; padding-bottom:0.1cm;" colspan="3">
-0.609
</td>
</tr>
<tr>
<td style="padding:0.2cm; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;">
N<sub>Subject</sub>
</td>
<td style="padding-left:0.5em; padding-right:0.5em;">
 
</td>
<td style="padding:0.2cm; text-align:center; padding-top:0.1cm; padding-bottom:0.1cm;" colspan="3">
27
</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
ICC<sub>Subject</sub>
</td>
<td style="padding-left:0.5em; padding-right:0.5em;">
 
</td>
<td style="padding:0.2cm; text-align:center; padding-top:0.1cm; padding-bottom:0.1cm;" colspan="3">
0.759
</td>
</tr>
<tr>
<td style="padding:0.2cm; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;">
Observations
</td>
<td style="padding-left:0.5em; padding-right:0.5em; border-top:1px solid;">
 
</td>
<td style="padding:0.2cm; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center; border-top:1px solid;" colspan="3">
108
</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / Ω<sub>0</sub><sup>2</sup>
</td>
<td style="padding-left:0.5em; padding-right:0.5em;">
 
</td>
<td style="padding:0.2cm; text-align:center; padding-top:0.1cm; padding-bottom:0.1cm;" colspan="3">
.866 / .861
</td>
</tr>
</table>

**Comment by strengejacke** [comment]
I focussed on the statistics that are most common in my research field. In general, it's of course possible to add other statistics as well (which are provided by `sjstats::re_var()`).

I must think of a way how to easily customize output of the random effects statistics.

**Comment by strengejacke** [comment]
Seems to be related to https://github.com/strengejacke/sjPlot/issues/209 and https://github.com/strengejacke/sjPlot/issues/251.

**Comment by michelersmith** [comment]
Wondering if this issue has been resolved? I would like to include variance for a random slope in an sjt.glmer table output.
Is it possible to add sjstats::re_var()) into the sjt.glmer function?

**Comment by strengejacke** [comment]
I'm working on it. I revised the table-output-function, being "generic" now (see `tab_model()`). I implemented printing the fixed effects, now I'm heading over for random effects and model statistics.
