### ISSUE TITLE
Warning when loading sjPlot: "Package version inconsistency detected."

### ISSUE THREAD

**Issue by jrosen48** [strengejacke/sjPlot#281]
I see the following warning when loading `sjPlot`:

``` r
library(sjPlot)
#> Warning in checkMatrixPackageVersion(): Package version inconsistency detected.
#> TMB was built with Matrix version 1.2.10
#> Current Matrix version is 1.2.11
#> Please re-install 'TMB' from source or restore original 'Matrix' package
#> Install package "strengejacke" from GitHub (`devtools::install_github("strengejacke/strengejacke")`) to load all sj-packages at once!
```

I tried `devtools::install_version("Matrix", version = "1.2.10", repos = "http://cran.us.r-project.org")` and `devtools::install_github("strengejacke/strengejacke")`, but this warning still appeared. Any tips on addressing this?

**Comment by strengejacke** [comment]
have you tried installing "TMB" from source?

`install.packages("file_to_tmb_source.tz", repos = NULL, type = "source")`

**Comment by jrosen48** [comment]
Thank you, no, I had not.

I just tried:

1. Downloading the file for "Package source" for TMB from [here](https://cran.r-project.org/web/packages/TMB/index.html) - this was using the file that ended in `.tar.gz`. 

And then installing using `install.packages("file_to_tmb_source.tz", repos = NULL, type = "source")` (this did not install the package).

2. Downloading the file for "OS X El Capital" binary - this one ended in `.tgz`.

And then installing this using the same command as above. This worked, but the same warning still appears. Can you suggest which file I should download (or what you could recommend I try)?

Thank you, again

**Comment by strengejacke** [comment]
I still haven't solved the issue for myself, I'm just ignoring the warning. When I find a solution, I'll post it here...

**Comment by jemus42** [comment]
My guess is that we might have to wait for new builds of TMB with the appropriate Matrix version to be available on CRAN (I, too, have tried various installations of TMB).

**Comment by jemus42** [comment]
My guess is that we might have to wait for new builds of TMB with the appropriate Matrix version to be available on CRAN (I, too, have tried various installations of TMB).

**Comment by strengejacke** [comment]
I just updated pkg "Matrix" from CRAN, then I completely removed TMB from my installed packages, downloaded the TMB-source from CRAN and installed locally from source package - the warning disappears for me now!

Anyone who can confirm this "workaround"?

**Comment by hbahamonde** [comment]
Yes, the warning does disappear. Thanks.
