### ISSUE TITLE
getting weird behaviour from sjPlot

### ISSUE THREAD

**Issue by tsbaguley** [strengejacke/sjPlot#282]
So trying to reproduce the example here:

https://strengejacke.wordpress.com/2017/10/11/more-support-for-bayesian-analysis-in-the-sj-packages-rstats-rstan-brms/

Get various error messages

`> hdi(m1)
# A tibble: 34 x 3
                            term     hdi.low    hdi.high
                           <chr>       <dbl>       <dbl>
 1                   b_Intercept  3.82045279  4.56513852
 2       b_FoodTreatmentSatiated -0.27469182 -0.15185447
 3                 b_ArrivalTime -0.09604503 -0.06654188
 4               b_SexParentMale -0.07780799  0.03903583
 5            sd_Nest__Intercept  0.18845603  0.35607907
 6                            zi  0.22863812  0.28731520
 7  r_Nest.AutavauxTV.Intercept. -0.40100704 -0.09059129
 8      r_Nest.Bochet.Intercept. -0.09164222  0.23203185
 9 r_Nest.Champmartin.Intercept. -0.26271866  0.07578086
10     r_Nest.ChEsard.Intercept.  0.22066585  0.50211468
# ... with 24 more rows
> theme_set(theme_sjplot())
> plot_model(m1, axis.lim = c(.6, 1.4))
Error: `.data` must have 34 rows, not 33`

> theme_set(theme_sjplot())
> plot_model(m1, axis.lim = c(.6, 1.4))
Error: `.data` must have 34 rows, not 33

I think I'm doing something stupid, but just in case ...

**Comment by tsbaguley** [comment]
OK. Seems to work after installing sjstats, sjlabelled and ggeffects. Will update and/or close shortly ...

**Comment by strengejacke** [comment]
Ok, thanks!

**Comment by tsbaguley** [comment]
I'm being stupid again. Is there a simple way to plot a logistic regression HDI
on a probability scale (switching between odds and log odds is easy)?

Thom

**Comment by strengejacke** [comment]
That's currently not implemented. You want something like `plogis()` instead of `exp()` for the coefficients?

**Comment by tsbaguley** [comment]
Yes. What I'm doing is fitting a cell means style model y ~ 0 + factor1 : factor
2 and then plotting the coefficients transformed to a probability scale. More
generally it might be useful to be able to specify a function to transform the
scale. So arguments of the form transform = c('exp', 'log', 'plugs').

Possibly I'm the only one who would ever need this ...

Thom

**Comment by strengejacke** [comment]
ok, I implemented such a feature. Argument `exponentiate` has been replaced with `transform`, where you can name any function (as character vector, e.g. `transform = "plogis"` or `transform = "dnorm"`) - no matter if that function makes sense or not.

**Comment by tsbaguley** [comment]
That’s brilliant - I’ll try it out tonight!

Thom

**Comment by tsbaguley** [comment]
Worked perfectly. 

This is beautiful!

Thom
