### ISSUE TITLE
Insufficient length of color palette provided

### ISSUE THREAD

**Issue by DeLaRiva** [strengejacke/sjPlot#283]
Hi,

I'm again using your astonishing package and try to set up a few plots according to an example I found on https://strengejacke.wordpress.com/2014/11/18/visualizing-generalized-linear-mixed-effects-models-part-2-rstats-lme4/ .
I can create all plots up to # plot probability curve of fixed effects 

`My model is  fit2.lme <- lmer(log(log(Amplification)) ~ poly(Voltage, 3) + (poly(Voltage, 1) | Serial_number), data = APD)`

and when I run` > sjp.glmer(fit2.lme, type = "fe.pc")` I get
```
Warning message:
Insufficient length of color palette provided. 2 color values needed. 
```

Can you please give me an advice? Thanks a lot in advance!

**Comment by strengejacke** [comment]
Do you have a reproducible example? Else, try playing with the `geom.colors`-argument.

**Comment by DeLaRiva** [comment]
Yes, thank you for have a looking at it! Unfortunately, `geom.colors` didn't affect anything.

I've attached a minimal script + its data. Thank you very much in advance!
[script.zip](https://github.com/strengejacke/sjPlot/files/1402606/script.zip)

**Comment by strengejacke** [comment]
Ok, first, you should create a response that is already transformed. Then, use `plot_model()`:

Example:

```
APD$l_Amplification <- log(log(APD$Amplification))
fit1.lme <- lmer(l_Amplification ~ poly(Voltage, 3) + (poly(Voltage, 1) | Serial_number), data = APD)
plot_model(fit1.lme, type = "slope")
plot_model(fit1.lme, type = "slope", colors = "Accent")
```
