### ISSUE TITLE
Sudden error message

### ISSUE THREAD

**Issue by jgm2017** [strengejacke/sjPlot#284]
Hi, I'm running sjt.lmer. Yesterday it worked beautifully, but today I am getting this error (and have not made any changes):

Error in model.frame.default(formula = resp_val(x) ~ stats::fitted(x),  : 
  invalid type (NULL) for variable 'resp_val(x)'

Can you help explain this error to me?

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by IssieWinney** [comment]
Hi, 

I also received this error message when attempting to make a table from a model of the form lmer(log(variable) ~ fixed + random). Creating a new variable to use in the model instead of using the function log(variable) within the model fixed the problem.

Thanks!

**Comment by strengejacke** [comment]
Should be fixed in *sjstats*, i.e. if you update *sjstats* from GitHub, this issue should be solved.
