### ISSUE TITLE
Feature request: in tables, align numbers vertically on the decimal point

### ISSUE THREAD

**Issue by johnfrombluff** [strengejacke/sjPlot#285]
Firstly, thanks for this totally awesome package! There is only one thing I'd like to see improved, as described in the subject line. I'm not sure if this is possible using HTML/CSS though.  If it is, I'm happy to try to code it myself and submit a patch, if you could provide a pointer to get started.

Cheers,

John

**Comment by strengejacke** [comment]
I'm not sure if I fully understand your request... What kind of alignment do you mean?

**Comment by johnfrombluff** [comment]
Sorry!  I'm not sure if this will render properly, but I'll try to illustrate:

This is ugly, and goes against style guides of many journals:
1.23
11.45
100.1

Aligning vertically on the decimal point looks like this:
```
  1.23
 11.45
100.1
```
If that's not possible, it could be faked by right-aligning and forcing the same number of decimal places on the right of the decimal point. (And including some padding on the right, probably).

Does that make sense? And if it's a hassle, feel free to ignore this request. It's a small niggle.

Thanks again for this awesome package,

John

**Comment by strengejacke** [comment]
Ok, understand. Right alignment should work with `CSS`. But adjusted padding / margin to align by decimal points seems difficult to impossible - it varies by font-size, for instance.

**Comment by johnfrombluff** [comment]
Yes, I understand. You can close this issue, if you like. Thanks for your reply! :-)

**Comment by strengejacke** [comment]
Just curious, do you have example, where journals require this style? And how do they achieve this? you need to manually layout the table, and w/o a monospaced font, you can't do this in any word processor, either - or am I missing something?

**Comment by johnfrombluff** [comment]
You can close this issue, thanks. I'll try to solve it myself, and send you a patch if I succeed. Cheers!

**Comment by strengejacke** [comment]
Ok, thanks.
