### ISSUE TITLE
Provide argument to sjt.lmer() to print degrees of freedom from Kenward-Roger approximation?

### ISSUE THREAD

**Issue by jrosen48** [strengejacke/sjPlot#286]
`sjt.lmer()` provides (by default) the option to estimate p-values based on the Kenward-Roger degrees of freedom approximation. Is it possible to include not just the p-values but also the degrees of freedom they're based on in the output (e.g., `show.df = T`)?

**Comment by strengejacke** [comment]
`pbkrtest::get_Lb_ddf()` just returns a single value, so I think it would make sense to add that information somewhere in the table footer?

**Comment by strengejacke** [comment]
Ah, thanks for the reminder! I'll look at it, seems to be not much effort to implement. Have you any experience on performance differences, as @jacob-long pointet out?

**Comment by strengejacke** [comment]
Fixed, will commit tonight. It's included in the generic `tab_model()` function.

**Comment by jrosen48** [comment]
Yay!
