### ISSUE TITLE
sjp.setTheme down "could not find function "sjp.setTheme"

### ISSUE THREAD

**Issue by mkrasmus** [strengejacke/sjPlot#287]
Just tried running code that was working yesterday:
```
sjp.setTheme(theme = "539",
              geom.label.color = "black", 
              geom.label.size = 2.5,
              axis.textsize = .9, 
              axis.title.size = .9,
              legend.size = .7,
              legend.item.size = 1)
```

Came back with "could not find function "sjp.setTheme"

I checked the sjPlot package  (2.4.0) and while there is a sjPlot-themes there is no longer a sjp.setTheme. I've tried reinstalling sjPlot via CRAN and git with no luck.

**Comment by strengejacke** [comment]
It's been renamed to `set_theme()`. See [news file](https://github.com/strengejacke/sjPlot/blob/master/NEWS.md).
