### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by r-lehtonen** [strengejacke/sjPlot#288]
I see  the announce of the latest update, but are a installation error:
> install.packages("sjPlot")
Error in install.packages : missing value where TRUE/FALSE needed

**Comment by r-lehtonen** [comment]
I found a solution: install direct in R, without RStudio

**Comment by strengejacke** [comment]
ok, so is this issue solved? There must be something else, because installing via RStudio should usually work.

**Comment by r-lehtonen** [comment]
I try to install in another computer, with same R and RStudio versions and works perfectly. I don't know was occur in the first PC, but is solved.

**Comment by strengejacke** [comment]
ok, thanks.
