### ISSUE TITLE
save_plot

### ISSUE THREAD

**Issue by araikes** [strengejacke/sjPlot#290]
I have a question. I have a fresh R installation and added sj* to my package list because I love it so much. However, I went to save a plot and save_plot is not exported from the sjPlot namespace. Did it get removed?

**Comment by strengejacke** [comment]
Yes, I removed it because it's difficult to reliably set proper font sizes for print quality plots... However, if you think it offers more or other benefits than `ggplot2::ggsave()`, I could add it back.
