### ISSUE TITLE
integrate sunflowerplot into a sjp.glmer plot

### ISSUE THREAD

**Issue by vanitas80** [strengejacke/sjPlot#293]
Hi there!
I am trying to plot the result of a glmer model with sjp.glmer. It works great! The slopes are easy to get. Thank you for that!
But instead of jittering my data points around 0 and 100% I would like to show the frequency of points at each x-value as a sunflowerplot. Is it possible to integrate a sunflowerplot into a sjp.glmer-plot?

Cheers, vanitas

**Comment by strengejacke** [comment]
What do you mean by "sunflower" plot? A rug plot at the margins (like here: http://ggplot2.tidyverse.org/reference/geom_rug.html)?

**Comment by vanitas80** [comment]
By sunflower plots I mean something like here: https://www.google.de/imgres?imgurl=http%3A%2F%2F1.bp.blogspot.com%2F-R94VkPiNMzQ%2FTZDVGrTAeLI%2FAAAAAAAACyw%2Fmk9UyJ0XP8c%2Fs1600%2Fgalton%252Bsunflower.png&imgrefurl=http%3A%2F%2Fsas-and-r.blogspot.com%2F2011%2F03%2Fexample-832-histdata-package-sunflower.html&docid=cuZsEePbiLZ0mM&tbnid=dsetk-SGhbW7ZM%3A&vet=10ahUKEwjOydCK067XAhVJyKQKHXnbCeMQMwglKAAwAA..i&w=500&h=400&bih=958&biw=1280&q=sunflower%20plot&ved=0ahUKEwjOydCK067XAhVJyKQKHXnbCeMQMwglKAAwAA&iact=mrc&uact=8

The number of pedals of a flower is giving the frequenzy.

**Comment by sjPlot** [comment]
I'm not sure how you want to plot frequencies on a probability scale? Does this plot type work for glm as well?

**Comment by vanitas80** [comment]
What I can get is Plot like this:
![a](https://user-images.githubusercontent.com/33423048/33173130-2c16851c-d053-11e7-91fa-8083f2ac1f4b.png)
This graph I made by this code: 
sjp.glmer(Model, type="pred", vars=c("Variable1", "Variable2"), facet.grid=F, show.scatter=T)
But as I only have 1 and 0 the scatter does not really help. Instead of the data points I would like to show frequencies....with this sunflowerplot:
![b](https://user-images.githubusercontent.com/33423048/33173488-a431aba2-d054-11e7-9b86-ef3ec8d98d29.png)
Code for this: sunflowerplot(dat$Variable1, dat$Y-of Model)

Is it possible to combine these plots? I can also easily remove the data points in plot A. But how to integrate the sunflowerplot, I have no idea.

Is anyone knowing a way to do this?

Thanks a lot in advance!

**Comment by strengejacke** [comment]
I'm not sure if it's easy to implement such a plot-style, since this would require new geoms. But essential, a rug-plot is typically the choice to emphasize the counts of data points. You could, e.g., use *ggeffects* and add a rug-plot, like described in my answer here:

https://github.com/strengejacke/sjPlot/issues/299#issuecomment-345443200
