### ISSUE TITLE
Calculating Actual Predicted Probabilities with sjPlot in R

### ISSUE THREAD

**Issue by neutraltaurus** [strengejacke/sjPlot#294]
The `sjPlot` package in R plots predicted probabilities. One example, involving a generalized hierarchical model would be: 

`pred <- sjp.glmer(model1, type="fe.pc", vars=c("var1"), show.scatter=FALSE, show.ci=TRUE)`

Does the `sjPlot` package not include a function that  displays predicted probabilities for the different values of a variable  in a logistic hierarchical regression model, as Stata does with the `at` attribute? In other words, is there a way to learn the exact three values of y that correspond to three different values of x. The plot gives me a close idea, but not the exact values.

(One would expect `prnt.plot=FALSE` to display the results, but it does not.)

**Comment by strengejacke** [comment]
Please use `plot_model()` with `type = "pred"` or `type = "eff"` to print marginal effects (predicted probabilities), or use the **ggeffects**-packages. Actually, **sjPlot** simply wraps ggeffects for effect-plots.

I'll add a vignette on how to display marginal effects with sjPlot in the next update, but there is a detailed vignette for ggeffects: https://cran.r-project.org/web/packages/ggeffects/vignettes/marginaleffects.html
See section "Marginal effects at specific values or levels" on how to mimic the `at`-option from STata.

**Comment by strengejacke** [comment]
And there's also one example here:
https://strengejacke.wordpress.com/2017/08/27/marginal-effects-for-negative-binomial-mixed-effects-models-glmer-nb-and-glmmtmb-rstats/

**Comment by neutraltaurus** [comment]
Thanks for the reply.

I must note though that the below two codes did not produce the same results for me:

`sjp.glmer(model1, type="fe.pc", vars=c("var1"), show.scatter=FALSE, show.ci=TRUE)`

`plot_model(model3, type="eff", terms=c("var1"), show.scatter=FALSE, show.ci=TRUE)`

The curve had the same shape but did not reach as high on the y-axis in the plot with the `plot_model` function. Is `pred` or `eff` not an exact equivalent of `fe.pc`?

**Comment by strengejacke** [comment]
`fe.pc` plots the "relationship" between predictor and response, and ignores all other predictors in the model. `plot_model(type = "eff")` and `plot_model(type = "pred")` plot marginal effects, holding other predictors constant at their typical value. Using `type="fe.pc"` is discouraged, and I will remove this options, as it's simply a "scatterplot" between outcome and predictor.

See `?ggeffects::ggpredict` and `?ggeffects::ggeffect` for the difference between these two plot types (corresponding to `plot_model(type = "pred")` and `plot_model(type = "eff")`).

**Comment by neutraltaurus** [comment]
Thanks! That explains it.

PS: I agree that it is a good idea to remove `type="fe.pc"` as it can be misleading.
