### ISSUE TITLE
Could you add std error 

### ISSUE THREAD

**Issue by xieguagua** [strengejacke/sjPlot#295]
As some journals required , could you add separate.std error.col  option, so we could report std error in the same col. 
Thanks for your wonderful work.

**Comment by strengejacke** [comment]
For which functions? The table-functions already allow to print s.e.

**Comment by xieguagua** [comment]
Dear Author,
Thanks for your reply,
Like this , s.e in the same column.
Thanks.
Best Regards.





在 2017-11-11 14:01:15，"Daniel" <notifications@github.com> 写道：


For which functions? The table-functions already allow to print s.e.

**Comment by strengejacke** [comment]
Implemented in the current draft of `tab_model()`.
