### ISSUE TITLE
question regarding plot_model()

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjPlot#296]
Hi, i just played around with the new general plotting function and it works very well for me :) 
Is it also possible use robust standard errors, e.g. in a forest plot? I didn't find an option for that in the description.

**Comment by sjPlot** [comment]
Except for some own tidiers, I use `broom::tidy()` to get the data for plotting. I'm not sure whether robust s.e. are supported.
Maybe this issue is linked to https://github.com/strengejacke/sjPlot/issues/295 - I may think of an option to include se as well...

**Comment by methodds** [comment]
awesome, thanks! :)
