### ISSUE TITLE
PLM Model: Two Errors with "argument "offset" is missing, with no default"

### ISSUE THREAD

**Issue by hbahamonde** [strengejacke/sjPlot#298]
My data is country-year. Following the instructions of the ```plm``` package, the data have been converted to ```pdata.frame```. The data have only continuous/numeric variables.

The model is of the type:

```
devtools::install_github("strengejacke/sjPlot", force = TRUE)

model = plm(y ~ x1 + x2 + X3 * X4,
        index = c("country","year"),
        model = "within", 
        effect = "twoways", 
        data = df)
```

Now, I try three methods to make this work.

# Method 1
```
sjp.int(model, type = "eff", int.term = "X3:X4") # It does not work with "X3 * X4" either

```

which generates the following error:

```
Error in Effect.default(predictors, mod, vcov. = vcov., ...) : 
  argument "offset" is missing, with no default
```

# Method 2

```
plot_model(model, type = "eff", terms = "X3:X4") # It does not work with "X3 * X4" either

```

which generates a *similar* but **not the same error**:

```
Error in Effect.default(focal.predictors = terms, mod = model, xlevels = xl,  : 
  argument "offset" is missing, with no default
```

Common denominator is ```argument "offset" is missing, with no default```.

# Method 3

```
plot_model(model, type = "int")
```

which gets me

```
Error in crossprod(beta, t(X)) : non-conformable arguments
```

- At first, when I was getting these errors, I was using both the ```lag()``` and ```diff()``` operators. To rule out the error was due to the use of these operators, I lagged and differentiate these variables manually. Now, the variables enter the model lagged and differentiated, but manually, .e.g. without the use of operators.

**Any ideas on what might be going on?**

**Comment by strengejacke** [comment]
All three methods you described wrap the [effects-package](https://cran.r-project.org/package=effects), so it's probably an issue of that package. You could try plot-type _pred_: `plot_model(model, type = "pred", terms = c("X3, "X4")` (Note that each term goes into an own element of the character vector).

Does this work? If not, please provide a reproducible example.

For the difference between `type = "pred"` and `type = "eff"`, see `?ggeffects::ggpredict` and `?ggeffects::ggeffect`.

**Comment by hbahamonde** [comment]
Thanks.

It did not work. However, just for the record, when I changed the parameters in ```plm```, from ```model = "within"``` to ```model = "pooling"```, both:

```
plot_model(model, type = "pred", terms = c("X3", "X4"))
```

and

```
plot_model(model, type = "int", int.term = "X3:X4")
```

work.

Since ```summary(model)``` works just fine, I don't think ```model``` is ill-parametrized. As you say, there must be some issue with the ```effects``` package.

**Comment by strengejacke** [comment]
Do you have a reproducible example, or some sample data? I think I need to handle `within` and `pooling` differently.

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
I think, meanwhile this should work. Please check, and if not, re-open the issue with a reproducible example.

**Comment by benjaminLynch** [comment]
Hi,
I'm quite new to R and I'm having a problem plotting a plm regression model with an interaction term.

Call:
plm(formula = TQFB_Lead1 ~ LEV + SIZE + SalesGrowth + ROA + INSCON + 
    RandD0 + LGDPPC + ES_Score + FreedomhouseCL + ES_Score * 
    FreedomhouseCL, data = AADATAsetwithInst01, effect = "twoways", 
    model = "within")

When I try to plot it like so:
plot_model(QInstitution01b, type = "int", terms = c("ES_Score", "FreedomhouseCL"))

I get the error:
Error in crossprod(beta, t(X)) : non-conformable arguments

It works if I use a pooled model or lm() to estimate the regression.
This seems to be simularto the problem experienced above, any idea what's going on or what I can do to solve this issue?

Many thanks

**Comment by strengejacke** [comment]
Looks like the same problem as here: 
https://github.com/strengejacke/sjPlot/issues/594
