### ISSUE TITLE
support for pscl::zeroinfl in sjp.glm()?

### ISSUE THREAD

**Issue by arcruz0** [strengejacke/sjPlot#300]
Thanks for the wonderful package. I was wondering if it was possible to add support for pscl::zeroinfl() models in sjp.glm. 
Is there any workaround that I'm not aware of? I know it is supported by ggeffects, but that does not let me do everything I could with sjp.glm (for example, "forest" hazard ratios plots).
Thanks in advance!

**Comment by strengejacke** [comment]
Please use `plot_model()`. `sjp.lm()`, `sjp.glm()`, `sjp.lmer()`, `sjp.glmer()` and `sjp.int()` will become deprecated in the future, and will later be removed.

```r
library(sjPlot)
library(pscl)
data("bioChemists", package = "pscl")
fm_zip2 <- zeroinfl(art ~ . | ., data = bioChemists)
plot_model(fm_zip2)
```

![rplot](https://user-images.githubusercontent.com/26301769/33229847-b91fe2de-d1d7-11e7-9bcf-3d2dab339c98.png)
