### ISSUE TITLE
Error in cbind_all(x)  in Version 2.4.0

### ISSUE THREAD

**Issue by annlaurin** [strengejacke/sjPlot#301]
Hi,

I've updated to the most recent version of sjPlot (2.4.0), and the function sjt.lmer that worked earlier now gives an error message:

Error in cbind_all(x) : Argument 2 must be length 784, not 615
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> sjt.lmer -> sjt.lm
Execution halted

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by annlaurin** [comment]
[prepared_data.txt](https://github.com/strengejacke/sjPlot/files/1504160/prepared_data.txt)
```r
rm(list=ls())

library(lme4)
library(sjPlot)

data17 <- read.table("prepared_data.txt", sep = ";", 
                   encoding = "UTF-8", 
                   na.strings = "NA", header = TRUE)

data17$navigation <- scale(data17$navigation)
data17$tech.quality <- scale(data17$tech.quality)
data17$lunch <- scale(data17$lunch)
data17$mean.eval <- scale(data17$mean.eval)
data17$Next.JPoint <- as.factor(data17$Next.JPoint)


recommend_lb.full <- lm(recommend ~ navigation + 
                          tech.quality + lunch.bin + 
                          mean.eval + city.bin +
                          venue + 
                          no.other.conf,
                        data = data17)
summary(recommend_lb.full)
sjt.lmer(recommend_lb.full)
```

**Comment by strengejacke** [comment]
Ok. It's because `scale` produces a matrix instead of a vector, and this does not work properly with my latest *sjstats*-update. I suggest standardizing using `sjmisc::std()`, then it works:

```r
library(lme4)
library(sjmisc)
library(sjPlot)

data17 <- read.table(
  "~/Downloads/prepared_data.txt",
  sep = ";",
  encoding = "UTF-8",
  na.strings = "NA",
  header = TRUE
)

data17 <- data17 %>%
  std(navigation,
      tech.quality,
      lunch,
      mean.eval,
      Next.JPoint,
      append = T)

recommend_lb.full <- lm(
  recommend ~ navigation_z +
    tech.quality_z + lunch.bin +
    mean.eval_z + city.bin +
    venue +
    no.other.conf,
  data = data17
)

summary(recommend_lb.full)
sjt.lm(recommend_lb.full)
```

**Comment by annlaurin** [comment]
Thanks!
A side question - sorry if it's wrong to ask it in a closed thread, I just don't know the appropriate place to ask this - were you perhaps planning to extend summarizing models nicely to polr() models as well? 
Thanks for what you do!

**Comment by strengejacke** [comment]
Yes, polr-models are already supported in `plot_model()`,  and the revised function for table-output will be `tab_model()`, which I'm currently working on.

**Comment by annlaurin** [comment]
That's great news, thanks!
