### ISSUE TITLE
sjp.lmer with type = "rs.ri" gives misleading results

### ISSUE THREAD

**Issue by anthonycrane** [strengejacke/sjPlot#302]
First off, thank you for this amazing package! I've been using R for numerous years and this is exactly what I've been waiting for.

I believe I may have found a slight bug in how sjp.lmer computes the regression lines for the random parts of the model. As the documentation says, "regression lines are computed as global intercept + random intercept + random slope". But wouldn't a more meaningful plot show "global intercept + random intercept + **global slope** + random slope"?

When I initially used this function I was interpreting the plotted lines as the _absolute_ slopes / intercepts for each cluster; however, the slopes of the lines which are plotted are the _deviation_ away from zero (just the random effect).

I'm (most people?) typically interested in plotting the fitted lines for each hierarchical cluster.  

Take this as a (very ugly) example. I generate longitudinal data from the following model:

y_{ij} = (R + r_i) * X_ij + e_ij

Where, r_i ~ N(0, 5) and e_ij ~ N(0, 0.01)

```
library(dplyr)
library(lme4)
library(purrr)
library(sjPlot)

set.seed(100)

mean_slope <- 10
random_deviation <- rnorm(10, 0, 5)
i <- 1:10
x <- 1:10

temp <-
  do.call(rbind,
          map2(.x = mean_slope, .y = random_deviation, .f = function(x, y) (x + y) * 1:10 + rnorm(10, 0, 0.01))) %>%
  data.frame()
temp$id <- 1:10

temp2 <- gather(temp, ind, value, -id) %>%
  arrange(id) %>%
  group_by(id) %>%
  mutate(time = 1:n())

mod <- lmer(value ~ time + (time|id), temp2)

sjp.lmer(fit  = mod,
         type = "coef")
```

![image](https://user-images.githubusercontent.com/5005648/33632836-bc93cafe-d9c3-11e7-8734-6051bb80c4a6.png)

As we see above, all of the slopes of the lines are positive. However when I use the following code, the slopes of the lines correspond to the deviation away from the average slope:

```
sjp.lmer(fit = mod,
       type = "rs.ri")
```

![image](https://user-images.githubusercontent.com/5005648/33632958-160632e8-d9c4-11e7-991a-5051595da662.png)

Was this the intended way in which this function should work? 

Thanks!

**Comment by strengejacke** [comment]
The random slopes are not all positive, see `sjp.lmer(mod, type = "re")` (or now: `plot_model(mod, type = "re")`).

`type = "coef"` calls `coef()` on `mod`, which is `fixef(mod) + ranef(mod)`. Hence, you get only positive values in your first plot, although the individual slopes are positive and negative.

> But wouldn't a more meaningful plot show "global intercept + random intercept + global slope + random slope"?

I'm not sure what would be more meaningful - it was my first intention to get an impression of the variance in the subjects. Maybe it would indeed make more sense to plot the slopes including global slope.

**Comment by njudd** [comment]
sjp.lmer is defunct, how do I make a graph showing each subjects random slope and intercept with plot_model?

**Comment by strengejacke** [comment]
Currently, the random-slope-intercept plots are not implemented, because I’m not sure whether it makes more sense to include the global slope as well. I have drafted a function that produces these plots, but I think it needs some more work, so maybe it’ll be released in a forthcoming update.

**Comment by strengejacke** [comment]
I'm not sure, but I guess that the last commit to _ggeffects_ actually addresses and closes this issue. You can plot predicted values, conditioned on random effects, for each group level.

See details [in this vignette](https://strengejacke.github.io/ggeffects/articles/effectsatvalues.html#marginal-effects-for-each-level-of-random-effects).

Taking your example from above (but restricted to 3 levels of the random effect, due to limited color palette):

```r
library(dplyr)
library(lme4)
library(tidyverse)
library(sjPlot)
library(ggeffects)

set.seed(100)

mean_slope <- 10
random_deviation <- rnorm(10, 0, 5)
i <- 1:10
x <- 1:10

temp <-
  do.call(rbind,
          map2(.x = mean_slope, .y = random_deviation, .f = function(x, y) (x + y) * 1:10 + rnorm(10, 0, 0.01))) %>%
  data.frame()
temp$id <- 1:10

temp2 <- gather(temp, ind, value, -id) %>%
  arrange(id) %>%
  group_by(id) %>%
  mutate(time = 1:n())

mod <- lmer(value ~ time + (time|id), temp2)

plot_model(mod, type = "pred", terms = c("time", "id [1,5,10]"), pred.type = "re")
```
![rplot](https://user-images.githubusercontent.com/26301769/47579614-caebe800-d94c-11e8-97ea-adefc1e97b5c.png)

```r
ggpredict(mod, terms = c("time", "id [1,5,10]"), type = "re") %>% plot()
```
![rplot01](https://user-images.githubusercontent.com/26301769/47579632-ddfeb800-d94c-11e8-91d4-1bbcb2f1cea0.png)
