### ISSUE TITLE
return data for sjt.df()

### ISSUE THREAD

**Issue by januz** [strengejacke/sjPlot#307]
The help states that `sjt.df()` "invisibly returns the data frame with the description information (data)", so I assumed that I could get the data frame with, e.g.,

```
data_out <- sjt.df(data_in)
data_out$data
````
but the data doesn't seem to be included in the list
```
names(data_out)
[1] "page.style"      "page.content"    "output.complete" "knitr"           "header"          "file"            "show"            "use.viewer"
```
Am I doing or understanding something wrong?

**Comment by strengejacke** [comment]
The helpfile is misleading here. As `sjt.df()` simply prints a data frame as HTML table, there's no need to return the data (input = output).

**Comment by januz** [comment]
what I was trying to do was to get the data that gets printed when one uses `describe = TRUE` and transform it a bit (selecting/ordering columns, etc.). I know I could just run `psych::describe` directly, do my transformations, and then pipe it to `sjt.df()` or `pixiedust`  for printing, but I liked your addition of number/percentage of missings.

**Comment by strengejacke** [comment]
Does `sjmisc::descr()` the job for you? It directly returns a data frame.

**Comment by januz** [comment]
thanks, that would be a possibility. You don't include a few columns though (number of missings, mad) and one cannot pass down arguments to the describe function, right?

**Comment by januz** [comment]
I now use a combination of the packages `skimr` and `pixiedust` to reach the desired result.
