### ISSUE TITLE
sjPlot (model, type=fe.slope) error

### ISSUE THREAD

**Issue by Caitlin1990** [strengejacke/sjPlot#308]
Hi, when I try and use fe.slope I get the following error message:

Computing p-values via Kenward-Roger approximation. Use `p.kr = FALSE` if computation takes too long.
Warning message:
In sjp.lme4(fit, type, vars, ri.nr, emph.grp, title, legend.title,  :
  Invalid option for `type` argument. Defaulting to `type = "fe"` now.

Is there any way to fix this?

**Comment by strengejacke** [comment]
Please try `plot_model(fit, type = "slope")`.

**Comment by strengejacke** [comment]
Please re-open if issue isn't solved yet.
