### ISSUE TITLE
Argument title = "my title" not working for type = "re" 

### ISSUE THREAD

**Issue by djach** [strengejacke/sjPlot#309]
I fitted a glmer with random intercepts for multiple parameters and am now trying to visualize them for one parameter. Here's the code: 

`plot_model(glmer, type = "re", title = "my title", sort.est = TRUE, grid = FALSE)[[1]]`

A title is produced automatically: "Random effects of VARIABLE_NAME (Intercept)", the title that I specified ("my title") is not produced. With other types (e.g., type = "est"), the problem doesn't occur.

**Comment by strengejacke** [comment]
I'll look into this. Meanwhile, as workaround, loading `library(ggplot2)` and adding a `+ ggtitle("mytitle")` should workaround this issue.
