### ISSUE TITLE
Feature request: sjt.corr: upper and lower matrix with different correlation coefficients

### ISSUE THREAD

**Issue by helix123** [strengejacke/sjPlot#31]
Would be nice if sjt.corr could display different correlation coefficients in the upper and lower triangle of the matrix. I think it is quite common to display Pearson and Spearman correlation coefficients and to do this in one matrix.

lower.tri(x, diag = FALSE) and upper.tri(x, diag = FALSE) might come in handy as mentioned here:
http://www.sthda.com/english/wiki/elegant-correlation-table-using-xtable-r-package

**Comment by strengejacke** [comment]
Closing in favor of https://github.com/easystats/correlation/issues/74
