### ISSUE TITLE
Discrepancy in how Kenward-Roger approximated p-values are calculated in sjt.lmer()

### ISSUE THREAD

**Issue by jrosen48** [strengejacke/sjPlot#310]
Hi, I have been working to understand how p-values can be calculated for mixed-effects models fit using `lme4::lmer()`, and have been using `sjt.lmer()` with `p.kr = TRUE` to use the Kenward-Roger approximation.

In diving into the code for the behind-the-scenes `p_value()` function (link here), I noted what I think is a discrepancy in how Kenward-Roger approximated p-values are calculated in `sjt.lmer()` in comparison to how they are calculated in the `lmerTest()` package. 

In particular, it seems like in the `p_value()` function, there is a single value calculated for the degrees of freedom, whereas in the output from the `summary()` method exported by the `lmerTest()` package, each coefficient is associated with different degrees of freedom. 

Here is an example:

```
library(lme4)
library(lmerTest)
library(pbkrtest)

d <- sleepstudy
d$random_var <- runif(180)

# Kenward-Roger approximated degrees of freedom calculated using the lmerTest() package
fit <- lmer(Reaction ~ Days + random_var + (Days | Subject), d)
summary(fit, ddf = "Kenward-Roger")

# Kenward-Roger appoximated degrees of freedom used for all t-tests in sjPlot::sjt.lmer()
get_Lb_ddf(fit, lme4::fixef(fit)) 
```

**Comment by strengejacke** [comment]
Any idea whether the _pbkrtest_ package can return a single df for each coefficient?

**Comment by jrosen48** [comment]
Good timing! Just worked on this for a package I am working on (for sensitivity analysis) [here](https://github.com/jrosen48/konfound/blob/master/R/konfound-lmer.R).

This should take a `merMod` object and return the degrees of freedom for each coef:

```
get_kr_df <- function(model_object) {
    L <- diag(rep(1, length(lme4::fixef(model_object))))
    L <- as.data.frame(L)
    out <- purrr::map_dbl(L, pbkrtest::get_Lb_ddf, object = model_object)
    names(out) <- names(lme4::fixef(model_object))
    out
}
```

I could try to work on a PR, if you would like and don't mind.

**Comment by strengejacke** [comment]
Ok, the `p_value()` is located in https://github.com/strengejacke/sjstats. A PR would be nice. Everything between lines 115-126 here: https://github.com/strengejacke/sjstats/blob/master/R/merMod_p.R#L97 need to be revised.

**Comment by jacob-long** [comment]
Hey @jrosen48, any idea how calculating a separate DF for each coefficient might affect performance? I'm not sure what all is being done by `pbkrtest` so it's hard for me to venture a guess for sure beyond that it's plausible that it could be much slower (the same process occurring several times instead of once) or much faster (each operation is less complex).

**Comment by strengejacke** [comment]
I wonder why there's a small discrepancy... `fit2` is fitted with _lmerTest_, `fit` with _lme4_:

```r
round(summary(fit2, ddf = "Kenward-Roger")$coefficients[, 3:5], 3)
#>                  df t value Pr(>|t|)
#> (Intercept) 200.193   5.461    0.000
#> e42dep      826.518  10.660    0.000
#> c172code    825.848   1.631    0.103
#> c160age     234.726  -0.221    0.825
#> c161sex     825.624   2.199    0.028

round_num(p_value(fit, TRUE), 3)
#> # A tibble: 5 x 3
#>   term        p.value std.error
#> 1 (Intercept)   0         1.00 
#> 2 e42dep        0         0.137
#> 3 c172code      0.103     0.201
#> 4 c160age       0.817     0.012
#> 5 c161sex       0.028     0.293

attr(p_value(fit, TRUE), "df.kr")
#> (Intercept)      e42dep    c172code     c160age     c161sex 
#>    200.1931    826.5183    825.8479    234.7257    825.6243 
```

**Comment by strengejacke** [comment]
Ok, the t-values differ for `summary(fit2)` and `summary(fit2, ddf = "Kenward-Roger")`. Any ideas how to adjust the t-values accordingly for KR approximation?

**Comment by strengejacke** [comment]
Ok, got it:

```r
round_num(p_value(fit, TRUE), 3)

#> # A tibble: 5 x 3
#>   term        p.value std.error
#> 1 (Intercept)   0         1.02 
#> 2 e42dep        0         0.138
#> 3 c172code      0.103     0.201
#> 4 c160age       0.825     0.012
#> 5 c161sex       0.028     0.293
```

**Comment by jrosen48** [comment]
Fantastic.
