### ISSUE TITLE
sjt.lmer not found

### ISSUE THREAD

**Issue by ypetscher** [strengejacke/sjPlot#311]
Great package and a fantastic solution for creating tables! Have found success with using sjt.lm but when I attempt to use sjt.lmer, I receive the following error following the code (using R 3.4.3):

> library(lme4)
> library(sjPlot)
> wr<-lmer(WR_ss.1~OBVAT+(1|site),REML=TRUE,data=a)
> sjt.lmer(wr)
Error: could not find function "sjt.lmer"

**Comment by strengejacke** [comment]
Please post the session info. The function exists, so I'm not sure what exactly is wrong with your setup.

**Comment by KerenRaiter** [comment]
I am having the same issue. 
My session info is as follows:

R version 3.5.1 (2018-07-02) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows >= 8 x64 (build 9200)  Matrix products: default  locale: [1] LC_COLLATE=English_Israel.1255  LC_CTYPE=English_Israel.1255    LC_MONETARY=English_Israel.1255 [4] LC_NUMERIC=C                    LC_TIME=English_Israel.1255      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] usethis_1.4.0     devtools_2.0.1    sjPlot_2.6.1.9000 TMB_1.7.15        openxlsx_4.1.0    readxl_1.1.0       [7] lme4_1.1-18-1     Matrix_1.2-14     forcats_0.3.0     stringr_1.3.1     dplyr_0.7.6       purrr_0.2.5       [13] readr_1.1.1       tidyr_0.8.1       tibble_1.4.2      ggplot2_3.0.0     tidyverse_1.2.1   usdm_1.1-18       [19] raster_2.6-7      sp_1.3-1           loaded via a namespace (and not attached):  [1] nlme_3.1-137       fs_1.2.6           lubridate_1.7.4    httr_1.3.1         rprojroot_1.3-2     [6] tools_3.5.1        backports_1.1.2    utf8_1.1.4         R6_2.2.2           sjlabelled_1.0.15  [11] lazyeval_0.2.1     colorspace_1.3-2   withr_2.1.2        prettyunits_1.0.2  processx_3.2.0     [16] tidyselect_0.2.4   mnormt_1.5-5       emmeans_1.3.0      curl_3.2           compiler_3.5.1     [21] cli_1.0.0          rvest_0.3.2        xml2_1.2.0         desc_1.2.0         sandwich_2.5-0     [26] scales_0.5.0       mvtnorm_1.0-8      psych_1.8.10       ggridges_0.5.1     callr_3.0.0        [31] digest_0.6.15      foreign_0.8-70     minqa_1.2.4        stringdist_0.9.5.1 base64enc_0.1-3    [36] pkgconfig_2.0.1    sessioninfo_1.1.1  pwr_1.2-2          rlang_0.2.1        rstudioapi_0.8     [41] bindr_0.1.1        zoo_1.8-3          jsonlite_1.5       zip_1.0.0          magrittr_1.5       [46] modeltools_0.2-22  bayesplot_1.6.0    fansi_0.2.3        Rcpp_0.12.18       munsell_0.5.0      [51] prediction_0.3.6   stringi_1.1.7      multcomp_1.4-8     yaml_2.2.0         snakecase_0.9.2    [56] MASS_7.3-50        pkgbuild_1.0.2     plyr_1.8.4         grid_3.5.1         parallel_3.5.1     [61] sjmisc_2.7.6       crayon_1.3.4       lattice_0.20-35    ggeffects_0.7.0    haven_1.1.2        [66] splines_3.5.1      sjstats_0.17.2     hms_0.4.2          ps_1.2.1           knitr_1.20         [71] pillar_1.3.0       estimability_1.3   pkgload_1.0.2      codetools_0.2-15   stats4_3.5.1       [76] glue_1.3.0         remotes_2.0.2      data.table_1.11.8  modelr_0.1.2       nloptr_1.2.1       [81] cellranger_1.1.0   gtable_0.2.0       assertthat_0.2.0   coin_1.2-2         xtable_1.8-2       [86] broom_0.5.0        survival_2.42-3    glmmTMB_0.2.2.0    memoise_1.1.0      bindrcpp_0.2.2     [91] TH.data_1.0-9
--
 
> | >
>

Thanks in advance for your assistance

**Comment by strengejacke** [comment]
This issue is one year old ;-)
Please use `tab_model()` now.
See https://strengejacke.github.io/sjPlot/articles/tab_mixed.html

**Comment by KerenRaiter** [comment]
Thank you Daniel,

 

I appreciate your quick response.

I have followed the code in the link you sent, but this is not what I’m looking for – I’m looking for a way to plot the expected values of the model, not just get an html table. 

I have spent a long time trying to figure out how to do this with sjPlot (including installing the development version etc), and have not found a way yet. Can you advise?

 

Keren

**Comment by strengejacke** [comment]
You should have opened another issue, because this one was about the _table_-function. To plot coefficients, you can use `plot_model()`, and to plot marginal effects, you can also use `plot_model()`, just with a different `type`-option. See package vignettes (also online: https://cloud.r-project.org/web/packages/sjPlot/index.html) on the topics "Plotting Interaction Effects of Regression Models", "Plotting Marginal Effects of Regression Models" and "Plotting Estimates (Fixed Effects) of Regression Models".

If you want marginal effects, you may also take a look at the _ggeffects_ package, which is doing the work for sjPlot (https://strengejacke.github.io/ggeffects/).

**Comment by KerenRaiter** [comment]
Thank you very much for your helpful answer. I didn’t even realise that that was about the table function – it had come up repeatedly when I had searched for ways to plot the model outputs. I’m getting up to speed now!
