### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by Manu4l** [strengejacke/sjPlot#312]
I get this error when I run the sjt.lm command based on the following example:

require(sjPlot) 
data(efc)

fit1 <- lm(barthtot ~ c160age + c12hour + c161sex + c172code, data=efc)
fit2 <- lm(neg_c_7 ~ c160age + c12hour + c161sex + c172code, data=efc)

sjt.lm(fit1, fit2,
       labelDependentVariables=c("Barthel-Index", "Negative Impact"),
       labelPredictors=c("Carer's Age", "Hours of Care", "Carer's Sex", "Educational Status"),
       showStdBeta=TRUE, pvaluesAsNumbers=TRUE, showAIC=TRUE)

**Comment by strengejacke** [comment]
The argument-names have changed. If you use the new, valid argument names, everything should work. See `?sjt.lm`.
