### ISSUE TITLE
sjp.glm doesn't work with cbind() outcome of glm model

### ISSUE THREAD

**Issue by RPanczak** [strengejacke/sjPlot#313]
Reposting here [from SO](https://stackoverflow.com/questions/47898781/in-r-how-can-i-use-sjplot-with-cbind-outcome-of-glm-model) since I didn't get much attention.

I'm trying to use `sjp.glm` command to plot the results of glm model. All works fine until I specify y outcome as a vector of successes and failures, which is one of the way glm can be called.

To illustrate the problem:

```
library(sjPlot)
library(sjmisc)
data(efc)

# dummy data
y0 <- ifelse(efc$neg_c_7 < median(na.omit(efc$neg_c_7)), 0, 1)
y1 <- ifelse(efc$neg_c_7 >= median(na.omit(efc$neg_c_7)), 0, 1)
df <- data.frame(y0 = y0, 
                 y1 = y1,
                 sex = to_factor(efc$c161sex),
                 dep = to_factor(efc$e42dep),
                 barthel = efc$barthtot,
                 education = to_factor(efc$c172code))

df_agg <- df %>% 
  dplyr::group_by(sex, dep, barthel, education) %>%                            
  dplyr::summarise(c0=sum(y0),
                   c1=sum(y1))

fit2 <- glm(cbind(c0, c1) ~., data = df_agg, family = binomial(link = "logit"))

# plot doesn't work
sjp.glm(fit2)
```

Am I doing something wrong or is it expected behaviour? If the latter - any workaround?

Many thanks for help!

**Comment by strengejacke** [comment]
It _was_ "expected" behaviour. Due to the support of labelled data, I expected the outcome to be a single variable. However, specifying the response with `cbind()` works with the `plot_model()` function, which will replace `sjp.glm()` and friends in a future update.

So, simply use `plot_model(fit2)`.

**Comment by RPanczak** [comment]
Many thanks for help! Sorry for not spotting `plot_model` earlier.
