### ISSUE TITLE
Won't install on ubuntu

### ISSUE THREAD

**Issue by DiogoFerrari** [strengejacke/sjPlot#314]
TMB.hpp does not find the Eigen/Dense library.

~/R/x86_64-pc-linux-gnu-library/3.4/TMB/include/TMB.hpp:53:10: fatal error: Eigen/Dense: No such file or directory
 #include <Eigen/Dense>
 
Some info 
[here](https://stackoverflow.com/questions/23284473/fatal-error-eigen-dense-no-such-file-or-directory)

**Comment by strengejacke** [comment]
This sounds like being an issue for the TMB package. Considering the check results, TMB does install on different Linux systems:
https://cran.r-project.org/web/checks/check_results_TMB.html
