### ISSUE TITLE
Error when using plot_model with type "pred" with weights

### ISSUE THREAD

**Issue by vandeynze** [strengejacke/sjPlot#315]
When attempting to move from `sjp.int` to `plot_model`, I experience the following error. The model I am estimating was estimated with weights. The function works fine when I estimate without weights, but throws the following error message when weights are included. It seems that plot_model gets held up at the prediction stage when weighted models are used.

`Error in eval(add.args[["w"]]) : object 'w' not found`

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by vandeynze** [comment]
`df <- mtcars
df$w <- rep(c(1,2,3,4), 8)
m <- glm(am ~ wt + gear*vs, data = df, family = binomial(link = "probit"), weights = w)
plot_model(m, type = "int")
summary(m)`

Hope this helps!
