### ISSUE TITLE
the argument "show.n=F" in sjPlot::xtab() does not work

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjPlot#317]
It remains to give Total, while the same argument used in sjPlot::sjp.grpfrq() works well. 
Thank you.

**Comment by strengejacke** [comment]
Can't reproduce this, for me it works well:

```
library(sjPlot)
# create 4-category-items
grp <- sample(1:4, 100, replace = TRUE)
# create 3-category-items
x <- sample(1:3, 100, replace = TRUE)

# plot "cross tablulation" of x and grp
sjp.xtab(x, grp)
```

![rplot](https://user-images.githubusercontent.com/26301769/34816563-931fe5fe-f6b5-11e7-87d3-51d288fa89a3.png)

```
sjp.xtab(x, grp, show.n = F)
```

![rplot01](https://user-images.githubusercontent.com/26301769/34816603-a6f733de-f6b5-11e7-981f-064da9a04775.png)

**Comment by frankcsliu** [comment]
Sorry for the confusion. My bad.
