### ISSUE TITLE
plot_model() not using labels for legend title

### ISSUE THREAD

**Issue by b1azk0** [strengejacke/sjPlot#318]
I just noticed that, when using:

`plot_model(fit, type = "int", show.data = T)`

Legend on the plot is taken from column name and not from column label, even when label attribute is set correctly:

```
> str(df$grupa)
 Factor w/ 3 levels "Control","Negative",..: 2 2 2 2 2 2 2 2 2 2 ...
 - attr(*, "label")= Named chr "Experimental condition"
  ..- attr(*, "names")= chr "grupa"
```

![obraz](https://user-images.githubusercontent.com/22635132/34818868-6768539a-f6bc-11e7-914f-d5368e43cb1b.png)

Is there any way around this?

Thank you

**Comment by strengejacke** [comment]
There is usually no `names` attribute for _variable_ labels. How did you import the data?

See here:

```
data(efc)
str(efc$c161sex)
#>  atomic [1:908] 2 2 1 1 2 1 2 2 2 2 ...
#>  - attr(*, "label")= chr "carer's gender"
#>  - attr(*, "labels")= Named num [1:2] 1 2
#>   ..- attr(*, "names")= chr [1:2] "Male" "Female"
```

_value labels_ (`labels`) do have a names attribute, _variable labels_ (`label`) don't. So, your data is not correctly labelled, that's why the legend title is not correct.

**Comment by b1azk0** [comment]
I took my data from a online google spreadsheet using 
`gsheet::gsheet2tbl()`
```

#After import
data(df)
str(df$grupa)

# Check labs vector
str(labs)
chr [1:101] "" "Sex" "Experimental condition" "" "Age"

df<- set_label(df, label = labs)
str(df$grupa)
 Factor w/ 3 levels "Control","Negative",..: 2 2 2 2 2 2 2 2 2 2 ...
 - attr(*, "label")= Named chr "Experimental condition"
  ..- attr(*, "names")= chr "grupa"
```

**Comment by b1azk0** [comment]
But when working with atomic vectors:

```
> str(df$ses)
 atomic [1:240] 0 -1 2 -1 0 1 -1 0 1 0 ...
 - attr(*, "labels")= Named num [1:5] -2 -1 0 1 2
  ..- attr(*, "names")= chr [1:5] "bardzo niska" "niska" "przecietna" "wysoka" ...
 - attr(*, "label")= chr "Self Esteem"
```

I also get skipped lables:

![obraz](https://user-images.githubusercontent.com/22635132/34822087-03158cb4-f6c6-11e7-9a77-98d0e995740a.png)

**Comment by b1azk0** [comment]
I've tried your code and it works properly:
![obraz](https://user-images.githubusercontent.com/22635132/34824043-30d8b958-f6cd-11e7-8fa7-106c142e19c5.png)

Then again, running code on my dataframe (even with only your packeages loaded) gives the same issue:
![obraz](https://user-images.githubusercontent.com/22635132/34824148-95b540c6-f6cd-11e7-8757-212bd41b74cf.png)

```
library(sjPlot)
library(sjlabelled)
library(sjmisc)
fit <- lm(stereotyp ~ ses * grupa, data = df)
plot_model(fit, type = "int", show.data = T)
```

If you have any idea on how to debug this on my side I'm happy to try it out

**Comment by strengejacke** [comment]
If possible, you could send me the data, so I try to reproduce your bug.

**Comment by b1azk0** [comment]
Done!
I used mail address from your github profile page

**Comment by b1azk0** [comment]
I think I reproduced the problem.
Legend label is skipped when not all categories are used.

This code replicates both my problem, and my data structure:

```
dummy <- tibble(a = sample(1:10, 300, replace=TRUE), 
                c = rep(c("a", "b", "c"), 100), 
                b = rnorm(n=300))

dummy$b[dummy$c=="c"] <- NA

dummy$c <- to_factor(dummy$c)
dummy$c <- set_label(dummy$c, "Variable C")

m <- lm(a ~ b * c, data = dummy)
plot_model(m, type = "int")
```

**Comment by strengejacke** [comment]
ok, thanks. I'll look into this.

**Comment by b1azk0** [comment]
Sorry, I didn't reply eariler. I used your fix when I was working on these data and it worked

**Comment by strengejacke** [comment]
Great, thanks for confirmation!
