### ISSUE TITLE
default theme used by sjPlots

### ISSUE THREAD

**Issue by b1azk0** [strengejacke/sjPlot#319]
Hi,
Didn't know if I should post this question here or to SO and eventually decided to leave it here.

I need to make some group mean plots that are not covered by sjp functions I was wandering how could I set up a theme for ggplot to match sjp default coloring (as seen in `sjp.xtab()` wich I used the most in my report)?
Thanks for any hints.

**Comment by strengejacke** [comment]
The default color palette for `sjp.xtab()` is _Paired_ (see `?sjp.xtab`, the `geom.colors`-argument), which means it gets the colours from the Paired-colorbrewer-palette.

You can extract colors from that palette with `RColorBrewer::brewer.pal(n, "Paired")`, with `n` being the nr. of required color values.

**Comment by b1azk0** [comment]
Thank you!
