### ISSUE TITLE
facet.grid = TRUE not working properly

### ISSUE THREAD

**Issue by b1azk0** [strengejacke/sjPlot#320]
facet.grid=T passed to a `sjp.grpfrq(type = "box")` call is drawing empty categories. Is there anyway around this?

```
dummy<- data.frame(a= rep(c("a", "b"), 30),
                   b= rep(c("x", "y", "z"), 20),
                   c=rnorm(60))

sjp.grpfrq(var.cnt =  dummy$c, 
           var.grp = dummy$b,
           intr.var = dummy$a,type="box",  facet.grid = T)
```
![obraz](https://user-images.githubusercontent.com/22635132/34905759-b633d428-f85f-11e7-84c9-7babfbc79636.png)

**Comment by b1azk0** [comment]
Daniel, sorry to bother you on Sunday. 
Could you please confirm this is a bug? Or it's just me doing something wrong?
Thanks

**Comment by strengejacke** [comment]
I haven't look into this, but I assume it's a bug (or, from ggplot-side, working as intended, but me having a wrong approach towards interaction terms...)
