### ISSUE TITLE
sjt.grpmean() displays duplicate tables

### ISSUE THREAD

**Issue by b1azk0** [strengejacke/sjPlot#321]
I just noticed (after running some mass package update) that sjt.grpmean() displays duplicate tables for every level of `var.grp =`

```
dummy <- data.frame (a = rep(c("a", "b"), 20),
                     b = rnorm(20))
sjt.grpmean(dummy$b, dummy$a)
```

![obraz](https://user-images.githubusercontent.com/22635132/34919170-56143b40-f95f-11e7-99b1-356a11abca09.png)

**Comment by strengejacke** [comment]
Yes, this issue is already fixed, the update will be commited within the next 1-2 weeks to CRAN. You can use `sjstats::grpmean()` in between, however, only for console output.
