### ISSUE TITLE
sjp.glmer type "pred" error

### ISSUE THREAD

**Issue by benny2801** [strengejacke/sjPlot#324]
Hi,

My glmer model looks like this:
y <-cbind(tot1$H, tot1$L)
m1.1 <- glmer(y~ Fed.Unfed + year + smear.quality + Estimated.age +
                X1W.MWS + X1W.NT + X1W.PP + number.of.nestlings.per.nest + Altitude + sex + disturbance   + (1| nest.ID), tot1, family=binomial(link=logit),control=glmerControl(optimizer="bobyqa"))
And I have to say I really love the sjp package.

I was trying now to plot some predictive values with the type="pred", like this:

sjp.glmer(m1.1, type = "pred.fe", vars = "Altitude")

Anyway, when I put one of my explanatoy variables (such as Altitude, which is a numeric continuous variable), I get this error message: 

Error in mutate_impl(.data, dots) : 
  Column `resp.y` must be length 284 (the number of rows) or one, not 0
In addition: Warning messages:
1: Unknown columns: `y` 
2: In min(new_value, na.rm = T) :
  no non-missing arguments to min; returning Inf

Any idea??

Thank you very much!

**Comment by strengejacke** [comment]
Could you try `plot_model()`? The function call should look like this:

```
plot_model(m1.1, type = "pred", terms = "Altitude")
```

**Comment by benny2801** [comment]
At this point I think it's that as well, because by applying
plot_model(m1.1, type = "pred", terms = "Altitude"), it gives me this plot with two independent variables instead of response variable and one independent

Is there any way I can get solve this? 
[prova.pdf](https://github.com/strengejacke/sjPlot/files/1640096/prova.pdf)

**Comment by benny2801** [comment]
And it gives me this warning message..

Warning messages:
1: Unknown columns: `y` 
2: Unknown columns: `y` 
3: Unknown columns: `y`

**Comment by strengejacke** [comment]
try `cbind()` directly in the formula, or include `y` in the data frame for the model.

**Comment by benny2801** [comment]
If I include y in the data frame I have a new error:

Error in mutate_impl(.data, dots) : 
  Evaluation error: Argument 1 must be length 284, not 568.

So I guess it can't really deal with 2 columns variables..?

**Comment by strengejacke** [comment]
Ok, might be that marginal effect plot types (like `"pred"` or `"int"`) can't cope with 2-column variables, however, the simple plot should. I must see if I find a reproducible example to do some tests and dive deeper into this issue (which is almost certain an issue of _ggeffects_, which does all the work for marginal effect plots in _sjPlot_).

**Comment by benny2801** [comment]
I could send you part of the data if you want!

2018-01-18 11:25 GMT+01:00 Daniel <notifications@github.com>:

**Comment by strengejacke** [comment]
Yes, that would be great, so I can re-fit your model to reproduce the error.

**Comment by strengejacke** [comment]
I looked a bit into this issue, but currently I don't know how to solve this. For marginal effects plots like `type = "pred"`, I use `expand.grid()` to create a combination of possible values. This does not seem to work with matrix-columns (like `cbind()`). Maybe there is a way I'm not aware of, and at least not in the related function in _ggeffects_, which prepares the required predictor levels.

**Comment by strengejacke** [comment]
I think this problem should be solved with the latest update from _ggeffects_. Can you confirm this?

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
I'll close this issue for now, but feel free to reopen if you still encounter any problems.

**Comment by phisherblack** [comment]
I am stuck on a problem. if I try to calculate standardized coefficient effects in the plot_model() function with type="std", everything works fine but if i change the type to "std2" it always throws an error..."Column `std.error` must be length 1 or 8, not 7". how is the length of the standard errors ok for std but not for std2? what am i missing?
