### ISSUE TITLE
sjt.lmer() not printing unconditional models

### ISSUE THREAD

**Issue by b1azk0** [strengejacke/sjPlot#325]
Is it possible to show side by side a random slope model with an uncoditional model?

Following code always gives error when passing `model0` to `sjt.lmer()`:
```

df <- data.frame(subj = rep (1:10, 10),
                 x = rnorm (100),
                 y = rnorm(100))

library(lme4)
library(sjPlot)

model0 <- lmer(y ~ ( 1 | subj), data = df)
model1 <- lmer(y ~ x + (x | subj), data =df)
sjt.lmer(model0)
sjt.lmer(model1)
```

**Comment by strengejacke** [comment]
This one is related to https://github.com/strengejacke/sjPlot/issues/139 and https://github.com/strengejacke/sjPlot/issues/78. I'll address this when revising the tab-functions in the next major update.

**Comment by strengejacke** [comment]
ok, works with the current draft of `tab_model()`, however, requires the latest GitHub of _sjstats_.
