### ISSUE TITLE
Error in UseMethod("fixef") :    no applicable method for 'fixef' applied to an object of class "logical"

### ISSUE THREAD

**Issue by mochicake** [strengejacke/sjPlot#326]
Hi,
I'm using the package (sjPlot). I've specified 4 models (m1, m2, m3, and m4).  Running the table on these four models does not give me any trouble. However, when trying to change the labels of the table, I get the following error. 

The code that I have is: 

```
library(sjPlot)
sjt.lmer(m1, m2, m3, m4,
         showHeaderStrings=T, 
         labelPredictors = c("ABC", "DEF"))
```
The error message that I get is: 

> Error in UseMethod("fixef") : 
>   no applicable method for 'fixef' applied to an object of class "logical"

I'm not sure why I'm getting this error message.

**Comment by strengejacke** [comment]
The argument names have changed. I'm almost certain that this is the reason for this issue. Please see `?sjt.lmer` and update the argument names for the function call.
