### ISSUE TITLE
sjt.frq doesn't work when first item is NA

### ISSUE THREAD

**Issue by phildias** [strengejacke/sjPlot#327]
Hi there,

I'm using this library to describe a dataset with a lot of missing values and noticed this strange behavior.

When the first item in a vector is NA (aka missing), sjt.frq() throws an error. Here's a small reproducible example:

```
x <- c(1,1,2,NA)
y <- c(NA,1,1,2)
sjt.frq(x) # This command executes fine
sjt.frq(y) # This command gives me an error
```
Error message:
Error: `data` only contains string vectors, where string vectors should be removed. No data to compute frequency table left. See argument `ignore.strings` for details.

Hope this helps!

**Comment by phildias** [comment]
Hi there! I noticed @strengejacke closed this issue. Does that mean this issue will be fixed/adjusted during the next release? 
Or did I just use the function improperly?
Sorry if this question is stupid, I'm kind of new to the whole world of git and wasn't sure what "issue closed" meant.
Thanks!

**Comment by strengejacke** [comment]
Yeah, it's fixed. However, it requires updating _sjmisc_, because it was an error in a function of that package.
