### ISSUE TITLE
plot_model error:  "contrasts can be applied only to factors with 2 or more levels"

### ISSUE THREAD

**Issue by shirokaner** [strengejacke/sjPlot#329]
Hi! I am trying to replicate my own models from last year when I used sjp.int().
The plot_model() function constantly returns a puzzling Error message : "Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :   contrasts can be applied only to factors with 2 or more levels".

The variables in cross-level interaction have 2 and 3 levels. I have already checked that both have at least two non-empty levels:
fctr <- lapply(data4[sapply(data4, is.factor)], droplevels)
sapply(fctr, nlevels)

So why the problem? And how can I plot my interaction effect correctly?

Model specification: 
glmer(trustunknown2 ~ var1 + var2 + var3 + var4 + var5 + var6 + var7 + var8 + var9 + int * Status + (1 + int | country), data = data, family = 'binomial')

My previous code that used to work: sjp.int(model)
My current code: plot_model(model, terms = c("Status", "int"), type = "eff")

**Comment by strengejacke** [comment]
Maybe in combination there are empty factor levels? Have you tried `sjp.int()` with exactly the same model?

**Comment by strengejacke** [comment]
Also, try `type = "pred"`. The error message you get stems from the effects package. It has been updated recently, this might also be a source for the error.

**Comment by shirokaner** [comment]
Thanks for a quick reply! Yes, the model is exactly the same.
Changing for `type = "pred"` returns the following:

> Note: uncertainty of the random effects parameters are not taken into account for confidence intervals.
> Error in snakecase::to_any_case(lab, case = case, preprocess = "(?<!\\d)\\.",  : 
>                                   unused argument (protect = "\\d")

**Comment by strengejacke** [comment]
You need to update the packages. There was a change in _snakecase_, which now requieres _sjlabelled_ in version 1.0.7 or higher to be installed. Could you update your packages and retry?

**Comment by shirokaner** [comment]
I reinstalled them both - and it worked well with 'type = "pred"'! 
Amazing! Thanks so much!!!

I tried my luck again with 'type = "eff"', just to check. Unfortunately, the result is still that error from the effects packages, even though all the levels and their combinations are at least 2:
> Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
>   contrasts can be applied only to factors with 2 or more levels

**Comment by strengejacke** [comment]
Have you tried using the effects-package directly, e.g. `effects::allEffects(...)`? If this does not work, it's really an issue of the effects üackage.

**Comment by shirokaner** [comment]
Yes, I have just tried effects::allEffects(model), and it works (R 3.4.2).
Another issue that pops up when I am trying plot_model (type = "eff") is that I need Matrix 1.2-12. 
I have switched to R 3.4.3, and the Matrix is alright now, but allEffects() do not work anymore)))

> Error in mod.matrix %*% mod$coefficients[!is.na(mod$coefficients)] : 
>   non-conformable arguments

Well, thanks a lot, I now know where  I should look at.

**Comment by strengejacke** [comment]
If you use `effects::effect ()` with the `xlevels` argument to specify the levels to compute for the interaction terms, you should get the same error message. If not, please provide a reproducible example so I can check whether it's an issue of my packages or not.
