### ISSUE TITLE
table output for glmmTMB model

### ISSUE THREAD

**Issue by orchidn** [strengejacke/sjPlot#330]
Hello Daniel,

I am using a Poisson glmmTMB with an offset term model and I used ggeffects to plot the results. I would like to obtain a table like the ones that can be created with sjt.lmer:
https://strengejacke.wordpress.com/2015/06/05/beautiful-table-outputs-summarizing-mixed-effects-models-rstats/

Is there a way I can do that for my glmmTMB model?
Thank you so much
M - O

**Comment by strengejacke** [comment]
Not yet, however, this is planned for a forthcoming update, possibly within the first quarter of 2018.

**Comment by orchidn** [comment]
Thank you so much for your quick reply!

Best!


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by strengejacke** [comment]
Not fully working yet, but the basics are implemented.
