### ISSUE TITLE
sjPlot change variable names

### ISSUE THREAD

**Issue by orchidn** [strengejacke/sjPlot#331]
Hi again,

I was wondering how can I get sjPlot to use the variable labels not names in my dataset. I tried this:
variable.labels <- get_var_labels(mydataset)

I get this error: could not find function "get_var_labels"
Is there any quick way to do this?
Thanks!

**Comment by strengejacke** [comment]
Which function do you mean? By default, all sjPlot-function automatically get the labels from labelled data.

`get_var_labels()` was renamed to `get_label()` and is located in the package _sjlabelled_.

**Comment by orchidn** [comment]
Thank you so much!


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by strengejacke** [comment]
Is this issue solved?

**Comment by orchidn** [comment]
Yes, thank you so much!


Sent from Outlook<http://aka.ms/weboutlook>
