### ISSUE TITLE
sjt.glmer

### ISSUE THREAD

**Issue by orchidn** [strengejacke/sjPlot#332]
Hi Daniel,

I have a Poisson glmer model with two cross-classified random intercepts and I would like to obtain a table describing the results, including the variance and the ICCs. I remember I did this last October but I cannot seem to figure out what I am doing wrong now when I am getting an error.

This is my model:
glmerou <- glmer(visits~age+x1+x2+x3+ x4 + x5+x6+offset(logExp)+(1|A)+(1|B), data=mydata, family=poisson)

I used this code:
sjt.glmer(glmerou, show.aic = TRUE, show.ci = FALSE,  show.ci = TRUE, show.re.var= TRUE, show.icc=TRUE, show.r2= TRUE, show.se = TRUE, p.numeric = FALSE)

I am getting this error message:
Error in `$<-.data.frame`(`*tmp*`, "std.error", value = character(0)) : 
  replacement has 0 rows, data has 8

I am not sure what am I doing wrong. Any help would be extremely appreciated!
Thanks!

**Comment by strengejacke** [comment]
Please provide a reproducible example. I cannot reproduce this issue with my own model:

```
library(sjmisc)
library(sjlabelled)
library(lme4)
data(efc)
efc$grp <- as.factor(efc$e15relat)
levels(efc$grp) <- get_labels(efc$e15relat)
fit.p <- glmer(tot_sc_e ~ neg_c_7 + e42dep + c161sex + (1 + c172code | grp),
               data = efc, family = poisson(link = "log"))
sjt.glmer(fit.p, show.aic = TRUE, show.ci = FALSE, show.re.var= TRUE, show.icc=TRUE, show.r2= TRUE, show.se = TRUE, p.numeric = FALSE)
```

**Comment by orchidn** [comment]
Hi Daniel,

Thank you so much! I will post my data - it is a huge dataset so I would probably post a random subsample.

I think my issue is the fact that my dataset is an object of class "c('grouped_df', 'tbl_df', 'tbl', 'data.frame')". Should I ungroup it?

Thanks! MikiD


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by strengejacke** [comment]
Might be that the grouped df is the reason behind this error, but I can't say for sure. You can send me a subsample of your data via email, if you like, but please provide a minimal reproducible example along with the data.

**Comment by orchidn** [comment]
Thank you very much! I sent you a copy of a subset of my data.

Best regards!

MD


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by strengejacke** [comment]
(solved via email)
