### ISSUE TITLE
sjt.glmer Is it possible to print the value of residual variance?

### ISSUE THREAD

**Issue by orchidn** [strengejacke/sjPlot#333]
Hi, I am using sjt.glmer to get the output of a Poisson glmer model with two cross-classified random effects.  I would like to include two more lines in the table, to indicate residual variance and the ICC for observations in the both groups A and B, as explained below:

Apart from the τ00, A and τ00, B, I would like the sjt.glmer package to add to my output table the residual variance sigma_2, as well, along with its SD. For my model, the residual variance is 1 (I got that using re_var(fit): # Within-group-variance:    1.000). 

Apart from the ICC that sjt.glmer provides for each of the two random effects A and B, I would like to get the ICC for the observations in cells belonging to both A and B groups, which I calculated manually as ICCA + ICCB. Also, for all ICCs, I would like to include the SE and the confidence intervals which I calculated manually and then included in the table based on bootstrapping in sjstats.

My question is: Could this be done altogether by specifying these options when calling the sjt.glmer with an option "show.all=TRUE" or something like that?

Thank you so much for all your help!
Best regards!

**Comment by strengejacke** [comment]
> Apart from the τ00, A and τ00, B, I would like the sjt.glmer package to add to my output table the residual variance sigma_2, as well, along with its SD. For my model, the residual variance is 1 (I got that using re_var(fit): # Within-group-variance: 1.000).

residual variance is already printed to the output, but the standard deviations are currently missing. I may add that to the output as well.

> Apart from the ICC that sjt.glmer provides for each of the two random effects A and B, I would like to get the ICC for the observations in cells belonging to both A and B groups, which I calculated manually as ICCA + ICCB.

I'm not sure what you exactly mean with "belonging to both" - an overall ICC, or for cross classified models the intersection of observations?

> Also, for all ICCs, I would like to include the SE and the confidence intervals which I calculated manually and then included in the table based on bootstrapping in sjstats.

This is really time consuming, I would not add that by default, but maybe I can add an option to include SE for the ICC as well. For Bayesion models, this is already included, as Bayesian models compute the posterior distribution, where it's no big deal to get the SD/SE and CI.

**Comment by strengejacke** [comment]
- SD for residual variance is not likely to be implemented
- ICC is revised and now only the "adjusted ICC" (see Nakagawa et al., doi: 10.1098/rsif.2017.0213) is printed
- SE for ICC is not likely to be implemented due to the above mentioned reasons
