### ISSUE TITLE
Compatibility of sjt.lmer-function with afex-package

### ISSUE THREAD

**Issue by JarkkoHautala** [strengejacke/sjPlot#334]
I’ve managed to run my analyses with afex mixed-function.
Now I want to print result tables and the most convenient way to do is to use sjt.lmer -function from sjPlot-package.
However, it seem not to find the TYPE III test p-values but provides different p-values and possibly confidence intervals (Wald).
Is this something which may be solved from  sjPlot -package handling the object returned from mixed-function?

**Comment by JarkkoHautala** [comment]
Another issue is that the random part in resulting table is incomplete, it seem to report only random intercepts with wrong labels.

**Comment by strengejacke** [comment]
Seems to be a duplicate of this issue: https://github.com/strengejacke/sjPlot/issues/334
