### ISSUE TITLE
sjp.grpfrq() strange behaviour

### ISSUE THREAD

**Issue by b1azk0** [strengejacke/sjPlot#335]
Previously when I called 
`sjp.grpfrq(df$sex, df$IPT5A)`
This chart would appear:
![obraz](https://user-images.githubusercontent.com/22635132/36026466-845d2100-0d97-11e8-9453-56ab2ba6692b.png)

I was asked to make some changes to this chart (leave only % and remove N) and I just found out, that same code now prints this chart:
![obraz](https://user-images.githubusercontent.com/22635132/36026505-ae1150de-0d97-11e8-87dd-abe5f26766af.png)

Is this some kind of bug?
How can I fix it or revert back to a version that gave results from 1st chart?

**Comment by strengejacke** [comment]
Do you have a reproducible example? I doubt that exactly the same code gives you two different outputs.

**Comment by b1azk0** [comment]
I don't have anything else than a .rmd file that I simply rerun - same data frame, same code - different result.
I'm not sure what else could I check, but the only thing that changed in between compilations of the RMD document are sj libraries that I've been updating now and then.

**Comment by strengejacke** [comment]
I could not reproduce your example. This works for me:

```
library(sjPlot)
data(efc)
sjp.grpfrq(efc$e42dep, efc$e16sex)
sjp.grpfrq(efc$e42dep, efc$e16sex, show.n = F)
```

So if you can provide a minimal reproducible example, that would be helpful to address this issue.

**Comment by b1azk0** [comment]
This is what I get when I run this code:
![obraz](https://user-images.githubusercontent.com/22635132/36040949-559e6952-0dc7-11e8-9c0e-caea28f73137.png)

**Comment by b1azk0** [comment]
Removing and reinstalling `ggplot2` fixed the problem.
Sorry for bothering.

**Comment by strengejacke** [comment]
ok, thanks for letting me know! I was slightly confused about this issue. ;-)
