### ISSUE TITLE
Feature request: safer argument syntax for sjt.* functions

### ISSUE THREAD

**Issue by apsalverda** [strengejacke/sjPlot#336]
Would it be possible to change the sjt.* functions so that predictor labels need to be associated explicitly with existing predictor variables?

The argument syntax I have in mind is:

`sjt.lmer(...., pred.labels = c(sex2 = "Carer's Sex", c12hour = "Hours of Care", barthel = "Elder's Dependency"))`

Currently, predictor labels are specified as follows:

`sjt.lmer(...., pred.labels = c("Carer's Sex", "Hours of Care", "Elder's Dependency"))`

Carer's Sex |   | 0.48 | -0.07 – 1.03 | .091
-- | -- | -- | -- | --
Hours of Care |   | 0.00 | -0.00 – 0.01 | .238
Elder's Dependency |   | -0.05 | -0.06 – -0.04 | <.001

Note that the labels have to be specified in the correct order.

If the user accidentally specifies the wrong order, predictors end up with the wrong coefficients:

`sjt.lmer(...., pred.labels = c("Carer's Sex", "Elder's Dependency", "Hours of Care"))`

Carer's Sex |   | 0.48 | -0.07 – 1.03 | .091
-- | -- | -- | -- | --
Elder's Dependency |   | 0.00 | -0.00 – 0.01 | .238
Hours of Care |   | -0.05 | -0.06 – -0.04 | <.001

It would be great if the function's argument syntax could help avoid this type of mistake.  Thanks!

**Comment by strengejacke** [comment]
This is what is planned for the next update, and it's currently implemented in this way in `plot_model()`. Automatic labelling is also easier, since `sjlabelled::get_term_labels()` returns a named vector, making the matching of labels to variables easier.
