### ISSUE TITLE
Export as pdf?

### ISSUE THREAD

**Issue by wraymond** [strengejacke/sjPlot#339]
Love the functionality here, and work great with Rmd, but I am wondering if here is a way to export/save the stand alone table as a stand alone pdf or image?

Generic example
`model.table <- sjt.lm(mod1, mod2, mod3)`

Then save/export `model.table` as pdf.

**Comment by strengejacke** [comment]
You can only export or copy/paste to word, and then create a PDF. I don't see any other options at the moment.
