### ISSUE TITLE
view_df() sorting and output problem

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjPlot#342]
![screen shot 2018-04-06 at 09 22 14](https://user-images.githubusercontent.com/12545793/38399278-0801804a-397c-11e8-823e-45317e8c001b.png)

The columns from left to right are ID, Name, Label, missing, Values, Value Labels, Freq. %, weighted Freq., and weighted %. 

Problem #1:  in the last two columns the sorting of the results is reversed. Please help check. 
Problem #2: it is more intuitive to see the regular sorting of Label and their values are from low to high. Currently I see the sorting is from high to low. Hope there is an argument to change the sorting, or at least set the sorting from low to high as the default. 

I am writing a report using this feature. I would very appreciate if this issue could be solved asap. Thank you.

**Comment by methodds** [comment]
Hi, I recently also tried to use `view_df()` and noticed another output problem: The "loading" progress is irritating in markdown files:
![image](https://user-images.githubusercontent.com/7460499/38415660-7ec15a6e-3992-11e8-800c-6ad13b9a3015.png)
This could for instance be solved by adding a `verbose`parameter, which only prints  progress if set to `TRUE`.

**Comment by strengejacke** [comment]
@methodds please use `hide.progress = TRUE` in knitr-docs.

**Comment by strengejacke** [comment]
@frankcsliu I can't reproduce this issue:

```r
library(sjPlot)
data(efc)
efc$weight <- rnorm(n = 908, mean = 1, sd = .2)

# weighted, not sorted
view_df(
  efc,
  weight.by = efc$weight,
  show.frq = T,
  show.prc = T,
  show.wtd.frq = T,
  show.wtd.prc = T
)

# weighted, sorted
view_df(
  efc,
  weight.by = efc$weight,
  sort.by.name = TRUE,
  show.frq = T,
  show.prc = T,
  show.wtd.frq = T,
  show.wtd.prc = T
)
```

**Comment by methodds** [comment]
Sorry, I didn't see that option (yes, verbose is more common).
