### ISSUE TITLE
Change CI bands for plot_model(glmer)

### ISSUE THREAD

**Issue by wendalkane23** [strengejacke/sjPlot#345]
Hello, 

This package is great! However, I am having trouble changing the color scheme of some figures for a glmer().  
`nematode<-glmer(nemgsoil~PERCENT_MOISt*loc+perc_OM+(1|stand), family=Gamma(link="log"), data=nem)
`

`A<-plot_model(nematode, type = "pred", terms=c("PERCENT_MOISt", "loc"),colors="gs", title="" )+labs(x="soil percent moisture")+labs(y="Nematodes per gram of soil")+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
`

The default output gives each location (two groups) a different color line (black or grey), and a matching confidence interval band (grey and light grey, respectively). My problem isn't changing the color palette, but rather changing it to a black and white or grey scale that would be good for publication. Whenever I implement the following code to make the background white, my "light grey" confidence interval band virtually disappears. 

`AA<- A+ theme(panel.background = element_rect(fill = "white", colour = "black",size = 0.5, linetype = "solid"))
`

So my question is, is there a way I can manually change the line color for each group? Or can I change the line type( ie dashed) for just one group. 

I posted a question on cross validated as well with some pictures that may make this a bit easier to understand. I have tried a bunch of various functions, but haven't had any luck.

https://stats.stackexchange.com/questions/342535/change-background-color-in-sjplot-results-in-missing-confidence-interval-band

Looks like my question was marked as "off-topic" on cross validated. Anyways, thanks for the help!

Wendal

**Comment by strengejacke** [comment]
Do you have some reproducible examples, and probably also some graphics where I can see what you exactly mean?

**Comment by strengejacke** [comment]
You can change the transparancy (alpha-level) via the `alpha`-argument, e.g.

```r
plot_model(nematode, type = "pred", terms = c("PERCENT_MOISt", "loc"), colors = "gs", alpha = .7, title = "" )
```

Does this solve your issue?

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
I'll close this issue for now, but feel free to reopen if you still encounter any problems.
