### ISSUE TITLE
Plot_model with brms custom family

### ISSUE THREAD

**Issue by tibo1** [strengejacke/sjPlot#347]
Hi!
I am trying to use the plot_model function in sjPlot and get the following error message: Error in get(fam$family, asNamespace("stats")) :  object 'custom' not found. I assume this is because I am not using a native family to the brms package (I am using beta binomial family, as specified here: https://cran.r-project.org/web/packages/brms/vignettes/brms_customfamilies.html). Is there a way for me to implement the plot_model function on my model while using this custom family? Many thanks in advance for your reply. Regards Tiril

**Comment by strengejacke** [comment]
Do you have a small reproducible example? Or at least an `brmsfit`-object would help, I guess.

**Comment by strengejacke** [comment]
Ok, this works for me. Do you have more details on which function fails?

**Comment by strengejacke** [comment]
I _think_ that this issue in **sjstats** should fix this issue.

**Comment by strengejacke** [comment]
See issue I opend at brms: If you want to plot marginal effects, you additionally need to create a `fitted_*()`-function:

```r
fitted_beta_binomial2 <- function(draws) {
  mu <- draws$dpars$mu
  trials <- draws$data$trials
  trials <- matrix(trials, nrow = nrow(mu), ncol = ncol(mu), byrow = TRUE)
  mu * trials
}
```

This, in combination with the fix in sjstats, should make `plot_model()` work.

**Comment by tibo1** [comment]
Ok, I will try as you suggest. Thank you very much for looking into this. Regards Tiril
