### ISSUE TITLE
Error in object@pp$b(1) : object 'merPredDb' not found

### ISSUE THREAD

**Issue by JensUErlandsen** [strengejacke/sjPlot#349]
I am trying to plot this model, but i dont know how to resolve these errors.

fit.f1 <- lmer(y ~ g * b + (1 | f), data=d1, REML=F)

> sjp.lmer(fit.f1)
Error in object@pp$b(1) : object 'merPredDb' not found
> plot_model(fit.f1)
Error in UseMethod("slice_") : 
  no applicable method for 'slice_' applied to an object of class "NULL"

Is there a solution somehow?
Best regards Jens

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by JensUErlandsen** [comment]
Im not sure how i should make it?

This is my linear model:

Linear mixed model fit by maximum likelihood  ['lmerModLmerTest']
Formula: y ~ g * b + (1 | f)
   Data: d1
      AIC       BIC    logLik  deviance  df.resid 
 743.6765  759.4264 -365.8383  731.6765        96 
Random effects:
 Groups   Name        Std.Dev.
 f        (Intercept) 16.112  
 Residual              7.114  
Number of obs: 102, groups:  f, 11
Fixed Effects:
(Intercept)          gwt           bk       gwt:bk  
     22.592        6.409       -5.920       11.691

**Comment by JensUErlandsen** [comment]
I realized, that this might have something to with it:

> library("sjPlot")
Install package "strengejacke" from GitHub (`devtools::install_github("strengejacke/strengejacke")`) to load all sj-packages at once!
Warning message:
In checkMatrixPackageVersion() : Package version inconsistency detected.
TMB was built with Matrix version 1.2.14
Current Matrix version is 1.2.8
Please re-install 'TMB' from source using install.packages('TMB', type = 'source') or ask CRAN for a binary version of 'TMB' matching CRAN's 'Matrix' package

I have tried to reinstall TMB.

**Comment by strengejacke** [comment]
A reproducible example is to provide the code that you ran to fit the model, and then either some code to create a fake data set, or some real data as `.RData`-file download. I don't think that the TMB-package is responsible for this, but you can just try to re-install it from source and see if it works.

**Comment by JensUErlandsen** [comment]
I just ran the code again, and it somehow worked.
Im sorry for your inconvenience - and thanks for your effort
Jens
