### ISSUE TITLE
Likert Style Box Plots to report data

### ISSUE THREAD

**Issue by EdResearcher** [strengejacke/sjPlot#350]
HI, 
I would like to report exact results with the sjp.likert function, not sample probabilities.
Is that possible? Do the categories have to equal 1?
And if so, how can I alter the following code to report my exact results?

stayrate1<- data.frame (
  question1= as.factor (sample(1:6, 96, replace = TRUE, prob = c(.16, .16, .16, .16, .16, .16))),
  question2= as.factor (sample(1:6, 96, replace = TRUE, prob = c(.16, .16, .16, .16, .16, .16))), 
  question3= as.factor (sample(1:6, 96, replace= TRUE, prob = c(.16, .16, .16, .16, .16, .16)))
)
sjp.likert(stayrate1, show.prc.sign = TRUE)

Thank you in advance for your time.

**Comment by strengejacke** [comment]
I'm not quite sure what kind of plot you would like to have? If it's a normal frequency plot, you can use something like this:

```r
library(tiydr)
tmp <- stayrate1 %>% 
  gather(key = "question", value = "frq", 1:3)
```

```r
sjp.grpfrq(tmp$frq, tmp$question)
```
![rplot](https://user-images.githubusercontent.com/26301769/43649037-55996890-973c-11e8-8e63-0f400bf47c4f.png)


```r
sjp.grpfrq(tmp$frq, tmp$question, bar.pos = "stack")
```
![rplot01](https://user-images.githubusercontent.com/26301769/43649038-57d61324-973c-11e8-9ec5-6020cd4c11a9.png)

**Comment by strengejacke** [comment]
_bump_

**Comment by EdResearcher** [comment]
Thank you, I will try it. I wanted to have a stacked frequency plot. So I could illustrate likert style response from left to right but with real data, not approximated from the data.

**Comment by strengejacke** [comment]
Maybe you may also want `sjp.stackfrq()`?
