### ISSUE TITLE
Error: $ operator not defined for this S4 class

### ISSUE THREAD

**Issue by anaveda** [strengejacke/sjPlot#351]
Hi,

I am trying to make a pred plot but I am getting an error about S4 class. 

I run a similar model with the same dataset and I used sjp.glmer and it worked.

This is my code, both variable that I am including in the plot continuous

> MD1=lmer(log(Distance)~No.Land.Cover+No.Patches+Edge.Density+Largest.Patch.Index+Contagion+(1|Id),data=hp.land)
> sjp.lmer(MD1,type="pred",vars="Edge.Density",facet.grid=F,show.ci=T,title="",show.scatter=F)
Error: $ operator not defined for this S4 class.

Then I changed the function:
> plot_model(MD1,type="pred",vars="Edge.Density",facet.grid=F,show.ci=T,title="",,show.scatter=F)
Error: `terms` needs to be a character vector with at least one predictor names: one term used for the x-axis, more optional terms as grouping factors.

Any input of what am I doing wrong?

Thanks,

**Comment by strengejacke** [comment]
Parameter names have changed in `plot_model()`. Use `terms` instead of `vars`, `ci.lvl` instead of `show.ci`, `grid` instead of `facet.grid` and `show.data` instead of `show.scatter`. Does this solve the issues?

**Comment by anaveda** [comment]
Thanks Daniel!!

I got this

 

>MD1=lmer(log(Distance)~No.Land.Cover+No.Patches+Edge.Density+Largest.Patch.Index+Contagion+(1|Id),data=hp.land)

 

> plot_model(MD1,type = "pred", terms = "Edge.Density")
Error in eval(predvars, data, env) : object 'Distance' not found

 

> plot_model(MD1,type = "pred", terms = c("Distance","Edge.Density"))
Error: cannot allocate vector of size 60.2 Gb
In addition: Warning message:
In log(Distance) : NaNs produced

 

 

=============================================================

Adrián Naveda-Rodríguez

Pho: 662-312-7435

E-mail: adrian.naveda@gmail.com

https://www.researchgate.net/profile/Adrian_Naveda-Rodriguez

https://publons.com/a/1189620/

**Comment by strengejacke** [comment]
`terms` indicates independent variables, not the response. If memory allocation is a problem, you can use the latest dev-version version of _ggeffects_, which has a `pretty` argument to use only "pretty" values, reducing memory usage.

**Comment by strengejacke** [comment]
Please update _ggeffects_ from CRAN, than the memory-issue should be solved.

**Comment by anaveda** [comment]
Hi Daniel, 
It is not working. I can not understand what happen. 
I am trying to get the plots with both functions, and none of them are working.

This was the first code that I used and it worked
MD1=lmer(log(Distance)~No.Land.Cover+No.Patches+Edge.Density+Largest.Patch.Index+Contagion+(1|Id),data=hp.land)

> sjp.lmer(MD1,type="pred",vars="No.Land.Cover",facet.grid=F,show.ci=T,title="",show.scatter=F)

![image](https://user-images.githubusercontent.com/38710822/39638101-c562d0ac-4f8a-11e8-8f3a-8554e2f7549c.png)

After upgrading, these errors came up
> sjp.lmer(MD1,type="pred",vars="No.Land.Cover",facet.grid=F,show.ci=T,title="",show.scatter=F)
`sjp.lmer()` will become deprecated in the future. Please use `plot_model()` instead.
Error: $ operator not defined for this S4 class

Using the plot function, the error that came up is about response variable, but the variable Distance is in the data set. I am not sure if this has to be with log transform include in the regression, but this was working with sjp.lmer before the upgrade.
> plot_model(MD1,type="pred", terms="No.Land.Cover")
Error in eval(predvars, data, env) : object 'Distance' not found

**Comment by strengejacke** [comment]
Hm, I think I need reproducible example then.

**Comment by strengejacke** [comment]
Do you have a reproducible example for this issue?

**Comment by anaveda** [comment]
Hi Daniel,

Thanks for your help with this issue. I can provide the dataset to re-run the code. The file is attached to the this email.

 

hp.land=read.csv("HR_Landscape_Metrics.csv")

 

##Model for Dispersal

MD1=lmer(log(Distance)~No.Land.Cover+No.Patches+Edge.Density+Largest.Patch.Index+Contagion+(1|Id),data=hp.land)

sjp.lmer(MD1,type="pred",vars="No.Land.Cover",facet.grid=F,show.ci=T,title="",show.scatter=F)

plot_model(MD1,type="pred", terms="No.Land.Cover")

 

All the best,

 

 

=============================================================

Adrián Naveda-Rodríguez

Pho: 662-312-7435

E-mail: adrian.naveda@gmail.com

https://www.researchgate.net/profile/Adrian_Naveda-Rodriguez

https://publons.com/a/1189620/

**Comment by strengejacke** [comment]
I'm afraid the attachment is not automatically posted on GitHub, so you may either directly go to GitHub's webinterface, or please send the data directly to me.

**Comment by strengejacke** [comment]
Ok, please log-transform the dependent variable before fitting the model:

```r
hp.land$log.Distance <- log(hp.land$Distance)
MD1 <-
  lmer(
    log.Distance ~ No.Land.Cover + No.Patches + Edge.Density + Largest.Patch.Index +
      Contagion + (1 | Id),
    data = hp.land
  )
plot_model(MD1, type = "pred", terms = "No.Land.Cover")
```
![rplot](https://user-images.githubusercontent.com/26301769/42394644-29402488-815b-11e8-8dd1-528a08ca56e1.png)
