### ISSUE TITLE
add option to display t statistic in sjt.lmer output

### ISSUE THREAD

**Issue by rentzb** [strengejacke/sjPlot#353]
Some journal reviewers request the t statistics from lmer outputs to be included in summary tables, but it seems that sjt.lmer() currently doesn't have this as an option. Could you add a new option, such as 'show.t', to include the t-values in the output of sjt.lmer?

**Comment by strengejacke** [comment]
It's already in progress, the option is called `show.stat` in https://github.com/strengejacke/sjPlot/blob/master/R/tab_model.R

I hope to submit the next package update by next week.

**Comment by rentzb** [comment]
Great! I look forward to it. Thanks!
