### ISSUE TITLE
Object not found while using sjt.lmer on sjPlot package

### ISSUE THREAD

**Issue by cuchisavila** [strengejacke/sjPlot#355]
Hi Everyone
Im trhing to create a nice table following the instructions from 
https://cran.r-project.org/web/packages/sjPlot/vignettes/sjtlmer.html
I installed all the packages and libraries necesarry and was able to use funciton sjt.lm(lm1) correctly!
However when I try to use the sjt.lmer(lme1) I get an error

#Linear mixed-effects model fit by REML
#Mixed effects: Fixed effect of spawners and loc.sst, and random intercepts and slopes for both loc.sst nd spawners
lme1<-lme(ln.rs~spawners+loc.sst,random = ~1 + spawners + loc.sst|stock,data=sockeye)
summary(lme1) #Note that standard dev of spawner effect is very small, try remove
sjt.lmer(lme1)

The summary function prinet out the lme1 perfectly, but the sjt.lmer give me this:
> sjt.lmer(lme1)
Error in eval(predvars, data, env) : object 'ln.rs' not found

The ln.rs is clearly there since it worked perfectly with the previous fucntion
why does it say its not there?
How can I fix this?
Thanks for the help

**Comment by strengejacke** [comment]
`lme()` is not supported by `sjt.lmer()`, only `lme4::lmer()`. In the forthcoming update, the new function to create tables, `tab_model()`, will be able to deal with lme() as well.
