### ISSUE TITLE
sjp.lm - geom.color: How to set a different color for significant estimates? 

### ISSUE THREAD

**Issue by JFormoso** [strengejacke/sjPlot#356]
Hi, 
I've tried to set a different color for coefficients with p-values under 0.05 but it only admits a different color for negative estimates. Can you help me with this? 
thanks,
Jesi

**Comment by strengejacke** [comment]
You can use `group.terms` to assign coefficients to specific groups (e.g. "1" for sig. and "2" for non-sig.) and then use `colors` to define the color for each group. This works for `plot_model()`. See example in `?plot_model`.

**Comment by JFormoso** [comment]
Thank you very much.
Jesi

2018-05-21 17:08 GMT-03:00 Daniel <notifications@github.com>:

**Comment by JFormoso** [comment]
Dear Daniel,

I apologize for the inconvinience.
I am using the plot_model function for diagnostic plots and I was wondering
if there is a way to change dot and line sizes in the homoscedasticity
plot.
Also, if you ever find yourself in Argentina you should let us know. My
advisor loves you.

Best regards,

Jesica

**Comment by strengejacke** [comment]
Please open a new issue for this.
