### ISSUE TITLE
error when trying to install package

### ISSUE THREAD

**Issue by Stormaarhus** [strengejacke/sjPlot#357]
Hey

I tried to install the package, but i cant get it to work.

used:
install.packages("sjPlot")

got this error code when i tried to load the package. And it do not work. 

> library(sjPlot)
Error: package or namespace load failed for ‘sjPlot’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package with the name ‘brms’

**Comment by strengejacke** [comment]
Try to use `install.packages("sjPlot", dependencies = TRUE)`, or install the missing packages manually (see last line in your output).
