### ISSUE TITLE
Confidence Intervals: sjp.glmer vs plot_model

### ISSUE THREAD

**Issue by Rtamashiro** [strengejacke/sjPlot#358]
Hi,

I am working with a dataset that plots count data against temperature. When I plot the GLMM using sap.glmer, the confidence band is much, much narrower than when I use plot_model. The prediction line is also slightly different. Is there something wrong in the commands that is responsible for this difference, and if not, which should I trust?

> sjp.glmer(model1, type = "pred", vars = c("Temperature", "Species_Name"), show.ci = T, facet.grid = F)
 
> plot_model(model1, type = "pred", terms = c("Temperature", "Species_Name"), pred.type = "fe", show.data = T)

**Comment by strengejacke** [comment]
The `sjp.glmer()` function is outdated. The results from `plot_model()` are exacter, even though the CI's narrower. But the computation for `plot_model()` is correct.
