### ISSUE TITLE
sjPlot: subscript axis labels 

### ISSUE THREAD

**Issue by Apache94** [strengejacke/sjPlot#359]
Hello

I have the following issue which I would like to tackle.

I'm using sjp.corr and want to costumize my axis labels. This work so far, but when I want using subscript label I get always an error message. 

This code works fine:
sjp.corr(Cormat ,show.p = F, show.legend = TRUE,sort.corr = F,corr.method = "pearson",
         axis.labels = c("bla1","bla2","","","","","","",""))

This one not:
sjp.corr(Cormat ,show.p = F, show.legend = TRUE,sort.corr = F,corr.method = "pearson",
         axis.labels = c(expression("DPD"[Campaign]),"","","","","","","",""))

Error message:
Fehler in sjmisc::word_wrap(axis.labels, wrap.labels) : 
  anyNA() applied to non-(list or vector) of type 'expression'

How can I use expression("DPD"[Campaign]) in axis.labels? Or is there another way?

**Comment by strengejacke** [comment]
Currently, the only way is to manually override the `scale_*()` function from the returned ggplot-object, so basically you would add another scale with your own labels.
