### ISSUE TITLE
jitter for plot_model()

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjPlot#362]
Hi,

is it possible to jitter values with `plot_model()`? The following two commands produce similar outputs, but I haven't found a way to jitter points in `plot_model()` (and why is the data green? =D).

```
library(sjmisc)
library(sjPlot)
data(efc)
m <- lm(neg_c_7 ~ pos_v_4 , data = efc)

# old function
sjp.lm(m, show.loess = TRUE)
```
![image](https://user-images.githubusercontent.com/7460499/40588936-5acdb960-61e5-11e8-87fa-5371694b7075.png)

```
# new function
plot_model(m, show.data = TRUE, type  = 'slope')
```
![image](https://user-images.githubusercontent.com/7460499/40588939-62d71778-61e5-11e8-9b62-dbfeb1afa51b.png)

By the way: why do you set the title of the plot according to the name of the independent variable label? It could just be placed at the x-axis and the title could be blank. But I guess that's up to personal preference.

**Comment by strengejacke** [comment]
A jitter option is indeed missing. But the plot "title" is already annotated to the x-axis. Try this:

```r
m <- lm(neg_c_7 ~ pos_v_4 + e42dep, data = efc)
plot_model(m, type  = 'slope')
plot_model(m, type  = 'slope', grid = FALSE)
```

**Comment by strengejacke** [comment]
Short note: as a workaround, you can currently add jitter manually:

`plot_model(m, type  = 'slope') + geom_jitter()`

**Comment by luciamawe** [comment]
Hello, as a follow up is it possible to jitter individual values when using type = "int"? If I implement the above, it just jitters the mains. Also, thank you for this fantastic package and for all the work it goes into it!
