### ISSUE TITLE
I can't use more than one model with sjt.lmer

### ISSUE THREAD

**Issue by gkshenaut** [strengejacke/sjPlot#364]
I get a message “Column 11 must be named”. If I do each one separately, each table looks OK, no error messages. But more than one, then I get the Column 11 error.

Where should I be looking to resolve this?

Thanks,
Greg

**Comment by strengejacke** [comment]
As the examples work for me: do you have a reproducible example?

**Comment by gkshenaut** [comment]
I can send you some R code and a spreadsheet. Would that be acceptable?

Greg

On May 30, 2018, at 14:49 , Daniel <notifications@github.com<mailto:notifications@github.com>> wrote:


As the examples work for me: do you have a reproducible example?

**Comment by strengejacke** [comment]
Yes, that should be ok.

**Comment by gkshenaut** [comment]
I figured it out. This and the other problem are due to interactions with the lmerTest package, which I also had loaded. Without lmerTest, everything appears to work correctly. Thank you.
