### ISSUE TITLE
sjt.lmer confidence interval format

### ISSUE THREAD

**Issue by gkshenaut** [strengejacke/sjPlot#365]
(1) It appears that the digits.ci argument affects only the second of the two numbers in the confidence interval; the other one remains very wide. For example, with the default digits.ci=2, I get things like this: `0.00114659536217154 — 0.10`. It seems to me it should affect both numbers (i.e., `0.00 — 0.20`).

(2) The order of the two numbers in the confidence interval is sometime “lesser — greater” and sometimes “greater — lesser”. For example: `0.566823028669263 — −0.31`. This appears to be the case [more often?] when the estimate is negative. It seems to me that in this case it should be `−0.31 — 0.57`.

Thanks,
Greg

**Comment by strengejacke** [comment]
Do you have any model that reproduces this bug?

**Comment by gkshenaut** [comment]
Which bug?

Greg

On May 30, 2018, at 14:47 , Daniel <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have any model that reproduces this bug?

**Comment by strengejacke** [comment]
The wrong CI.

**Comment by gkshenaut** [comment]
I figured it out. This and the other problem are due to interactions with the lmerTest package, which I also had loaded. Without lmerTest, everything appears to work correctly. Thank you.

**Comment by strengejacke** [comment]
Great, thanks!
