### ISSUE TITLE
error from plot_model(..., type = "int")

### ISSUE THREAD

**Issue by meriops** [strengejacke/sjPlot#366]
When I call `plot_model(m, type = "int")` on [this binomial `glmer` model](https://github.com/strengejacke/sjPlot/files/2069218/m.txt), I get an `Error in sprintf [...] invalid format : '%i' [...]`. All continuous variables in the model are standardized, and all the "strengejacke" packages are at their latest version from github... Am I doing something wrong?

**Comment by strengejacke** [comment]
Sorry, compiling the text file doesn't work, there seems to be a typo. Can you save the model object as `.rda` or `.RData`?

**Comment by meriops** [comment]
[Here](https://github.com/strengejacke/sjPlot/files/2069370/m.RData.txt) is a `.RData` file with an added `.txt` extension for github to accept the upload.

**Comment by meriops** [comment]
Thanks Daniel. https://github.com/strengejacke/sjPlot/commit/3d58dac5a9313031c391e0e3fe3d1960d0a205ca fixes the initial error. However, I now get `Error: A continuous variable cannot be mapped to linetype` for any value of `mdrt.values` (the two variables in my interaction are continuous).

**Comment by strengejacke** [comment]
Do you have a reproducible example? I checked `plot_model(m, type = "int")` with the model you provided, and it worked well.

**Comment by meriops** [comment]
After digging further, I realised I had a faulty `scales` package. It works with the latest `scales` from CRAN / github. Sorry for the noise. And thanks for your great tools!
