### ISSUE TITLE
Rename "Fixed Parts" and "Random Parts"

### ISSUE THREAD

**Issue by vkehayas** [strengejacke/sjPlot#368]
Thanks for the useful package!
I humbly suggest renaming "Fixed Parts" and "Random Parts" to "Fixed Effects" and "Random Effects", respectively, for tables of mixed models.
The current wording does not appear grammatically correct (when presenting a single model there is only one "part").
My suggestion is in accordance with the definition of mixed-effects models, which are composed of "fixed effects" and "random effects".
I can gladly submit a PR if you agree with the suggestion but do not have time to make the change.

**Comment by strengejacke** [comment]
PR won't work, as sjt.(g)mer are no longer maintained. Instead, there will be `tab_model()`, and it's exactly that part I'm currently working on. So I'll consider this there.

**Comment by strengejacke** [comment]
Probably you could file a PR, as the old functions are not immediately removed, but first living in parallel with `tab_model()`, then become deprecated and finally defunct. There might be some overlap for both methods where some users still use `sjt.*()`, while others already use `tab_model()`. For this case, you may open a PR that addresses this issue, if you like.

**Comment by strengejacke** [comment]
I'll leave this issue open, as reminder for `tab_model()`.
