### ISSUE TITLE
sjPlot library error

### ISSUE THREAD

**Issue by ford12345** [strengejacke/sjPlot#369]
Hello.

When loading sjPlot, I am receiving a new error after updating to 3.5.0.

> library(sjPlot)
Error: package or namespace load failed for ‘sjPlot’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘ggeffects’

thanks.

**Comment by strengejacke** [comment]
Make sure you have installed package _ggeffects_.

**Comment by ford12345** [comment]
I am getting the same error with ggeffects.

I begin w/ sjlabelled -> sjmisc -> sjstats -> ggeffects -> sjPlot

**Comment by strengejacke** [comment]
Ok. Either install all clean from CRAN, or - if you install from GitHub - you may need the GitHub versions then.
