### ISSUE TITLE
sjplot::tab_model() does not support AIC statistic for tweedie glms

### ISSUE THREAD

**Issue by darrennorris** [strengejacke/sjPlot#376]
Hi, fantastic package.
This issue is due to how underlying stats::AIC and AICcmodavg::AICc deal with tweedie glms.
Currently with sjplot::sjt.glm there is no AIC for glm models fitted with a tweedie family.
Would it be possible to enable show.aic to use tweedie::AICtweedie for tweedie glms?

Thanks,
Darren

library(statmod)
library(tweedie)
y <- rgamma(20,shape=5)
x <- 1:20
glmt <- glm(y~x,family=tweedie(var.power=1,link.power=1))
tweedie::AICtweedie(glmt)
sjplot::sjt.glm(glmt, show.aic = TRUE) # returns NA for aic
stats::AIC(glmt)
AICcmodavg::AICc(glmt)

**Comment by strengejacke** [comment]
This should finally work now, when package **performance** is up to date.
