### ISSUE TITLE
plot_model fails where sjp.lmer works

### ISSUE THREAD

**Issue by bshor** [strengejacke/sjPlot#377]
I am fitting a linear multilevel model with lmer() (and continuous predictors of interest). The trouble I am having is that plot_model() which I know is superceding sjp.lmer does not appear to be working. Eg:

```
> sjp.lmer(fit.diff.maj[["r.maj"]],type="pred",var=c("polar"),show.ci = T, show.scatter = F)
Error in summary.connection(connection) : invalid connection
```
But this fails:

```
> plot_model(fit.diff.maj[["r.maj"]],type="pred",term=c("polar"))
Following variables had many unique values and were prettified: polar. Use `pretty = FALSE` to get smoother plots with all values, however, at the cost of increased memory usage.
Following variables had many unique values and were prettified: polar. Use `pretty = FALSE` to get smoother plots with all values, however, at the cost of increased memory usage.
Error: cannot allocate vector of size 267.3 Gb

```

This is the model I call:

```
fit.diff.maj[["r.maj"]]=lmer(diff~(1|st)+(1|year)+(1|k.id)+chamber+leadertype+sd+polar,data=subset(topleaderz,majority == T & party=="R"))
```

I think this is related to ggeffects because I get the same error with a call to ggpredict()

```
> ggpredict(fit.diff.maj[["r.maj"]], terms = "polar")
Following variables had many unique values and were prettified: polar. Use `pretty = FALSE` to get smoother plots with all values, however, at the cost of increased memory usage.
Following variables had many unique values and were prettified: polar. Use `pretty = FALSE` to get smoother plots with all values, however, at the cost of increased memory usage.
Error: cannot allocate vector of size 267.3 Gb

```
Thanks!

**Comment by strengejacke** [comment]
The problem is that the CI calculated by `sjp.lmer()` are not exact, while `plot_model()` produces much more precise confidence intervals for the predictions. You could maybe try to reduce the range of the plotted values, e.g - assuming that polar has a range from 0 to 10 or so: 

```r
plot_model(fit.diff.maj[["r.maj"]], type = "pred", terms = "polar [1,3,5,7,9]")
```

**Comment by bshor** [comment]
Yes, there are in the high hundreds of unique values.

The predictor ranges from 1 to 3. Using your suggestion, I tried but got the same error message:

```
> plot_model(fit.diff.maj[["r.maj"]],type="pred",term=c("polar [1,2,3]"))
Following variables had many unique values and were prettified: polar. Use `pretty = FALSE` to get smoother plots with all values, however, at the cost of increased memory usage.
Error: cannot allocate vector of size 1606.8 Gb
```

**Comment by strengejacke** [comment]
hm, strange. Do you have all packages up to date? What happens when you use 
```r
ggeffects::ggpredict(fit.diff.maj[["r.maj"]], "polar [1,2,3]")
```

**Comment by bshor** [comment]
Same error for ggeffects. I am using R 3.5.0 64bit on Windows, sjPlot v2.4.1, and ggeffects 0.3.3.

**Comment by strengejacke** [comment]
do you still see the Message that variables were prettified?

**Comment by strengejacke** [comment]
I think the current GitHub-version could solve this issue. Can you try

```r
devtools::install_github("strengejacke/ggeffects")
ggeffects::ggpredict(fit.diff.maj[["r.maj"]], "polar [1,2,3]")
# alternatively:
ggeffects::ggpredict(fit.diff.maj[["r.maj"]], "polar [1,2,3]", pretty = TRUE)
```

**Comment by bshor** [comment]
Thanks for the update! I installed the new GitHub version and there is no longer an allocation error but ... there's another error now (irrespective of setting pretty):

```
 ggpredict(fit.diff.maj[["r.maj"]], terms = "polar [1,2,3]")
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
```

**Comment by strengejacke** [comment]
w/o reproducible example it's difficult to say, but I guess that either one of your factors has only one level (maybe because other levels are missing in the data), or `polar` is not numeric. In this case, you must define valid levels inside the square brackets.

**Comment by bshor** [comment]
Thank you for fixing this. Indeed the problem is that some predictors were either logical or characters, instead of factors. With the new version of the package and that change, all works again.
