### ISSUE TITLE
Error in .axisPars(usr, log = log, nintLog = nint) :    infinite axis extents [GEPretty(inf,nan,5)]

### ISSUE THREAD

**Issue by FabiolaEto** [strengejacke/sjPlot#381]
Hi,

Thanks for such great package. However, even after installing the last development:

> library(devtools)
> devtools::install_github("strengejacke/sjPlot")

I am trying to plot the following Cox model:

> mod=coxph(y ~ (a.gidade + sexo2 + raca2 + escol2 + escolmae3 + rendacat2), data=b4, x=T)
> plot_model(mod, type="est", terms = c("sexo2", "raca2", "escol2", "rendacat2"))

I am having issues when I try to select only the variables I want to be plotted by using the argument `terms`. The following error and warning message shows up:

> Error in .axisPars(usr, log = log, nintLog = nint) : 
>   infinite axis extents [GEPretty(inf,nan,5)]
> In addition: Warning messages:
> 1: In min(new_value, na.rm = T) :
>   no non-missing arguments to min; returning Inf
> 2: In min(dat$conf.low) : no non-missing arguments to min; returning Inf
> 3: In min(dat$estimate) : no non-missing arguments to min; returning Inf
> 4: In max(dat$conf.high) : no non-missing arguments to max; returning -Inf
> 5: In max(dat$estimate) : no non-missing arguments to max; returning -Inf
> 6: In .axisPars(usr, log = log, nintLog = nint) : NaNs produced

Do you have a clue of what that could be?

**Comment by strengejacke** [comment]
Do the names in `terms` match the coefficients' names? What is the output from `coef(mod)`?

**Comment by FabiolaEto** [comment]
Yes, the `term` names do match the coefficients' names. Actually I'm interested in the `exp(coef)` which is the estimates of the model. The output from `coef(mod)` is this: 

> > coef(mod)
>          a.gidade2          a.gidade3          a.gidade4          sexo2masc 
>         0.53983240         0.79189170         1.08100878         0.30081783 
>  raca2parda         raca2preta       raca2amarela      raca2indigena 
>         0.14046859         0.32975443         0.02806670        -0.03248068 
>  escol22º grau    escol2< 2º grau      escolmae3meio escolmae3< 1º grau 
>         0.20796454         0.22490810         0.11021688         0.19512079 
>  rendacat22         rendacat21 
>         0.06859091         0.18173921

**Comment by strengejacke** [comment]
Coefficients names differ from what you've specified in `terms`. Eg, one name is `sexo2masc`, not `sexo2`.

**Comment by strengejacke** [comment]
Sorry, wait. `sexo2` should be correct, term names should match names from the formula.
Do you have a reproducible example?

**Comment by strengejacke** [comment]
Else, do you havea reproducible example?

**Comment by FabiolaEto** [comment]
I thought  I should specify the `terms` names and not its categories. When I specified the categories names it worked properly. Thank you very much!

**Comment by strengejacke** [comment]
No, else you can't remove just a specific level from the output. That's why it must be the coefficient name in this case. I revised the docs and hope that this is clearer now.
