### ISSUE TITLE
view_df() argument weight.by seems not working

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjPlot#384]
library(sjPlot)
load("../TNSS2015.rda") 
view_df(TNSS2015,
        file="TNSS2015tab2.html",  
        show.na = T, 
        show.frq = T, 
        show.prc = T, 
        weight.by = TNSS2015$w, 
        show.wtd.frq = T, 
        show.wtd.prc = T 
        ) 

The weight.by argument seems not work; if I comment out the argument the function worked fine.
Please advice. Thank you! 

data: 
https://jmp.sh/CgpRPPX

**Comment by strengejacke** [comment]
Please use `weight.by = w`:

```r
view_df(TNSS2015,
        file="TNSS2015tab2.html",  
        show.na = T, 
        show.frq = T, 
        show.prc = T, 
        weight.by = w, 
        show.wtd.frq = T, 
        show.wtd.prc = T 
        ) 
```

**Comment by frankcsliu** [comment]
Thank you. This solved the puzzle.
