### ISSUE TITLE
error from tab_model function

### ISSUE THREAD

**Issue by JM-RG** [strengejacke/sjPlot#385]
Hi,
sjPlot package is fascinating so first of all thank you for this amazing contribution to R users community.

I would like to create an lmer output table using the _tab_model_ function. However I get this (btw not so informative) error:    _Error: Column 6 must be named_

The model is in the format 
_mod <-lmer( y ~ (-1) + Sex + (1|ID) + (1|Year), data = df, REML = TRUE, verbose=TRUE, na.action="na.fail", control=lmerControl(optimizer="Nelder_Mead"))_

I get all the common outputs from the model without problems. Also, using tidy_lmer function I can get a more simple output table of the model without problems.

I have inspecting some time the tab_model function inside, trying to find where the fix is comming but with no luck.

Do you have some idea where the problem could be?

I have no reproduccible example but the output of the model can be found here:

https://www.dropbox.com/s/29922nqycgjbst7/mod.Rdata?dl=1

and I can provide more information if needed.

Thank you so much in advance.

**Comment by strengejacke** [comment]
I think the `(-1)` on your formula is causing troubles. Maybe with a function from _sjstats_, like `sjstats:: model_frame()` or `sjstats::pred_vars()`. I'm currently traveling, but will look into this after I'm back.
Maybe you can check if the same issue occurs due the example model in `lme4::lmer()`, with `(-1)` in the formula?

**Comment by JM-RG** [comment]
Hi Daniel,

thanks for your quick reply. Surprisingly to me I tried `tab_model` with the example models provided in `lme4::lmer()` and got the same error with both intercept structure sintax (with and without _(-1)_) .
I also check in my own model without (-1) and same problem pops up: _Error: Column 6 must be named_

I was initially thinking the problem may came from my data but looks like the problem comes from other aspect since it also happens with different data.

I hope you can provide help with this issue in the next days. 

thank you again

**Comment by JM-RG** [comment]
Hi again,

I have tried the same approach in another computer with different R sessions and got the same error.
In case it is informative you can find my session info here:
https://www.dropbox.com/s/bwzyv4q8jjyfu8k/sessionInfo.txt?dl=0

In another computer with a different session (see sessionInfo document linked), the function worked out well with the example data from lme4, restarting the session and charging only regression-modeling related libraries lme4 and sjPlot:
https://www.dropbox.com/s/bjhwee4c3idai8g/sessionInfo_zz.txt?dl=0

However, runing my model especifying `lme4::lmer` give me this error:

```
Computing p-values via Wald-statistics approximation (treating t as Wald z).
Error in UseMethod("family") : 
  no applicable method for 'family' applied to an object of class "logical"
```
Whereas the class of the objet model with mi initial session was `lmerModLmerTest` (from lmerTest), the class of the model launching this new error is `lmerMod `(from lme4)
So it may be related to interaction among packages or something similar? Just to trying to give you as much information as possible....

**Comment by strengejacke** [comment]
When I re-fit the model user `lme4::lmer()`, it works for me. The error lies in [the broom-package](https://github.com/tidymodels/broom):

```r
broom::tidy(mod)
#> Error: Column 6 must be named
```

**Comment by strengejacke** [comment]
I opened an issue: https://github.com/tidymodels/broom/issues/446

**Comment by strengejacke** [comment]
Can you confirm that `tab_model()` works when you use _lme4_ to fit the model?

**Comment by strengejacke** [comment]
_broom_ should be no problem if loaded, only _lmerTest_, I think. I'll close this issue now, we need to wait for the _broom.mixed_ package to be released.

**Comment by strengejacke** [comment]
I added a workaround (i.e. an own tidier) for lmerModLmerTest-Objects, so this issue should be fixed in sjPlot now. Will commit tonight.
