### ISSUE TITLE
help with plot_model

### ISSUE THREAD

**Issue by phisherblack** [strengejacke/sjPlot#395]
I am stuck on a problem. if I try to calculate standardized coefficient effects in the plot_model() function with type="std", everything works fine but if i change the type to "std2" it always throws an error..."Column std.error must be length 1 or 8, not 7". how is the length of the standard errors ok for std but not for std2? what am i missing?

**Comment by strengejacke** [comment]
Do you have a reproducible example? I have no problems, e.g.

```r
library(sjmisc)
library(sjPlot)
data(efc)
efc <- to_factor(efc, c161sex, e42dep, c172code)
m <- lm(neg_c_7 ~ pos_v_4 + c12hour + e42dep + c172code, data = efc)
plot_model(m, type = "std2")
```

![rplot](https://user-images.githubusercontent.com/26301769/43947326-150a9a46-9c88-11e8-84bc-ed013244962b.png)

**Comment by strengejacke** [comment]
The issue with `tab_model()` is resolved with https://github.com/strengejacke/sjPlot/commit/6a4dff88c0ee265b1bb8cf30d5f696b0c3cc624a

What about the initial issue?

**Comment by rasmusmunks** [comment]
Thanks! Your library is a life-saver.
Updated package. Encountered a different issue.

```r
library(tidyverse)
library(sjPlot)
library(lme4)
fit <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy, REML = F)
fit %>% tab_model()
```
Gives error:
```r
Error in fi$is_multivariate || fi$is_categorical : 
  invalid 'y' type in 'x || y'
```

**Comment by strengejacke** [comment]
Yes, need to update _sjstats_ from GitHub as well.

**Comment by rasmusmunks** [comment]
Thanks. Sorry for not thinking about that. `tab_model()` works perfectly now. 

I think I might have reproduced OP's original issue too.

```r
ibrary(tidyverse)
library(sjstats)
library(sjPlot)
library(lme4)
# Previous example.
fit <- lmer(Reaction ~ Days + (1 + Days | Subject), sleepstudy, REML = F)
fit %>% tab_model(show.std = "std2")
fit %>% plot_model(type = "std2")
# Problems using iris.
iris_fit <- lmer(Sepal.Length ~ Sepal.Width + Petal.Length + (1 | Species), data = iris)
iris_fit %>% tab_model(show.std = "std2")
iris_fit %>% plot_model(type = "est")
iris_fit %>% plot_model(type = "std2")
```
`type = "est"` for iris gives no errors, but with `type = "std2"` I get:

```Error: `.data` must have 3 rows, not 2```

Updated all dependent libraries from GitHub in the proper order.
