### ISSUE TITLE
vignettes not showing

### ISSUE THREAD

**Issue by phisherblack** [strengejacke/sjPlot#398]
hi,
For some reason, none of the vignettes for sjPlot is accessible. 
browseVignettes("sjPlot") returns nothing and https://strengejacke.github.io/sjPlot/ just loops back to the same page.
can you help?

**Comment by strengejacke** [comment]
I don't have any problems. The vignettes are also [available at CRAN](https://cran.r-project.org/package=sjPlot).

**Comment by phisherblack** [comment]
Thank you. i was using this link - http://127.0.0.1:13229/session/Rvig.4ac032b04748.html
i'll use the ones on CRAN.
