### ISSUE TITLE
Error when using sjp.lmer

### ISSUE THREAD

**Issue by dglodzik** [strengejacke/sjPlot#4]
Thank you very much for your work, this is useful.

I am trying to use sjp.glmer from the version I just installed from github. I tried your example from: http://www.r-bloggers.com/visualizing-generalized-linear-mixed-effects-models-with-ggplot-rstats-lme4/

library(sjPlot)
library(lme4)
fit <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
# simple plot

sjp.lmer(fit)

This gives me the following error:

> sjp.lmer(fit)
> Error in array(NA, c(J, K)) : 'dims' cannot be of length 0

Please could you advise if there is a way I could use the function?

Thank you very much
Dominik

**Comment by radekbace** [comment]
Hi Daniel

I have loaded the latest versions of 'lme4' and 'sjPlot', but function sjp.glmer gives me this Error: Package 'lme4' needed for this function to work. Please install it.
Do you know where is the mistake?
Thank you very much
Radek

**Comment by sjPlot** [comment]
Please see https://github.com/sjPlot/devel/issues/28
