### ISSUE TITLE
terms order wrong

### ISSUE THREAD

**Issue by xieguagua** [strengejacke/sjPlot#401]
library(sjPlot)
library(MASS)
house.plr <- polr(Sat ~ Infl + Type + Cont, weights = Freq, data = housing)
house.plr
summary(house.plr, digits = 3)
## slightly worse fit from
plot_model(
  house.plr
)

![image](https://user-images.githubusercontent.com/31589570/44300570-afa4a100-a33b-11e8-8b59-3f14f87ad00a.png)

the  Infl + Type + Cont chanaged to Cont+Infl+Type 
:)

**Comment by strengejacke** [comment]
Terms are sorted in alphabetical order by default. You can either sort by estimates (`sort.est = TRUE`) or define an own order (argument `order.terms`).

**Comment by albertostefanelli** [comment]
Is it possible to have an option that does not sort the estimates in alphabetical order or that follow the order of the fitted model? Would make like easier

**Comment by strengejacke** [comment]
should work now with the latest commit.
