### ISSUE TITLE
plot_model & line.size

### ISSUE THREAD

**Issue by anaveda** [strengejacke/sjPlot#403]
Hi,
I am trying to plot the effect of my regression model. I want to increase line width. I used line.size but it is not working.

This is my code and result:

MD0=lmer(Distance~Trt2+(1|Id),data=hp.land)
p1=plot_model(MD0, type = "eff", terms = "Trt2", title="",axis.title = c("Sex and Age","Dispersal Distance (km)"),
              line.size = 3)
p1+font_size(axis_title.x = 20,axis_title.y = 20,labels.x = 12, labels.y = 12)

![image](https://user-images.githubusercontent.com/38710822/44487162-2f23c000-a61b-11e8-8999-0d74685125dd.png)

Any input on this? I am using ver. 2.5.0.

Thanks!

**Comment by anaveda** [comment]
Hi Daniel,

Thanks. I am sending you the data to reproduce the plot. Lest see if you get it.

Best,

 

=============================================================

Adrián Naveda-Rodríguez

Pho: 662-312-7435

E-mail: adrian.naveda@gmail.com

https://www.researchgate.net/profile/Adrian_Naveda-Rodriguez

https://publons.com/a/1189620/

**Comment by strengejacke** [comment]
Ok, I just saw you were plotting effect-plots... These are handled differently, I'll investigate further.

**Comment by strengejacke** [comment]
But you need to update _ggeffects_ from GitHub before this works in _sjPlot_, or you wait for updates on CRAN.

**Comment by Ecotone23** [comment]
@strengejacke Hi Daniel, is there a way to change the thickness of vline in plot_model? Thanks.
