### ISSUE TITLE
Change dot size un diagnostic plots (plot_modelo)

### ISSUE THREAD

**Issue by JFormoso** [strengejacke/sjPlot#404]
Hi!
I am using the plot_model function for diagnostic plots and I was wondering if there is a way to change dot and line sizes in the homoscedasticity plot. I've tried dot.size and line.size within plot_model, and within ser_theme(theme_sjplot()).

Thanks,

Jesica

**Comment by strengejacke** [comment]
Ok, fixed this in the current GitHub-version. `dot.size` and `line.size` now also apply to diagnostic-plots.
