### ISSUE TITLE
plot_model (Error in snakecase::to_any_case)

### ISSUE THREAD

**Issue by vkmcheung** [strengejacke/sjPlot#405]
I am following the vignette (Plotting Estimates (Fixed Effects) of Regression Models) step by step, but when I get to "plot_model "I get the following error:

Error in snakecase::to_any_case(lab, case = case, sep_in = prep, sep_out = posp) : unused arguments (sep_in = prep, sep_out = posp)

I have tried my own lmerMod object and also get the same error.

Interestingly, setting case = NULL,  or using  "plot_models" circumvents the problem.

Thanks!

**Comment by strengejacke** [comment]
Strange, this error must have occured during the package checks before I submitted to CRAN. Do you have a reproducible example?

**Comment by strengejacke** [comment]
Closing this in favor of https://github.com/strengejacke/sjPlot/issues/413
