### ISSUE TITLE
What does determine the number of points in `sjp.lmer(model, type = "re.qq")`?

### ISSUE THREAD

**Issue by ImanYZ** [strengejacke/sjPlot#407]
In my previous models, this method plotted all the points in the dataset, similar to what you see below:
![image](https://user-images.githubusercontent.com/3834517/44795066-d357ba80-ab77-11e8-9e53-91d5ab2b0615.png)
However, for my new model, it plots only four points, though the summary of the `lmer` model indicates 180 observations.
![image](https://user-images.githubusercontent.com/3834517/44795164-0ef28480-ab78-11e8-8c64-6f409e5a0453.png)
My code has not changed and I've not set any parameters other than `type = "re.qq"`. How can I have all the points plotted?

Also, when I run this command, I get the error message: "'sjp.lmer' is deprecated. Use 'plot_model' instead." However, when I use `plot_model`, it gives me the error:
"Error in match.arg(type) : 'arg' should be one of “est”, “re”, “eff”, “pred”, “int”, “std”, “std2”, “slope”, “resid”, “diag”"

**Comment by strengejacke** [comment]
Do you have a reproducible example? For `plot_model()`, use `type = "diag"` to get the above shown plots.

**Comment by ImanYZ** [comment]
`type = "diag"` works fine. 
Thank you.

**Comment by strengejacke** [comment]
So can I close this issue?
