### ISSUE TITLE
plot_model marginal effect continuous predictor 

### ISSUE THREAD

**Issue by nfaivre** [strengejacke/sjPlot#409]
Hi there, 
I encountered an issue when changing from sjp.glmer to plot_model, attempting to plot the marginal effect of such model: 
 m4 = glmer(cor ~ conf * cond  + (conf*cond| suj) , data = a, family = binomial) 

When running sjp.glmer(m4,type = "pred",vars=c('conf','cond')), I obtain two nice sigmoids, as expected as conf is a numerical. 

But when running plot_model(m4,type = "pred",terms=c('conf','cond')), I get only estimates around 6 values of conf. I tried to fiddle with terms = c('conf [0:1]') with no success, see below

![image](https://user-images.githubusercontent.com/34683012/44944704-d7841200-addb-11e8-8a25-f2a8bd766d88.png)

Any idea? Thanks in advance!

**Comment by strengejacke** [comment]
This is to avoid memory problems. You can force to plot all values, if you have all packages up to date:

`plot_model(m4,type = "pred",terms=c('conf [all]','cond'))`

**Comment by nfaivre** [comment]
That worked, sorry for missing that option.
Thanks for your quick answer, and for this great package!

**Comment by strengejacke** [comment]
As marginal effects are based on _ggeffects_, you find all options here: https://strengejacke.github.io/ggeffects/articles/effectsatvalues.html
