### ISSUE TITLE
Show.ci=0.90

### ISSUE THREAD

**Issue by Shelbyti** [strengejacke/sjPlot#410]
Within tab_model, show.ci is supposed to function as either logical or numeric (between 0 and 1, indicating the range of the confidence intervals). However, when specifying show.ci=0.90 (or any other value) the output table does not change and continues to give the default 0.95 CI. Is there a way to get 90% CI in the output table?

**Comment by strengejacke** [comment]
are you sure, or is it due to rounding? I can't reproduce this bug, and get different result for following:

```r
library(sjmisc)
linbrary(sjPlot)
data(efc)
efc <- to_factor(efc, c161sex, e42dep, c172code)
m <- lm(neg_c_7 ~ pos_v_4 + c12hour + e42dep + c172code, data = efc)
tab_model(m)
tab_model(m, show.ci = .5)
```

**Comment by Shelbyti** [comment]
I don't believe it's due to rounding. When I calculate the CIs manually for 90% and 95%  for the actual estimates they are quite a bit different, but I'm not sure how to calculate the CIs for the actual odds ratios which is why I'm wanting to use the tab_model output. Hopefully I have provided enough information for this to be reproducible, let me know if there are any issues. Thanks.

[EULU_log reg_R export_practice data.xlsx](https://github.com/strengejacke/sjPlot/files/2446651/EULU_log.reg_R.export_practice.data.xlsx)

Here is the code I use for the tab_model:

library(lme4)
library(sjPlot) 
library(sjmisc)

#import dataset as EULU

EULU$Site <- factor(EULU$Site)  
EULU$Year <- factor(EULU$Year)  

myglmer<-glmer(Detections ~ NEness +StreamD + FlowAcc + Slope + BA + (1 | Site)  + (1 | Year)  + (1 | Array), data = EULU, family = binomial (link=logit)) 

#rerun to fix convergence
ss <- getME(myglmer,c("theta","fixef"))
m3 <- update(myglmer,start=ss,control=glmerControl(optimizer="bobyqa",
                                                   optCtrl=list(maxfun=2e4)))

#produce table
tab_model(m3, show.ci=0.5)    #Shows same CI as below
tab_model(m3, show.ci=0.95)

**Comment by strengejacke** [comment]
ok, this is an issue of the _broom_ package, and it doesn't seem to work in _broom.mixed_, either. I [filed an issue](https://github.com/bbolker/broom.mixed/issues/30), maybe I will add a workaround meanwhile this issue is being fixed.

**Comment by strengejacke** [comment]
added a workaround that fixes this isse. will commit later.
