### ISSUE TITLE
sjp.glmer Reporting predicted probabilities for specific x-values?

### ISSUE THREAD

**Issue by sentenza3000** [strengejacke/sjPlot#412]
Is it possible in any way to report specific predicted probabilities for x-values from an sjPlot element created with sjp.glmer?

Core problem: I have the element “plot1” (a result of a proper sjPlot command).
plot1<-sjp.glmer(model1, type="pred", ...)
I am just trying to extract a specific value y for a certain value x (thus, an y-value in the same row of the data frame like a certain x-value). But I don’t succeed with the very short code below. It always just returns “numeric(0)”. I am also not sure whether plot1$data$y actually represent the predicted probabilities. If not, where are the values for the predicted probabilities stored?

```
.plot1<-sjp.glmer(model1, type="pred", ...)
mean(plot1$data$x)
[1] 2.272503e-16
.plot1$data$y[plot1$data$x==mean(plot1$data$x)]
numeric(0)
.plot1$data$y[plot1$data$x==2.272503e-16]
numeric(0)
.plot1$data$y[plot1$data$x==0.01822207]
numeric(0)
.print(plot1$data$y[plot1$data$x==mean(plot1$data$x)])
numeric(0)
```

Thank you in advance.

**Comment by strengejacke** [comment]
`sjp.glmer()` is deprecated now and replaced by `plot_model()` now. However, sjPlot uses the ggeffects-package for marginal effects, which returns the data frame with the values you need. I suggest you take a look [at ggeffects](https://strengejacke.github.io/ggeffects/).

**Comment by sentenza3000** [comment]
I was aware of the shift to `plot_model`, but still tried to understand how the earlier function and its elements were structured. In any case, your response made me now switch to the new `plot_model` earlier than I was planning. Thanks for your quick response and this amazing, comprehensive package!
