### ISSUE TITLE
Split conditional and zi-plot, or use free scale

### ISSUE THREAD

**Issue by strengejacke** [strengejacke/sjPlot#414]
"I'm using your sjPlot package to plot various aspects of a glmmTMB model I've written, a model which has both a conditional and a zero-inflated component. Currently, when I use plot_model(model), it plots both the coefficients of the conditional and zero-inflated components together, even though the two are on different scales. As a result, the coefficients for the conditional component collapse toward 0 as compared to the coefficients for the zero-inflated component (see attached image). Is there a way to split these into two separate plots?"

![zinb-wtp](https://user-images.githubusercontent.com/26301769/45541337-1f109200-b80f-11e8-98e7-d78cdd2a4c6c.png)

**Comment by strengejacke** [comment]
There is a simple solution to allow the facets to have free axes - however, then it is not possible to define own axis limits. Another option would indeed be to split the plots. I'm trying to implement both options. The latter has the advantage of more correct axis titles, since the ZI-part is mostly not "incidence rate ratios", but rather Odds Ratios of count.

**Comment by TMax66** [comment]
Hi strengejacke,
did you implement that options to split the plots for zi-plot??

thank you
Massimo

**Comment by strengejacke** [comment]
You can use the `grid`-argument:

``` r
library(pscl)
#> Classes and Methods for R developed in the
#> Political Science Computational Laboratory
#> Department of Political Science
#> Stanford University
#> Simon Jackman
#> hurdle and zeroinfl functions by Achim Zeileis
library(sjPlot)
#> Install package "strengejacke" from GitHub (`devtools::install_github("strengejacke/strengejacke")`) to load all sj-packages at once!

data("bioChemists")
model <- zeroinfl(art ~ fem + mar + kid5 + ment | kid5 + phd, data = bioChemists)

plot_model(model, grid = FALSE)
#> $conditional
```

![](https://i.imgur.com/CesUTVH.png)

    #> 
    #> $zero_inflated

![](https://i.imgur.com/Qh5XvoZ.png)

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
