### ISSUE TITLE
tab_model function and the use of a list of linear models

### ISSUE THREAD

**Issue by LDSamson** [strengejacke/sjPlot#415]
Hi, I really like your package and the tables that it can produce. 
Just one point I came across: in the old sjt.lm function I could input a list of linear models to produce a table, while in the newer function tab_model it produces an error when I give a list of linear models as input. See the code below. Of course it's not a big issue, but I was wondering if I am doing something wrong here.

# load package
library(sjPlot)
library(sjmisc)
library(sjlabelled)

# sample data
data("efc")
efc <- as_factor(efc, c161sex, c172code)

m1 <- lm(barthtot ~ c160age + c12hour + c161sex + c172code, data = efc)
m2 <- lm(neg_c_7 ~ c160age + c12hour + c161sex + e17age, data = efc)

# Create a list with linear models
models <- list(m1, m2)

# Create different output tables
sjt.lm(models)         # This code works fine
tab_model(models) # This code gives the following error message:
                                # Error in UseMethod("family") : no applicable method for 'family' applied to an 
                                    object of class "list"
tab_model(m1, m2) # This code works fine as well

**Comment by strengejacke** [comment]
Thanks, fixed. Will commit tonigjht.

**Comment by cathytao** [comment]
Hi, I saw this post is closed but I encountered the exact same issue when I tried it earlier today. 

Error in UseMethod("family") : 
  no applicable method for 'family' applied to an object of class "function"

Greatly appreciated if you could provide any updates.

**Comment by strengejacke** [comment]
Update should be on CRAN. If you still encounter this issue, please post a reprex and your session info.
