### ISSUE TITLE
tab_model 'names attribute' error

### ISSUE THREAD

**Issue by smcnew** [strengejacke/sjPlot#416]
Hi: I'm was using sjt.lmer and sjt.glm successfully a couple months ago but now I'm having trouble. I went back and reinstalled sjlabelled, sjmisc, sjstats, ggeffects and sjPlot from Github and I still can't generate tables from most of my models. I switched to tab_model but keep getting this error (sample data from iris): 

```
> tab_model(lm(Sepal.Length~Petal.Length + Petal.Width + Sepal.Width +Species, data=iris))
Error in names(models) <- unlist(lapply(match.call(expand.dots = F)$...,  : 
  'names' attribute [2] must be the same length as the vector [1]
```

Strangely, the function works if one of the model terms is removed e.g. 
`tab_model(lm(Sepal.Length~Petal.Length + Petal.Width + Species, data=iris))` 

Both models run successfully outside of tab_model. Any help would be greatly appreciated!

**Comment by strengejacke** [comment]
This one works as well:

```r
m <- lm(Sepal.Length~Petal.Length + Petal.Width + Sepal.Width +Species, data=iris)
tab_model(m)
```

So you should not fit the model "on the fly". Strange though...

**Comment by strengejacke** [comment]
ok, the problem was `deparse()`, that inserted a line-break in too long arguments. This is what happened here, now arguments can be max. 500 chars long.

**Comment by smcnew** [comment]
Thanks for the quick reply! Assigning the model to an object works.
