### ISSUE TITLE
Error downloading sjPlot package

### ISSUE THREAD

**Issue by hmarsh** [strengejacke/sjPlot#418]
When I attempted to update the sjPlot package, it was removed completely and I got this message:

ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/broom’
Warning in install.packages :
  installation of package ‘broom’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/zn/t996l02s3zsbfqr2jk08fft40000gn/T/RtmpQNlUuP/downloaded_packages’

I tried multiple times to install it again and was unable to get it to download successfully. Any help would be appreciated.

**Comment by strengejacke** [comment]
Do you have more details about the error message? It looks like it has something to do with the broom-package.
