### ISSUE TITLE
plot_model transformation of estimates

### ISSUE THREAD

**Issue by connyvs** [strengejacke/sjPlot#422]
Hi, the function information of plot_model doesn't specify which transformations are possible. My dependent variable is inverse-transformed (-1000/DV) - is there a way to back-transform the estimates in the plot?
Thanks!

**Comment by strengejacke** [comment]
Just define your own function:

```r
myfun <- function(x) x*2
plot_model(model, transform = "myfun")
```

**Comment by ElmoreEcology** [comment]
I can only get this method to work when I do not designate a type argument. Is there a way to make transform work when type="pred"?

**Comment by strengejacke** [comment]
I suggest using _ggeffects_ directly then (see https://strengejacke.github.io/ggeffects/). Examples for defining own values or functions are shown in this vignette: https://strengejacke.github.io/ggeffects/articles/introduction_effectsatvalues.html
