### ISSUE TITLE
Discrepancy between plot_model output and estimate from lmer summary 

### ISSUE THREAD

**Issue by Gangrelino** [strengejacke/sjPlot#424]
Hello all. 

I am new to R and general linear models, but I have been using the `plot_model` for a while, and really appreciate the work that has been done on the function. 
Recently, I was running linear mixed effect model (`lmer` function) in r and used `plot_model` to get a graph. I am not completely sure what `plot_model `does, but the line generated by `plot_mode`l for one of the fixed effect  **indicates a negative trend,** **while the beta estimate from the summary indicates a positive one.** 

- Here is the **summary of the model**: 
![output 2 _li](https://user-images.githubusercontent.com/8277381/47043263-6b225f80-d14a-11e8-8345-acd412640da8.jpg)

- **Random Effects Summary:** 
![ranef](https://user-images.githubusercontent.com/8277381/47042676-24803580-d149-11e8-8667-c9fdb154e87d.png)

- And the **graph from plot_model function**: 
![graph](https://user-images.githubusercontent.com/8277381/47042687-2944e980-d149-11e8-874a-77f848904303.png)

**###_QUESTIONS_###**
My question is then **what is the `plot_model` function doing**? why do we have a **line going down**, **if the beta estimate** for the **year effect** indicates a **positive effect**? And how were these lines generated in the first place? 

I appreciate any help!

**Comment by strengejacke** [comment]
What is the R code you used to create the plot?

**Comment by Gangrelino** [comment]
here is the code: plot_model(dall.intcp, type="slope", show.loess=F, pred.type = c("fe", "re"))

**Comment by strengejacke** [comment]
Ok, the documentation is maybe a bit unclear here. `type = "slope"` is a kind of diagnostic plot that simply checks the (linear) relationship between two variables: the response and one predictor. So, the "coefficient" that is actually plotted is `lm(Tot.V ~ Year)`.

What kind of plot do you like to have?
