### ISSUE TITLE
Load failed for 'sjPlot'

### ISSUE THREAD

**Issue by eichhork** [strengejacke/sjPlot#425]
Hi, 
unfortunately the "sjPlot" ist not able to load. 
I get following Error: 

Error: package or namespace load failed for ‘sjPlot’:
 .onLoad in loadNamespace() für 'broom' fehlgeschlagen, Details:
  Aufruf: NULL
  Fehler: 'import' ist kein von 'namespace:backports' exportiertes Objekt
In addition: Warning message:
Paket ‘sjPlot’ wurde unter R Version 3.4.4 erstellt 

I tried both, the official release and the latest development build. 
Is there any fix to that I am not aware of?
Thanks!

**Comment by strengejacke** [comment]
> Error: package or namespace load failed for ‘sjPlot’:
.onLoad in loadNamespace() für 'broom' fehlgeschlagen, Details:
Aufruf: NULL

The error message indicates that there's a problem with the broom-package (installation issue?). I guess that not all package dependencies are installed properly, you may try to install other packages first, using `dependencies = TRUE` as argument.
