### ISSUE TITLE
Some variance components equal zero. Respecify random structure!

### ISSUE THREAD

**Issue by huibronson** [strengejacke/sjPlot#426]
my model seems to have a random slope that has zero variance. but since I need to include it to follow "keep it maximal", I cannot trim the random structure down. is there a way to get around it?

**Comment by strengejacke** [comment]
Which function do you use? I assume `tab_model()`. If so, you probably need to hide the output for r-squared and ICC.

**Comment by strengejacke** [comment]
_bump_
