### ISSUE TITLE
Question: change default fonts in sj outputs (wrong character rendering)

### ISSUE THREAD

**Issue by b1azk0** [strengejacke/sjPlot#428]
Hello,
i'm quite sure that this should be easy, but can't find any solution.
When using `sjp.frq()` or any other I get plots with "weird" fonts where polish characters should appear, for example:
![image](https://user-images.githubusercontent.com/22635132/47357326-a8489d80-d6c6-11e8-89f7-5b5de1f5a629.png)
This is also true for some characters in table outputs:
![image](https://user-images.githubusercontent.com/22635132/47357368-c9a98980-d6c6-11e8-95c6-d0848dece53f.png)

Variable labels (as imported by `sjlabels`  from a spss files) look correct in console view:
```

> str(df$gender)
 Factor w/ 4 levels "1","2","3","4": 1 1 3 4 1 1 1 3 1 2 ...
 - attr(*, "labels")= Named num [1:4] 1 2 3 4
  ..- attr(*, "names")= chr [1:4] "typ androgyniczny" "typ kobiecy" "typ męski" "typ nieokreślony"
 - attr(*, "label")= chr "Płeć Psychologiczna"
```

Is there anyway I can fix this? Tables are not that important as I will edit final doc in libreoffice anyway, but plots are priority.

```
version  R version 3.5.1 (2018-07-02)
 os       Manjaro Linux               
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Warsaw               
 date     2018-10-23  

sjlabelled   * 1.0.14   2018-09-12 [1] CRAN (R 3.5.1)                            
 sjmisc       * 2.7.5    2018-09-13 [1] CRAN (R 3.5.1)                            
 sjPlot       * 2.6.1    2018-10-14 [1] CRAN (R 3.5.1)                            
 sjstats      * 0.17.1   2018-10-02 [1] CRAN (R 3.5.1)                                                     
 strengejacke * 0.3.0    2018-10-21 [1] Github (strengejacke/strengejacke@d41d521)
```

**Comment by strengejacke** [comment]
Could you try changing the default font, e.g. with `set_theme()` or adding `theme_sjplot(base_family = "<yourfont>")` to your plot?

**Comment by b1azk0** [comment]
Yes, that helps:

`sjp.frq(df$gender) + theme_sjplot(base_family = "Cantarell")`

 
![image](https://user-images.githubusercontent.com/22635132/47358259-8c92c680-d6c9-11e8-8bee-b72c7acc4d18.png)

Any chance you could help me out how to set this permanently?

I might be interested in tweaking additional font parameters to make them look more consistent:

![image](https://user-images.githubusercontent.com/22635132/47358331-bea42880-d6c9-11e8-9340-851a369d35d6.png)

**Comment by b1azk0** [comment]
After all, clearing up font packages I had my linux machine clearead the whole problem. I don't even need the `set_theme()` function.
Thanks for your help

**Comment by strengejacke** [comment]
Glad to hear it works now!
