### ISSUE TITLE
Question- Line Plot

### ISSUE THREAD

**Issue by Farscape1** [strengejacke/sjPlot#432]
How can i plot an interaction as a line plot rather than dot and whisker for mixed-model. There doesn't seem to be an argument for changing plot type (interaction is with categorical predictors).

**Comment by strengejacke** [comment]
Do you want marginal effects plot?

**Comment by Farscape1** [comment]
Yes

from LGv20

**Comment by strengejacke** [comment]
What is LGv20?

**Comment by Farscape1** [comment]
Sorry that is my phone.

**Comment by strengejacke** [comment]
For categorical predictors, the default are dots with error bars (lines hardly make sense on a discrete scale). If you want to produce marginal effects plots with lines for categorical predictors, I suggest using the [ggeffects-package](https://strengejacke.github.io/ggeffects/). This returns the raw data which can be used for plotting.
