### ISSUE TITLE
Error with tab_model: how to display non-transformed results for logit?

### ISSUE THREAD

**Issue by cathytao** [strengejacke/sjPlot#433]
I am running a regression using cross-listed mixed logit -

> m1 <- glmer (dv ~ iv + (1 | level1) + (1 | level2), data = datnew, family=binomial, control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

I have no problem with getting OR from this -
> tab_model(m1)

But how to get the non-transformed coefficients instead?

>tab_model (m1, transform)
Error in UseMethod("family") : 
  no applicable method for 'family' applied to an object of class "function"
>tab_model(m1, NULL)
Error in UseMethod("family") : 
  no applicable method for 'family' applied to an object of class "NULL"

**Comment by strengejacke** [comment]
Please use `tab_model(m1, transform = NULL)`, see Section https://strengejacke.github.io/sjPlot/articles/tab_model_estimates.html#generalized-linear-models
