### ISSUE TITLE
plot_model(..., type = "diag") works only for lm objects

### ISSUE THREAD

**Issue by meriops** [strengejacke/sjPlot#437]
I can't get the diagnostic plots to work with anything else than `lm` objects. Is that by design? I don't see anything about this in the documentation...

**Comment by strengejacke** [comment]
Diagnostic plots should work for lm, glm, Stan-models, and mixed models. Note that the diagnostic plots are very general and may not be useful for models of _every_ distributional family.

**Comment by strengejacke** [comment]
True, the diagnostic plots only apply to linear and linear mixed models (and Stan models). I should add this to the manual.

**Comment by meriops** [comment]
That'd be great. Thanks for the quick response, Daniel.
