### ISSUE TITLE
plot_grid doesn't work on mixed models diagnostic plots

### ISSUE THREAD

**Issue by reyntjesr** [strengejacke/sjPlot#438]
I can't do a plot_grid on the diagnostic plots of a mixed model:

```
library(lme4)
m <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
ps=plot_model(m, type = "diag")
plot_grid(ps) # error
```
I solved it by creating this function:
```
##' unnests the plots of sjPlot plot_model
##'
##'
##' @param ps a list of all plots
##' @return the unnested list
##' @author Robert Reijntjes
##' @examples
##' # plot assumptions
##' library(lme4)
##' m <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
##' ps=plot_model(m, type = "diag")
##' ps=unnestPlots(ps)
##' plot_grid(ps)
##' @export
unnestPlots <-function(ps) {
  sz=length(ps)
  for (i in sz:-1:1)
  {
    if (class(ps[[i]])=='list')
    {
        szNest=length(ps[[i]])
        for (j in 1 : szNest)
        {
          if (j==szNest)
            ps[[i]]=ps[[i]][[j]]
          else
            append(ps, ps[[i]][j], i) # don't know if this works or is needed
        }
    }
  }
  ps
}
```
now plot_grid works:
```
library(lme4)
m <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
ps=plot_model(m, type = "diag")
ps=unnestPlots(ps)
plot_grid(ps) 
```
Maybe you should unnest the list of plots in the plot_model function

with kind regards,
  Robert

**Comment by strengejacke** [comment]
That's because due to the random effects, the QQ-plots for random effects itself returns a list. Thus, you have a list of plots, where one plot itself is a list of plots (so you have nested lists of plots).

A quick-and-dirty-workaround is to fix the QQ-plots for random effects (2nd element):

```r
ps[[2]] <- ps[[2]]$Subject
plot_grid(ps)
```

**Comment by strengejacke** [comment]
You can use `performance::check_model()`, however, this requires updating [**performance**](https://github.com/easystats/performance) and [**see**](https://github.com/easystats/see) from GitHub (and possibly also [**insight**](https://github.com/easystats/insight)). Next updates for CRAN are planned within the next weeks...

``` r
library(performance)
library(see)
library(lme4)

m <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
check_model(m)
```

![](https://i.imgur.com/MIrkEHT.png)

<sup>Created on 2019-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by reyntjesr** [comment]
Thanks! I'll take a look at the package
