### ISSUE TITLE
plot_model not finding interaction term in model

### ISSUE THREAD

**Issue by gimmeshelter75** [strengejacke/sjPlot#439]
I'm trying to create a plot of the interactive effect of two variables on an outcome variable in a linear regression model using plot_model. I have an interaction term in my model (BLK70*FP59), but when I use type = "int" I get "Error: No interaction term found in model."

I can get the plot I want using type = "pred", but I want to change the values of the moderator term (FP59 below) in the interaction. How can I do this? See below example:

```
library(sjPlot)
model1 <- lm(HR70 ~ . - NAME - STATE_NAME,
       data = crimeExFilt)
model2 <- update(model1, ~ . - PO60 - PO70 -
              HC60 - HC70 - POL60 - POL70 -
              RD60 - RD70 - PS60 - PS70)
model3 <- update(model2, ~ . - GI69)
model4 <- update(model3, ~ . - GI59)
model5 <- update(model4, ~ . - MFIL59)
model6 <- update(model5, ~ . - FP69)
model7 <- update(model6, ~ . - FH60)
model8 <- update(model7, ~ . - DV60)
model9 <- update(model8, ~ . - UE60)
model10 <- update(model9, ~ . - DNL70)
model11 <- update(model10, ~ . - DNL60)
model12 <- update(model11, ~ . - BLK60)
model13 <- update(model12, ~ . - UE70)
model14 <- update(model13, ~ . + BLK70*FP59)
plot_model(model14, type = "pred", terms = c("BLK70", "FP59"))
```
In the plot_model documentation I can see the mdrt.values function, but that doesn't work with type = "pred".

Also, how can I add more lines for differing values of FP59?  The default plot shows three lines with fixed values but I'd like to add more lines and specify the values of FP59 used to create the lines.

Thanks

**Comment by strengejacke** [comment]
For marginal effects plots (`type = "pred"` and `type = "eff"`), `plot_model()` simply wraps the _ggeffects_ package.

Please see these vignettes for different options for which values can be chosen:
https://strengejacke.github.io/ggeffects/articles/effectsatvalues.html

(and as introduction) https://strengejacke.github.io/ggeffects/articles/marginaleffects.html

or this vignette from _sjPlot_:
https://strengejacke.github.io/sjPlot/articles/plot_interactions.html

In your case, use e.g.
``` r
plot_model(model14, type = "pred", terms = c("BLK70", "FP59 [meansd]"))
plot_model(model14, type = "pred", terms = c("BLK70", "FP59 [quart]"))
```

etc.

**Comment by gimmeshelter75** [comment]
thank you!!

On 17 Nov 2018, at 17:18, Daniel <notifications@github.com<mailto:notifications@github.com>> wrote:


For marginal effects plots (type = "pred" and type = "eff"), plot_model() simply wraps the ggeffects package.

Please see these vignettes for different options for which values can be chosen:
https://strengejacke.github.io/ggeffects/articles/effectsatvalues.html

(and as introduction) https://strengejacke.github.io/ggeffects/articles/marginaleffects.html

or this vignette from sjPlot:
https://strengejacke.github.io/sjPlot/articles/plot_interactions.html

In your case, use e.g.

plot_model(model14, type = "pred", terms = c("BLK70", "FP59 [meansd]"))
plot_model(model14, type = "pred", terms = c("BLK70", "FP59 [quart]"))

etc.
