### ISSUE TITLE
Error: could not find function "sjt.df"

### ISSUE THREAD

**Issue by bjce** [strengejacke/sjPlot#441]
Hello. First of all, thank you very much for writing the package! I have a simple and maybe silly question, I tried the package with this simple example:

```
library(sjPlot)
data(iris)
sjt.df(iris, file="sjt_des.doc")
```
but got this error message
```
Error in sjt.df(iris, file = "sjt_des.doc") : 
  could not find function "sjt.df"
```

After having a look at issue [#68](https://github.com/strengejacke/sjPlot/issues/68) I ran `sessioninfo()` and got the following info: 
```
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14

other attached packages:
[1] [...] sjPlot_2.6.1 
```
Any idea of what went wrong?

**Comment by strengejacke** [comment]
Yes, the function is now named `tab_df()`. :-)
