### ISSUE TITLE
font size and organization of table output

### ISSUE THREAD

**Issue by daisyburr** [strengejacke/sjPlot#443]
My table output has so many variables that it goes onto 2 pages. In order to avoid this, is there a way to a) make font size smaller and/or b) specify that random effects go in another column, making the table wider instead of longer?
Thanks!
Current command:
tab_model(glmer_STAI, collapse.ci = TRUE, title = "Results of non-linear mixed model predicting emotion regulation condition", 
          pred.labels = c("Intercept","GSR", "CS","LL","CS:LL","LL:GSR","CS:GSR","LL:STAI","CS:STAI","GSR:STAI","LL:CS:GSR","LL:CS:STAI","LL:GSR:STAI","CS:GSR:STAI","LL:CS:GSR:STAI"))

**Comment by strengejacke** [comment]
You can change the font-size via the `CSS`-argument. See details here:
https://strengejacke.github.io/sjPlot/articles/table_css.html

Random effects are shown in a completely different "layout" than the fixed parameters, so there's no proper way to put the random effects into a new column. You could only remove them from the output (see `show.*`-arguments in `tab_model()`) and add them back by calulating the values on your own (e.g. `sjstats::icc()` or `sjstats::re_var()` etc.).
