### ISSUE TITLE
Feature request: gmnl and mlogit 

### ISSUE THREAD

**Issue by albertostefanelli** [strengejacke/sjPlot#448]
Amazing package. thanks so much for the hard work. 

I wonder if you are willing to support multinominal logistic and probit choice models specifically for the new extensive package gmnl https://cran.r-project.org/web/packages/gmnl/gmnl.pdf developed by Mauricio Sarrias. 

Thanks

**Comment by albertostefanelli** [comment]
gmnl still not supported with last dev version of sjPlot (2.6.2.9000) under R 3.5.2 om macOS High Sierra 10.13.6     

```
plot_model(whatever_name)                                                           
Error in UseMethod("family") :                                                       
  no applicable method for 'family' applied to an object of class "gmnl"
```

**Comment by strengejacke** [comment]
Sorry, you need to update sjstats from GitHub as well.
