### ISSUE TITLE
sjPlot plot_model distance between lines

### ISSUE THREAD

**Issue by brentrug** [strengejacke/sjPlot#449]
Hi
I did this plot with following command:

`plot_model(fit, type = "pred", terms = c("degree_of_urbanization", "language"), dot.size = 2) + labs(y = "NEFI Overall Score", x = "Degree of urbanization", title = "Predicted values of NEFI Overall Score")
`

How can I change the distance between those lines. They are much too close and I don't want to make my plot much wider.

![bildschirmfoto 2019-01-27 um 14 04 12](https://user-images.githubusercontent.com/6370972/51802437-79ecd800-224a-11e9-87e8-5da66eafe057.png)

**Comment by strengejacke** [comment]
Use something like `dodge = .5`. sjPlot simply wraps ggeffects for marginal effects plots. Some arguments from `plot_model()` are passed down to ggeffects `plot()` method. See https://strengejacke.github.io/ggeffects/reference/plot.html

**Comment by brentrug** [comment]
Cool. That did work! Thanks

**Comment by nabaesjodar** [comment]
How could you make it work also for to data points?
This only works for the means and bars:
plot_model(celfnb, type = "eff", terms=c("fTrat", "Linea"),
           show.data = T, **dodge=0.8**)
