### ISSUE TITLE
plot_model not connecting interaction variables from glmer

### ISSUE THREAD

**Issue by ElmoreEcology** [strengejacke/sjPlot#453]
I am plotting specific variables from a top performing glmer model shown below. 

top.guild<-glmer(n_carcasses~PC1+Migratory*Insectivore+Migratory*Woodland+Insectivore*Woodland+(1|Site), offset=lns, family=poisson, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

To visualize how specific variables interact with each other I am using lines such as:

MigWoomod=plot_model(top.guild, type = "eff", terms = c("Migratory","Woodland"), title = "",axis.title = "","Migratory", axis.lim=c(0,0.225))

which gives an output graph:
![rplot01](https://user-images.githubusercontent.com/47396873/52364320-8cb19a80-2a0a-11e9-80fa-4934d8361472.jpeg)

How can I connect the points to clearly show the interaction between variables

**Comment by strengejacke** [comment]
Since you have categorical variables, it's not common (or not even "correct") to connect the data points. However, you could set up the plot using ggplot, e.g. by using the _ggeffects_ package (with the `ggeffect()`-function). Some examples are shown here:

https://strengejacke.github.io/ggeffects/articles/marginaleffects.html

**Comment by strengejacke** [comment]
Oh, it's even simpler. Just add `geom_line()` to your call:

```r
library(sjPlot)
library(ggplot2)

data(iris)
m <- lm(Petal.Length ~ Species * Sepal.Width, data = iris)
plot_model(m, type = "eff", terms = c("Species", "Sepal.Width")) + geom_line()
```

![rplot](https://user-images.githubusercontent.com/26301769/52440109-92e46b80-2b1d-11e9-9bf7-880b75debc46.png)

**Comment by ElmoreEcology** [comment]
Thanks for the help!
