### ISSUE TITLE
Memory allocation issue with plot_model

### ISSUE THREAD

**Issue by BenjaminBlanchard** [strengejacke/sjPlot#455]
When I run plot_model on my object (produced using glmer in the lme4 package), plot_model is unable to produce confidence intervals, giving the following error:

> Could not compute confidence intervals, probably due to memory allocation problems. Try using the `n`-tag (with different values) to reduce number of predicted values, e.g. `terms="Species_disc [n=10]"`.

However, I'm already working with small values for n (two fixed effects, one with only two categories and the other with only three [automatic bins selected by the plot_model]), and adjusting n does not fix the problem. Is there a way to fix this memory allocation problem?

**Comment by strengejacke** [comment]
It depends on the model, it might be that there are other problems. Do you have a reproducible example?

**Comment by strengejacke** [comment]
Or try to update ggeffects from GitHub (see https://github.com/strengejacke/ggeffects). The current dev-version should give a more informative message for the cause of the error. Maybe this helps further in this issue?

**Comment by strengejacke** [comment]
The workaround is to not use `cbind(y, 1- y) ~ ` in the formula. It's better to create a variable `1-y` beforehand and than fit the model, e.g.

```r
negative_y <- 1-y
glmer(cbind(y, negative_y) ~ ...)
```
