### ISSUE TITLE
Error message "data.frame (fr, vars) : undefined columns selected

### ISSUE THREAD

**Issue by Mrfulle82** [strengejacke/sjPlot#456]
Does anyone have any tips on how to solve this? I keep getting the message "Error in `[.data.frame`(fr, vars) : undefined columns selected" when trying to plot a glmer predictive model with 1 random effect. I have checked my column names and they match what is in the code string. Here is the code that keeps giving ke the error: 

plot_model(OKnsurv11dtmax, type = "pred", terms = c("11d_abstmaxpnest"), ci.lvl = .95, title = "", axis.title = c("Abs high temp during 11 day incubation","Predicted RCW nesting success"))

If anyone has any advice, please let me know!

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by Mrfulle82** [comment]
Here is the line of code. CSV file is attached.

attach(OKRCWNestingClimate_v3)
library(AER)
library(lme4)
library(MASS)
library(bbmle)

OKnsurv11dtmax = glmer(nest_survived ~ `11d_abstmaxpnest` + (1|year), data=OKRCWNestingClimate_v3, family=binomial)

library(sjPlot)
library(sjmisc)
library(ggpubr)
library(ggplot2)

plot_model(OKnsurv11dtmax, type = "pred", terms = c("11d_abstmaxpnest"), ci.lvl = .95, title = "", axis.title = c("Abs high temp during 11 day incubation","Predicted nesting success"))

##Error in `[.data.frame`(fr, vars) : undefined columns selected

[OKRCWNestingClimate_v3.xlsx](https://github.com/strengejacke/sjPlot/files/2847968/OKRCWNestingClimate_v3.xlsx)

**Comment by strengejacke** [comment]
Ok, I see. It's due to the "wrong" column names. Column resp. variable names should not begin with numbers. If you fix this, everything works as expected:

```r
library(janitor)
OKRCWNestingClimate_v3 <- clean_names(OKRCWNestingClimate_v3)

m <- glmer(nestsurvived ~ x11dabstmaxpnest + (1 | year),
           data = OKRCWNestingClimate_v3,
           family = binomial
)
plot_model(m, type = "pred", terms = c("x11dabstmaxpnest"), ci.lvl = .95, title = "", axis.title = c("Abs high temp during 11 day incubation","Predicted nesting success"))
```
