### ISSUE TITLE
Error when using type = "pred" for model with transformed predictor(s)

### ISSUE THREAD

**Issue by meristematic** [strengejacke/sjPlot#461]
Using `plot_model` with `type = "pred"` (unlike `type = "eff"`) does not seem to work when there is at least one transformed predictor in the model.

Example:
```
testmod <- glmer(Petal.Length ~ Sepal.Width + sqrt(Sepal.Length) + (1|Species),
                    data = iris, 
                    glmerControl(optimizer = "bobyqa",
                                 optCtrl = list(maxfun = 100000)),
                    na.action = na.fail,
                    family = Gamma(link = "inverse"))

```
```
> plot_model(testmod, type = "pred", term = "Sepal.Width")
Error in eval(predvars, data, env) : object 'Sepal.Length' not found
```

**Comment by strengejacke** [comment]
Thanks. As a workaround, you need to do the transformation before fittng the model, i.e. create a new variable with the squareroot of Sepal.Length.

Once sjPlot is updated on CRAN, it will use a new package, _insight_. You can then download insight from GitHub, and it will work w/o transforming before fitting. However, this currently only works for the GitHub-version from _insight_, and sjPlot must be updated on CRAN (so you have to live with the workaround for a while).

In the long term (about April 2019), the next release cycle for insight should fix this bug, so you can use the official CRAN versions...

**Comment by strengejacke** [comment]
Should be fixed with the forthcoming update...
