### ISSUE TITLE
Hopeful to use sjPlot, but having errors when try to use any functions from the package

### ISSUE THREAD

**Issue by lyartsev** [strengejacke/sjPlot#463]
First of all, the package looks great and I really would like to create the mixed model plots I need.
I have followed the installation instructions, and installed the following packages on RStudio Cloud;
install.packages("sjlabelled")
install.packages("sjmisc")
install.packages("sjstats")
install.packages("ggeffects")
install.packages("sjPlot")

However, every function I try from the sjPlot package is not recognized by r...
"could not find function "sjp.lmer"
"could not find function "set_theme"
"could not find function "sjp.setTheme" etc.
I am not sure how to fix it, any ideas?
The package sjPlot is version 2.6.2
The Rstudio cloud is 3.5.2
(The Rstudio I additionally tried to use it with no success is 1.0.153)

Thank you!!

**Comment by lyartsev** [comment]
I was able to find the problem!

**Comment by strengejacke** [comment]
Ok, great! Functions have been renamed and "merged" into single functions that do the task for different model types. I think this is clearer than having one function for each model class...
