### ISSUE TITLE
cant find sjt.lm

### ISSUE THREAD

**Issue by gareth-harman** [strengejacke/sjPlot#464]
For some reason I can't seem to find the sjt.lm function. 

I have loaded (lme4, sjmisc, sjstats, and sjPlot), but the function doesn't exist.

R version 3.5.1 (2018-07-02)
versions( lme4_1.1-20, sjmisc_2.7.7, sjstats_0.17.3, sjPlot_2.6.2)

I might be making an error, any ideas?

**Comment by strengejacke** [comment]
It's located in `sjmisc::frq()`. See `out`-argument for different output options (table, plot, console). I'll add back a more generic function in sjPlot in a future update.
