### ISSUE TITLE
Give deprecated message for sjt.* functions

### ISSUE THREAD

**Issue by dflynn-volpe** [strengejacke/sjPlot#467]
I like the new tab_model() function. I haven't used this package for a few months, so my old code with sjt.glm wasn't working. 

Related to other issues (like #464), would it be possible to generate deprecated function messages rather than errors when using the old functions by mistake? Like in here: https://www.r-bloggers.com/r-deprecate-functions-with-roxygen2/

Thanks

**Comment by strengejacke** [comment]
There were actually deprecated and defunct messages before functions were removed, I think about a period of about 5-6 month? Maybe this was too short for some "usage-cycles" of some users, but I desperately wanted to clean up my package. ;-)

**Comment by dflynn-volpe** [comment]
Got it -- I'll close this. I apparently was on the slower usage cycle, but I think you might find others are in a similar situation. Consider as a courtesy to us irregular users keeping these deprecation messages for a year or so!
