### ISSUE TITLE
tab_model() not fully compatible with Cox regression

### ISSUE THREAD

**Issue by yilunsun** [strengejacke/sjPlot#468]
tab_model() makes great output table for coxph.object (results of coxph() from survival package). The only issue is that the summary part (number of subjects, deviance, etc.) will fail to output even if the corresponding arguments are set to TRUE. I was wondering if there could be a quick fix for that.

**Comment by strengejacke** [comment]
Do you have a reprex?

**Comment by yilunsun** [comment]
Thanks Daniel for your prompt reply. The reprex is shown as follows. I took data generation part from survival package document. The generated table looks more weird on my laptop, because there is no bottom border there.

``` r
library(survival)
library(sjPlot)
#> Learn more about sjPlot with 'browseVignettes("sjPlot")'.
# Create the simplest test data set 
test1 <- list(time=c(4,3,1,1,2,2,3), 
              status=c(1,1,1,0,1,1,0), 
              x=c(0,2,1,1,1,0,0), 
              sex=c(0,0,0,0,1,1,1)) 
# Fit a stratified model 
fit <- coxph(Surv(time, status) ~ x + strata(sex), test1) 
# Output Model Result
tab_model(fit)
```

<table style="border-collapse:collapse; border:none;">

<tr>

<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">

 

</th>

<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">

Surv(time,status)

</th>

</tr>

<tr>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">

Predictors

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

Estimates

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

CI

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

p

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">

x

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

2.23

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

0.45 – 11.18

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

0.329

</td>

</tr>

</table>

<sup>Created on 2019-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yilunsun** [comment]
Thanks very much Daniel! This is very helpful.
