### ISSUE TITLE
change order of x axis labels

### ISSUE THREAD

**Issue by sdesai90** [strengejacke/sjPlot#469]
Hi, 

Is there a way to change the order of the x axis labels in say sjp.xtab ()? For example, my current plot has x axis labels of 1,2,3 but can I specify it to 1,3,2? 

Thanks for the great package!

**Comment by strengejacke** [comment]
You can relevel the factor that is along the x-axis:

``` r
library(sjPlot)
#> Learn more about sjPlot with 'browseVignettes("sjPlot")'.
data(iris)
iris$Group <- sample(1:4, nrow(iris), TRUE)

sjp.xtab(iris$Species, iris$Group, show.values = F)
```

![](https://i.imgur.com/VU6GU0I.png)

``` r

# relevel factor on x-axis
iris$Species <- relevel(iris$Species, ref = "virginica")
sjp.xtab(iris$Species, iris$Group, show.values = F)
```

![](https://i.imgur.com/NON0wc3.png)

<sup>Created on 2019-11-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
