### ISSUE TITLE
TMB and Matrix version

### ISSUE THREAD

**Issue by tuskenbastard** [strengejacke/sjPlot#479]
Hello, 
I just want to know which version of TMB and Matrix you would recommend on R version 3.5.3. 
I cannot get sjPlot to work because it asks for TMB and i cannot get this package to work because it need a special Matrix version.  Is there a way to use sjPlot on the current RStudio version? I'm a newbie and have tried to install your package for days.

thank you for your time

**Comment by strengejacke** [comment]
If you get this waring:

```r
Warning message:
In checkMatrixPackageVersion() : Package version inconsistency detected.
TMB was built with Matrix version 1.2.17
Current Matrix version is 1.2.15
Please re-install 'TMB' from source using install.packages('TMB', type = 'source') or ask CRAN for a binary version of 'TMB' matching CRAN's 'Matrix' package
```

simply follow the instruction:
`install.packages('TMB', type = 'source')`
