### ISSUE TITLE
Ability to rename "Predictors" and "Estimates" columns

### ISSUE THREAD

**Issue by JCruk** [strengejacke/sjPlot#480]
Is it possible to add an argument to rename these columns? In previous versions `sjt.lmer` would allow for providing a custom string for "Fixed Parts".

If I apply a transform to a logistic model, to produce probabilities rather than odds ratios, it would be nice to rename the "Odds Ratios" column to "Probabilities".

Is there a way to do this with an argument as opposed to manually editing a saved html file?

Thanks!

**Comment by strengejacke** [comment]
See docs here:
https://strengejacke.github.io/sjPlot/reference/tab_model.html

You can use the `string.*` arguments, or the `strings` argument.
