### ISSUE TITLE
tab_model group.terms not working

### ISSUE THREAD

**Issue by bbjonz** [strengejacke/sjPlot#481]

**Comment by bbjonz** [comment]
Hi,

First, thanks for your work on package development!  I'm using tab_model in sjPlot to create a regression table. It seems that the group.terms is not working as intended. Here is a reproducible example using the ubiquitous mtcars dataset:

`data(mtcars)
testlm <- lm(mpg~disp*as.factor(gear), data=mtcars)
sjPlot::tab_model(testlm, group.terms = TRUE)`

And here's the output (in RStudio on a Mac running 10.14.3, though the same thing happens on RStudio Server/Ubuntu):

![image](https://user-images.githubusercontent.com/32881398/55997424-462d2600-5c6f-11e9-8bee-42cd57629723.png)

The factors for the "gear" variable are not indented.  Thanks in advance.

Joe

**Comment by strengejacke** [comment]
`group.terms` is not yet implemented, the argument is a (confusing) placeholder.

**Comment by strengejacke** [comment]
Closing in favor of https://github.com/strengejacke/sjPlot/issues/507

`group.terms` will not be implemented, instead you can show the reference level with `show.reflvl`.
