### ISSUE TITLE
Displaying average marginal effects in plot_model()?

### ISSUE THREAD

**Issue by simcho1994** [strengejacke/sjPlot#483]
Firstly, I just wanted to thank you for the great package. 
Also I was wondering if it is possible to use plot_model() to display the average marginal effects across all observations, instead of the marginal effects holding all other variables constant, as type="pred" does.  

Thanks in advance !

**Comment by strengejacke** [comment]
No. You can't plot / compute average marginal effects [as defined here](https://stats.stackexchange.com/tags/marginal-effect/info). You probably can use the **margins** package, or `emmeans::emtrend()` to get average marginal effects.
