### ISSUE TITLE
tab_model inside for loop not printing in rmarkdown

### ISSUE THREAD

**Issue by aurora-ramalho** [strengejacke/sjPlot#485]
It is known that a print statement is needed for things to get printed inside a for loop (plots, tables, etc.), but with tab_model using print doesn't work as it opens the table in a browser tab.
I'm using lmer and I need results='asis' to insert multiple tab_models inside each {.tabset}.

**Comment by strengejacke** [comment]
The `tab_model()` function returns four elements with the content of the HTML tables. See some details [here](https://strengejacke.github.io/sjPlot/articles/table_css.html). Maybe you can put together your string as required?

**Comment by DanielEWeeks** [comment]
I was able to get 'tab_model' HTML tables to print within a for loop by doing the following inside of an `results="asis"` R code chunk:

```{r, results="asis"}
for (i in 1:2) {
n <- 500
x <- rnorm(n)
e <- rnorm(n)
y <- 2*x + e
r <- lm(y ~ x)
cat(tab_model(r)$knitr,"\n--------\n")
}
```

**Comment by strengejacke** [comment]
Yes, that works for me as well. I think this is the best solution.
