### ISSUE TITLE
How to change the names of predictor variables 

### ISSUE THREAD

**Issue by davidcanarte** [strengejacke/sjPlot#487]
I am using the SjPlot package for plotting odds ratio of some mixed models I am working on (plot_model(my_model, ….). However, I cannot find how to change the labels of the predictors? As I have them now, the predictor labels are the same as in the regression output performed in R.

**Comment by strengejacke** [comment]
You mean `axis.labels`?
See https://strengejacke.github.io/sjPlot/articles/plot_model_estimates.html#labelling-the-plot

**Comment by davidcanarte** [comment]
Thanks! it works now. My data had no labels (only variable names) and sjlabelled worked to do so before plotting.
