### ISSUE TITLE
Error when using type = "pred" for interaction term

### ISSUE THREAD

**Issue by JDLeongomez** [strengejacke/sjPlot#488]
I have been using `plot_model` with `type = "pred"` to plot an interaction. It used to work perfectly until around 2 months ago, but now I always get the same error:

`mod3 <- lmer(Health ~ Height + Waist + (Waist:Height) + Sex + Population + (1 | Country), data = dat)`

`plot_model(mod3, type = "pred", terms = c("Height [all]", "Waist [quart]", "Sex"))`

`> "Sex" was not found in model terms. Maybe misspelled?
Error in eval(predvars, data, env) : object 'Population' not found`

I have tried everything I can think of, including updating packages from GitHub versions, and still get the same error.

**Comment by strengejacke** [comment]
Just remove the paranthesis around `Waist:Height`.

**Comment by JDLeongomez** [comment]
Thanks!
