### ISSUE TITLE
tab_model() returns incorrect values for fixed part in `binomial` model

### ISSUE THREAD

**Issue by AlxndrMlk** [strengejacke/sjPlot#490]
Hi Daniel!

First of all thanks for your amazing job with `sjPlot`! I think it's a great and super-versatile package!

I am using it successfully and it makes examining and reporting MLMs way faster. Amazing! I am really grateful for your effort! <3 

Yesterday I encountered an issue using `tab_model()`. I am describing it below, attaching code for the table, models as well as`tab_model()` output and expected output.

## Issue:

The issue I found only appeared in the context of one group of models. One common feature of all these models is that they have binomial DV.

All the values for the **fixed** part of the models were **incorrec**t, but **random** part was entirely **correct**. 

To deal with this issue I tried to brute-force overwrite `my_table$page.content` with corrected values (**Expected output** section below) but the out put remained unchanged (**Actual output** section below).
 
## Models used:

* `model_20 <- glmer(bctprd ~ 1 + (1 | cntry), family = binomial, data = data_2)`

* `model_21 <- glmer(bctprd ~ lrscale_centered + (1 | cntry), family = binomial, data = data_2)`

* `model_22 <- glmer(bctprd ~ lrscale_centered + (lrscale_centered | cntry), family = binomial, data = data_2)`

* `model_23 <- glmer(bctprd ~ lrscale_centered * full_democracy + (lrscale_centered | cntry), 
                  family = binomial, 
                  data = data_2)`
* `model_24 <- glmer(bctprd ~ lrscale_centered * full_democracy + lrscale_centered * gdp_centered + (lrscale_centered | cntry), 
                  family = binomial, 
                  data = data_2)`

## Table code:

```{r}
tab_model(model_20, model_21, model_22, model_23, model_24,

          show.ci      = FALSE,
          show.dev     = TRUE,
          show.r2      = FALSE,
          show.ngroups = FALSE,
          show.obs     = FALSE,
          p.style      = 'asterisk',

          pred.labels = c("Intercept",
                          "Conservatism",
                          "Full democracy",
                          "Conservatism x full dem.",
                          "GDP",
                          "Conservatism x GDP"),

          dv.labels   = c("Model 0",
                          "Model 1",
                          "Model 2",
                          "Model 3",
                          "Model 4"),

          title = "Table 2. Comparison of models: `model_20`, `model_21`, `model_22`, `model_23`, `model_24`")


```

## Actual output (HTML; raw):

<table>\n<caption>Table 2. Comparison of models: `model_20`, `model_21`, `model_22`, `model_23`, `model_24`</caption>\n<tr>\n<th class=\"thead firsttablerow firsttablecol col1\">&nbsp;</th>\n<th colspan=\"1\" class=\"thead firsttablerow\">Model 0</th>\n<th colspan=\"1\" class=\"thead firsttablerow\">Model 1</th>\n<th colspan=\"1\" class=\"thead firsttablerow\">Model 2</th>\n<th colspan=\"1\" class=\"thead firsttablerow\">Model 3</th>\n<th colspan=\"1\" class=\"thead firsttablerow\">Model 4</th>\n</tr>\n<tr>\n<td class=\"depvarhead firsttablerow firsttablecol col1\">Predictors</td>\n<td class=\"depvarhead firsttablerow col2\">Odds Ratios</td>\n<td class=\"depvarhead firsttablerow col3\">Odds Ratios</td>\n<td class=\"depvarhead firsttablerow col4\">Odds Ratios</td>\n<td class=\"depvarhead firsttablerow col5\">Odds Ratios</td>\n<td class=\"depvarhead firsttablerow col6\">Odds Ratios</td>\n</tr>\n<tr>\n<td class=\"tdata firsttablecol col1\">Intercept</td>\n<td class=\"tdata centeralign modelcolumn1 col2\">0.19 <sup>***</sup></td>\n<td class=\"tdata centeralign modelcolumn2 col3\">0.19 <sup>***</sup></td>\n<td class=\"tdata centeralign modelcolumn3 col4\">0.19 <sup>***</sup></td>\n<td class=\"tdata centeralign modelcolumn4 col5\">0.10 <sup>***</sup></td>\n<td class=\"tdata centeralign modelcolumn5 col6\">0.14 <sup>***</sup></td>\n</tr>\n<tr>\n<td class=\"tdata firsttablecol col1\">Conservatism</td>\n<td class=\"tdata centeralign modelcolumn1 col2\"></td>\n<td class=\"tdata centeralign modelcolumn2 col3\">0.89 <sup>***</sup></td>\n<td class=\"tdata centeralign modelcolumn3 col4\">0.90 <sup>***</sup></td>\n<td class=\"tdata centeralign modelcolumn4 col5\">0.94 <sup>**</sup></td>\n<td class=\"tdata centeralign modelcolumn5 col6\">0.93 <sup>**</sup></td>\n</tr>\n<tr>\n<td class=\"tdata firsttablecol col1\">Full democracy</td>\n<td class=\"tdata centeralign modelcolumn1 col2\"></td>\n<td class=\"tdata centeralign modelcolumn2 col3\"></td>\n<td class=\"tdata centeralign modelcolumn3 col4\"></td>\n<td class=\"tdata centeralign modelcolumn4 col5\">3.72 <sup>***</sup></td>\n<td class=\"tdata centeralign modelcolumn5 col6\">1.96 <sup></sup></td>\n</tr>\n<tr>\n<td class=\"tdata firsttablecol col1\">Conservatism x full dem.</td>\n<td class=\"tdata centeralign modelcolumn1 col2\"></td>\n<td class=\"tdata centeralign modelcolumn2 col3\"></td>\n<td class=\"tdata centeralign modelcolumn3 col4\"></td>\n<td class=\"tdata centeralign modelcolumn4 col5\">0.90 <sup>***</sup></td>\n<td class=\"tdata centeralign modelcolumn5 col6\">0.94 <sup></sup></td>\n</tr>\n<tr>\n<td class=\"tdata firsttablecol col1\">GDP</td>\n<td class=\"tdata centeralign modelcolumn1 col2\"></td>\n<td class=\"tdata centeralign modelcolumn2 col3\"></td>\n<td class=\"tdata centeralign modelcolumn3 col4\"></td>\n<td class=\"tdata centeralign modelcolumn4 col5\"></td>\n<td class=\"tdata centeralign modelcolumn5 col6\">1.25 <sup>*</sup></td>\n</tr>\n<tr>\n<td class=\"tdata firsttablecol col1\">Conservatism x GDP</td>\n<td class=\"tdata centeralign modelcolumn1 col2\"></td>\n<td class=\"tdata centeralign modelcolumn2 col3\"></td>\n<td class=\"tdata centeralign modelcolumn3 col4\"></td>\n<td class=\"tdata centeralign modelcolumn4 col5\"></td>\n<td class=\"tdata centeralign modelcolumn5 col6\">0.98 <sup></sup></td>\n</tr>\n<tr>\n<td colspan=\"6\" class=\"randomparts\">Random Effects</td>\n</tr>\n\n<tr>\n<td class=\"tdata leftalign summary\">&sigma;<sup>2</sup></td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">3.29</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">3.29</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">3.29</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">3.29</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">3.29</td>\n\n<tr>\n<td class=\"tdata leftalign summary\">&tau;<sub>00</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.87 <sub>cntry</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.86 <sub>cntry</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.86 <sub>cntry</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.42 <sub>cntry</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.35 <sub>cntry</sub></td>\n\n<tr>\n<td class=\"tdata leftalign summary\">&tau;<sub>11</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">&nbsp;</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">&nbsp;</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.01 <sub>cntry.lrscale_centered</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.00 <sub>cntry.lrscale_centered</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.00 <sub>cntry.lrscale_centered</sub></td>\n\n<tr>\n<td class=\"tdata leftalign summary\">&rho;<sub>01</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">&nbsp;</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">&nbsp;</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">-0.42 <sub>cntry</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.09 <sub>cntry</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.25 <sub>cntry</sub></td>\n\n<tr>\n<td class=\"tdata leftalign summary\">ICC</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.21</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.21</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.21</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.12</td>\n<td class=\"tdata summary summarydata\" colspan=\"1\">0.10</td>\n<tr>\n<td class=\"tdata leftalign summary firstsumrow\">Deviance</td>\n<td class=\"tdata summary summarydata firstsumrow\" colspan=\"1\">34292.811</td>\n<td class=\"tdata summary summarydata firstsumrow\" colspan=\"1\">33946.398</td>\n<td class=\"tdata summary summarydata firstsumrow\" colspan=\"1\">33838.457</td>\n<td class=\"tdata summary summarydata firstsumrow\" colspan=\"1\">33815.251</td>\n<td class=\"tdata summary summarydata firstsumrow\" colspan=\"1\">33807.618</td>\n</tr>\n<tr>\n<td colspan=\"6\" class=\"footnote\">* p&lt;0.05&nbsp;&nbsp;&nbsp;** p&lt;0.01&nbsp;&nbsp;&nbsp;*** p&lt;0.001</td>\n</tr>\n\n</table>

## Expected output (HTML; "\n" removed):

<table><caption>Table 2. Comparison of models: `model_20`, `model_21`, `model_22`, `model_23`, `model_24`</caption><tr>
    <th class=\"thead firsttablerow firsttablecol col1\">&nbsp;</th><th colspan=\"1\" class=\"thead firsttablerow\">Model 0</th><th colspan=\"1\" class=\"thead firsttablerow\">Model 1</th><th colspan=\"1\" class=\"thead firsttablerow\">Model 2</th><th colspan=\"1\" class=\"thead firsttablerow\">Model 3</th><th colspan=\"1\" class=\"thead firsttablerow\">Model 4</th></tr>
    <tr><td class=\"depvarhead firsttablerow firsttablecol col1\">Predictors</td><td class=\"depvarhead firsttablerow col2\">Odds Ratios</td><td class=\"depvarhead firsttablerow col3\">Odds Ratios</td><td class=\"depvarhead firsttablerow col4\">Odds Ratios</td><td class=\"depvarhead firsttablerow col5\">Odds Ratios</td><td class=\"depvarhead firsttablerow col6\">Odds Ratios</td></tr>
    <tr><td class=\"tdata firsttablecol col1\">Intercept</td>
        <td class=\"tdata centeralign modelcolumn1 col2\">-1.65 <sup>***</sup></td>
        <td class=\"tdata centeralign modelcolumn2 col3\">-1.67 <sup>***</sup></td>
        <td class=\"tdata centeralign modelcolumn3 col4\">-1.67 <sup>***</sup></td>
        <td class=\"tdata centeralign modelcolumn4 col5\">-2.30 <sup>***</sup></td>
        <td class=\"tdata centeralign modelcolumn5 col6\">-1.99 <sup>***</sup></td></tr>
        <tr><td class=\"tdata firsttablecol col1\">Conservatism</td>
            <td class=\"tdata centeralign modelcolumn1 col2\"></td>
            <td class=\"tdata centeralign modelcolumn2 col3\">-0.12 <sup>***</sup></td>
            <td class=\"tdata centeralign modelcolumn3 col4\">-0.11 <sup>***</sup></td>
            <td class=\"tdata centeralign modelcolumn4 col5\">-0.06 <sup>**</sup></td>
            <td class=\"tdata centeralign modelcolumn5 col6\">-0.08 <sup>**</sup></td></tr>
            <tr><td class=\"tdata firsttablecol col1\">Full democracy</td>
                <td class=\"tdata centeralign modelcolumn1 col2\"></td>
                <td class=\"tdata centeralign modelcolumn2 col3\"></td>
                <td class=\"tdata centeralign modelcolumn3 col4\"></td>
                <td class=\"tdata centeralign modelcolumn4 col5\">1.31 <sup>***</sup></td>
                <td class=\"tdata centeralign modelcolumn5 col6\">0.67 <sup></sup></td></tr>
                <tr><td class=\"tdata firsttablecol col1\">Conservatism x full dem.</td>
                    <td class=\"tdata centeralign modelcolumn1 col2\"></td>
                    <td class=\"tdata centeralign modelcolumn2 col3\"></td>
                    <td class=\"tdata centeralign modelcolumn3 col4\"></td>
                    <td class=\"tdata centeralign modelcolumn4 col5\">-0.11 <sup>***</sup></td>
                    <td class=\"tdata centeralign modelcolumn5 col6\">-0.06 <sup></sup></td></tr>
                    <tr><td class=\"tdata firsttablecol col1\">GDP</td>
                        <td class=\"tdata centeralign modelcolumn1 col2\"></td>
                        <td class=\"tdata centeralign modelcolumn2 col3\"></td>
                        <td class=\"tdata centeralign modelcolumn3 col4\"></td>
                        <td class=\"tdata centeralign modelcolumn4 col5\"></td>
                        <td class=\"tdata centeralign modelcolumn5 col6\">0.22 <sup>*</sup></td></tr>
                        <tr><td class=\"tdata firsttablecol col1\">Conservatism x GDP</td>
                            <td class=\"tdata centeralign modelcolumn1 col2\"></td>
                            <td class=\"tdata centeralign modelcolumn2 col3\"></td>
                            <td class=\"tdata centeralign modelcolumn3 col4\"></td>
                            <td class=\"tdata centeralign modelcolumn4 col5\"></td>
                            <td class=\"tdata centeralign modelcolumn5 col6\">-0.02 <sup></sup></td></tr>
                            <tr><td colspan=\"6\" class=\"randomparts\">Random Effects</td></tr><tr>
                                <td class=\"tdata leftalign summary\">&sigma;<sup>2</sup></td>
                                <td class=\"tdata summary summarydata\" colspan=\"1\">3.29</td>
                                <td class=\"tdata summary summarydata\" colspan=\"1\">3.29</td>
                                <td class=\"tdata summary summarydata\" colspan=\"1\">3.29</td>
                                <td class=\"tdata summary summarydata\" colspan=\"1\">3.29</td>
                                <td class=\"tdata summary summarydata\" colspan=\"1\">3.29</td>
                                <tr>
                                    <td class=\"tdata leftalign summary\">&tau;<sub>00</sub></td>
                                    <td class=\"tdata summary summarydata\" colspan=\"1\">0.87 <sub>cntry</sub></td>
                                    <td class=\"tdata summary summarydata\" colspan=\"1\">0.86 <sub>cntry</sub></td>
                                    <td class=\"tdata summary summarydata\" colspan=\"1\">0.86 <sub>cntry</sub></td>
                                    <td class=\"tdata summary summarydata\" colspan=\"1\">0.42 <sub>cntry</sub></td>
                                    <td class=\"tdata summary summarydata\" colspan=\"1\">0.35 <sub>cntry</sub></td>
                                    <tr><td class=\"tdata leftalign summary\">&tau;<sub>11</sub></td>
                                        <td class=\"tdata summary summarydata\" colspan=\"1\">&nbsp;</td>
                                        <td class=\"tdata summary summarydata\" colspan=\"1\">&nbsp;</td>
                                        <td class=\"tdata summary summarydata\" colspan=\"1\">0.01 <sub>cntry.lrscale_centered</sub></td>
                                        <td class=\"tdata summary summarydata\" colspan=\"1\">0.00 <sub>cntry.lrscale_centered</sub></td>
                                        <td class=\"tdata summary summarydata\" colspan=\"1\">0.00 <sub>cntry.lrscale_centered</sub></td>
                                        <tr><td class=\"tdata leftalign summary\">&rho;<sub>01</sub></td>
                                            <td class=\"tdata summary summarydata\" colspan=\"1\">&nbsp;</td>
                                            <td class=\"tdata summary summarydata\" colspan=\"1\">&nbsp;</td>
                                            <td class=\"tdata summary summarydata\" colspan=\"1\">-0.42 <sub>cntry</sub></td>
                                            <td class=\"tdata summary summarydata\" colspan=\"1\">0.09 <sub>cntry</sub></td>
                                            <td class=\"tdata summary summarydata\" colspan=\"1\">0.25 <sub>cntry</sub></td><tr>
                                                <td class=\"tdata leftalign summary\">ICC</td>
                                                <td class=\"tdata summary summarydata\" colspan=\"1\">0.21</td>
                                                <td class=\"tdata summary summarydata\" colspan=\"1\">0.21</td>
                                                <td class=\"tdata summary summarydata\" colspan=\"1\">0.21</td>
                                                <td class=\"tdata summary summarydata\" colspan=\"1\">0.12</td>
                                                <td class=\"tdata summary summarydata\" colspan=\"1\">0.10</td><tr>
                                                    <td class=\"tdata leftalign summary firstsumrow\">Deviance</td>
                                                    <td class=\"tdata summary summarydata firstsumrow\" colspan=\"1\">34292.811</td>
                                                    <td class=\"tdata summary summarydata firstsumrow\" colspan=\"1\">33946.398</td>
                                                    <td class=\"tdata summary summarydata firstsumrow\" colspan=\"1\">33838.457</td>
                                                    <td class=\"tdata summary summarydata firstsumrow\" colspan=\"1\">33815.251</td>
                                                    <td class=\"tdata summary summarydata firstsumrow\" colspan=\"1\">33807.618</td></tr>
                                                    <tr><td colspan=\"6\" class=\"footnote\">* p&lt;0.05&nbsp;&nbsp;&nbsp;** p&lt;0.01&nbsp;&nbsp;&nbsp;*** p&lt;0.001</td></tr></table>

Do you have any idea why this might be the case?

Thanks and best,
Aleksander

**Comment by AlxndrMlk** [comment]
I just noticed that values in **Actual output** are exponentials of the values in **Expected output**. 

Therefore **odds ratios** are used in the **Actual output** instead of **log-odds ratios** (as in `lmer` outputs).

I this possible to switch odds ratios to log-odds ratios here?

**Comment by strengejacke** [comment]
Ok, thanks for digging deeper into this issue and resolving it...
