### ISSUE TITLE
Deconflicting internal labels in plot_likert using ggrepel

### ISSUE THREAD

**Issue by ibecav** [strengejacke/sjPlot#493]
Hi I love the `plot_likert` function but while `values = "sum.outside"` helps wondering if you might consider a feature request to add `ggrepel` to use it to help deconflict interior labels by adjusting those that conflict slightly up or down.

Replace lines 698-715 of plot_likert.R with the following after adding ggrepel::geom_text_repel to the namespace.

    gp <- gp +
      geom_text_repel(
        data = dplyr::filter(mydat.pos, .data$frq > 0),
        aes(
          x = .data$x,
          y = .data$freq,
          label = sprintf("%.*f%s", digits, 100 * .data$frq, percsign),
          direction = "y",
          position=position_stack(vjust=0.5, reverse = TRUE),
          force = .5,
          point.padding = NA
        )
      ) +
      geom_text_repel(
        data = dplyr::filter(mydat.neg, .data$frq < 0),
        aes(
          x = .data$x,
          y = .data$freq,
          label = sprintf("%.*f%s", digits, 100 * abs(.data$frq), percsign),
          direction = "y",
          position=position_stack(vjust=0.5, reverse = TRUE),
          force = .5,
          point.padding = NA
        )
      )

**Comment by strengejacke** [comment]
Doesn't seem to work, I always get this error:

```r
Warning: Ignoring unknown aesthetics: direction, position, force, point.padding
Warning: Ignoring unknown aesthetics: direction, position, force, point.padding
Don't know how to automatically pick scale for object of type PositionStack/Position/ggproto/gg. Defaulting to continuous.
Error: Aesthetics must be either length 1 or the same as the data (18): position
```

**Comment by ibecav** [comment]
Sorry, made a stupid typo (used .data$freq instead of .data$frq).  Fixed now here's a reprex from your help file.  I'll submit a proper PR to make your life cleaner...

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(sjPlot)
#> Learn more about sjPlot with 'browseVignettes("sjPlot")'.
library(sjmisc)
data(efc)
# find all variables from COPE-Index, which all have a "cop" in their
# variable name, and then plot that subset as likert-plot
mydf <- find_var(efc, pattern = "cop", out = "df")

plot_likert(mydf)
```

![](https://i.imgur.com/yEqfwst.png)

``` r

plot_likert(
  mydf,
  grid.range = c(1.2, 1.4),
  expand.grid = FALSE,
  values = "sum.outside",
  show.prc.sign = TRUE
)
```

![](https://i.imgur.com/gaAhSbo.png)

``` r

# Plot in groups

plot_likert(mydf, c(2,1,1,1,1,2,2,2,1))
```

![](https://i.imgur.com/GDwotE5.png)

``` r

groups <- sjt.pca(mydf)$factor.index
plot_likert(mydf, groups = groups)
```

![](https://i.imgur.com/Q76VThJ.png)

``` r

plot_likert(mydf,
            c(rep("B", 4), rep("A", 5)),
            sort.groups = FALSE,
            grid.range = c(0.9, 1.1),
            geom.colors = "RdBu",
            rel_heights = c(6, 8),
            wrap.labels = 40,
            reverse.scale = TRUE)
```

![](https://i.imgur.com/iH6zuuV.png)

``` r

# control legend items
six_cat_example = data.frame(
  matrix(sample(1:6, 600, replace = TRUE),
         ncol = 6)
)

six_cat_example <-
  six_cat_example %>%
  dplyr::mutate_all(~ordered(.,labels = c("+++","++","+","-","--","---")))

# Old default
plot_likert(
  six_cat_example,
  groups = c(1, 1, 1, 2, 2, 2),
  group.legend.options = list(nrow = 2, byrow = FALSE)
)
```

![](https://i.imgur.com/JQiIQz6.png)

``` r

# New default
plot_likert(six_cat_example, groups = c(1, 1, 1, 2, 2, 2))
```

![](https://i.imgur.com/7wbUcmf.png)

<sup>Created on 2019-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
> Sorry, made a stupid typo (used .data$freq instead of .data$frq)

I thought that I already fixed that typo, and still got the error, but your examples look good! Will look into it, thanks!

**Comment by ibecav** [comment]
Okay I also had a misplaced closing ")" around the aes section which I fixed as well.
