### ISSUE TITLE
tab_model shows error messages for non-linear brms model

### ISSUE THREAD

**Issue by mages** [strengejacke/sjPlot#494]
Hi there,

I tried to display the following non-linear model from the `brms` vignette with `tab_model`, but got an error message.
```s
library(brms)
loss <- read.csv("https://paul-buerkner.github.io/data/loss.csv")
fit_loss <- brm(
  bf(cum ~ ult * (1 - exp(-(dev/theta)^omega)),
     ult ~ 1 + (1|AY), omega ~ 1, theta ~ 1, 
     nl = TRUE),
  data = loss, family = gaussian(),
  prior = c(
    prior(normal(5000, 1000), nlpar = "ult"),
    prior(normal(1, 2), nlpar = "omega"),
    prior(normal(45, 10), nlpar = "theta")
  ),
  control = list(adapt_delta = 0.9)
)
library(sjPlot)
tab_model(fit_loss)
# Error: 'model' has no random effects.
```
Is this an expected behaviour?

Thanks

**Comment by strengejacke** [comment]
Should be fixed now, but probably requires updating the packages [**insight**](https://github.com/easystats/insight) and [**performance**](https://github.com/easystats/performance) from GitHub before.

**Comment by mages** [comment]
Thanks, beautiful! 
![Screenshot 2019-06-12 at 20 31 19](https://user-images.githubusercontent.com/1146581/59380479-2094c980-8d51-11e9-99f3-e1b4ff9489b7.png)
Much appreciated!
