### ISSUE TITLE
Unable to export as .jpg

### ISSUE THREAD

**Issue by rpmady** [strengejacke/sjPlot#499]
Is there a way to export as a ".jpg"? I tried this, but I can't seem to open it: 
```
tab_df(df.mod1, alternate.rows=TRUE, 
       CSS = list(css.firsttablecol = 'font-weight: bold;',
                  css.firsttablerow = '+font-weight: bold;'),
       file="df.mod1.jpg") 
```

**Comment by strengejacke** [comment]
No, the table functions create a HTML-table, and it is only possible to save the table as HTML-file.

**Comment by rpmady** [comment]
Okay, that's what I though. Thank you!
