### ISSUE TITLE
loading sjPlot throws an error

### ISSUE THREAD

**Issue by cstecker** [strengejacke/sjPlot#500]
loading sjPlot throws an error and the usual remedies don't work (e.g. updating all packages).

> library(sjPlot)
Error: package or namespace load failed for ‘sjPlot’:
 Objekt ‘typical_value’ ist nicht von 'namespace:sjmisc' exportiert
In addition: Warning message:
Paket ‘sjPlot’ wurde unter R Version 3.5.3 erstellt

**Comment by strengejacke** [comment]
> Objekt ‘typical_value’ ist nicht von 'namespace:sjmisc' exportiert

This error message seems to indicate that not all your packages are up to date.

**Comment by cstecker** [comment]
Many thanks for the quick reply -- and sorry. It works indeed after not only selectively updating some packages but all packages.

**Comment by strengejacke** [comment]
Great, good to know it solved your issue!
