### ISSUE TITLE
how to use plot_grid with a numeric vector of length less than 4

### ISSUE THREAD

**Issue by davidcanarte** [strengejacke/sjPlot#501]
I am running 4 hierarchical logistic models and I am reporting average marginal effects of significant predictors per model, and I am using "plot_grid" 
> plot_grid(x, margin = c(1, 1, 1, 1)) # This is working for models with 4 significant predictors

But how could I plot my models but with a numeric vector of 3 or 2 (one after the other in one line)? I am stuck with this because I have one model with only 3 significant predictors.

Thanks

**Comment by strengejacke** [comment]
I'm not sure I fully understand your problem. `plot_grid()` has nothing to do with significance of model coefficients. It just arranges plots.

**Comment by davidcanarte** [comment]
Sorry for not being clear! what I meant is that when I try to plot 3 models using 'plot_grid(x, margin = c(1, 1, 1))' rather than four as in the manual's example 'plot_grid(x, margin = c(1, 1, 1, 1))', I end up with an empty space at the bottom right, and I don't want that. How could I have my 3 models in one plot horizontally?

**Comment by strengejacke** [comment]
Ah, I see. `plot_grid()` is really a quick wrapper around `gridExtra`, so it offers almost no flexibility. However, if you don't feel comfortable with gridExtra, you can use the function [`see::plots()](https://easystats.github.io/see/reference/plots.html), which has a `ncol` and `nrow` argument, to force a specific number of rows or columns.

**Comment by davidcanarte** [comment]
Thanks for answering! I will check that

**Comment by strengejacke** [comment]
I'll close this for now, but feel free to re-open if you encounter any issues...
