### ISSUE TITLE
Error when trying to plot interaction from a lme (nlme) model

### ISSUE THREAD

**Issue by ManuelSpinola** [strengejacke/sjPlot#502]
I got the following erro when trying to plow an lme (nlme) model with interaction

mod_adi_01 <- lme(mean_adi ~ Hour*Site, random = ~ 1 | SiteR, weight = varIdent(form = ~ 1 | SiteR), data = df_02) 

plot_model(mod_adi_01, type = "int")

Error: Must use a vector in `[`, not an object of class matrix.

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
This works for me.

``` r
library(nlme)
library(sjPlot)
data("Orthodont")

fm1 <-
  lme(
    distance ~ age * Sex,
    random =  ~ age | Subject,
    weights = varIdent(form =  ~ 1 | Sex),
    data = Orthodont
  )

plot_model(fm1, type = "int")
```

![](https://i.imgur.com/7jIA7RR.png)

<sup>Created on 2019-11-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
