### ISSUE TITLE
sjt.xtab() handling 1 level variable

### ISSUE THREAD

**Issue by dancaisido** [strengejacke/sjPlot#504]
I have 2 variables, and I am to create a cross table, thus, using your function, sjt.xtab()
However, one of my variables has only 1 level/value, and I was wondering why sjt.xtab() ran successfully when it's a 1x10 table, but not on a 10x1 table. Error has something to do with the rowSums. I'm thinking that since 1x10 table has only 1 row, then that's why we're getting a rowSums issue, but I dont understand why we didn't get any colSums issue when we are trying to generate the 10x1 table (which has only 1 column)? 

Hope you could help us! Thanks so much!

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by strengejacke** [comment]
_bump_
