### ISSUE TITLE
sjt.xtab() file="..." option

### ISSUE THREAD

**Issue by dancaisido** [strengejacke/sjPlot#505]
Hello Mr SJ!

We really find the sjt.xtab useful in the Shiny tool that we are currently developing. We've been waiting this feature for quite a long time now, as we really need to generate a cross table into an Excel file. However, due to the limitation and environment of the sjPlot's output, i.e. HTML attributes, we were only able to render it and converted (using rMarkdown) the cross table output into an HTML file.

We recently learned about this update, and this is really a useful feature! However, is there a way to finally use it and incorporate it into the Shiny dashboard? The "file" is nowhere to be found when the function was ran using the R Shiny environment (launched in an external server already).

Thanks so much! :)

**Comment by strengejacke** [comment]
I have no idea about Shiny, maybe you could ask in a related forum?
