### ISSUE TITLE
tab_model not working for glmer with Gamma family specified

### ISSUE THREAD

**Issue by kevlim83** [strengejacke/sjPlot#511]
Hi,

I am trying to summarize a simple test model using glmer from the lme4 package.

`
m<- glmer(Y~X*Z + (1|Z:ID), data=testdata);

m2<-glmer(Y~X*Z + (1|Z:ID), data=testdata, family=Gamma)
`
When I use tab_model on model m, it works perfectly, but when the Gamma family is specified in model m2, tab_model() returns an error "object dist.variance not found", but the summary(m2) works.

I looked up the source code and found the error to be related to the insight package. Any ideas how to resolve this issue?

Thanks.

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by kevlim83** [comment]
Thanks for the reply.

See this example as a reproducible case:
`
require(lme4);
 data(cake);
tab_model(glmer(angle~recipe*temperature + (1|recipe:replicate),cake,family=Gamma(link="identity")))
`

**Comment by strengejacke** [comment]
Should work now after updating _insight_ from GitHub, but it probably needs some adjustment. The variance components are probably not accurate.

**Comment by tissotrv** [comment]
I have a similar issue, when trying to summarize a glmer model with tab_model, with family=gamma specified.

I am just getting the following error message:

Error in .compute_variance_distribution(x, var.cor = vals$vc, faminfo,  : 
  object 'dist.variance' not found

**Comment by strengejacke** [comment]
> Should work now after updating insight from GitHub, but it probably needs some adjustment. The variance components are probably not accurate.

**Comment by tissotrv** [comment]
i just reinstalled insight. Still does'nt work.

**Comment by strengejacke** [comment]
Have you installed from GitHub? I checked the initial example, and it worked fine. Else, do you have a reproducible example?

**Comment by tissotrv** [comment]
Nevermind. It works! Thanks for your help!
