### ISSUE TITLE
Inconsistent results between sjPlot and Anova()when including interaction terms in lmer()

### ISSUE THREAD

**Issue by curlsloth** [strengejacke/sjPlot#512]
Hi,

First of all, thank you for this awesome package!

I am using this package to plot the forest-plot of standardized beta values.
My model includes interaction terms
`m1.3.5=lmer(Q3~1+Q4+gender+gcOUT*gender+maxXcorr*gender+(1+Q4+gcOUT*gender+maxXcorr*gender|sub)) `

The results of Anova (car package)

```
Anova(m1.3.5)
Analysis of Deviance Table (Type II Wald chisquare tests)

Response: Q3
                   Chisq Df Pr(>Chisq)    
Q4              228.6415  1  < 2.2e-16 ***
gender            0.4101  1   0.521927    
gcOUT             7.8720  1   0.005021 ** 
maxXcorr          6.2570  1   0.012370 *  
gender:gcOUT      2.3550  1   0.124884    
gender:maxXcorr   0.5016  1   0.478812  
```

Here is the plot: 
`plot_model(m1.3.5, type = "std",se=TRUE,line.size=1.5,dot.size=4,show.values = TRUE)`
![question](https://user-images.githubusercontent.com/52460429/60524941-807cf100-9cbb-11e9-8084-47877f126854.png)

The plot and the Anova() results seems to be quite different.
For example, the gcOUT effect is significant in Anova. However, the SE of the plot of that variable crossed 0, and it does not have *, suggesting it's not significant.

Could you clarify why I have this inconsistence?

Note that if without interaction variables, then the results of these 2 appear to be consistent.

Thank you!

**Comment by strengejacke** [comment]
I can't say for sure w/o reproducible example, but I guess this is because p-values might be calculated differently (using Kenward-Roger approximation of DFs in sjPlot).

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
Just revisited this issue. `Anova()` performes Type-II/Type-III Anova tables, while `plot_model()` just visualizes what `summary()` returns for the coefficients. So these outputs refer to something (completely) different.

**Comment by curlsloth** [comment]
Thank you for your response :)
