### ISSUE TITLE
tab_mode return error: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by Adai5839** [strengejacke/sjPlot#513]
Hi Daniel,

Thank you so much for this package! It really helps a lot!

I recently ran into the error message below. 

> tab_model(CCT_RSMod_CFA_null,CCT_RSMod_CFA_Hof)
Error in if (!is.null(newnames) && length(newnames) != ncol(x)) { : 
  missing value where TRUE/FALSE needed

The weird thing is the exact same code worked last week and nothing has changed.
Could you please give me some hints on what might be the issue? I tried to reinstall the package, Rstudio, and R platform and to change the computer I use, but nothing seems to help.

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by Adai5839** [comment]
> Do you have a reproducible example?

You can find the code ([Here](https://drive.google.com/file/d/1fVzAzwQtYE-C0YZ4EdyU1mvu-Ek3Qqgq/view?usp=sharing)) and data file [here](https://drive.google.com/open?id=1HNOvA03Kts4UnuBwNJwj8v5A2s3fyhIi)

**Comment by strengejacke** [comment]
`Model1` fails when calling `broom::tidy()`:

```r
broom::tidy(Model1, conf.int = TRUE, conf.level = .95, effects = "fixed")
```

So you can't call `tidy()` with `effects = "fixed"` when the model has no fixed effects (intercept-only-model). I must see if I can fix this inside sjPlot, or if this is actually a broom-issue.

**Comment by strengejacke** [comment]
ok, closing in favor of https://github.com/tidymodels/broom/issues/722

**Comment by Adai5839** [comment]
Thank you for your prompt work!

I also got the gut feeling that it might be an issue of broom as [similar issue](https://github.com/strengejacke/sjPlot/issues/56#issue-97235201) appeared previously.
