### ISSUE TITLE
Why is the default scale for ggplot2 plots created by plot_model() for models with Poisson outcomes on a log scale?

### ISSUE THREAD

**Issue by jrosen48** [strengejacke/sjPlot#514]
`plot_model()` is incredibly helpful and flexible; thanks for all the effort this took to create. 

*One quick question*: Why is the default scale for ggplot2 plots created by plot_model() for models with Poisson outcomes on a log scale? I thought that transforming the coefficient into an incidence rate suggested that it can be easily interpreted linearly.

**Comment by strengejacke** [comment]
Are your packages up tp date? For me, the default is IRR:

``` r
library(sjPlot)
counts <- c(18,17,15,20,10,20,25,13,12)
outcome <- gl(3,1,9)
treatment <- gl(3,3)
glm.D93 <- glm(counts ~ outcome + treatment, family = poisson())
plot_model(glm.D93)
```

![](https://i.imgur.com/BQnr9wz.png)

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jrosen48** [comment]
Thank you - my version was up to date but I was (wildly) misunderstanding the nature of the IRR scale. Is that a common scale for rate? I tried to use ``gplot2::ggplot_build()` to determine what the scale was, but didn't get too far. Sorry, this is now out-of-scope but can you tell me what the scale is? And is it common for rates? thank you.

**Comment by strengejacke** [comment]
It's just `exp(coef(model))`.

**Comment by jrosen48** [comment]
thank you so much, how is the scale (in your above case) with limits of .1 and 5?

I.e., below, the default scale seems to simply be the identity/linear. I tried to find scale is used (or how the scale is used), but could not find it.

thank you, again.

``` r
library(ggplot2)

d <- data.frame(var1 = exp(1:10),
                var2 = c(rep('a', 5), rep('b', 5)))

ggplot(d, aes(x = var2, y = var1)) + 
  geom_point() +
  coord_flip()
```

![](https://i.imgur.com/dkBAlXV.png)

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
It's on the log scale. The counterpart of an Odds Ratio of 4/1 is 1/4, or of 3 is 1/3, so eg both .25 and 4 or .33 and 3 need to have the same visual distance from 1. That's why they're on a log scale.

**Comment by jrosen48** [comment]
Thanks!
