### ISSUE TITLE
Robust standard errors not working in tab_model()

### ISSUE THREAD

**Issue by Zirys1** [strengejacke/sjPlot#515]
I do not get the robust standard errors to work. 
I use the following syntax:

tab_model(m, vcov.fun = "vcovHC", vcov.type = "HC3")

It does not work. The Documentation file is not quite clear in metnioning the correct syntax for the robust option.

Would be happy about help.

**Comment by strengejacke** [comment]
That looks like the correct syntax. Is the model you use supported by the sandwich package?

**Comment by Zirys1** [comment]
It's a standard linear model (lm). It worked with sjt.lm and robust=T. That is why I was confused.

**Comment by strengejacke** [comment]
I'll get back to this after my vacation.
