### ISSUE TITLE
breaking down interaction?

### ISSUE THREAD

**Issue by dfareri** [strengejacke/sjPlot#516]
Hi,
I have run an analysis for some data examining developmental differences in learning using glmer and this analysis reveals a significant two way interaction between age and learning strategy.  I have plotted this effect using sjPlot, but I was wondering whether it was possible to use sjPlot to breakdown the interaction as a function of another factor in my model even if the 3-way effect is not significant, just for visualization purposes and for my own understanding of the data.  Is it possible to do something like this?  

Thank you for your time and attention.

Best,
Dominic

**Comment by strengejacke** [comment]
I'm not sure I understand what you would like to achieve. Can you elaborate more on this or do you have an example?

**Comment by dfareri** [comment]
Thanks for the quick reply, and sorry for the lack of clarity.  I think I have figured part of this out.  However I am running into a separate issue now using the terms option in plot_model. 

When I use this option and specify 3 values of a continuous variable to be plotted as 3 separate lines:

plot_model(model=accuracy_by_context_strategy_AgeMC_rfx, type = "int", terms = c("Context","AgeMC [-6.77 .227 7.23]","strategy")) 

the resultant plot still just shows two lines for the age variable, the min and max, which is what happens if I just use:

plot_model(model=accuracy_by_context_strategy_AgeMC_rfx, type = "int").  

Am I not using this flag correctly?

Thanks & sorry for the confusion again.

**Comment by strengejacke** [comment]
For `type = "int"`, you can only use the `mdrt.values`-argument for specific values. Else, try `type = "pred"` and add the requested values in brackets (as you did in your example). 

`terms = c("Context","AgeMC [-6.77 .227 7.23]","strategy")` will display marginal effects for a three-way-interaction, if there is any, you don't need `type = "int"`, which is just a convenient shortcut.

See also docs for the ggeffects-package:
https://strengejacke.github.io/ggeffects/articles/ggeffects.html#two-way-three-way--and-four-way-interactions
https://strengejacke.github.io/ggeffects/articles/introduction_effectsatvalues.html
