### ISSUE TITLE
Confidence Interval disappears from marginal effects plot when I set a y axis (sometimes)

### ISSUE THREAD

**Issue by bshor** [strengejacke/sjPlot#517]
I have a mixed model I estimate with lmer(). I am trying to plot the marginal effect of my predictor of interest, and it works, including printing a confidence interval. But when I try to adjust the y axis limits, the CI disappears sometimes.

```
d.min1<-plot_model(fit.diff.maj[["d.min"]],type="eff",
term="polar [0.7,2.3]",pred.type="re")
d.min2<-plot_model(fit.diff.maj[["d.min"]],type="eff",
term="polar [0.7,2.3]",pred.type="re",axis.lim=c(-.6,.6))

plot_grid(list(d.min1,d.min2))

```

(sjPlot tells me I'm setting a new scale for y which I assume is just something other than the default).

![image](https://user-images.githubusercontent.com/468070/60902392-250baf80-a235-11e9-94ac-9c2c68aa4911.png)

I've tried the trick of setting the axis limit in ggplot with

```
d.min2<-plot_model(fit.diff.maj[["d.min"]],type="eff",
term="polar [0.7,2.3]",pred.type="re")+ylim(-.6,.6))
```

But I get the same result: a disappearing CI.

**Comment by strengejacke** [comment]
I guess the values of the confidence intervals exceed the axis limits, and thus disappear. I think this should work when you set the limits within `coord_cartesian()`.

**Comment by bshor** [comment]
Thanks! This solved the problem.
