### ISSUE TITLE
Suspicious kinks in marginal effects plot estimate and confidence intervals

### ISSUE THREAD

**Issue by bshor** [strengejacke/sjPlot#518]
I'm trying to do a marginal effects plot of a generalized mixed effects model, with a binary outcome variable fit with glmer() from the lme4 package. The marginal effect estimate and confidence intervals look kind of suspicious, though, with kinks at major intervals of the predictor I am plotting.

Here's what I mean. The interval is angular, not smooth, with kinks at round numbers of the predictor of interest (0.0, 0.5, 1.0, 1.5)

![image](https://user-images.githubusercontent.com/468070/61010711-07c20880-a33d-11e9-88a5-31b965522661.png)

Here's the code I use to invoke the plot (minus the appearence code):

```
plot_model(fit[["r"]],type="eff",term=c("pred.np"),pred.type="re")
```

**Comment by strengejacke** [comment]
I think you can solve this issue with the `all` tag:
See https://strengejacke.github.io/ggeffects/articles/introduction_effectsatvalues.html, section pretty value ranges, or see examples in this vignette: https://strengejacke.github.io/ggeffects/articles/practical_logisticmixedmodel.html

**Comment by bshor** [comment]
Ahh ... beautiful!

![image](https://user-images.githubusercontent.com/468070/61158067-8776e100-a4bd-11e9-9141-53354d484858.png)
