### ISSUE TITLE
Suppress Printing of "Wald-statistics approximation" message

### ISSUE THREAD

**Issue by bbjonz** [strengejacke/sjPlot#520]
Hi,

First, thanks, Daniel, for developing sjPlot--it's become a "go to" package for me.  I'd like to make a request, however.  Is there a way to turn off the "Computing p-values via Wald-statistics approximation (treating t as Wald z)" message?  I've tried setting warn=-1 in options and suppressMessages(library(sjPlot)) to no avail.  To make matters more interesting, I've set show.p = FALSE, yet the function seems to compute probability values by default.  Thanks for your help.

I should mention that that I'm working with lmer objects--not sure what it does with other objects.

**Comment by strengejacke** [comment]
closed in https://github.com/strengejacke/sjPlot/commit/ca29861fe8c8a1d38bfa8070ac43832afa2d7996
