### ISSUE TITLE
Add unique reference lines to each facet of plot_model when grid = TRUE

### ISSUE THREAD

**Issue by acolsen** [strengejacke/sjPlot#523]
I would like to add single, unique, horizontal reference lines to each facet of my plot_model object.  I tried to use techniques that work for ggplot objects, but all 4 reference lines were printed on each of the 4 facets instead of one on each.  Is this possible with plot_model objects?  Thanks for any help.

`veg7<- lmer(Ag_VOR~year+ Eco_div +year*Eco_div+(1|lpci_contr)+(1|newecosite),data=HagenData2)`

```
plotveg7 <- plot_model(veg7,type="eff",terms = c("year","Eco_div"),ci.lvl = 0.95,pred.type = "re",title = "",axis.title = c("Year","Visual Obstruction"), legend.title = "Ecoregion",grid = TRUE,colors = "bw")+set_theme(axis.linecolor.x = "black",axis.linecolor.y = "black",)+font_size(axis_title.x=18, axis_title.y=18, labels.x=14, labels.y=14)+
            scale_x_continuous(breaks = c(2012,2013,2014,2015,2016,2017,2018))+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```
![image](https://user-images.githubusercontent.com/53317837/61910089-8778d700-aee8-11e9-928e-a536a55e0e1d.png)

`dummy2 <- data.frame(Eco_div = c("Shinnery Oak Prairie","Sand Sagebrush Prairie","Mixed Grass Prairie","Shortgrass/CRP Mosaic"), Z = c(2,3,4,5))`

`plotveg7 + geom_hline(data = dummy2, aes(yintercept=Z), linetype="dotted")`
![image](https://user-images.githubusercontent.com/53317837/61909715-bb9fc800-aee7-11e9-8df3-8eee04d76dd9.png)

**Comment by strengejacke** [comment]
I think the only way is to return single plots instead of facets, and then add a geom_hline() manually to each plot. Not sure whether you can map this to an aesthetic in the way you prefer?

Maybe on stackoverflow you can get more help related to this issue...
