### ISSUE TITLE
plot_model not recognizing axis labels from sjlabelled

### ISSUE THREAD

**Issue by ElmoreEcology** [strengejacke/sjPlot#524]
I am having trouble with plot_model in sjplot not using the labelled terms for axis labels. I added labels to the variables using set_label, then ran my models, then used plot_model to plot.
`str(radarbirdsndif)`

> 'data.frame':	301 obs. of  28 variables:
 $ Number_Surveys           : int  12 15 15 15 15 15 15 15 14 15 ...
  ..- attr(*, "label")= Named chr "Number of Surveys"
  .. ..- attr(*, "names")= chr "Number_Surveys"
 $ Number_Carcasses         : int  1 0 0 0 0 0 0 2 2 0 ...
  ..- attr(*, "label")= Named chr "Total Carcasses"
  .. ..- attr(*, "names")= chr "Number_Carcasses"
 $ Number_Carcasses_Adjusted: num  1.13 0 0 0 0 ...
  ..- attr(*, "label")= Named chr "Adjusted number of Carcasses"
  .. ..- attr(*, "names")= chr "Number_Carcasses_Adjusted"
 $ date                     : Date, format: "2015-04-01" "2015-04-02" "2015-04-03" "2015-04-04" ...
 $ lns                      : num  2.48 2.71 2.71 2.71 2.71 ...
  ..- attr(*, "label")= Named chr "Log number of Surveys"
  .. ..- attr(*, "names")= chr "lns"
 $ Mean_MTR                 : num  311.4 1062.7 670.8 63.3 384.7 ...
  ..- attr(*, "label")= Named chr "Mean Migration Traffic Rate"
  .. ..- attr(*, "names")= chr "Mean_MTR"
 $ Mean_FF                  : num  10.7 16.02 13.96 9.71 14.22 ...
  ..- attr(*, "label")= Named chr "Mean Speed"
  .. ..- attr(*, "names")= chr "Mean_FF"
 $ Mean_DD                  : num  -7.74 23.51 80.28 185.73 -2.52 ...
  ..- attr(*, "label")= Named chr "Mean Direction"
  .. ..- attr(*, "names")= chr "Mean_DD"
 $ Mean_U                   : num  -4.278 2.881 1.978 -2.088 -0.457 ...
  ..- attr(*, "label")= Named chr "Mean U"
  .. ..- attr(*, "names")= chr "Mean_U"
 $ Mean_V                   : num  7.63 13.89 4.27 -5.26 14.07 ...
  ..- attr(*, "label")= Named chr "Mean V"
  .. ..- attr(*, "names")= chr "Mean_V"
 $ Mean_Height              : num  684 715 689 476 783 ...
  ..- attr(*, "label")= Named chr "Mean Height"
  .. ..- attr(*, "names")= chr "Mean_Height"
 $ season                   : Factor w/ 2 levels "spring","fall": 1 1 1 1 1 1 1 1 1 1 ...
  ..- attr(*, "label")= Named chr "Season"
  .. ..- attr(*, "names")= chr "season"
 $ firstHourmtrmean         : num  245 585 398 145 152 ...
  ..- attr(*, "label")= Named chr "Civil Dusk MTR"
  .. ..- attr(*, "names")= chr "firstHourmtrmean"
 $ firsthalfmtrmean         : num  342.1 1251.7 751.2 65.5 421.8 ...
  ..- attr(*, "label")= Named chr "First Half MTR"
  .. ..- attr(*, "names")= chr "firsthalfmtrmean"
 $ secondhalfmtrmean        : num  265.8 1126.1 776.6 45.3 399 ...
  ..- attr(*, "label")= Named chr "Second Half MTR"
  .. ..- attr(*, "names")= chr "secondhalfmtrmean"
 $ lasthrmtrmean            : num  255.6 283.6 253.3 37.6 NaN ...
  ..- attr(*, "label")= Named chr "Civil Dawn MTR"
  .. ..- attr(*, "names")= chr "lasthrmtrmean"
 $ firstHourHGHTmean        : num  581 658 632 479 588 ...
  ..- attr(*, "label")= Named chr "Civil Dusk Height"
  .. ..- attr(*, "names")= chr "firstHourHGHTmean"
 $ firsthalfHGHTmean        : num  636 789 771 456 818 ...
  ..- attr(*, "label")= Named chr "First Half Height"
  .. ..- attr(*, "names")= chr "firsthalfHGHTmean"
 $ secondhalfHGHTmean       : num  748 671 648 470 815 ...
  ..- attr(*, "label")= Named chr "Second Half Height"
  .. ..- attr(*, "names")= chr "secondhalfHGHTmean"
 $ lasthrHGHTmean           : num  638 580 496 470 NaN ...
  ..- attr(*, "label")= Named chr "Civil Dawn Height"
  .. ..- attr(*, "names")= chr "lasthrHGHTmean"
 $ firstHourFFmean          : num  8.87 17.17 12.96 10.45 11.27 ...
  ..- attr(*, "label")= Named chr "Civil Dusk Speed"
  .. ..- attr(*, "names")= chr "firstHourFFmean"
 $ firsthalfFF              : num  10.83 17.83 14.53 9.24 14.57 ...
  ..- attr(*, "label")= Named chr "First Half Speed"
  .. ..- attr(*, "names")= chr "firsthalfFF"
 $ secondhalfFFmean         : num  10.3 14.5 14 10.5 14.5 ...
  ..- attr(*, "label")= Named chr "Second Half Speed"
  .. ..- attr(*, "names")= chr "secondhalfFFmean"
 $ lasthrFFmean             : num  10.48 14.79 12.83 6.74 NaN ...
  ..- attr(*, "label")= Named chr "Civil Dawn Speed"
  .. ..- attr(*, "names")= chr "lasthrFFmean"
 $ firstHourDDmean          : num  3.185 0.559 84.146 187.635 -15.293 ...
  ..- attr(*, "label")= Named chr "Civil Dusk Direction"
  .. ..- attr(*, "names")= chr "firstHourDDmean"
 $ firsthalfDDmean          : num  -16.25 10.84 39.24 196.54 -5.24 ...
  ..- attr(*, "label")= Named chr "First Half Direction"
  .. ..- attr(*, "names")= chr "firsthalfDDmean"
 $ secondhalfDDmean         : num  7.55 24.04 90.48 184.54 2.17 ...
  ..- attr(*, "label")= Named chr "Second Half Direction"
  .. ..- attr(*, "names")= chr "secondhalfDDmean"
 $ lasthrDDmean             : num  -25.8 86.3 178.1 164.8 NaN ...
  ..- attr(*, "label")= Named chr "Civil Dawn Direction"
  .. ..- attr(*, "names")= chr "lasthrDDmean"

`radarbirdsndif<-set_label(radarbirdsndif, c("Number of Surveys", "Total Carcasses", "Adjusted number of Carcasses", "Date", "Log number of Surveys", "Mean Migration Traffic Rate", "Mean Speed", "Mean Direction", "Mean U", "Mean V", "Mean Height", "Season", "Civil Dusk MTR", "First Half MTR", "Second Half MTR", "Civil Dawn MTR","Civil Dusk Height", "First Half Height", "Second Half Height", "Civil Dawn Height", "Civil Dusk Speed", "First Half Speed", "Second Half Speed", "Civil Dawn Speed","Civil Dusk Direction", "First Half Direction", "Second Half Direction", "Civil Dawn Direction"))`

`get_label(radarbirdsndif)`

>                 Number_Surveys               Number_Carcasses      Number_Carcasses_Adjusted                           date 
           "Number of Surveys"              "Total Carcasses" "Adjusted number of Carcasses"                         "Date" 
                           lns                       Mean_MTR                        Mean_FF                        Mean_DD 
       "Log number of Surveys"  "Mean Migration Traffic Rate"                   "Mean Speed"               "Mean Direction" 
                        Mean_U                         Mean_V                    Mean_Height                         season 
                      "Mean U"                       "Mean V"                  "Mean Height"                       "Season" 
              firstHourmtrmean               firsthalfmtrmean              secondhalfmtrmean                  lasthrmtrmean 
              "Civil Dusk MTR"               "First Half MTR"              "Second Half MTR"               "Civil Dawn MTR" 
             firstHourHGHTmean              firsthalfHGHTmean             secondhalfHGHTmean                 lasthrHGHTmean 
           "Civil Dusk Height"            "First Half Height"           "Second Half Height"            "Civil Dawn Height" 
               firstHourFFmean                    firsthalfFF               secondhalfFFmean                   lasthrFFmean 
            "Civil Dusk Speed"             "First Half Speed"            "Second Half Speed"             "Civil Dawn Speed" 
               firstHourDDmean                firsthalfDDmean               secondhalfDDmean                   lasthrDDmean 
        "Civil Dusk Direction"         "First Half Direction"        "Second Half Direction"         "Civil Dawn Direction" 

`fa10<-glm(formula = Number_Carcasses_Adjusted ~ firsthalfmtrmean + 
           lasthrFFmean + lasthrmtrmean + firsthalfmtrmean:lasthrFFmean + 
           firsthalfmtrmean:lasthrmtrmean + 1, data = radarbirdsndif, 
         subset = (season == "fall"), na.action = "na.roughfix")`

`fa1model=plot_model(fa10, type="pred",terms=c("firsthalfmtrmean[0, 2500, 5000, 7500]", "lasthrFFmean[7,13,19]"), title="b. Fall Season")`

> 
![image](https://user-images.githubusercontent.com/47396873/62067362-24918380-b1f9-11e9-8095-1a1ea5e6ae65.png)
How can I make the plot_model recognize my labels?

**Comment by strengejacke** [comment]
I can't say exactly without a reproducible example, but I _think_ it might be due to the `subset`-option in `lm()`. Make sure to subset your data before (either with dplyr, which preserves the labels, or you use `sjmisc::copy_labels()` to add back value and variable labels), and then fit the model w/o subset-option in lm.

Does that work?

**Comment by strengejacke** [comment]
_bump_

**Comment by ElmoreEcology** [comment]
I did not fix this problem. I went back and changed the names of labels on the input to reflect what I wanted.
