### ISSUE TITLE
Hiding percentages in sjp.stackfrq doesn't work. 

### ISSUE THREAD

**Issue by tkasci** [strengejacke/sjPlot#525]
To reproduce:
```
data(efc)
start <- which(colnames(efc) == "c82cop1")
end <- which(colnames(efc) == "c90cop9")
sjp.stackfrq(efc[, start:end], show.prc = F)
```
Percentages are still shown.

**Comment by strengejacke** [comment]
Sorry, maybe this is not obvious: `show.prc` displays the _axis labels_, while `show.values` shows the percentage-values inside the plot.

Maybe it's better renaming the arguments?

**Comment by tkasci** [comment]
Oops, sorry. Well, at least "whether values should be plotted or not" as a descriptor for `show.values` was not that obvious to me :)
