### ISSUE TITLE
error when using tab_model with multiple membership brm

### ISSUE THREAD

**Issue by kturetsky** [strengejacke/sjPlot#528]
Hi,

I get the following error when I try to use tab_model with a multiple membership brms model:

> Error in `[.data.frame`(mf, , unique(c(response, fixed.component.data,  : 
>   undefined columns selected

Here is a reproducible example:

```
library(brms)
library(sjPlot)

exd <- data.frame(
  sid = c(1:300),
  t1id = sample(200:215, 300, replace=TRUE),
  t2id = sample(200:215, 300, replace=TRUE),
  y = rnorm(300, mean = 85, sd = 8),
  x = rnorm(300, mean = 50, sd = 10)
)

exm <- brm(y ~ x + (1|mm(t1id, t2id)), data=exd)
tab_model(exm)
```

The brm output for this model looks very similar to the output for the same model without the multiple membership term (e.g., y ~ x + (1|t1id)), so I'm hoping it might be possible to use tab_model for the multiple membership type as well.

Thank you!

**Comment by strengejacke** [comment]
This was a bug in [insight](https://easystats.github.io/insight/). I tested it, and it works for me. Try installing *insight** _from Github_, and then it should work for you as well...

**Comment by kturetsky** [comment]
That fixed it! Thanks.
