### ISSUE TITLE
tab_stackfrq() show error when some items had zero-values.

### ISSUE THREAD

**Issue by lilian1222** [strengejacke/sjPlot#532]
This code 
tab_stackfrq(as.data.frame(TAPS_PG_first %>% select("PS1","PS2")),
             value.labels=c('0'='Level I', '1'='Level II','2'='Level III','3'='Level IV'),
             var.labels = c("PS1","PS2"),
             alternate.rows = TRUE,
             show.n = TRUE)

got this error:
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

I think this error caused by the PS2 does not have 0.

table(TAPS_PG_first$PS1)

  0   1   2   3 
  1   8 279  12 

 table(TAPS_PG_first$PS2)

  1   2   3 
 17 277   6 

But old version sjt.stackfrq works fine for this.

Thanks.

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by lilian1222** [comment]
[TAPS.xlsx](https://github.com/strengejacke/sjPlot/files/3509204/TAPS.xlsx)
Please use attached file. Thanks!
tab_stackfrq(as.data.frame(TAPS%>% select("PS1","PS2","PS3","PS4","PS5","PS6","PS7","PS8","PS9","PS10")),
                          value.labels=c('0'='Level I', '1'='Level II','2'='Level III','3'='Level IV'),
             var.labels = c("PS1","PS2","PS3","PS4","PS5","PS6","PS7","PS8","PS9","PS10"),
             alternate.rows = TRUE,show.n = TRUE)
