### ISSUE TITLE
tab_model no longer working for nlme/lme models?

### ISSUE THREAD

**Issue by erikaroper** [strengejacke/sjPlot#536]
Hello,

A few weeks ago I was able to use tab_model with some nlme mixed models to produce some nice output tables.

e.g. m1 <- lme(variable ~  fixed, random = ~1|site, data = data)

However when rerunning the models today I've found that tab_model no longer works for these models and returns this error:

Error in beta %*% t(X) : requires numeric/complex matrix/vector arguments

I've been unable to work out what the error means.

I've tested tab_model on the same models, but using lmer instead and it works fine.

I'm hoping this is an easy fix, or maybe just user error. Please let me know if you need any more info. Thanks!

And thanks for making such a useful package!

**Comment by strengejacke** [comment]
I think you can solve it by setting `show.re.var` and `show.icc` and `show.r2` to `FALSE`. Strange that there is an error, I thought these were captured. Do you have a small reproducible example?

**Comment by strengejacke** [comment]
Can you please install [**insight**](https://github.com/easystats/insight) from GitHub, and see if the error still occurs?

**Comment by erikaroper** [comment]
Ahh, perfect! Thank you! Changing those options to FALSE has fixed the problem.

I had installed insight earlier and unfortunately it did not help with the error.

**Comment by strengejacke** [comment]
> I had installed insight earlier and unfortunately it did not help with the error.

I just fixed that issue in insight. so you need to re-install **from GitHub**. In that case, it should also work without setting the above mentioned options to `FALSE`.

**Comment by erikaroper** [comment]
Thank you!
