### ISSUE TITLE
sjp.grpfrq - show percentage by var.cnt or var.grp categories

### ISSUE THREAD

**Issue by mgironamata** [strengejacke/sjPlot#537]
Is there a way of getting "sjp.grpfrq" to show percentages relative to each var.cnt category? - i.e., so that the sum of percentage values for each of the x-axis (var.cnt) categories adds to 100%.

This old post [https://strengejacke.wordpress.com/2013/03/05/easily-plotting-grouped-bars-with-ggplot/](url) (see Figure 1) suggests it used to be possible?

Thanks,
Marc

**Comment by strengejacke** [comment]
I think `sjp.xtab()` probably is what you're looking for?

**Comment by mgironamata** [comment]
Yes, this is exactly what I was looking for - thanks for the prompt feedback.
