### ISSUE TITLE
tab_model: order of predictors

### ISSUE THREAD

**Issue by Jasmine1990** [strengejacke/sjPlot#540]
Hello!

I have a big table with multiple models one next to the other. I used the best set of covariates so not all the predictors are included in each model. I was wondering if it was possible to re-order the predictors. 

Thanks!
Jasmine

**Comment by strengejacke** [comment]
I think the `order.terms` argument should work.

**Comment by Jasmine1990** [comment]
ok, the problem was that since I did not have all covariates included in each model I needed to print the table and then ordering terms. Thanks!

**Comment by liyispatial** [comment]
> I think the `order.terms` argument should work.

Hi Sir. I am using tab_model for zero-inflated part and I wonder if there's a way to re-order coefficients of zero-inflated model part? Currently order.terms only works for count part. Thanks a lot.
