### ISSUE TITLE
Possible to add support for clmm2 objects from `Ordinal`

### ISSUE THREAD

**Issue by JCruk** [strengejacke/sjPlot#541]
This collection of functions is absolutely amazing!

Is it possible to add in support for clm2 and clmm2 model objects from the Ordinal package? The structure appears to be very similar to clmm objects.

**Comment by strengejacke** [comment]
Should be fixed in _parameters_ and _insight_. _parameters_ has just been submitted, so clm2 should work once you update from CRAN the next days. clmm2 should work once insight is updated, or you update from GitHub.
