### ISSUE TITLE
tab_model error Error in if (!is.null(newnames) && length(newnames) != ncol(x)) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by Moorie142** [strengejacke/sjPlot#543]
Hi, 
I keep running into an error when using the sjplot library and nlme:

NullModel<-lme(Neuroticism~1, random=~1|PersonalID, method = "ML", data = TraitLongT1T4, na.action=na.omit, control=list(opt="optim"))

Mod1<-lme(Neuroticism~Timepoint, random=~Timepoint|PersonalID, correlation=corAR1(), na.action=na.omit, method = "ML", data = TraitLongT1T4, control=list(opt="optim"))

Mod2<-lme(Neuroticism~Timepoint + Place, random=~Timepoint|PersonalID, correlation=corAR1(), na.action=na.omit, method = "ML", data = TraitLongT1T4, control=list(opt="optim"))

Mod3<-lme(Neuroticism~Timepoint + Place + Timepoint*Place, random=~Timepoint|PersonalID, correlation=corAR1(), na.action=na.omit, method = "ML", data = TraitLongT1T4, control=list(opt="optim"))

tab_model(NullModel, Mod1, Mod2, Mod3, show.ci=F, show.se=T,
          dv.labels = c("Null Model","Model 1", "Model 2", "Model 3"),
          string.est = "B",  string.se = "SE",  string.std = "β")

Error in if (!is.null(newnames) && length(newnames) != ncol(x)) { : missing value where TRUE/FALSE needed

There was the same issue on the following thread: https://github.com/strengejacke/sjPlot/issues/513 but don't understand the responses 

Any help would be greatly appreciated - what does this error message mean?

Many thanks
Ian

**Comment by strengejacke** [comment]
Do you have a reproducible example, or some data which allows me to fit the models you posted?

**Comment by Moorie142** [comment]
Thank you so much for your reply. Hopefully this opens
[TraitT1T4Long.csv.zip](https://github.com/strengejacke/sjPlot/files/3614278/TraitT1T4Long.csv.zip)

Code: Place 0 = Home; 1 = Abroad
Time: 0 = T1, 1 = T2, 2 = T3, 3 = T4

**Comment by strengejacke** [comment]
closed in https://github.com/easystats/parameters/commit/fc2c0e2a7d232e93c4673c173528def5970165ce

Should be fixed once sjPlot is updated on CRAN (within the next 1-2 weeks)
