### ISSUE TITLE
transform estimate with a specific function

### ISSUE THREAD

**Issue by EPinzuti** [strengejacke/sjPlot#544]
I transformed the data before computing xmdl6.1 (lmer model) with log10, now I would like to plot with the original scale so I need to define a function for that:
 myfun <- function(x) 10^(x)

 plot_model(xmdl6.1,type="int",terms=c(emo,cond,LE_GHQ),transform="myfun",axis.title=c("Life Events/GHQ","Reaction time"),title="",axis.labels=NULL,axis.label=c("cong","incong","neutr","adv"))

When I run it, nothing change, the estimates are still log10 transformed. Is there a way to do this?

**Comment by strengejacke** [comment]
Not sure, for me it works fine. Do you have a reproducible example?

``` r
library(sjPlot)
#> Learn more about sjPlot with 'browseVignettes("sjPlot")'.
data(mtcars)

m <- lm(mpg ~ log(hp) + gear, data = mtcars)

plot_model(m)
```

![](https://i.imgur.com/EekT2iY.png)

``` r

plot_model(m, transform = "exp")
```

![](https://i.imgur.com/O8x6T1o.png)

``` r

myfun <- function(x) 10^x
plot_model(m, transform = "myfun")
```

![](https://i.imgur.com/G94Peey.png)

<sup>Created on 2019-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
_bump_

**Comment by MaudeBau** [comment]
Any way of doing this with type="pred" plots? 
In the style of plot_model(model,transform="myfun",type="pred") for instance?
It does it automatically in many cases (logit, poisson), but if the transformation is not the default one?

**Comment by strengejacke** [comment]
For _marginal effects plots_ (i.e. `type = "pred"`), the predicted values are always on the scale of the response value. You can, however, apply transformations to the focal terms, see [here](https://strengejacke.github.io/ggeffects/articles/introduction_effectsatvalues.html).

**Comment by MaudeBau** [comment]
Bri.li.ant. Thank you so much!
