### ISSUE TITLE
plot_model random effects: facet.grid not working

### ISSUE THREAD

**Issue by sjungkunz** [strengejacke/sjPlot#546]
Hi Daniel,

it seems as if "facet.grid" is not working in the plot_model command for random effects models. Or is there something I missed? Whenever selecting "facet.grid = FALSE", R returns both intercept and slope in the same plot side by side. Is it possible to plot these in separate plots?

Thanks!

Code:

library(sjPlot)
library(sjmisc)
library(lme4)

data(efc)

fit <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)

plot_model(fit, type = "re", facet.grid = FALSE)

**Comment by strengejacke** [comment]
The argument is named `grid`, not `facet.grid`:

```r
plot_model(fit, type = "re", grid = TRUE)
plot_model(fit, type = "re", grid = FALSE)
```

**Comment by AriFarugie** [comment]
Hey Daniel,
there is still an issue for the grid function

```
fit<-lm(Reaction ~ Days, sleepstudy)

plot_model(fit, type = "diag", grid=T)
```

for `type "diag" ` it is not working. Do you have any suggestions?
