### ISSUE TITLE
using plot_model for binomial glmm with interaction terms

### ISSUE THREAD

**Issue by gef06** [strengejacke/sjPlot#547]
Hi, 

I have a model fit with lme4 with a variety of continuous covariates and one categorical covariate (group, with four levels), with interactions between two of the continuous covariates and group. The model output is as follows:

Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
 Family: binomial  ( logit )
Formula: use ~ z.elandP + z.zebraP + z.buffaloP + z.wildebeestP + z.precip +  
    z.dist_settle + group + z.elandP:group + z.wildebeestP:group +  
    z.precip:group + (1 | animals_code:yearSeason) + (1 + z.wildebeestP +  
    z.dist_settle | animals_code) + (0 + z.elandP | animals_code) +  
    (0 + z.zebraP | animals_code) + (0 + z.buffaloP | animals_code) +  
    (0 + z.precip | animals_code)
   Data: data_model
Control: glmerControl(optCtrl = list(maxfun = 20000))

     AIC      BIC   logLik deviance df.resid 
 37406.6  37664.7 -18673.3  37346.6    40241 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-1.4397 -0.5285 -0.3941 -0.2306 17.3337 

Random effects:
 Groups                  Name          Variance Std.Dev. Corr       
 animals_code.yearSeason (Intercept)   0.02436  0.1561              
 animals_code            (Intercept)   0.90538  0.9515              
                         z.wildebeestP 0.05383  0.2320   -0.46      
                         z.dist_settle 0.23968  0.4896   -0.04 -0.37
 animals_code.1          z.elandP      0.13071  0.3615              
 animals_code.2          z.zebraP      0.12839  0.3583              
 animals_code.3          z.buffaloP    0.33554  0.5793              
 animals_code.4          z.precip      0.98601  0.9930              
Number of obs: 40271, groups:  animals_code:yearSeason, 52; animals_code, 36

Fixed effects:
                              Estimate Std. Error z value Pr(>|z|)    
(Intercept)                   -1.67950    0.29424  -5.708 1.14e-08 ***
z.elandP                       0.10599    0.09914   1.069  0.28500    
z.zebraP                       0.65083    0.07166   9.083  < 2e-16 ***
z.buffaloP                     0.53459    0.10974   4.871 1.11e-06 ***
z.wildebeestP                  0.06761    0.06908   0.979  0.32772    
z.precip                       0.61263    0.30037   2.040  0.04139 *  
z.dist_settle                 -0.31482    0.09886  -3.184  0.00145 ** 
groupf subadult               -0.24807    0.58007  -0.428  0.66890    
groupm adult                  -0.43036    0.45116  -0.954  0.34013    
groupm subadult                0.19008    0.47553   0.400  0.68936    
z.elandP:groupf subadult      -0.37019    0.12440  -2.976  0.00292 ** 
z.elandP:groupm adult         -0.34429    0.16292  -2.113  0.03458 *  
z.elandP:groupm subadult      -0.26798    0.18514  -1.447  0.14779    
z.wildebeestP:groupf subadult  0.23458    0.12446   1.885  0.05947 .  
z.wildebeestP:groupm adult     0.28829    0.11042   2.611  0.00903 ** 
z.wildebeestP:groupm subadult  0.11731    0.11343   1.034  0.30103    
z.precip:groupf subadult      -0.22326    0.36000  -0.620  0.53514    
z.precip:groupm adult         -0.67379    0.46237  -1.457  0.14505    
z.precip:groupm subadult      -1.59183    0.51729  -3.077  0.00209 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

The corresponding plot_model output appears as follows:

![image](https://user-images.githubusercontent.com/8470090/65328087-5eee2000-dbad-11e9-8796-341df84f4d63.png)

I have two queries about the output:

1. it looks like the estimates are exactly as they are in the model output, is there any way to adjust them so that e.g. the . z.precip slope coef for "groupf subadult" is the reference level + z.precip:groupf adult difference in slope? It was my understanding that that was how that effect should be interpreted?

2. are the standard errors shown on the default plot_model settings also transformed? Or are these the original standard errors from the log odds?

I apologise if this is not the right type of forum to ask this question! Any help would be much appreciated!

Genevieve

**Comment by strengejacke** [comment]
1. Yes, `plot_model()` and `tab_model()` are similar to `summary()`, except that the ouput is a plot or a HTML table.

> is the reference level + z.precip:groupf adult difference in slope? It was my understanding that that was how that effect should be interpreted?

Not sure, but you're probably looking for [marginal effects](https://strengejacke.github.io/ggeffects/),  and [how to plot interaction terms](https://strengejacke.github.io/ggeffects/articles/practical_logisticmixedmodel.html)? You could also do this with `plot_model(type = "int")`.

2. The plot shows CI by default. If you set `se` to `TRUE` or some vcov-functions, the standard errors are _not_ transformed, but on the link scale.

**Comment by gef06** [comment]
When I try plot_model(type = "int"), I get an error message that there is no interaction term present in the model -- but I am able to plot the model predictions fine using other plot_model syntax.

What I was trying to do in the display, was show that the slope for e.g. the second level of group (subadult female) is 0.61263-0.22326 (positive), rather than displaying just the -0.22326 (which I thought could be interpreted at a glance as if the slope for them was negative), but have realised I can also achieve this by hand! Your plots look great though, so was tempting to try to do this inside the plot_model framework.

Thank you for info on the CI/standard error behaviour!

**Comment by strengejacke** [comment]
Ok, it still sounds to me that you want to plot marginal effects, that take both main effect and interaction effect at the same time into account.

**Comment by gef06** [comment]
Thanks, I have done that. I appreciate the time to respond to my questions!
