### ISSUE TITLE
Adding labels "a, b, c, d" to each graph using plot_grid

### ISSUE THREAD

**Issue by davidcanarte** [strengejacke/sjPlot#548]
Hello
I combined 4 different cross-level interactions from 4 different models into 1 plot using "plot_grid". Below is the code

# Save pdf file
pdf(file = "./my_figures/cross_level_panel.pdf", 
     width = 20, height = 18)
plot_grid(list(p1.int, p2.int, p3.int, p4.int))
          labels = c("A", "B", "C", "D")
dev.off()

But I can't figure it out how to assign the letters to each of the plots. How can I do that?

**Comment by strengejacke** [comment]
You could try [see::plots()](https://easystats.github.io/see/reference/plots.html), which has a `tags`-argument to assign letters to plots.

**Comment by strengejacke** [comment]
Ok, you can add tags now with the `tags`-argument.
