### ISSUE TITLE
plotting models with transformed terms

### ISSUE THREAD

**Issue by ashenkin** [strengejacke/sjPlot#549]
Hi there,
It seems that when terms are modified inside parentheses, sjplot isn't able to identify them.  Plotting "fit" and "fit2" below works, but "fit2" fails.
Thanks,
Allie

`library(sjPlot)
library(ggplot2)
data(efc)
theme_set(theme_sjplot())

fit <- lm(barthtot ~ c12hour, data = efc)

plot_model(fit, type = "pred", terms = "c12hour")

fit2 <- lm(barthtot ~ log(c12hour), data = efc)
plot_model(fit2, type = "pred", terms = "c12hour")

fit3 <- lm(barthtot ~ log(c12hour/10), data = efc)
plot_model(fit3, type = "pred", terms = "c12hour")
`

**Comment by strengejacke** [comment]
fixed in https://github.com/easystats/insight/commit/adfb1fdd2114887607213885806bc9315e375e15
Once the _insight_ pkg is updated on CRAN, this should work. You can also update _insight_ from GitHub.

**Comment by ashenkin** [comment]
Ok, thanks, that now works.  However, something strange is going on with lmer.  Any thoughts?
```
library(sjPlot)
library(ggplot2)
data(efc)
theme_set(theme_sjplot())
efc$cat = rep_len(factor(c(letters[1:5])), 908)
efc$cat2 = sample(factor(c(letters[1:10])), size = 908, replace = T)
fit4 <- lmer(barthtot ~ (1|cat2) + log10(c12hour/10)*cat, data = efc)
plot_model(fit4, type = "pred", terms = "c12hour")
`c12hour` was not found in model terms. Maybe misspelled?
Error in model.frame.default(delete.response(terms(object, fixed.only = TRUE)),  : 
  invalid type (closure) for variable 'cat'
```

**Comment by strengejacke** [comment]
This is related to https://github.com/easystats/insight/issues/79

It works once you write `fit4 <- lmer(barthtot ~ log10(c12hour/10)*cat + (1|cat2), data = efc)`

**Comment by ashenkin** [comment]
Ok, thanks... so, is this an insight issue then?  Kind of a pain to rewrite and refit all mixed models - some of which take days to converge...  esp when convention is to place random effects before fixed...

**Comment by strengejacke** [comment]
Yes, sorry for the inconvenience. It's not straightforward separating random from fixed effects in the formula part when random effects are placed before fixed, especially since we have these "special" formulas in brms... If you have any ideas how to write the correct regex for parsing the formula, let me know!

**Comment by ashenkin** [comment]
Gotcha - i'm not familar with brms... search for a pipe inside parens isn't enough for identifying random effects?

**Comment by strengejacke** [comment]
Usually, `lme4::nobars()` would work, but not in these cases:
https://github.com/easystats/insight/issues/79#issuecomment-507202500

And, formulas from packages feisr/felm/lfe/panelr have `|` to separate instrumental variables, so it's not as easy as just searching for `|`...

**Comment by strengejacke** [comment]
Should be fixed now. After updating _insight_ from GitHub, this should work now.
