### ISSUE TITLE
tab_model order for factor variable

### ISSUE THREAD

**Issue by CarolineXGao** [strengejacke/sjPlot#552]
Hi Daniel,

I am using the show.reflvl=TRUE argument in tab_model. It seems that the order of the factor variable is following the alphabetical order of the factor labels rather than the factor level. See this example: 

model<-lm(Sepal.Length ~ Species,data=iris)
tab_model(model,show.reflvl=TRUE,show.intercept=FALSE)
iris$Species2<-factor(as.character(iris$Species),labels=c("virginica","setosa", "versicolor"))
model<-lm(Sepal.Length ~ Species2,data=iris)
tab_model(model,show.reflvl=TRUE,show.intercept=FALSE)

Do you mind to have a look? 

Thanks very much.

Best,

Caroline

**Comment by CarolineXGao** [comment]
Also, it seems that if I added a label of the variable, "Reference" is also printed for the label column. 

iris$Species2<-factor(as.character(iris$Species),labels=c("virginica","setosa", "versicolor"))
label(iris$Species2)<-"Species"
model<-lm(Sepal.Length ~ Species2,data=iris)
tab_model(model,show.reflvl=TRUE,show.intercept=FALSE)

Thanks~~

Caroline

**Comment by strengejacke** [comment]
In your second example, the `label()` function does not exist.

**Comment by CarolineXGao** [comment]
Sorry label function is from Hmisc. 

Thanks ~~

Caroline
