### ISSUE TITLE
Feature request: Compatibility with papaja package (or: latex)

### ISSUE THREAD

**Issue by hsorlie** [strengejacke/sjPlot#555]
Hi! First: Thank you for making and maintaining this package. For me, tab_model() has made it a breeze to share and communicate results from analyses with my non-R supervisor and co-authors. Your work is very much appreciated!

I know that tab_model() only creates HTML output. However, have you considered making it latex/PDF friendly? One good argument is the papaja package (https://github.com/crsh/papaja). I'm currently writing a manuscript with papaja in RStudio, and love the apa6-formatted PDF/word files it creates, references, tables, figures and all. However, I tried to incorporate tab_model() in the script to get my models presented correctly, but  got this error message:

! Package inputenc Error: Unicode character σ (U+03C3)
(inputenc)                not set up for use with LaTeX.

I really believe papaja + sjPlot would be a really powerful combination, if this would work. Is it doable, or worth looking into? There seems to be something being done at https://github.com/juliandavidmr/HtmlTableToLatex , but not for R as far as I can tell.

Thank you!
kind regards, Henrik

**Comment by strengejacke** [comment]
> However, have you considered making it latex/PDF friendly?

Yes, that'd be great, but LaTex / PDF is out of my scope, actually. I don't have the time to learn LaTex well enough to address this issue.
