### ISSUE TITLE
A "diamond" summary for plot_model()

### ISSUE THREAD

**Issue by 0yarzabal** [strengejacke/sjPlot#556]
Hello Daniel, I am sorry for opening a new topic if this question was already answered.

I am using your package to perform a meta-analysis and is one of the best packages that I used so far. I used the` plot_model()` to plot the random effects of my glmm best model and everything is working fine. However, I realized that the `plot_model()` does not have a summary argument. In this way, the “summary diamond” usually showed in meta-analysis  is absent. I tried to use the `show.summary = T` and `summary.pos = "r"` arguments, but nothing happened.

There is a way to show this “summary diamond” on the plot? Is something that was not implemented? Or I can use another plot function that could show me this result?

Here's an image of what I am talking about.

![500px-Pre-term_corticosteroid_data svg](https://user-images.githubusercontent.com/56030963/66862496-606df680-ef67-11e9-81c5-0a3274355c9c.png)

Thank you very much for all your hard work.

Guilherme

**Comment by strengejacke** [comment]
This option is not available. I'm not sure if this makes sense, because in meta-analysis, the "diamond" is based on the weighted average of the estimates, while for random effects, the average is typically approx. zero.
