### ISSUE TITLE
sjp.grpfrq returning incorrect labels on y-axis

### ISSUE THREAD

**Issue by drnikolaf** [strengejacke/sjPlot#557]
Hello,

This is the first time I have had this issue with this package. 

I have R version 3.6.1 (2019-07-05) -- "Action of the Toes",  Mac Mojave 10.14.6.

I have the following ex code:

sjp.grpfrq(dat$year, dat$Method, type = "line", show.values = FALSE)

rather than printing the years (1992-2018) on the y-axis, I am receiving a grid count of years, every 10. (0, 10, 20)

the literature suggests it will automatically return the range on the y & x.

I have looked through the read-ups and I am not seeing how to change this.

Any help would be appreciated.  

Thank you.

**Comment by drnikolaf** [comment]
One last question: is there a way using this package to obtain the percentage for each subgroup on the x-axis rather than the total across the x-axis?

sjp.grpfrq(dat$year, dat$Method, type = "bar", bar.pos = c("stack"), show.axis.values = TRUE, show.values = TRUE, show.n = FALSE, show.prc = TRUE) 

where I could return the percentage for each year = 100, rather than all years =100 percent?

**Comment by strengejacke** [comment]
Do you have some data for a reproducible example?

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
_bump_
