### ISSUE TITLE
tab_model returns an error from intervals.lme (where to specify "which="fixed""?)

### ISSUE THREAD

**Issue by Adai5839** [strengejacke/sjPlot#560]
Hi Daniel,

I recently ran into an error from intervals.lme
` tab_model(CCT_IV_rs)
Error in intervals.lme(x, level = i, ...) : 
  cannot get confidence intervals on var-cov components: Non-positive definite approximate variance-covariance
 Consider 'which = "fixed"'`

Can you please tell me where to specify which="fixed"? (I do get CIs with the specification)

By the way, I don't get why tab_model still wants to get CIs when I have show.ci=F.

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by lisesp** [comment]
Hi Daniel, I have had the same problem. I am not sure why it can't create a table.
Here is my example:
#my model:
H2d <- lme(Intrusive_memory ~ as.factor(condition23_1)/as.factor(CS), random = ~ 1|ID, data= IM_hyp2subset, method="ML")

tab_model(H2d)
Error in intervals.lme(x, level = i, ...) : 
  cannot get confidence intervals on var-cov components: Non-positive definite approximate variance-covariance
 Consider 'which = "fixed"'

What can I do?

**Comment by strengejacke** [comment]
Do you probably have a small reproducible example?

**Comment by lisesp** [comment]
I am new at all this, I don't think I know how to provide you with a reproducible example, unfortunately :-/
