### ISSUE TITLE
plot_model does not plot errors around interactions when model includes " : "

### ISSUE THREAD

**Issue by cward02** [strengejacke/sjPlot#566]
Hi, great package - have shared with my lab and we are all pleased we can save 10-20 lines of code plotting using this package - well done and thank you!

I am having trouble plotting figures with plot_model where my model includes interactions only, ie. "X:Z" instead of "X*Z". The resulting plot shows only smoothed lines with no error plotted. Using the same data, it plots fine if I incude the interaction as X*Z - but unfortunately due to *stats* I can't include both the interaction and the variables. 

I was wondering if this was something that could be fixed or is just a result of not having error associated with the variable that isn't included in the model on its own?

Thanks! 

Chris

PS - I can share code/data privately through email if necessary. Cheers

**Comment by strengejacke** [comment]
> but unfortunately due to stats I can't include both the interaction and the variables.

I'm not quite sure what kind of model you're fitting? Do you have a reprex with some toy datasets, like mtcars or iris?

**Comment by strengejacke** [comment]
_bump_
