### ISSUE TITLE
Setting axis limits for plot_model, type="pred" interaction effects

### ISSUE THREAD

**Issue by howmanyapples** [strengejacke/sjPlot#567]
Hello,
I am running into an issue when trying to plot some interactions on from my linear regression. I have 2 interactions, and I am trying to plot them with the same y-axis limits (I would like the y-axis to be set  as 0, 80). I have tried both the axis.lim=c(0,80) and the ggplot2 workaround but I always get this weird effects (shown in the attached graphs) where the confidence intervals kind of just stops randomly. 

The regression looks something like:
emo1<-lm(Y~(grp_e1+grp_e2)*zposO, data=Data)

Using no limits: plot_model(emo1,type="pred", terms=c("zposO", "grp_e2"))
![Original](https://user-images.githubusercontent.com/57707081/68752034-edf24400-0602-11ea-9f45-3fedf133c2aa.png)
axis.lim: plot_model(emo1,type="pred", terms=c("zposO", "grp_e2"), axis.lim=c(-0,80))
![axis_lim](https://user-images.githubusercontent.com/57707081/68752044-f480bb80-0602-11ea-80d5-2c165b0010b4.png)
ggplot workaround: plot_model(emo1,type="pred", terms=c("zposO", "grp_e2"))+ ylim(-0,80)
![gglot_workaround](https://user-images.githubusercontent.com/57707081/68752067-fc406000-0602-11ea-9322-d632a0f9666b.png)

**Comment by strengejacke** [comment]
>  where the confidence intervals kind of just stops randomly.

No, not randomly. Your CI is negative at some points, so you have negative y-values on the left side of the x-axis. Setting the y-limits to 0 and 80, it will clip off the negative region.
