### ISSUE TITLE
sjPlot failed to install on mac OS

### ISSUE THREAD

**Issue by Grelot** [strengejacke/sjPlot#568]
Hi, thanks for your awesome work,

We failed to install sjPlot on rstudio in mac OS :

It returned the following error:
```
error: package or namespace load failed for ‘sjstats’:
 object ‘principal_components’ is not exported by 'namespace:performance' 
```

Do you have any idea what it means and ultimately how to solve it ?

**Comment by strengejacke** [comment]
Yes, it looks like you need to update your packages, in particular the _performance_ package (however, make sure to also install the _parameters_ package, where `principal_components()` is now actually located.
