### ISSUE TITLE
tab_model('show.reflvl = TRUE') dont work after update to 2.8

### ISSUE THREAD

**Issue by ogtveit** [strengejacke/sjPlot#569]
After updating to sjPlot 2.8.0 `tab_model('show.reflvl = TRUE')` doesnt produce rows with the reference level. Now reference rows are also missing from the example at: https://strengejacke.github.io/sjPlot/articles/tab_model_estimates.html#including-reference-level-of-categorical-predictors

**Comment by strengejacke** [comment]
Yes, a bit annoying that I did not see this "bug" before submission... But it's fixed now in the latest commit.
