### ISSUE TITLE
Support for bootstrapped linear models

### ISSUE THREAD

**Issue by AmirDJV** [strengejacke/sjPlot#571]
First of all, thank you for this great package! 

I was wondering if there or will be support for bootstrapped linear models? 

As a temporary solution, I was looking to change the output values of `tab_model()` before it prints out the table. Can I do that?

This will create this amazing table: 
```
library(tidyverse)
library(sjPlot)
library(car)

model1 <- lm(mpg~drat*vs, data = mtcars) 
model2 <- lm(mpg~drat*vs*am, data = mtcars) 

tab_model(model1, model2, show.intercept = FALSE)
```
![image](https://user-images.githubusercontent.com/25877896/69521478-c044bd80-0f67-11ea-82c8-b00bcaee8a1d.png)

Is there a possibility to create a similar table with bootstrapped CI? 
something like this: 

```
model1Boot <- car::Boot(model1, R = 1000)
model2Boot <- car::Boot(model2, R = 1000)

#Do not run
tab_model(model1Boot, model2Boot, show.intercept = FALSE)
```

Thank you for help!

**Comment by strengejacke** [comment]
Since `tab_model()` now uses [`model_parameers()`(https://easystats.github.io/parameters/reference/model_parameters.default.html) to generate coefficient-table, I could probably add a `bootstrap`-argument that simply calls the bootstrapping-method from `model_parameters()`.

**Comment by AmirDJV** [comment]
@strengejacke  Thank you for your prompt reply.

I tried going over your code (quickly and unresponsively) and I found only one call for `parameters::model_parameters()` in:
[model_params <- parameters::model_parameters(model, ci = ci.lvl, component = component)](https://github.com/strengejacke/sjPlot/blob/50d22d9fbd6837d9d378ca5910cddd632e119336/R/tidiers.R#L41). Is it possible? 

As the output of:
` parameters::model_parameters(model, ci = 0.95, bootstrap = FALSE, iterations = 1000) ` 
is equal to: 
` parameters::model_parameters(model, ci = 0.95, bootstrap = TRUE, iterations = 1000) ` (if I haven't missed anything, which I probably have), would it sufficient to add the argument `bootstrap = TRUE,  iterations = 1000`

to here:
[model_params <- parameters::model_parameters(model, ci = ci.lvl, component = component)](https://github.com/strengejacke/sjPlot/blob/50d22d9fbd6837d9d378ca5910cddd632e119336/R/tidiers.R#L41)

and here: 
[tidy_model <- function(model, ci.lvl, tf, type, bpe, se, robust, facets, show.zeroinf, p.val, standardize = FALSE, ...) ](https://github.com/strengejacke/sjPlot/blob/50d22d9fbd6837d9d378ca5910cddd632e119336/R/tidiers.R#L3)

BTW, because `tidy_model` and `tab_model` support `...`, I was trying to run
`tab_model(model1, bootstrap = TRUE, iterations = 1000)`, which resulted with: 

> Error: $ operator is invalid for atomic vectors
> In addition: Warning message:
> Could not access model information.

Which give me the feeling that it's not that easy to solve. 
Please tell me if there is anything I can help with and thank you!

**Comment by strengejacke** [comment]
You're correct in your reasoning, it's quite easy to implement. And `...` doesn't work because the dots capture the models input and don't pass any arguments down to other methods.

**Comment by AmirDJV** [comment]
I've d/l the scripts and made the changes locally.
I've made some tests and it seems to work fine. 
Would you like me to open a pull request? 

```
model1 <- lm(mpg~drat*vs, data = mtcars)

tab_model(model1, bootstrap = TRUE,
          iterations = 1000, seed = 123)
```

![image](https://user-images.githubusercontent.com/25877896/69586652-e57b0f80-0feb-11ea-88f4-68d4d0c27c30.png)


```
set.seed(123)
parameters::model_parameters(model1, ci = 0.95,
                             bootstrap = TRUE,
                             iterations = 1000) 
```

```
Parameter   | Coefficient |           95% CI |     p
----------------------------------------------------
(Intercept) |       -0.94 | [-11.59,  15.19] | > .1 
drat        |        5.20 | [  0.23,   8.33] | < .05
vs          |        2.34 | [-28.86,  20.06] | > .1 
drat * vs   |        0.77 | [ -4.10,   9.00] | > .1
```

**Comment by strengejacke** [comment]
Yes, feel free to open a PR, and add yourself as contributor to the description file.

**Comment by AmirDJV** [comment]
I'm somewhat new to the all github process so I hope I followed the rules correctly.
