### ISSUE TITLE
Namespace ‘ggeffects’ is imported by ‘sjPlot’ 

### ISSUE THREAD

**Issue by xiaotuxiaotu520** [strengejacke/sjPlot#574]
Hi there, can anyone help with this?
Error in value[[3L]](cond) : 
  Package ‘ggeffects’ version 0.12.0 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘ggeffects’ is imported by ‘sjPlot’ so cannot be unloaded

btw, how to plotting random slopes depending on random intercepts now?
thank you very much.

Minhuang

**Comment by strengejacke** [comment]
When does this error occur? For your second question, see https://strengejacke.github.io/ggeffects/articles/introduction_randomeffects.html, last section.

**Comment by xiaotuxiaotu520** [comment]
Thank you, Daniel.
I removed ‘ggeffects’ and re-installed it, it works now.
For random slope models, can the packages deal with nested random effect?
For example, nest_a nested in Subject:
m <- lmer(Reaction ~ Days + (1 + Days | Subject/nest_a), data = sleepstudy)
thenm how ggpredict() and plot() work?

Best,
Minhuang

**Comment by strengejacke** [comment]
I think the most complex scenario are two fixed effects terms (e.g. an interaction) and two group factors of random effects, or one fixed effects and three group factors of nested random effects. For example:

``` r
library(ggeffects)
library(lme4)
#> Loading required package: Matrix
data(sleepstudy)
    
set.seed(123)
sleepstudy$mygrp <- sample(1:5, size = 180, replace = TRUE)
sleepstudy$mysubgrp <- NA
for (i in 1:5) {
  filter_group <- sleepstudy$mygrp == i
  sleepstudy$mysubgrp[filter_group] <-
    sample(LETTERS, size = sum(filter_group), replace = TRUE)
}

sleepstudy$group <- "treatment"
n_subjects <- length(unique(sleepstudy$Subject))
control_group <- sample(unique(sleepstudy$Subject), size = n_subjects / 2, replace = FALSE)
sleepstudy$group[sleepstudy$Subject %in% control_group] <- "control"

m <- lmer(
  Reaction ~ Days * group + (1 + Days | mygrp / mysubgrp), 
  data = sleepstudy, 
  control = lmerControl(check.nobs.vs.nRE = "ignore")
)
#> boundary (singular) fit: see ?isSingular


ggpredict(m, c("Days", "group", "mygrp", "mysubgrp [sample=4]"), type = "re") %>% plot()
#> Loading required namespace: ggplot2
```

![](https://i.imgur.com/ryvYpJU.png)

<sup>Created on 2019-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Or switch lower and upper hierarachy in plot:

``` r
ggpredict(m, c("Days", "group", "mysubgrp [sample=4]", "mygrp [sample=4]"), type = "re") %>% plot()
```

![](https://i.imgur.com/9VT6mxu.png)

<sup>Created on 2019-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
