### ISSUE TITLE
How to use sjPlot with output from ChainLadder package

### ISSUE THREAD

**Issue by aegerton** [strengejacke/sjPlot#575]
Please can you assist me with getting sjPlot to work with the output from the ChainLadder package?
Here is an example;-
```
library(magrittr)
library(ChainLadder)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
MCLincurred %>% 
  MackChainLadder(est.sigma = 'Mack') %>% 
  tab_model()
```
The error message is as follows;-
```
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
Could not access model information. 
````

**Comment by strengejacke** [comment]
The ChainLadder package is currently not supported. I can take a closer look at that pkg and see how to add support for it.

**Comment by aegerton** [comment]
Thanks @strengejacke
