### ISSUE TITLE
FIxing order of terms in legend in plot_model(.., type = 'pred')

### ISSUE THREAD

**Issue by pablobernabeu** [strengejacke/sjPlot#577]
Hello,

Awesome package! I'd just like to suggest a tweak in `plot_model(.., type = 'pred')`, to show the terms in the legend in the same vertical order as they appear on the plot at x = 0 (see reversed order in the [first and second plots here](http://www.strengejacke.de/sjPlot/articles/plot_interactions.html#two-way-interactions)). Adding **`+ guides(color=guide_legend(reverse = TRUE))`** did it for me.

Best regards

**Comment by strengejacke** [comment]
Well, there's no general rule that the first (upper) category in the legend is also the line with the higher y-values (or vice versa) - it depends on the data and model. If the effect (in your example, the coefficient for `c161sex`) is negative, the reference category `Male` would be the upper line, if the effect is positive (as in the example), the reference category is "lower" than the other categories.

**Comment by pablobernabeu** [comment]
Thanks. The reversal made the look clearer to me with my initial plots. Yet, indeed as you mention, I've realised with other plots just now that the default reversal doesn't always cut it.  ¯\_(ツ)_/¯
