### ISSUE TITLE
tab_model, lme4 terms in wrong order

### ISSUE THREAD

**Issue by SilMerAl** [strengejacke/sjPlot#581]
When adding lmer-models to tab_model, the predictor terms change order to a different one than that which is shown using summary(),or by other table-packages like texreg. I have tried to set order.terms to both TRUE and FALSE, neither of which change the term order. When adding other types of models (clmm or glmer) this does not happen. They do not appear to be ordered by estimate size, alphabetically, or by any other logic that I can see.

**Comment by strengejacke** [comment]
yes, that's an issue in the [parameters-package](https://easystats.github.io/parameters). It's already solved, an update is planned within the next weeks...

**Comment by SilMerAl** [comment]
Awesome. It's such an incredibly useful tool, highly appreciated!
