### ISSUE TITLE
plot_model predicts values of first predictor instead of response variable (for lme)

### ISSUE THREAD

**Issue by syl-vie** [strengejacke/sjPlot#582]
ex: lme(response~predictor1+predictor2)
when I use plot_model(mod[lme], type = "eff") the first predictor instead of the response variable is used for the predicted values i.e. the y-axis is not the "response" but "predictor1"
How can I change that? I would like to have predicted values of "response" in the plot.
Thank you in advance for your help.

**Comment by strengejacke** [comment]
Do you have a reproducible example? The y-axis should always reflect the predicted values of the response.

**Comment by syl-vie** [comment]
here is an reproducible example:
library(nlme)
library(sjPlot)

set.seed(12)
response <- rpois(1000,5)
pred1 <- rnorm(1000, 10)
pred2 <- rnorm(1000, 20)
plot <- rep(1:100, each= 10)
df <-data.frame(response,pred1, pred2,plot)

mod <- lme(log(response+0.001) ~ pred1 + pred2, random = ~1|plot, data = df)

plot_model(mod, type = "eff")
The effect plot uses "pred1" for the y-axis instead of "response".

**Comment by syl-vie** [comment]
Could anybody reproduce the strange occurrence of "pred1" on the y-axis with the given example? What should I change in my code to get "response" on the y-axis?
Thank you in advance for your help.

**Comment by strengejacke** [comment]
Your example works fine for me, everything as expected (with `response` at the y-axis, and predictors at the x-axis):

``` r
library(nlme)
library(sjPlot)

set.seed(12)
response <- rpois(1000,5)
pred1 <- rnorm(1000, 10)
pred2 <- rnorm(1000, 20)
plot <- rep(1:100, each= 10)
df <-data.frame(response,pred1, pred2,plot)

mod <- lme(log(response+0.001) ~ pred1 + pred2, random = ~1|plot, data = df)

plot_model(mod, type = "eff")
#> $pred1
```

![](https://i.imgur.com/BR959Z7.png)

    #> 
    #> $pred2

![](https://i.imgur.com/tfddH2v.png)

<sup>Created on 2020-01-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
This is in line what the **effects** package returns:

``` r
library(nlme)
library(sjPlot)

set.seed(12)
response <- rpois(1000,5)
pred1 <- rnorm(1000, 10)
pred2 <- rnorm(1000, 20)
plot <- rep(1:100, each= 10)
df <-data.frame(response,pred1, pred2,plot)

mod <- lme(log(response+0.001) ~ pred1 + pred2, random = ~1|plot, data = df)

plot(effects::allEffects(mod))
```

![](https://i.imgur.com/CcC9Ixc.png)

<sup>Created on 2020-01-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by syl-vie** [comment]
Thank you for your answer!
I get the same plots as you (slope, CI, range), but the label is wrong; "pred1" instead of "response". But if that's the only issue, it is reassuring. 
in effects package the y-axis is correctly labelled with "log(response + 0.001)".

**Comment by syl-vie** [comment]
I just downloaded "strengejacke" from github and now it works! Perfect. 
before I was using sjPlot from CRAN.
Thank you again for your answers.

**Comment by strengejacke** [comment]
Great, thanks!
