### ISSUE TITLE
sjplot error: no applicable method for 'cronbachs_alpha' applied to class double

### ISSUE THREAD

**Issue by bac3917** [strengejacke/sjPlot#584]
I have a dataframe of 27 dichotomous (coded 0,1) variables and running the command below throws the 'cronbachs_alpha' applied to class double error. I assume it's sensible to include variables of class double in a factor analysis.  Any advice?

`sjt.fa(rf2, rotation = c( "varimax"),show.cronb = FALSE,show.comm = FALSE)`

**SessionInfo:**
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sjPlot_2.8.1         listviewer_3.0.0     rlist_0.4.6.1        jsonlite_1.6         data.table_1.12.8   
 [6] DT_0.11              missMDA_1.16         Factoshiny_2.1       FactoInvestigate_1.5 shiny_1.4.0         
[11] FactoMineR_2.1       kableExtra_1.1.0     psych_1.9.12.31      readxl_1.3.1         gridExtra_2.3       
[16] reshape2_1.4.3       EnvStats_2.3.1       ggthemes_4.0.0       scales_1.0.0         treemap_2.4-2       
[21] expss_0.10.1         lubridate_1.7.4      forcats_0.4.0        stringr_1.4.0        dplyr_0.8.3         
[26] purrr_0.3.3          readr_1.3.1          tidyr_1.0.0          tibble_2.1.3         ggplot2_3.2.1       
[31] tidyverse_1.3.0

**Comment by strengejacke** [comment]
do you have a reproducible example?

**Comment by bac3917** [comment]
My data file has 64,000 cases, but here are 20 of them with the 26 variables, and related code:

`rf2<-structure(list(family_hn_teen_parent = c(0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_child_disabilities = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_parent_disabilities = c(1, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_mental_illness = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_low_education = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0), family_hn_low_income = c(0, 
0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_recent_immigrant = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_substance_abuse = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_legal_guardian = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_insecure_housing = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_incarcerated_parent = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_low_birth_weight = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_death_in_family = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_domestic_violence = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_child_abuse = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_hn_military_family = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_oc_armed_forces = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_oc_single_parent = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_oc_esl = c(0, 
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_oc_low_student_achievement = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_oc_multiple_children = c(1, 
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0), family_oc_adoptive_parent = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_oc_relative_as_caregiver = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_oc_behavior_concerns = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_oc_first_time_parents = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), family_oc_correctional_system = c(0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)), row.names = c(NA, 
20L), class = "data.frame")
> `
res = FactoMineR::MFA(rf2, 
                      group=c(8,8,10), # values must add to total # of variables
                      type=c("s"), 
                      name.group=c("apple","banana","pear"),
                      #num.group.sup = c(1,3), # i'm not sure what this does
                      graph=TRUE)

**Comment by strengejacke** [comment]
It looks like the data is not feasible for PCA / FA.
