### ISSUE TITLE
plot_model does not find variables when using an interaction term in lmerMod object

### ISSUE THREAD

**Issue by Crismoc** [strengejacke/sjPlot#586]
I am trying to plot a two-way interaction in a linear mixed model, but when using an additional predictor `sjPlot()` causes an error saying it cannot find a variable outside the interaction term (additionally it states it does not find the variables in the interaction, although it creates the plot when not including additional variables).

Here is a reprex:

```
m <- lme4::lmer(mpg ~ (1 | gear) + wt*vs + hp, data = mtcars)
sjPlot::plot_model(m, type = "int", terms = c("wt", "vs"))
#> `wt` was not found in model terms. Maybe misspelled?
#> `vs` was not found in model terms. Maybe misspelled?
#> Error in eval(predvars, data, env): object 'hp' not found
```
(R version 3.6.1, sjPlot 2.7.2 in Windows 10)

Is this an error in the function? If so, is it possible to fix it?

**Comment by strengejacke** [comment]
works fine for me, are all your packages up to date?

**Comment by Crismoc** [comment]
Indeed, updating packages fixed the error. Thank you very much!
