### ISSUE TITLE
tab_model error with univariate cox regression

### ISSUE THREAD

**Issue by mdponzini** [strengejacke/sjPlot#587]
The example in issue #468 no longer produces any output and return the following error:

![image](https://user-images.githubusercontent.com/14928670/73108265-ab779e00-3eb4-11ea-81d3-4e9906337364.png)

**Comment by strengejacke** [comment]
Closed in https://github.com/easystats/parameters/commit/5bf720e02f1ac015958d685ed16a97bdf26ec82d
