### ISSUE TITLE
Error in tab_model when using spline

### ISSUE THREAD

**Issue by sciatro** [strengejacke/sjPlot#588]
Thanks for all the hard work on this great package. 

I think I may have run into a regression somewhere in the 2.6 ... 2.8 upgrade. I am not a regular enough user of splines to know exactly where this stopped working; however, somewhere between the 2.6 family and current 2.8 the following started to fail:

    # Setup
    library(sjPlot)
    library(lspline)
    data("mtcars")

    # All of this works as expected 
    fit <- lm(mpg~hp, data = mtcars)
    summary(fit)
    tab_model(fit)
    
    # Now add a spline, fits, & base summary, but now w/ error on tab_model
    sfit <- lm(mpg~lspline(hp, knots = c(150)), data = mtcars)
    summary(sfit)

    # Next line is the new error
    tab_model(sfit)

The error is: 

    Error in `[.data.frame`(md, , needed.vars, drop = FALSE) : 
      undefined columns selected

Perhaps this has something to do with the way names are assigned as it looks like it can be rescued with manual naming as follows:

    rescue <- model.matrix(mpg~lspline(hp, knots = c(150))-1, data = mtcars)
    colnames(rescue) <- c("Knot1", "Knot2")
    rfit <- lm(mpg ~ Knot1 + Knot2, data = cbind(mtcars, rescue))
    summary(rfit)
    # No problem now
    tab_model(rfit)

    # Double check that sfit & rfit are the same
    stopifnot(all(coef(rfit) == coef(sfit)))
    stopifnot(all(predict(rfit) == predict(sfit)))

**Comment by strengejacke** [comment]
The pattern `lspline()` was not yet caught in [`clean_names()`](https://github.com/easystats/insight/blob/master/R/clean_names.R), but is fixed now.
