### ISSUE TITLE
Incorrect random effects estimates displayed in tab_model for brms

### ISSUE THREAD

**Issue by mjadkins** [strengejacke/sjPlot#591]
Hi Daniel, I have noticed that the random effects estimates presented in the tab_model table differ substantially from the values in the raw brms output. Fitting the model in lme4 and using tab_model results in the correct values displayed. See the example below:

#----------------------------
library(R2MLwiN)
library(brms)
library(sjPlot)
library(lme4)
options(mc.cores = parallel::detectCores())
data(tutorial, package="R2MLwiN")

m1 <-brm(normexam ~ sex + standlrt + (1|school), data=tutorial)
m1
tab_model(m1)

m2 <-lmer(normexam ~ sex + standlrt + (1|school), data=tutorial)
summary(m2)
tab_model(m2)
#----------------------------

**Comment by strengejacke** [comment]
I can't run your example, because I'm getting this error:

>  Error in unserialize(socklist[[n]]) : error reading from connection 

But maybe you could try changing the centrality index from median to mean? This can be done using the `bpe`-argument:

```r
tab_model(m1, bpe = "mean")
```

Does this help?

**Comment by mjadkins** [comment]
Thanks for the quick reply. That error might be due to running the chains in parallel. If you remove the line "options(mc.cores = parallel::detectCores())", does the problem persist?

Re: changing median to mean. No unfortunately it doesn't. It seems to be something to do with the way in which the function processes the brms output. I have included two screenshots output of the function for the same model. The first fitted with brms(Screenshot 2020-02-07 09 50 11) and the second with rstanarm (Screenshot 2020-02-07 09 48 03). The fixed effects are fine, but the random effects are completely different. 

![Screenshot 2020-02-07 09 50 11](https://user-images.githubusercontent.com/5891712/74019279-4a10fe00-498f-11ea-993a-72d381b566e9.png)
![Screenshot 2020-02-07 09 48 03](https://user-images.githubusercontent.com/5891712/74019290-4e3d1b80-498f-11ea-8d40-776305546b4b.png)

**Comment by strengejacke** [comment]
Ok, I got it. The difference is due to different computational approaches, see https://easystats.github.io/performance/reference/icc.html for details.

Since brms can handle many, many different distributional families, and for most of them a "classical" variance decomposition makes no sense, there's a different approach in calculating variance components. In case of Gaussian models, this approach may lead to different results as compared to the "classical" calculation of the ICC and variance components.

If you want to get comparable ICC's between Bayesian and ferquentist models, I recommend using rstanarm, since rstanarm offers the same functions as lme4, and thus the calculation is the same (and therefore, ICC and variance components should be more similar).

**Comment by strengejacke** [comment]
Left model is lm4, middle is brms and right model is rstanarm.

![image](https://user-images.githubusercontent.com/26301769/74023008-f4dce880-499e-11ea-9dae-1ec3f819a59b.png)

**Comment by mjadkins** [comment]
Ok, so for the brms model, when the tab_model is running the icc function behind the scenes then it results in this:

icc(m1) 
# Random Effect Variances and ICC

Conditioned on: all random effects

## Variance Ratio (comparable to ICC)
Ratio: 0.11  CI 95%: [0.06 0.17]

## Variances of Posterior Predicted Distribution
Conditioned on fixed effects: 0.88  CI 95%: [0.83 0.94]
Conditioned on rand. effects: 1.00  CI 95%: [0.94 1.06]

## Difference in Variances
Difference: 0.12  CI 95%: [0.06 0.17]

And for RStanarm:
icc(m3)
# Intraclass Correlation Coefficient

     Adjusted ICC: 0.142
  Conditional ICC: 0.096

Thanks very much for the clarification, at least I'm understanding why it's returning these values. It's a really nice time saving function and I'll certainly use it for rstanarm models going forward.
