### ISSUE TITLE
Support for adjusted p-values

### ISSUE THREAD

**Issue by tormodb** [strengejacke/sjPlot#595]
No issue, more of a request. Is there plan to support adjusted p-values? There is already a transform function, but it would be great if the p-values could be passed through p.adjust, allowing to pass the "methods" argument to obtain properly adjusted p-values when adding several models together with tab_model. 

Is a viable workaround to replace the p-values in the summary(lm_model) with adjusted p-values, or are they recalculated or obtained in another way when producing the table?

**Comment by strengejacke** [comment]
Should work now, but you also need to update [parameters](https://easystats.github.io/parameters) from GitHub.

```r
m <- lm(Sepal.Length ~ Petal.Length + Petal.Width + Species * Sepal.Width, data = iris)
tab_model(m)
tab_model(m, p.adjust = "holm")
```

**Comment by davewi13** [comment]
Hi, I am trying to use p.adjust as described above but the output I get is the same regardless of the option I set for p.adjust.  I've attached my session info in case that helps.

[Session_info_padjust_issue.txt](https://github.com/strengejacke/sjPlot/files/4313226/Session_info_padjust_issue.txt)

**Comment by kdawg32** [comment]
I am trying to use "fdr" corrections over multiple models, ie. tab_model(m1,m2,m3, p.adjust= "fdr"). Is FDR corrections being applied to each model separately, or is it being applied to each IV individually across all models?

**Comment by strengejacke** [comment]
To each model separately.
