### ISSUE TITLE
Suggestion for view_df(): more summary statistics for continuous variables

### ISSUE THREAD

**Issue by gustavobrp** [strengejacke/sjPlot#596]
As the title says, just a suggestion for the view_df() function: show more information about continuous variables besides the range of it. Mean; min., med. and max. values; standard deviation; and IQR.

Best!

**Comment by strengejacke** [comment]
You can get summary of sample descriptions using [`sjmisc::descr()`](https://strengejacke.github.io/sjmisc/reference/descr.html).
