### ISSUE TITLE
Incorrect random effects estimates in tab_model for glmer

### ISSUE THREAD

**Issue by JCruk** [strengejacke/sjPlot#597]
In the process of a current project write-up, the random effects variance in '3.29' in all of my models summarized with tab_model, which does not agree with summary() called on the fitted model objects.

It looks like the variance is reported as Tao and '3.29' is being reported as variance for all models

**Comment by strengejacke** [comment]
do you have a reproducible example, or at least an output of tab_model and summary?

**Comment by JCruk** [comment]
My apoligies!

Here is a reproducible example:

```
library(MASS)
library(lme4)

generate_data = function(
  n # number of units
  , k # number of trials within each condition within each unit
  , I # population intercept
  , vI # across-units variance of intercepts
  , A # population A effect
  , vA # across-units variance of A effects
  , rIA # across-units correlation between intercepts and A effects
){
  Sigma = c(
    vI , sqrt(vI*vA)*rIA
    , sqrt(vI*vA)*rIA , vA
  )
  Sigma = matrix(Sigma,2,2)
  means = mvrnorm(n,c(I,A),Sigma)
  temp = expand.grid(A=c('a1','a2'),value=0)
  temp$A = factor(temp$A)
  contrasts(temp$A) = contr.sum
  from_terms = terms(value~A)
  mm = model.matrix(from_terms,temp)
  data = expand.grid(A=c('a1','a2'),unit=1:n,trial=1:k)
  for(i in 1:n){
    data$value[data$unit==i] = rbinom(k*2,1,plogis(as.numeric(mm %*% means[i,])))
  }
  data$unit = factor(data$unit)
  data$A = factor(data$A)
  contrasts(data$A) = contr.sum
  return(data)
}


this_data = generate_data(
  n = 100 # number of units
  , k = 100 # number of trials within each condition within each unit
  , I = 2 # population intercept
  , vI = .1 # across-units variance of intercepts
  , A = .5 # population A effect
  , vA = .2 # across-units variance of A effects
  , rIA = .6 # across-units correlation between intercepts and A effects
)

fit = glmer(
  data = this_data,
  formula = value ~ A + (1|unit),
  family = binomial
)

summary(fit)
tab_model(fit)
```

**Comment by strengejacke** [comment]
I don't see any inconsistencies here. The different variance components are explained in more detail [here](https://easystats.github.io/insight/reference/get_variance.html) and [here](https://easystats.github.io/parameters/reference/random_parameters.html).

The variance in the `summary()` relates to the random intercept (i.e. between-group variance). The sigma-squared in `tab_model()` is the residual variance. For logistic regression the residual variance is fixed to `pi^2/3`.

**Comment by JCruk** [comment]
Thank you for the explanation!
