### ISSUE TITLE
Error: Confidence intervals could not be computed.

### ISSUE THREAD

**Issue by LindaWvanR** [strengejacke/sjPlot#598]
When a log-transformed or polynomial predictor is included in the lmer model, sjPlot gives an error message re. confidence intervals that can not be computed. After taking out the transformed predictor, the CIs are included again in the plots.   

Perhaps the size is interfering here: 
* Reason: "cannot allocate vector of size 85.2 Gb"
* Source: NULL

Another error message:
Error: Confidence intervals could not be computed.
Model has log-transformed response. Back-transforming predictions to original response scale. Standard errors are still on the log-scale.
Note: the log-transformed predictor is not in the plot, though another predictor, also included in an interaction between the log-transformed predictor and the other predictor, is included.

Interestingly enough, when the log-transformed predictor **is** included in the plot, the confidence intervals are calculated and printed in the plot.

**Comment by strengejacke** [comment]
do you have a reproducible example? It might be that if the log-term is held constant, that there are too many data in the model matrix to compute the CI.

**Comment by LindaWvanR** [comment]
Hi, thank you for your response. I actually sent you a sample dataset and my script via the unofficial way (Researchgate). Please let me know if I need to send it again and thank you for your help, I really appreciate it. 

I also have another question. As you can see in my script, I have a log-transformed DV, and a lot of predictors, of which one is also log-transformed. The graphs are really useful in interpreting the results, but I am also trying to back transform the estimates to calculate the effects. Where can I find info on how the back transformations take place in sjPlot?
Thank you!

**Comment by DeAngelisA** [comment]
I just noted the same error fitting an ordered-logit model with `MASS::polr()`.

``` r
library(tidyverse)
library(MASS)
#> 
#> Attaching package: 'MASS'
#> The following object is masked from 'package:dplyr':
#> 
#>     select
library(sjPlot)
#> Learn more about sjPlot with 'browseVignettes("sjPlot")'.
dat <- tibble(
  x1 = rnorm(1000, 0, 1),
  e = rnorm(1000, 0, 1),
  y = 0 + 1 * x1 + e
)

dat <- dat %>% 
  mutate(
    y_ord = factor(cut_interval(y, 3), 
                   labels = c("Strongly Disagree", "Neither agree nor disagree", "Strongly Agree")
    )
  )
fit <- MASS::polr(y_ord ~ x1, data = dat)
plot_model(fit, type = "pred")
#> Data were 'prettified'. Consider using `terms="x1 [all]"` to get smooth plots.
#> 
#> Re-fitting to get Hessian
#> Error: Confidence intervals could not be computed.
#> * Reason: "non-conformable arguments"
#> * Source: mm %*% vcm
#> $x1
```

![](https://i.imgur.com/lXyBmwF.png)

<sup>Created on 2020-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Thanks, should be fixed after updating [*ggeffects*](https://strengejacke.github.io/ggeffects/) from GitHub.

``` r
library(tidyverse)
library(MASS)
#> 
#> Attaching package: 'MASS'
#> The following object is masked from 'package:dplyr':
#> 
#>     select
library(sjPlot)
#> #refugeeswelcome
dat <- tibble(
  x1 = rnorm(1000, 0, 1),
  e = rnorm(1000, 0, 1),
  y = 0 + 1 * x1 + e
)

dat <- dat %>% 
  mutate(
    y_ord = factor(cut_interval(y, 3), 
                   labels = c("Strongly Disagree", "Neither agree nor disagree", "Strongly Agree")
    )
  )
fit <- MASS::polr(y_ord ~ x1, data = dat)
plot_model(fit, type = "pred")
#> Data were 'prettified'. Consider using `terms="x1 [all]"` to get smooth plots.
#> 
#> Re-fitting to get Hessian
#> $x1
```

![](https://i.imgur.com/HnXLx0I.png)

<sup>Created on 2020-05-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
