### ISSUE TITLE
tab_model on categorical brmsfit object adds unintended string to CI column

### ISSUE THREAD

**Issue by JCruk** [strengejacke/sjPlot#599]
I have fitted a model with brms and summary provides estimates for all combinations of outcome and predictor.

I have uploaded the fitted brms model [here ](https://easyupload.io/s2n0hg)

```
library(brms)
library(sjplot)

summary(mod)
tab_model(mod)

```

The resulting html file from 'tab_model' alternates estimates with outcome and all but the last predictor and only the last predictor.

**Comment by strengejacke** [comment]
My guess after quickly looking at it might be the name of the variable `Mean_Income.s`. Could you rename it into something without underscore, like `MeanIncome.s`, and see if the problem is solved? If yes, I have a clue where to start when fixing this issue.

**Comment by JCruk** [comment]
Replacing the underscore in the variable with a dot (Mean_Income.s -> Mean.Income.s) corrected the issue!

**Comment by JCruk** [comment]
Another quirk is that if 'collapse.ci' is set to 'TRUE' on this model, a string of the outcome is added below each CI:

```
      0.17
(0.05 – 0.70)
   (Content)
```

Is there a flag/switch for that behaviour?
