### ISSUE TITLE
gsub error appears when using tab_model

### ISSUE THREAD

**Issue by Joern0207** [strengejacke/sjPlot#603]
Hi, I am calculating a multi-level-model (with lmer) and when I try to put the outcomes into a HTML-Table with tab_model the following error appears: 

_Issue in gsub("Statistic", gsub("-statistic", "", attr(statistic, "statistic",  : 
  invalid 'replacement' Argument_

tab_model worked for me fine a several weeks ago but now the error message appears everytime.

Many thanks in advance!

Best wishes 
Jörn

**Comment by strengejacke** [comment]
I can't say for sure without a reproducible example, but it sounds like you were using the lmerTest-package. If so, try updating [insight](https://easystats.github.io/insight/) and [parameters](https://easystats.github.io/parameters) from GitHub, then it should work.

**Comment by Joern0207** [comment]
Hmm, now when you mentioned to update paramters, I remember that after installing parameters the error appeared. I have reinstalled parameters and insight (through command "githubinstall") but it still does not work. However I refitted the modells with the command "lme4::lmer" and then it worked again fine (ignoring lmerTest). Seems to be that maybe their exists a conflict with the parameters package? Thank you very much for the hint!

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by alecristia** [comment]
x=rnorm(100)
y=rnorm(100)
z=rnorm(100)
rndm=rep(paste("id",1:10),10)
nester=rep(c("a","b"),50)
bin=sample(c("m","f"),100,rep=T)

lmer(x~y*z*bin+(1|nester:rndm))->test
plot_model(test, vline.color = "red") #fails
lmer(x~y+z+bin+(1|nester:rndm))->test
plot_model(test, vline.color = "red") #fails
lmer(x~y+(1|nester:rndm))->test
plot_model(test, vline.color = "red") #succeeds

The error emerges whenever there are multiple fixed effects.

**Comment by strengejacke** [comment]
hm, none of those examples fails for me.

``` r
library(lme4)
#> Loading required package: Matrix
library(sjPlot)
x=rnorm(100)
y=rnorm(100)
z=rnorm(100)
rndm=rep(paste("id",1:10),10)
nester=rep(c("a","b"),50)
bin=sample(c("m","f"),100,rep=T)

lmer(x~y*z*bin+(1|nester:rndm))->test
plot_model(test, vline.color = "red") #fails
```

![](https://i.imgur.com/7lJLiRF.png)

``` r
lmer(x~y+z+bin+(1|nester:rndm))->test
plot_model(test, vline.color = "red") #fails
```

![](https://i.imgur.com/Dudp2qk.png)

``` r
lmer(x~y+(1|nester:rndm))->test
plot_model(test, vline.color = "red") #succeeds
#> Warning: Interaction terms are not supported by this plot type. Output for
#> interaction terms may be inappropriate.
```

![](https://i.imgur.com/7TVQWBf.png)

<sup>Created on 2020-02-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Same when I use lmerTest instead of lme4:

``` r
library(lmerTest)
#> Loading required package: lme4
#> Loading required package: Matrix
#> 
#> Attaching package: 'lmerTest'
#> The following object is masked from 'package:lme4':
#> 
#>     lmer
#> The following object is masked from 'package:stats':
#> 
#>     step
library(sjPlot)
x=rnorm(100)
y=rnorm(100)
z=rnorm(100)
rndm=rep(paste("id",1:10),10)
nester=rep(c("a","b"),50)
bin=sample(c("m","f"),100,rep=T)

lmerTest::lmer(x~y*z*bin+(1|nester:rndm))->test
plot_model(test, vline.color = "red") #fails
```

![](https://i.imgur.com/CwHibcD.png)

``` r
lmerTest::lmer(x~y+z+bin+(1|nester:rndm))->test
#> boundary (singular) fit: see ?isSingular
plot_model(test, vline.color = "red") #fails
```

![](https://i.imgur.com/iMkiqZe.png)

``` r
lmerTest::lmer(x~y+(1|nester:rndm))->test
#> boundary (singular) fit: see ?isSingular
plot_model(test, vline.color = "red") #succeeds
#> Warning: Interaction terms are not supported by this plot type. Output for
#> interaction terms may be inappropriate.
```

![](https://i.imgur.com/R4QcMKo.png)

<sup>Created on 2020-02-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pa280** [comment]
Hi!

I am having the same issue when using tab_model and lmerTest to do my lmer model.

It seems that everything is fine when I use lmer on the lme4 package, but not when I use lmerTest, I've tried update insight and parameters package but it seems they are up to date.

Not entirely sure what is happening, everything was working few weeks ago

**Comment by strengejacke** [comment]
Do you have a reproducible example? As I wroe [here](https://github.com/strengejacke/sjPlot/issues/603#issuecomment-589987190) it might be that you need to update packages from GitHub. For me, everything [works well](https://github.com/strengejacke/sjPlot/issues/603#issuecomment-590791504).

**Comment by AvaloKit** [comment]
I had this issue too. An update to the insight and parameters package from GitHub solved the issue

**Comment by pa280** [comment]
Thanks!!

I did update parameters and insight from GitHub and it got solved!
