### ISSUE TITLE
Error in array(NA, c(J, K)) : 'dims' cannot be of length 0

### ISSUE THREAD

**Issue by iago-pssjd** [strengejacke/sjPlot#604]
I get the error `Error in array(NA, c(J, K)) : 'dims' cannot be of length 0` in example
```
library(lme4)
library(sjPlot)
fm1 <- lmer(Reaction ~ Days + (Days | Subject) + (0+Reaction| Subject), sleepstudy)
plot_model(fm1, type = "re", sort.est = "sort.all", grid = FALSE)
```
I know this model is singular, but I get this error with my working data with a similar model which is not singular (even I get the message `boundary (singular) fit: see ?isSingular`, if I apply the function `isSingular` to the model I get `FALSE`).

What is happening?

**Comment by strengejacke** [comment]
Closing in favor of https://github.com/easystats/parameters/issues/202 - the source of this issue is `parameters::standard_error(model, effects = "random")`.

**Comment by andreifoldes** [comment]
Hello 
I'm having issue with the following irrespective of parameters::standard_error(x, effects = "random") working.
```
> x = lme(Reaction ~ Days, random =  ~Days|Subject, sleepstudy)
> plot_model(x, "re")
```
