### ISSUE TITLE
package cannot be installed: installation of package ‘sjPlot’ had non-zero exit status

### ISSUE THREAD

**Issue by enderam** [strengejacke/sjPlot#605]
install.packages("sjPlot")
Error in install.packages : Updating loaded packages
> install.packages("sjPlot")
Installing package into ‘/Users/me/Library/R/3.4/library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘ellipsis’, ‘rlang’, ‘vctrs’, ‘lifecycle’, ‘dplyr’, ‘sjstats’, ‘tidyr’

  There are binary versions available but the source versions are later:
          binary source needs_compilation
ellipsis   0.1.0  0.3.0              TRUE
rlang      0.3.1  0.4.5              TRUE
vctrs      0.1.0  0.2.3              TRUE
dplyr    0.8.0.1  0.8.4              TRUE
sjstats   0.17.4 0.17.9             FALSE
tidyr      0.8.3  1.0.2              TRUE
sjPlot     2.6.2  2.8.2             FALSE

Do you want to install from sources the packages which need compilation?
y/n: y
installing the source packages ‘ellipsis’, ‘rlang’, ‘vctrs’, ‘lifecycle’, ‘dplyr’, ‘sjstats’, ‘tidyr’, ‘sjPlot’

trying URL 'https://cran.rstudio.com/src/contrib/ellipsis_0.3.0.tar.gz'
Content type 'application/x-gzip' length 7371 bytes
==================================================
downloaded 7371 bytes

trying URL 'https://cran.rstudio.com/src/contrib/rlang_0.4.5.tar.gz'
Content type 'application/x-gzip' length 816813 bytes (797 KB)
==================================================
downloaded 797 KB

trying URL 'https://cran.rstudio.com/src/contrib/vctrs_0.2.3.tar.gz'
Content type 'application/x-gzip' length 753205 bytes (735 KB)
==================================================
downloaded 735 KB

trying URL 'https://cran.rstudio.com/src/contrib/lifecycle_0.1.0.tar.gz'
Content type 'application/x-gzip' length 150752 bytes (147 KB)
==================================================
downloaded 147 KB

trying URL 'https://cran.rstudio.com/src/contrib/dplyr_0.8.4.tar.gz'
Content type 'application/x-gzip' length 1179051 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/src/contrib/sjstats_0.17.9.tar.gz'
Content type 'application/x-gzip' length 216013 bytes (210 KB)
==================================================
downloaded 210 KB

trying URL 'https://cran.rstudio.com/src/contrib/tidyr_1.0.2.tar.gz'
Content type 'application/x-gzip' length 812005 bytes (792 KB)
==================================================
downloaded 792 KB

trying URL 'https://cran.rstudio.com/src/contrib/sjPlot_2.8.2.tar.gz'
Content type 'application/x-gzip' length 833531 bytes (813 KB)
==================================================
downloaded 813 KB

* installing *source* package ‘rlang’ ...
** package ‘rlang’ successfully unpacked and MD5 sums checked
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘rlang’
* removing ‘/Users/me/Library/R/3.4/library/rlang’
* restoring previous ‘/Users/me/Library/R/3.4/library/rlang’
Warning in install.packages :
  installation of package ‘rlang’ had non-zero exit status
* installing *source* package ‘ellipsis’ ...
** package ‘ellipsis’ successfully unpacked and MD5 sums checked
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘ellipsis’
* removing ‘/Users/me/Library/R/3.4/library/ellipsis’
* restoring previous ‘/Users/me/Library/R/3.4/library/ellipsis’
Warning in install.packages :
  installation of package ‘ellipsis’ had non-zero exit status
* installing *source* package ‘lifecycle’ ...
** package ‘lifecycle’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘rlang’ 0.3.1 is being loaded, but >= 0.4.0 is required
ERROR: lazy loading failed for package ‘lifecycle’
* removing ‘/Users/me/Library/R/3.4/library/lifecycle’
Warning in install.packages :
  installation of package ‘lifecycle’ had non-zero exit status
* installing *source* package ‘vctrs’ ...
** package ‘vctrs’ successfully unpacked and MD5 sums checked
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘vctrs’
* removing ‘/Users/me/Library/R/3.4/library/vctrs’
* restoring previous ‘/Users/me/Library/R/3.4/library/vctrs’
Warning in install.packages :
  installation of package ‘vctrs’ had non-zero exit status
* installing *source* package ‘dplyr’ ...
** package ‘dplyr’ successfully unpacked and MD5 sums checked
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘dplyr’
* removing ‘/Users/me/Library/R/3.4/library/dplyr’
* restoring previous ‘/Users/me/Library/R/3.4/library/dplyr’
Warning in install.packages :
  installation of package ‘dplyr’ had non-zero exit status
ERROR: dependency ‘lifecycle’ is not available for package ‘tidyr’
* removing ‘/Users/me/Library/R/3.4/library/tidyr’
Warning in install.packages :
  installation of package ‘tidyr’ had non-zero exit status
ERROR: dependency ‘tidyr’ is not available for package ‘sjstats’
* removing ‘/Users/me/Library/R/3.4/library/sjstats’
Warning in install.packages :
  installation of package ‘sjstats’ had non-zero exit status
ERROR: dependencies ‘sjstats’, ‘tidyr’ are not available for package ‘sjPlot’
* removing ‘/Users/me/Library/R/3.4/library/sjPlot’
Warning in install.packages :
  installation of package ‘sjPlot’ had non-zero exit status

**Comment by strengejacke** [comment]
The installation already failed for the first package:

> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘rlang’

This is actually no issue with sjPlot, but rather an issue with your setup. I suggest you ask for help in a related forum, it might even be an issue with your OS setup, and not R itself?

**Comment by enderam** [comment]
body{font-family:Helvetica,Arial;font-size:13px}I thought that too. I’m using R Studio. I tried also with the original setup. It does not seem to work. Thanks!    From: Daniel <notifications@github.com>Reply: strengejacke/sjPlot <reply@reply.github.com>Date: 2 March 2020 at 13:28:50To: strengejacke/sjPlot <sjplot@noreply.github.com>Cc: enderam <enderam@icloud.com>, Author <author@noreply.github.com>Subject:  Re: [strengejacke/sjPlot] package cannot be installed: installation of package ‘sjPlot’ had non-zero exit status (#605)  The installation already failed for the first package:



xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

ERROR: compilation failed for package ‘rlang’



This is actually no issue with sjPlot, but rather an issue with your setup. I suggest you ask for help in a related forum, it might even be an issue with your OS setup, and not R itself?
