### ISSUE TITLE
order.terms not honored when plotting

### ISSUE THREAD

**Issue by drcanak** [strengejacke/sjPlot#606]
using sjPlot 2.8.2.

"order.terms" works when creating a table using "tab_model".  However, "order.terms" does not seem to be honored when using "plot_model".  No errors, but the displayed order always remains the same regardless of how the order of terms is specified. This is for a binary logistic regression object.

Awesome package!  Use it all the time.  Just can't figure out why order.terms is not working in a plot. 
 Thank you for all your efforts here.

**Comment by strengejacke** [comment]
was a bug. should be fixed in between. If you don't mind, try to install sjPlot from GitHub and check if you still encounter this issue.

**Comment by drcanak** [comment]
Yes,

just installed from Github using:

library(devtools)
devtools::install_github("strengejacke/sjPlot")

And tested.  The order of terms now works as expected.  Thx!
