### ISSUE TITLE
Duplicated parameter estimates in tab_model() with BRMS multinomial model

### ISSUE THREAD

**Issue by JCruk** [strengejacke/sjPlot#610]
I have fitted some multinomial models with BRMS. When I pass these fitted models to tab_model(), I get the following warnings:

Warning messages:
1: In if (grepl(pattern = pattern, x = rn)) { :
  the condition has length > 1 and only the first element will be used
2: In if (grepl(pattern = pattern, x = rn)) { :
  the condition has length > 1 and only the first element will be used
3: In if (grepl(pattern = pattern, x = rn)) { :
  the condition has length > 1 and only the first element will be used
4: In if (grepl(pattern = pattern, x = rn)) { :
  the condition has length > 1 and only the first element will be used

I also see that estimates for one of the categories (Caregiver) are duplicated in the summary table:
```
 	Dependent variable
Predictors	Odds Ratios	CI (95%)
muBuilding_Intercept	3.08	1.72 – 5.15
muCaregiver_Intercept	4.00	2.76 – 5.62
muCaregiver_Intercept	4.00	2.76 – 5.62
muPatient_Intercept	11.93	8.64 – 16.40
muPatientpsych_Intercept	1.59	1.06 – 2.37
muSDOH_Intercept	2.24	1.28 – 3.77
muCanmeds_Intercept	8.22	5.91 – 11.29
muExpertise_Intercept	4.44	3.04 – 6.37
muRecommendations_Intercept	2.08	1.35 – 3.15
Random Effects
σ2	-0.00
τ00	-0.01
ICC	0.03
N Group	16
Observations	3854
```
I have uploaded the fitted model as an RData file [here](http://s000.tinyupload.com/index.php?file_id=16365932127651992952)

```
library(sjPlot)
load("What_Multi_NoCode_Int_Only_Mod.RData")

tab_model(What_Multi_Int_Only_Mod)

```

**Comment by strengejacke** [comment]
Should be fixed after updating [**insighjt** from GitHub](https://github.com/easystats/insight/).

**Comment by JCruk** [comment]
Works perfectly - thank you!
