### ISSUE TITLE
plot_models not working for lmer-models

### ISSUE THREAD

**Issue by SilMerAl** [strengejacke/sjPlot#613]
Using plot_models on random effect models made with lmer returns the following error:

Error in as.character.default(x) : 
  no method for coercing this S4 class to a vector

The same models can plotted one by one with plot_model, and made into a joint table with tab_model. lmerTest is not loaded.

**Comment by ecophysiological** [comment]
Hi guys, I am also receiving the same error after attempting to use the plot_models function.

I was previously able to get a forest plot containing three glmer models using plot_models, but for some reason am hitting this error:

Error in as.character.default(x) : 
  no method for coercing this S4 class to a vector

As SilMerAl has mentioned, the same models can be plotted individually with plot_model.

Does this have anything to do with the new update?

Appreciate any help and thanks in advance.

**Comment by ecophysiological** [comment]
Hi again,

just thought would keep you in the loop - I installed an older version of the package using the following code:

PackageURL =  "https://cran.r-project.org/src/contrib/Archive/sjPlot/sjPlot_2.8.0.tar.gz"
install.packages(PackageURL, repos=NULL, type="source")

and was able to run plot_models() successfully on glmer() models.

I think this more strongly suggests this to be an error with the new version.
