### ISSUE TITLE
crPlots-$ operator not defined for this S4 class

### ISSUE THREAD

**Issue by epstewart111** [strengejacke/sjPlot#617]
I'm not sure if this is the correct place to post this, but I'm receiving an error when trying to test for nonlinearity in the main predictor of a mixed effects model using crPlots in the car package. The code is very basic and straightforward, which makes me think it's an issue with the package.

Here's the model:
m <- glmer(out ~ var1 + var2 + (group|1), data=df, binomial(link=logit), nAGQ=1, control = glmerControl(calc.derivs = FALSE))

I'm trying to test whether var1 is nonlinear using crPlots:
crPlots(m, terms = ~var1)

However, I'm receiving this error:
$ operator not defined for this S4 class.

I've tried different things, like crPlots(m, terms = ~.), but they all produce the same error. 

Any thoughts? Thanks!

**Comment by strengejacke** [comment]
I don't know what `crPlots()` does, it's not part of the sjPlot package.
