### ISSUE TITLE
Disappearing confidence intervals when changing axis limits of incidence ratio plot

### ISSUE THREAD

**Issue by pauljerem** [strengejacke/sjPlot#620]
Hi,

I'm using `plot_model` to generate incidence ratio plots for a `glmmTMB` zero-inflated model using:

`plot_model(model, type = "std", title = "")`

This gives:

![Screenshot 2020-04-06 at 11 50 15](https://user-images.githubusercontent.com/31322182/78550942-da878580-77fc-11ea-9ad1-b46f60a2607f.png)

But, when I try to adjust the x-axis to match plots from another model (following the method suggested [here](https://github.com/strengejacke/sjPlot/issues/440)), some of the confidence intervals disappear:

![Screenshot 2020-04-06 at 11 50 27](https://user-images.githubusercontent.com/31322182/78551181-30f4c400-77fd-11ea-8bc7-1483f9445bcf.png)

I found a solution to disappearing confidence intervals for marginal effects plots [here](https://github.com/strengejacke/sjPlot/issues/517), but trying to apply it on an incidence ratio plot just flips the axes, without adjusting their range.

Any idea how I can change the axis range and keep the confidence intervals?

Many thanks.

**Comment by strengejacke** [comment]
when the intervals (i.e. the lines from `geom_errorbar()`) exceed the visible x-axis range, these are omitted from the plot. So you have to use the largest range and use this for all plots.

**Comment by pauljerem** [comment]
Ah, got it! Thanks v. much for responding so quickly! :)
