### ISSUE TITLE
plot_model honours partially option OutDec

### ISSUE THREAD

**Issue by csrabak** [strengejacke/sjPlot#622]
A call to plot_model with options(OutDec=',') set prior to calls to sjPlot functions displays for the effect plot (type="pred") a mix of:
1) for the x axis the term values are shown with a comma as radix mark;
2) for the y axis the percentages are shown with a dot as radix point.

Here's an example:
 
![image](https://user-images.githubusercontent.com/10200568/78605802-97480980-7832-11ea-9e65-76bccd616eda.png)

Is this a bug or just some tweaking in how to call the function?

**Comment by strengejacke** [comment]
Not sure, but I think this is related to the *scales* package, which is responsible for printing the percentage-labels...

**Comment by csrabak** [comment]
I beg to differ Daniel!
I'll explain:

The scales toolkit has a special flag to choose the decimal mark.

Pls run example(scales) to see it changed to (in the example so called) "french_percent".
So I _think_ the sensible thing to do is to have the parameter decimal.mark = options("OutDec") in the functions that call scales function and the automagically will have the arrangement for all situations.

Do you agree?

**Comment by strengejacke** [comment]
You're right. Changed because I removed _scales_ from the dependencies, and am now using `insight::format_value()`.

Closing in favor of https://github.com/easystats/insight/issues/193

**Comment by csrabak** [comment]
Thank you very much!
And accept againg my kudos for your excellent job on this fine piece of SW!

Regards
