### ISSUE TITLE
Receiving error of 'Error in object@pp$b(1) : object 'merPredDb' not found' for lme4 models

### ISSUE THREAD

**Issue by sobenn** [strengejacke/sjPlot#627]
None of my existing code for plot_model works for lme4 objects since the new update,

**Comment by strengejacke** [comment]
You could try to update the [*parameters* package](https://easystats.github.io/parameters) (from CRAN), does this solve your issue?

**Comment by sobenn** [comment]
I'm afraid not, all associated packages are up to date

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by strengejacke** [comment]
_bump_
