### ISSUE TITLE
plot_xtab mislabelling factor levels, v. 2.8.3

### ISSUE THREAD

**Issue by Westendline** [strengejacke/sjPlot#628]
Please see the link to an issue I posed in stackoverflow:

https://stackoverflow.com/questions/61219021/problem-with-sjplotplot-xtab-mislabelling-factor-levels/61220198#61220198

This bug is not occurring in v. 2.8.0

**Comment by strengejacke** [comment]
possible duplicate of #616, should be fixed already.
