### ISSUE TITLE
Loading of sjPlot comes up with error message

### ISSUE THREAD

**Issue by LMacKenzie-png** [strengejacke/sjPlot#630]
I tried loading sjPLot recently and it told me it required r version 3.6.3. Since updating this I receive variations of the following message when trying to loading sjPlot:
 
Error: package or namespace load failed for ‘sjPlot’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘bayestestR’ 0.5.2 is already loaded, but >= 0.5.3 is required

**Comment by strengejacke** [comment]
I looks like your packages are not up to date. Try to restart R / Rstudio, and then update all packages.

**Comment by LMacKenzie-png** [comment]
Hi, 
thank you for your answer. I have updated all packages and now I get this message:
Error: package or namespace load failed for ‘sjPlot’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.4.2 is already loaded, but >= 0.4.5 is required
I have updated everything to the best of my knowledge.

**Comment by strengejacke** [comment]
This again indicates that one of the packages used by sjPlot requires rlang version 0.4.5 or higher, so the solution is most likely to update all packages.
