### ISSUE TITLE
plot_model with models with scaled polynomial terms fails

### ISSUE THREAD

**Issue by cbjrobertson** [strengejacke/sjPlot#631]
Similar to #549, but I've updated all my packages and am still running into this error: 

```
library(sjPlot)
library(ggplot2)
data(efc)
efc = efc[!is.na(efc$c12hour),]

fit <- lm(barthtot ~ poly(c12hour,2), data = efc)
plot_model(fit, type = "pred", terms = "c12hour")
```
![Rplot01](https://user-images.githubusercontent.com/22371870/80099842-062d9e00-8567-11ea-8049-248c423bb909.jpeg)
```
fit2 <- lm(barthtot ~ scale(c12hour), data = efc)
plot_model(fit2, type = "pred", terms = "c12hour")
```
![Rplot02](https://user-images.githubusercontent.com/22371870/80099896-1ba2c800-8567-11ea-93cb-1daca56f43ca.jpeg)
```
fit3 <- lm(barthtot ~ scale(poly(c12hour,2)), data = efc)
plot_model(fit3, type = "pred", terms = "c12hour")

>Error in `[.data.frame`(md, , needed.vars, drop = FALSE) : 
  undefined columns selected
```
Any help appreciated!

**Comment by cbjrobertson** [comment]
Bump?

**Comment by strengejacke** [comment]
Should be fixed with GitHub version of [insight](https://github.com/easystats/insight/).
