### ISSUE TITLE
plot_model fails with scaled polynomial terms

### ISSUE THREAD

**Issue by cbjrobertson** [strengejacke/sjPlot#634]
After your latest update to #631 (thank you!), I am now getting the following error (which appears to be some idiosyncratic feature of my real data):

```
data <- read.csv("https://raw.githubusercontent.com/cbjrobertson/data_share/master/data.csv")

mod1 <- glmer(y ~ poly(x1,2) + poly(x2,2) + (1|group),family=binomial,data=data)
plot_model(mod1,type='pred',terms=c("x2 [all]"))
```
![example](https://user-images.githubusercontent.com/22371870/80584199-3cf13180-8a09-11ea-88fc-8738179ae0e0.jpg)

```
mod2 <- glmer(y ~ scale(poly(x1,2)) + scale(poly(x2,2)) + (1|group),family=binomial,data=data)
plot_model(mod2,type='pred',terms=c("x2 [all]"))
>Error in poly(x1, 2) : 'degree' must be less than number of unique points
```
Thanks for your great package!

**Comment by strengejacke** [comment]
You have two poly-terms, but you're holding `x1` constant (i.e. set to one value). This does not work for prediction-plots. 

I think the solution might be to a) remove one poly-term, or b) maybe use splines or `I(x1^2)`, or c) define `x1` as well in `terms`.

**Comment by strengejacke** [comment]
closing it, meanwhile it works:

``` r
library(lme4)
#> Loading required package: Matrix
library(sjPlot)
#> Learn more about sjPlot with 'browseVignettes("sjPlot")'.
data <- read.csv("https://raw.githubusercontent.com/cbjrobertson/data_share/master/data.csv")
mod1 <- glmer(y ~ poly(x1,2) + poly(x2,2) + (1|group),family=binomial,data=data)
plot_model(mod1,type='pred',terms=c("x2 [all]"))
```

![](https://i.imgur.com/3Kq5agN.png)

<sup>Created on 2020-09-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
