### ISSUE TITLE
plot_grpfrq (weight_by issue)

### ISSUE THREAD

**Issue by lucascividanes** [strengejacke/sjPlot#635]
I've been struggling to use the weight_by = parameter in the plot_grpfrq() function.

The plot includes only a few levels. It reports that the other rows were removed because they contain missing values, but the same variables work pretty well with the tab_xtab() function.

Any idea why? Is it a bug?

**Comment by strengejacke** [comment]
Do you have a reproducible exampl

**Comment by lucascividanes** [comment]
This is the result for tab_xtab():

tab_xtab(OD_2017$sexo, OD_2017$pe_bici, encoding = "UTF-8", weight.by = OD_2017$fe_via)

![image](https://user-images.githubusercontent.com/37715256/81353010-5b58cc00-909e-11ea-8cc0-4165e1db22f4.png)

And this is the result for plot_grpfrq() without with the weight.by parameter respectively:

plot_grpfrq(OD_2017$sexo, OD_2017$pe_bici, coord.flip = T)

![image](https://user-images.githubusercontent.com/37715256/81353230-dfab4f00-909e-11ea-87ae-570c775da3fe.png)

plot_grpfrq(OD_2017$sexo, OD_2017$pe_bici, coord.flip = T, weight.by = OD_2017$fe_via)

![image](https://user-images.githubusercontent.com/37715256/81353254-ecc83e00-909e-11ea-9c6d-80b7f715bf3a.png)

**Comment by strengejacke** [comment]
Can't reproduce the weighting issue:

``` r
library(sjmisc)
library(sjPlot)
#> Install package "strengejacke" from GitHub (`devtools::install_github("strengejacke/strengejacke")`) to load all sj-packages at once!
data(efc)
set.seed(123)
efc$weights <- abs(rnorm(n = nrow(efc), mean = 1, sd = .5))

flat_table(efc, e15relat, e16sex)
#>                         e16sex male female
#> e15relat                                  
#> spouse/partner                  123     48
#> child                           110    362
#> sibling                          13     16
#> daughter or son -in-law          15     70
#> ancle/aunt                       10     13
#> nephew/niece                      2     20
#> cousin                            1      5
#> other, specify                   22     70
plot_grpfrq(efc$e15relat, efc$e16sex, show.values = TRUE)
```

![](https://i.imgur.com/2AGVJsK.png)

``` r

flat_table(efc, e15relat, e16sex, weights = weights)
#>                         e16sex male female
#> e15relat                                  
#> spouse/partner                  127     48
#> child                           112    364
#> sibling                          10     14
#> daughter or son -in-law          14     80
#> ancle/aunt                       11     14
#> nephew/niece                      3     19
#> cousin                            1      5
#> other, specify                   22     68
plot_grpfrq(efc$e15relat, efc$e16sex, show.values = TRUE, weight.by = efc$weights)
```

![](https://i.imgur.com/4na2BbC.png)

<sup>Created on 2020-05-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Please provide a _reproducible_ example, so I can figure out if there's a bug.

**Comment by strengejacke** [comment]
_bump_

lease provide a _reproducible example_, so I can figure out if there's a bug.
