### ISSUE TITLE
Compatibility with MuMIn model averaging

### ISSUE THREAD

**Issue by LJones42** [strengejacke/sjPlot#651]
Hi! First thankyou for creating a lovely way for visualising the results of mixed effect models, I am excited to use plot_model() in my PhD thesis! I am currently running model selection and averaging using the MuMIn package.

Is it possible to use plot_model() to display model averaged results, such as below:

`model_aves <- model.avg(get.models(dredge_results, subset = delta < 2))`
`aves_summary <- round(summary(model_aves)$coefmat.subset, 3)`
`plot_model(aves_summary, type = "std", show.values = TRUE)`

At the moment I get the following error: "Error: $ operator is invalid for atomic vectors
In addition: Warning message:
Could not access model information."

Many thanks,
Lizzie

**Comment by strengejacke** [comment]
Do you have a reproducible example? I think this should be possible already...

**Comment by LJones42** [comment]
Hi Daniel,

Really appreciate you getting back to me! I’ve made an example using the iris dataset. I’ve attached the code to this email :)

Thanks for any help or ideas!
Lizzie

Lizzie Jones
PhD Candidate
Email: lizzie.jones@ioz.ac.uk <mailto:lizzie.jones@ioz.ac.uk>

**Comment by strengejacke** [comment]
Unfortunately, you can't send attachment to GitHub via email, so you could either mail me directly, or visit the GItHub page to attach the sample.

**Comment by LJones42** [comment]
GitHub newbie sorry! Here's the code as a txt. file

Thanks!

[modelavg_sjplot.txt](https://github.com/strengejacke/sjPlot/files/4832632/modelavg_sjplot.txt)

**Comment by strengejacke** [comment]
You should use `model_aves`, the averaging-object, not `model_ave`, which is a simple matrix (and no model object). Then it works.

```r
plot_model(model_aves, type = "std", show.values = TRUE, value.offset = .3, title = "Averaged results")
```
