### ISSUE TITLE
sjplot: tab_model error in plm fixed effect model

### ISSUE THREAD

**Issue by hvictory1993** [strengejacke/sjPlot#652]
Problem sample:
```r
library(plm)
test3333=data.frame(ID=c('TOM','TOM','TOM','TOM','MARY','MARY','MARY','JOHN','JOHN'),Year=c(1992:1995,1991:1993,1993:1994),ret=rnorm(9))
test3333=pdata.frame(test3333)
test3333['lag']=plm::lag(test3333$ret)
test3333=na.omit(test3333)
test3333model=ret~lag
model=plm(test3333model,data=test3333,model='within',effect = 'individual',index=c('ID','Year'))
tab_model(model)
```

Error in data.frame(..., stringsAsFactors = FALSE) : 
 arguments imply differing number of rows: 0, 1

I think the problem is on the intercept, but I tried to use show.intercept=F still not work

My data has 4 model, different independent variables:1,2,4,8
tab_model only works on model2 and model4
model1 error: Error in data.frame(..., stringsAsFactors = FALSE) : arguments imply differing number of rows: 0, 1
model4 error: Error in `[.data.frame`(mf, , model_terms, drop = FALSE) :  undefined columns selected

thanks

**Comment by strengejacke** [comment]
Thanks, should be fixed in a forthcoming update of the [parameters-package](https://easystats.github.io/parameters/index.html), which will be submitted to CRAN the next days.
