### ISSUE TITLE
"Arguments imply differing number of rows" error if model has categorical interaction terms

### ISSUE THREAD

**Issue by popovs** [strengejacke/sjPlot#656]
I was getting the following error when trying to run `plot_model()` on some of my models:

> Error in data.frame(..., stringsAsFactors = FALSE) : 
>   arguments imply differing number of rows: ##, ##

I've narrowed the error down to models that have interaction terms between two categorical variables. Not sure if this is intended (perhaps there is a quirk to plotting effect size of such an interaction term?)

Here is a crap but reproducible example:
> A <- c("frogs", "frogs", "frogs", "turtles", "turtles", "frogs", "turtles", "frogs")
> B <- c("bog", "swamp", "bog", "bog", "swamp", "beach", "swamp", "bog")
> x <- sample(x = 1:10, size = 8)
> y <- sample(x = -5:13, size = 8)
> response <- rnorm(n = 8, mean = 2, sd = 1)
> df <- cbind(A, B, x, y, response)
> df <- as.data.frame(df)
> model <- lm(response ~ A * B + x + y, data = df)
> plot_model(model)

**Comment by strengejacke** [comment]
Should be fixed in https://github.com/easystats/parameters/commit/eea8ac5472dcaa0ac1d88400733d189e59a1d3b4. So once _parameters_ is updated on CRAN, you should be able to reproduce the plot.

``` r
A <- c("frogs", "frogs", "frogs", "turtles", "turtles", "frogs", "turtles", "frogs")
B <- c("bog", "swamp", "bog", "bog", "swamp", "beach", "swamp", "bog")
x <- sample(x = 1:10, size = 8)
y <- sample(x = -5:13, size = 8)
response <- rnorm(n = 8, mean = 2, sd = 1)
df <- cbind(A, B, x, y, response)
df <- as.data.frame(df)
model <- lm(response ~ A * B + x + y, data = df)
#> Warning in model.response(mf, "numeric"): using type = "numeric" with a factor
#> response will be ignored
#> Warning in Ops.factor(y, z$residuals): '-' not meaningful for factors
sjPlot::plot_model(model)
#> Warning in Ops.factor(r, 2): '^' not meaningful for factors
#> Warning: Model matrix is rank deficient. Parameters x2, x6, x9, y0, y10, y12,
#> y13, y3, y4, y8, Aturtles:Bbog, Aturtles:Bswamp were not estimable.
#> Warning in Ops.factor(r, 2): '^' not meaningful for factors
#> Warning: Model has zero degrees of freedom!
#> Warning in Ops.factor(r, 2): '^' not meaningful for factors

#> Warning in Ops.factor(r, 2): '^' not meaningful for factors
#> Warning: Model has zero degrees of freedom!
```

![](https://i.imgur.com/HhFjrgF.png)

<sup>Created on 2020-07-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
