### ISSUE TITLE
Plotting interactions from within-subjects effects

### ISSUE THREAD

**Issue by jogrue** [strengejacke/sjPlot#657]
Hi Daniel,

I was playing around with various panel models for within-subject effects and was also trying to fit and plot an interaction as a within estimator. Basically, I tried something like this:

```r
plm_mod <- plm::plm(x ~ a*b + wave,
                    data = moddata, effect = "individual")
felm_mod <- lfe::felm(x ~ a*b + wave | id,
                      data = moddata)
lm_mod <- lm(x ~ 0 + a_within + b_within +
               a_b_within + wave + id,
             data = moddata)
lmer_mod <- lme4::lmer(x ~ a_within + b_within +
                         a_b_within + 
                         a_between + b_between +
                         a_b_between +
                         wave + (1 | id),
                       data = moddata)
panelr_mod <- panelr::wbm(x ~ a*b, # works
                          data = moddata,
                          id = "id", wave = "wave",
                          interaction.style = "demean",
                          use.wave = TRUE, wave.factor = TRUE)
panelr_mod2 <- panelr::wbm(x ~ a*b + c, # doesn't work
                          data = moddata,
                          id = "id", wave = "wave",
                          interaction.style = "demean",
                          use.wave = TRUE, wave.factor = TRUE)

sjPlot::plot_model(plm_mod, type = "int")
sjPlot::plot_model(felm_mod, type = "int")
sjPlot::plot_model(lm_mod, type = "int")
sjPlot::plot_model(lmer_mod, type = "int")
sjPlot::plot_model(panelr_mod, type = "int")
sjPlot::plot_model(panelr_mod2, type = "int")
```

I ran plm and the lfe::felm models with interactions. With both, I could not plot the interactions. The lfe package does not offer predict and plm still has this error: https://github.com/strengejacke/sjPlot/issues/594

With the panelr package I had some success, as long as my model did not include any other terms besides the interaction (`y ~ a*b` worked, but `y ~ a*b + c` or `y ~ a*b | d` didn't). If another term is present, I get this message: `Error in X %*% lme4::fixef(object) : non-conformable arguments`. So panelr would be an option and I guess my problems here are panelr issues (and have nothing to do with your packages). EDIT: I now also get the same error (also with ggpredict) from the simple model. Will have to investigate this further.

My prefered approach towards such models, however, was to use lme4 directly and fit a random-effects within-between model. I used your de_mean function from the sjmisc package in the past and now used the demean function from the parameters package. I demeaned the interaction term (i.e., the product of the two terms was demeaned). Of course, now, ggeffect and sjPlot do not recognize this model term as an interaction term. The same is true for lm models.

So my main question would be, is there an easy way to plot the demeaned interaction term in a within-effects model? Is there maybe an option to manually tell ggeffects that a certain term is an interaction term?

**Comment by strengejacke** [comment]
Do you have a small toy-example or some data so I can reproduce your models?

> I demeaned the interaction term (i.e., the product of the two terms was demeaned). Of course, now, ggeffect and sjPlot do not recognize this model term as an interaction term. The same is true for lm models.

Yes, I think the _panelr_ package should be the best option here, as it does all the demeaning internally, preserving the interaction effects.

> If another term is present, I get this message: Error in X %*% lme4::fixef(object) : non-conformable arguments.

Is this an error by _panelr_ or by _sjPlot_?
