### ISSUE TITLE
show.values not working in plot_model() for glmer

### ISSUE THREAD

**Issue by bshor** [strengejacke/sjPlot#661]
I am trying to plot a predicted values plot for my glmer model fit. I can't seem to get it to display the raw values for some reason (and it worked in the older sjp.glmer when it was called "show.scatter"). Here is the function call:

`plot_model(mlm.sample.all[["r"]],type="pred",show.values=TRUE,terms=c("party.diff [all]"),axis.title = c("Party Difference","Switch Probability"),title="",show.ci=T,axis.lim = list(c(-1,1),c(0,1)))
`

I get a warning about a scale for y that confuses me:

`Scale for 'y' is already present. Adding another scale for 'y', which will replace the existing scale.
`

Here is my output which looks right except for lacking the values which are distributed across the -1,1 on the x axis, and 1,0 on the y axis (eg, probabilities).

![image](https://user-images.githubusercontent.com/468070/88096863-f3723780-cb5c-11ea-99d7-ea0a70a5e986.png)

**Comment by bshor** [comment]
I see now that the correct option is show.data(). But I still get the strange scale already present problem.

**Comment by strengejacke** [comment]
I'll look into it. However, for effects-plots, _sjPlot_ internally uses [ggeffects](https://strengejacke.github.io/ggeffects/index.html), so you might think about using _ggeffects_ directly. The syntax is quite similar.

``` r
library(ggeffects)
library(sjmisc)
library(lme4)
#> Loading required package: Matrix

set.seed(123)

dat <- data.frame(
  outcome = rbinom(n = 100, size = 1, prob = 0.35),
  var_binom = as.factor(rbinom(n = 100, size = 1, prob = 0.2)),
  var_cont = rnorm(n = 100, mean = 10, sd = 7),
  group = sample(letters[1:4], size = 100, replace = TRUE)
)

dat$var_cont <- sjmisc::std(dat$var_cont)

m1 <- glmer(
  outcome ~ var_binom + var_cont + (1 | group), 
  data = dat, 
  family = binomial(link = "logit")
)

pr <- ggpredict(m1, terms = "var_cont")
#> Data were 'prettified'. Consider using `terms="var_cont [all]"` to get smooth plots.
pr
#> 
#> # Predicted probabilities of outcome
#> # x = var_cont
#> 
#>     x | Predicted |   SE |       95% CI
#> ---------------------------------------
#> -2.50 |      0.34 | 0.62 | [0.13, 0.63]
#> -2.00 |      0.34 | 0.53 | [0.16, 0.59]
#> -1.00 |      0.36 | 0.37 | [0.21, 0.53]
#>  0.00 |      0.37 | 0.29 | [0.25, 0.51]
#>  0.50 |      0.38 | 0.31 | [0.25, 0.52]
#>  1.00 |      0.38 | 0.35 | [0.24, 0.55]
#>  2.00 |      0.40 | 0.51 | [0.19, 0.64]
#>  3.50 |      0.42 | 0.79 | [0.13, 0.77]
#> 
#> Adjusted for:
#> * var_binom = 0
#> *     group = 0 (population-level)
#> Standard errors are on link-scale (untransformed).

plot(pr, add.data = TRUE)
#> Loading required namespace: ggplot2
```

![](https://i.imgur.com/RvO0lVO.png)

<sup>Created on 2020-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
There are some examples for plotting:

https://strengejacke.github.io/ggeffects/articles/introduction_plotmethod.html
https://strengejacke.github.io/ggeffects/articles/introduction_plotcustomize.html
