### ISSUE TITLE
using plot_model with geeglm - plotting marginal effects with type = "eff"... show.values not working

### ISSUE THREAD

**Issue by JamesSteeleII** [strengejacke/sjPlot#668]
I'm new to using sjplot (which is great vbtw), and also new to GEEs and using geepack. I can get my marginal effects plotted from the geeglm model using type = "eff" but I want to add labels/values to the data points in the plot. When using show.value=TRUE though the values don't seem to be added to the plot. 

I have tried using predict(model, type = "response") to pull them separately and try to label manually, but predict doesn't seem to like my geeglm model either.

Any suggestions?

Thanks,

James

**Comment by strengejacke** [comment]
There is currently no option to add text-values to the effects-plots. You can workaround this by using [ggeffects](http://strengejacke.github.io/ggeffects) directly and building your own ggplot-object (some examples [can be found here](https://strengejacke.github.io/ggeffects/articles/ggeffects.html)).
