### ISSUE TITLE
tab_model not working after updating insights and parameters

### ISSUE THREAD

**Issue by LIVF** [strengejacke/sjPlot#669]
Hi, 
I  am writing a report comparing models using _tab_model()_ but I cannot print the summary of some models. I get this error:

_Error in gsub("Statistic", gsub("-statistic", "", attr(statistic, "statistic",  : 
  invalid 'replacement' argument_

I have updated packages *insights* and *parameters* from github, although it has not solved the issue. I think it may be because these models have a markov random field smooth and are calculated with function _bam()_ from *mgcv*. The models with the MRF smooth calculated with function _gam()_ are nicely produced.  Is there a way I could produce the tables? 
Many thanks.
L

**Comment by strengejacke** [comment]
I think `bam` models are not supported yet. Must check.
