### ISSUE TITLE
Confidence intervals have disappeared again

### ISSUE THREAD

**Issue by LindaWvanR** [strengejacke/sjPlot#672]
Hi Daniel, 

How are you? I am having a similar issue I had before: when I use "pred" as type creating a plot, the confidence intervals cannot be computed. It does work with type="emm" though, so I thought there may be an issue in ggeffects. I installed the latest version, but unfortunately, it does not work. Can you help me?

Thanks and have a good day. 
Linda

**Comment by strengejacke** [comment]
Do you have a small reproducible example that demonstrates this behaviour?
