### ISSUE TITLE
Warning of of removal of missing values when using "plot_model", but models do not have NAs

### ISSUE THREAD

**Issue by davidcanarte** [strengejacke/sjPlot#678]
Hello

Please, I am in need of some help

I am trying to plot the odds ratios of a set of mixed effects logistic regressions (5 in total, one plot at a time)  with the function "plot_model". All models converged and there aren't no missing values in predictors and outcomes. When plotting, however, the same two predictors (one at level-1, and the other at level-2) across the 5 models are not plotted. The rest of predictors are plotted just fine. 

Also, I am having this warning across all plots; "geoms" vary. As said, there are not missing values in my data.
"# Warning messages:
#1: Removed 2 rows containing missing values (geom_point). 
#2: Removed 2 rows containing missing values (geom_text). "

This is code I am using... 
"# Plot
pdf("./Plots/my_model.OR.pdf", height = 12)
plot_model(my_model., show.values = TRUE, 
           value.offset = .4, 
           value.size = 3,
           dot.size = 1.5, sort.est = TRUE,
           title = "Outcome", 
           axis.lim = c(0.4, 4),
           axis.labels = var.labs,
           vline.color = alpha("grey50", 0.5)) + 
  theme_bw() 
dev.off()"

Thanks

**Comment by davidcanarte** [comment]
I fixed it... It was the function "axis.lim". I changed the values "axis.lim = (0.04, 4) to make those OR plot. You can close this issue.

**Comment by strengejacke** [comment]
Thanks, yes, the warning referred to ggplot, saying that not all data could be plotted (because these were out of axis-range).
