### ISSUE TITLE
modifying y-axis of marginal effects

### ISSUE THREAD

**Issue by ellie-story** [strengejacke/sjPlot#679]
I am plotting a logistic regression interaction using plot_model. The marginal effects are being displayed as a % on the y-axis from 20%-40%. I want to change the y-axis range from 0%-100%. How could i do that?

Code:
plot_model(gbg_gender, type = "int", title = "Marginal Effects of GBG x Gender Interaction in Predicting Trouble Sleeping", axis.title = "8th grade trouble sleeping", 
           colors = c("firebrick", "blue"), show.legend = T, legend.title = "GBG")

**Comment by tguerra** [comment]
Did you try the `axis_lim` argument? It is a vector of length 2 which defines the range of the plot axis.

**Comment by strengejacke** [comment]
For marginal effects plot, sjPlot uses the [ggeffects](https://strengejacke.github.io/ggeffects/index.html) package, which allows some more customization for plotting. You can than use the `limits`-argument:

``` r
library(ggeffects)
dat <- data.frame(
  outcome = rbinom(n = 100, size = 1, prob = 0.35),
  var_binom = as.factor(rbinom(n = 100, size = 1, prob = 0.2)),
  var_cont = rnorm(n = 100, mean = 10, sd = 7),
  group = sample(letters[1:4], size = 100, replace = TRUE)
)

m1 <- glm(
  outcome ~ var_binom + var_cont, 
  data = dat, 
  family = binomial(link = "logit")
)

me <- ggpredict(m1, "var_binom")
plot(me)
#> Loading required namespace: ggplot2
```

![](https://i.imgur.com/h571HAO.png)

``` r
plot(me, limits = c(0,1))
```

![](https://i.imgur.com/ux9yCuU.png)

<sup>Created on 2020-09-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

See also https://strengejacke.github.io/ggeffects/articles/introduction_plotcustomize.html#changing-the-y-axis-appearance-1
