### ISSUE TITLE
plot_model: change line types

### ISSUE THREAD

**Issue by yellow2cosmic** [strengejacke/sjPlot#680]
I'm new in sjplot and apologize if this has been answered, but I did not find the solution yet. 

I am plotting mixed effect model by plot_model.
set_theme(base = theme_sjplot(), title.align = "center")
plot_model(model1, type = "int", mdrt.values = "minmax", colors = "Set1")

<img width="479" alt="Screen Shot 2020-09-03 at 4 59 43 PM" src="https://user-images.githubusercontent.com/64693640/92166653-f53f4400-ee06-11ea-999b-d63e92315925.png">

 I'm aware of how to change line colors, but I'm not sure how to change line types with dots at each time point. The plot I want is like this, with different line types. Any help would be really appreciated. Thanks!

<img width="807" alt="Screen Shot 2020-09-03 at 5 00 18 PM" src="https://user-images.githubusercontent.com/64693640/92166664-fa03f800-ee06-11ea-9aed-f1b75e581ed2.png">

**Comment by strengejacke** [comment]
This customization is beyond the possible settings of sjPlot. For effects plots, sjPlot uses [ggeffects](http://strengejacke.github.io/ggeffects). I suggest you use _ggeffects_ directly, and use the data frame to setup an own ggplot-plot. See examples on the referenced ggeffects-website.
