### ISSUE TITLE
lmer with Single FE Factor plotting as line

### ISSUE THREAD

**Issue by coverton-usgs** [strengejacke/sjPlot#683]
This is maybe a user-error issue but, I understand that when a single effect is in the a model the default plot option for plot_model is a line.  That makes sense, but my single variable model is a categorical factor.  The line file produced is referencing the factor index value for a line.  Is there a convenient way to short circuit that behavior and get the same type of graph (horizontal lines for an type="est" as opposed to a vertical for a type="eff"?

Currently I am adding a nuisance variable to the model to get what I want and removing terms.

```
spaceuse_subset$nuisancevar<-sample(letters[1:2],nrow(spaceuse_subset), replace=T)

a<-lme4::lmer(Log_Hectares ~ -1 + cadencefactor + (1|taxon_detail) + (1|local_identifier) , data = spaceuse_subset)
b<-lme4::lmer(Log_Hectares ~ -1 + cadencefactor + nuisancevar + (1|taxon_detail) + (1|local_identifier) , data = spaceuse_subset)

plot_model(a)
plot_model(b, order.terms = c(1,2,3,4,5,6,7,8))
```
plot_model(a):
![image](https://user-images.githubusercontent.com/43579258/92687349-37c5bc80-f2f0-11ea-998e-07bf1a8b6d67.png)

plot_model(b, order.terms = c(1,2,3,4,5,6,7,8)):
![image](https://user-images.githubusercontent.com/43579258/92687410-55932180-f2f0-11ea-915d-3682a4255529.png)

**Comment by strengejacke** [comment]
Thanks, should work after updating _sjPlot_ and [_insight_](http://easystats.github.io/insight) from GitHub:

``` r
iris$nuisancevar <- sample(letters[1:2], nrow(iris), replace = T)
a <- lm(Sepal.Length ~ -1 + nuisancevar, data = iris)
sjPlot::plot_model(a)
```

![](https://i.imgur.com/LkZ7Ep6.png)

<sup>Created on 2020-09-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
