### ISSUE TITLE
Failing to load sjPlot

### ISSUE THREAD

**Issue by jonmcphetres** [strengejacke/sjPlot#687]
I had what I guess was an older version of sjPlot and it was working fine.
I was creating a demonstration and installed a new version of sjPlot, now I can't load the library.

I also tried installing the dev version, but the error persists. Here's the error:

Error: package or namespace load failed for ‘sjPlot’: object ‘variance_decomposition’ is not exported by 'namespace:performance'

6. stop(msg, call. = FALSE, domain = NA)
5. value[[3L]](cond)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
3. tryCatchList(expr, classes, parentenv, handlers)
2. | tryCatch({ attr(package, "LibPath") <- which.lib.loc ns <- loadNamespace(package, lib.loc) env <- attachNamespace(ns, pos = pos, deps, exclude, include.only) ...
1. library(sjPlot)

**Comment by strengejacke** [comment]
Please try to update your packages, resp. install / update the _performance_ package. That should resolve your issue.

**Comment by jonmcphetres** [comment]
Thanks- sorry I forgot to mention I tried that as well. It did not solve the issue.

**Comment by strengejacke** [comment]
Can you post your session info? `sessionInfo()`

**Comment by jonmcphetres** [comment]
Hmmm, so for some reason it has resolved... not sure what happened.
