### ISSUE TITLE
Error to install sjPlot package in R

### ISSUE THREAD

**Issue by eq84240** [strengejacke/sjPlot#688]
I would like to install sjPlot but I have this error message, someone can help me please ?
> install.packages("sjPlot")
Installing package into ‘C:/Users/elodi/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
       binary source needs_compilation
sjPlot  2.8.3  2.8.5             FALSE

installing the source package ‘sjPlot’

trying URL 'https://cran.rstudio.com/src/contrib/sjPlot_2.8.5.tar.gz'
Content type 'application/x-gzip' length 875497 bytes (854 KB)
downloaded 854 KB

* installing *source* package 'sjPlot' ...
** package 'sjPlot' correctement décompressé et sommes MD5 vérifiées
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error : object 'variance_decomposition' is not exported by 'namespace:performance'
ERROR: lazy loading failed for package 'sjPlot'
* removing 'C:/Users/elodi/Documents/R/win-library/3.5/sjPlot'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘sjPlot’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\elodi\AppData\Local\Temp\RtmpkdLsxr\downloaded_packages’
>

**Comment by strengejacke** [comment]
Seems to be the same issue as here: https://github.com/strengejacke/sjPlot/issues/687
