### ISSUE TITLE
tab_model is slow

### ISSUE THREAD

**Issue by awcm0n** [strengejacke/sjPlot#691]
I'm running a simple logistic regression analysis using stats::glm with 670,136 subjects. On my aging MacBook Pro, tab_model takes close to 2 minutes to create the html table from the fit object (attached). Is there a way to speed this up?

[fit1a.rda.zip](https://github.com/strengejacke/sjPlot/files/5321149/fit1a.rda.zip)

**Comment by strengejacke** [comment]
That's most likely due to profiled confidence intervals. Try setting the argument `df_method = "wald"`.

**Comment by awcm0n** [comment]
> That's most likely due to profiled confidence intervals. Try setting the argument `df.method = "wald"`.

That doesn't work. I receive the following error message after about a minute:
Could not access model information.Error in if (fam.info$is_linear) transform <- NULL else transform <- "exp" : 
  argument is of length zero

**Comment by strengejacke** [comment]
Takes ~5 seconds on an old Laptop, w/o any errors or warnings:

```r
tab_model(fit1a, df.method = "wald")
```

![image](https://user-images.githubusercontent.com/26301769/95305015-b8db8980-0885-11eb-9c37-67bf12f333c9.png)

Are your packages up to date?

**Comment by awcm0n** [comment]
Here is what's happening on my end on both a Windows PC and a MacBook Pro:

**Windows PC (Intel Core i7-6700 with 32 GB RAM, Windows 10 Enterprise version 1909)**
- R version 4.0.2, sjPlot version 2.8.5

> tab_model(fit1a, df_method = "wald")
Profiled confidence intervals may take longer time to compute. Use 'df_method="wald"' for faster computation of CIs.
Could not access model information.Error in if (fam.info$is_linear) transform <- NULL else transform <- "exp" : 
  argument is of length zero

> start.time <- Sys.time()
> tab_model(fit1a)
Profiled confidence intervals may take longer time to compute. Use 'df_method="wald"' for faster computation of CIs.
> end.time <- Sys.time()
> time.taken <- end.time - start.time
> time.taken
Time difference of 1.254089 mins

**MacBook Pro (mid 2012 with 8 GB RAM, macOS Catalina 10.15.7)**
- R version 4.0.2, sjPlot version 2.8.5

> tab_model(fit1a, df_method = "wald")
Profiled confidence intervals may take longer time to compute. Use 'df_method="wald"' for faster computation of CIs.
Could not access model information.Error in if (fam.info$is_linear) transform <- NULL else transform <- "exp" : 
  argument is of length zero

> start.time <- Sys.time()
> tab_model(fit1a)
Profiled confidence intervals may take longer time to compute. Use 'df_method="wald"' for faster computation of CIs.
> end.time <- Sys.time()
> time.taken <- end.time - start.time
> time.taken
Time difference of 1.622317 mins

**Comment by awcm0n** [comment]
Here is what's happening on my end on both a Windows PC and a MacBook Pro (after updating R and sjPlot which didn't change the outcome):

**Windows PC (Intel Core i7-6700 with 32 GB RAM, Windows 10 Enterprise version 1909)**
- R version 4.0.2, sjPlot version 2.8.5

> tab_model(fit1a, df_method = "wald")
Profiled confidence intervals may take longer time to compute. Use 'df_method="wald"' for faster computation of CIs.
Could not access model information.Error in if (fam.info$is_linear) transform <- NULL else transform <- "exp" : 
  argument is of length zero

> start.time <- Sys.time()
> tab_model(fit1a)
Profiled confidence intervals may take longer time to compute. Use 'df_method="wald"' for faster computation of CIs.
> end.time <- Sys.time()
> time.taken <- end.time - start.time
> time.taken
Time difference of 1.254089 mins

**MacBook Pro (mid 2012 with 8 GB RAM, macOS Catalina 10.15.7)**
- R version 4.0.2, sjPlot version 2.8.5

> tab_model(fit1a, df_method = "wald")
Profiled confidence intervals may take longer time to compute. Use 'df_method="wald"' for faster computation of CIs.
Could not access model information.Error in if (fam.info$is_linear) transform <- NULL else transform <- "exp" : 
  argument is of length zero

> start.time <- Sys.time()
> tab_model(fit1a)
Profiled confidence intervals may take longer time to compute. Use 'df_method="wald"' for faster computation of CIs.
> end.time <- Sys.time()
> time.taken <- end.time - start.time
> time.taken
Time difference of 1.622317 mins

**Comment by strengejacke** [comment]
Try `df.method`, not `df_method`.

**Comment by awcm0n** [comment]
Much better:
> start.time <- Sys.time()
> tab_model(fit1a, df.method = "wald")
> end.time <- Sys.time()
> time.taken <- end.time - start.time
> time.taken
Time difference of 3.58165 secs

Thanks for looking into this issue.
