### ISSUE TITLE
Problem with plotting interaction in logistic mixed effects regression

### ISSUE THREAD

**Issue by Marven82** [strengejacke/sjPlot#695]
I'm trying to plot a two-way interaction from a logistic mixed effects regression model, and this somehow fails. Here's my syntax (data file is attached):

temp <- read.table("data2.txt", T)
temp$rand1 <- as.factor(temp$rand1)
temp$rand2 <- as.factor(temp$rand2)
temp$var1 <- as.numeric(temp$var1)
temp$var2 <- as.numeric(temp$var2)
temp$factor1 <- as.factor(temp$factor1)
temp$factor2 <- as.factor(temp$factor2)
temp$dep <- as.factor(temp$dep)

set_label(temp$dep) <- "Odds ratio for dep"

data.lmer <- glmer(dep ~ (var1+var2+factor1+factor2)+factor1*factor2+factor1*var1+ (1 + factor2 | rand1) + (1 | rand2), family = binomial, control = glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 10000000)), data = temp)

plot_model(data.lmer, value.size = 4, dot.size = 3, type = "pred", terms = c("factor1", "factor2"))

Somehow it is plotting percentages rather than the Log odds and I hope you can tell me what is going wrong here. Thanks in advance!

Marco

[data2.txt](https://github.com/strengejacke/sjPlot/files/5355435/data2.txt)

**Comment by strengejacke** [comment]
` type = "pred"` shows (marginal) effects plots, and these are on the response scale, resp. predicted probabilities for logistic regression models. See help on the `type`-argument in [`?plot_model`](https://strengejacke.github.io/sjPlot/reference/plot_model.html), and the related vignettes.
