### ISSUE TITLE
view_df alignment issue

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjPlot#70]
the font size of the value labels seems fixed and cannot be aligned with values perfectly. 
![screen shot 2015-10-22 at 21 09 24](https://cloud.githubusercontent.com/assets/12545793/10669678/6f6be0e8-7914-11e5-9d87-8b51c1dcd33f.png)
Could you help on this? Thank you.

**Comment by sjPlot** [comment]
Due to different line heights, I currently only see the solution to create a separate table row for each value - which would require a lot of code changes... I'll keep this issue open, but it has lower priority for me at the moment (also because lack of time).

**Comment by frankcsliu** [comment]
Thanks for taking it into consideration. We understand and appreciate
how much you have done in most recent updates. These really helped the
presentation of our works.

Best,
Frank

**Comment by sjPlot** [comment]
Could you try the `line-height` CSS attribute?

```
library(sjmisc)
library(sjPlot)
data(efc)
view_df(efc, CSS = list(css.table = '+line-height:2em'))
```

**Comment by strengejacke** [comment]
Any news on this issue? Else I would close it...
