### ISSUE TITLE
Extracting values for inline quoting

### ISSUE THREAD

**Issue by mbac** [strengejacke/sjPlot#701]
Hi,

Is it possible to extract values resulting from a `tab_model` call? In this case, I'm interested in parameter estimates, their CIs and the p-value as presented in the final HTML table. The idea would be to mention them within the full text body in Rmarkdown docs, and of course to have them automatically updated upon knitting whenever something changes in the model.

At the moment, I'm using an entirely separate call to `broom.mixed::tidy` to extract the params, but of course this rules out any bootstrapping in `tab_model`, which could be usefuil.

Thanks a lot for this package, by the way, it really helped so much…

**Comment by strengejacke** [comment]
`tab_model()` and `plot_model()` are more or less "wrappers" around [`parameters::model_parameters()`](https://easystats.github.io/parameters/). There are a lot of examples in the linked vignetted, how to standardize, robust estimation etc. Version 0.9.0 of _parameters_ is submitted to CRAN, should be available shortly, with some new feature and also including new supported models.

**Comment by mbac** [comment]
Thank you sooo much… Don't ban me, but I have to ask… Why such similar-but-not-quite-identical name for parameters column names with respect to broom.mixed::tidy? Asking for a friend…

The packages you're authoring/maintaining are really useful and smart, it would be just a little easier on us end-users if they could be somewhat standardized, at least as far as possible…

**Comment by strengejacke** [comment]
Not sure if I understand correctly. The `print()` method uses "context" specific column names for thr output, however, the underlying data frame has (almost) "standardized" column names. To ensure you always get the same column names, you can use [`insight::standardize_names()`](https://easystats.github.io/insight/reference/standardize_names.html), and using that function with the argument `stlye = "broom"` returns column names for the data frame that comply to broom-conventions.

**Comment by strengejacke** [comment]
> it would be just a little easier on us end-users if they could be somewhat standardized, at least as far as possible…

The _easystats_ project aims at a consistent API / function design, where you *should* expect the same column names of returned data frames, or the same argument names (where applicable) etc. We have a rough ["easystats-style-guide"](https://easystats.github.io/easystats/), which we try to adopt consistently across packages.

The sj-packages were developed when I started using/learning R, so there's not a complete consistent design across those packages. But I'm trying to harmonize all sj-packages, and if possible also according to the easystats-style / naming conventions...

**Comment by mbac** [comment]
Hi! `insight::standardize_names()` is _exactly_ what I meant: consider making `style = "broom"`—IMHO, that would make it perfect… 

Again, thanks and congratulations on your great work.
