### ISSUE TITLE
tab_model gives "NA" for conditional R2 value

### ISSUE THREAD

**Issue by robuu** [strengejacke/sjPlot#703]
To report the results of my generalized linear mixed-effects models I have been using the tab_model function. For one of my models everything worked fine, however for my second model a value of 'NA' was provided for the conditional R2. I was wondering what could be the cause of this? 

Many thanks,
Robert

**Comment by strengejacke** [comment]
please try `performance::r2_nakagawa(model)`, which is more verbose and should show you possible messages, warnings or errors.

**Comment by robuu** [comment]
Thanks for the quick reply! I did as you suggested and got the following warning message: can't compute random effect variances. some variance components equal zero. This is strange considering the random effect variances are all greater than 0. But it must have something to do with my model rather than the tab_model package. 

Thanks for your help.

**Comment by strengejacke** [comment]
Do you have a reproducible example? Or at least the output from `summary()`? Usually, this means that some RE variances are at least very close to zero.

**Comment by robuu** [comment]
Here is the summary output. Could it have to do with the singular fit issue? 

`Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) [
glmerMod]
 Family: binomial  ( logit )
Formula: Presabs ~ Matrix_category + logPatch_size * (PA_reclassified +  
    Guild + Forest_dependence + Migration + logHWI + logBodymass) +  
    (1 + logPatch_size | Short_ref) + (1 | Binomial_iucn)
   Data: Threatened
Control: glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e+05))

     AIC      BIC   logLik deviance df.resid 
   690.1    848.2   -311.0    622.1      741 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.3384 -0.4146 -0.1930  0.1618  6.9952 

Random effects:
 Groups        Name          Variance Std.Dev. Corr
 Binomial_iucn (Intercept)   1.3139   1.1463       
 Short_ref     (Intercept)   0.5305   0.7283       
               logPatch_size 0.1395   0.3734   1.00
Number of obs: 775, groups:  Binomial_iucn, 42; Short_ref, 23

Fixed effects:
                                 Estimate Std. Error z value Pr(>|z|)    
(Intercept)                       1.50613    3.73365   0.403 0.686658    
Matrix_category1                  0.70571    0.54743   1.289 0.197352    
Matrix_category2                 -0.23628    0.84916  -0.278 0.780822    
Matrix_category3                 -0.30911    0.74729  -0.414 0.679135    
Matrix_category4                  0.34665    0.56447   0.614 0.539137    
Matrix_category5                  0.37829    1.88089   0.201 0.840601    
Matrix_category6                 -0.34844    0.65696  -0.530 0.595851    
logPatch_size                     0.30504    1.52697   0.200 0.841660    
PA_reclassified2                  1.66965    0.67745   2.465 0.013717 *  
PA_reclassified3                 -1.76627    1.06358  -1.661 0.096777 .  
Guild1                            2.35782    1.92554   1.225 0.220763    
Guild2                           -0.64141    0.89354  -0.718 0.472863    
Guild3                           -2.56399    0.92789  -2.763 0.005723 ** 
Guild4                           -1.94408    1.38050  -1.408 0.159059    
Guild5                            3.35547    0.99637   3.368 0.000758 ***
Forest_dependence2                0.78299    1.11312   0.703 0.481792    
Migration2                        0.81099    1.07216   0.756 0.449401    
logHWI                           -0.39635    2.28043  -0.174 0.862018    
logBodymass                      -1.76936    0.75165  -2.354 0.018574 *  
logPatch_size:PA_reclassified2   -0.13640    0.34611  -0.394 0.693512    
logPatch_size:PA_reclassified3    1.46293    0.50914   2.873 0.004062 ** 
logPatch_size:Guild1             -1.35987    1.03214  -1.318 0.187662    
logPatch_size:Guild2              0.22588    0.42493   0.532 0.595030    
logPatch_size:Guild3              0.83854    0.41199   2.035 0.041818 *  
logPatch_size:Guild4              1.55550    0.66647   2.334 0.019600 *  
logPatch_size:Guild5             -1.14460    0.42449  -2.696 0.007008 ** 
logPatch_size:Forest_dependence2 -0.69323    0.50602  -1.370 0.170702    
logPatch_size:Migration2          0.06923    0.46397   0.149 0.881390    
logPatch_size:logHWI             -0.63680    0.95576  -0.666 0.505234    
logPatch_size:logBodymass         0.73413    0.37258   1.970 0.048792 *  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation matrix not shown by default, as p = 30 > 12.
Use print(x, correlation=TRUE)  or
    vcov(x)        if you need it

convergence code: 0
boundary (singular) fit: see ?isSingular`

**Comment by robuu** [comment]
Here is the summary output (I left out the fixed effects for clarity). Could it have to do with the singular fit issue?

`Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) [
glmerMod]
 Family: binomial  ( logit )
Formula: Presabs ~ Matrix_category + logPatch_size * (PA_reclassified +  
    Guild + Forest_dependence + Migration + logHWI + logBodymass) +  
    (1 + logPatch_size | Short_ref) + (1 | Binomial_iucn)
   Data: Threatened
Control: glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e+05))

     AIC      BIC   logLik deviance df.resid 
   690.1    848.2   -311.0    622.1      741 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.3384 -0.4146 -0.1930  0.1618  6.9952 

Random effects:
 Groups        Name          Variance Std.Dev. Corr
 Binomial_iucn (Intercept)   1.3139   1.1463       
 Short_ref     (Intercept)   0.5305   0.7283       
               logPatch_size 0.1395   0.3734   1.00
Number of obs: 775, groups:  Binomial_iucn, 42; Short_ref, 23

convergence code: 0
boundary (singular) fit: see ?isSingular`

**Comment by strengejacke** [comment]
Ok, it looks indeed like your problem is the singular fit here:

> boundary (singular) fit: see ?isSingular

See https://easystats.github.io/performance/reference/check_singularity.html and `?lme4::isSingular` for details. However, you can probably calculate the R2 manually and try to modify the tolerance for singularity-checks, see details here: https://easystats.github.io/performance/reference/r2_nakagawa.html
