### ISSUE TITLE
Error when I try to run anything

### ISSUE THREAD

**Issue by jnsger** [strengejacke/sjPlot#704]
I get the following error when I try to do anything really:
Error: object ‘standardize_names’ is not exported by 'namespace:insight'

Seems to have happened when I updated from 2.8.5 to 2.8.6. It all works fine on a different machine that I still have the old version of sjPlot on.

Problem machine is running R version 4.0.2.

**Comment by strengejacke** [comment]
I think you need to update the _insight_ package
