### ISSUE TITLE
Rownames do not appear in tab_df (sjPlot)

### ISSUE THREAD

**Issue by lukasla** [strengejacke/sjPlot#705]
The example below is from the help for 'tab_df {sjPlot}'. The only change is that I added the argument 'show.rownames=T', which should add the row names to the table. However, they don't appear. Anyone has an idea what I am doing wrong?

library(sjPlot) #loading the library
data(iris)
tab_df(iris[1:5, ],show.rownames=T)

Thanks a lot! 
Lukas

PS: I coppied this question from my stackoverflow account. Figured that I might get help quicker here. Sorry for double posting!

**Comment by strengejacke** [comment]
Thanks! Row numbers were (intentionally) prevented from being printed as "row names", but I changed this behaviour now.
