### ISSUE TITLE
arguments imply differing number of rows

### ISSUE THREAD

**Issue by bckrick96** [strengejacke/sjPlot#706]
I am having trouble with the plot_model function and have not been able to resolve it. Whenever I attempt to plot the marginal effects of my panel model (two fixed effects), I keep getting this error: 

"Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 7182, 9176" 

If I run a simple lm then this error does not occur and the graph is generated. Any advice to resolve the issue.

**Comment by strengejacke** [comment]
Do you have a reproducible example?
