### ISSUE TITLE
sjp.int not working

### ISSUE THREAD

**Issue by soominoh1** [strengejacke/sjPlot#707]
Hi! I'm a big fan of your package - thank you - and wanted to ask how to use sjp.int with your package. Per this page (http://www.strengejacke.de/sjPlot/reference/sjp.int.html) it seems like sjp.int was released under version 2.4.1; was this removed or renamed? Further, I tried installing v 2.4.1 using tgz from the archive but it says "package has non-zero exit status" so I wasn't able to use the backdoor to get it to work.  Your response would be greatly appreciated. Many thanks!

**Comment by strengejacke** [comment]
Hi, all these functions are re-implemented in `plot_model()`. See [this vignette](https://strengejacke.github.io/sjPlot/articles/plot_interactions.html), or maybe even better, directly use the [ggeffects-package](https://strengejacke.github.io/ggeffects).

**Comment by soominoh1** [comment]
Thanks for the reply. It doesn't work with plm fixed effects though, does it? Or am I doing something wrong? If you could please help clarify, I'd be ever so grateful! (See here for a Stackoverflow post on how plot_model does not work with fixed effects plm: https://stackoverflow.com/questions/64892622/plotting-interaction-terms-from-fixed-effects-models-plm)

**Comment by strengejacke** [comment]
Maybe related to https://github.com/strengejacke/ggeffects/issues/121?
