### ISSUE TITLE
What is the σ2 reported by sjPlot for Random Effects?

### ISSUE THREAD

**Issue by skanskan** [strengejacke/sjPlot#708]
Hello.

I have used sjPlot with a glmmTMB logistic model and the random effects output is:

```
Random Effects
σ2	3.30
τ00 ID:City	9.99
τ00 City	1.54
```
τ00 City is the variance of the variable City
τ00 ID:City is the variance of the interaction ID:City

But what is σ2? The remaining variance?
How can I calculate the residuals?
Using residuals(mymodel) produce an out of memory error.

How can I report σ2 and τ00City on a paper relating it to the odds ratio or on the proportion of the total variance explained by City?

**Comment by strengejacke** [comment]
The variance components are described here:
https://easystats.github.io/insight/reference/get_variance.html
