### ISSUE TITLE
Use tab_model with Rmarkdown for PDF

### ISSUE THREAD

**Issue by kambanane** [strengejacke/sjPlot#712]
This is likely my own issue, but....

How do I use tab_model in an Rmarkdown document that is exported to a PDF?

When I render the PDF I expect a nice, formatted table like I see in the preview window in Rstudio, but what I see is a long string of text. 

Here is some reproducible code. 

---
title: "test"
author: "me"
date: "2020/12/6"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sjPlot)
```

## A table

```{r cars}
tab_model(lm(mpg~cyl, data=mtcars))



```

**Comment by strengejacke** [comment]
`tab_model()` generates HTML output only, so rendering for PDF does not work. But within the [easystats-project](https://easystats.github.io/easystats/), we are currently designing an API that helps us to export tables into markdown, which then again render nicely in PDF. See for instance here: https://cran.r-project.org/web/packages/parameters/vignettes/model_parameters_formatting.html#formatting-the-parameters-table-in-markdown

That said, "simple" parameters tables can be used for markdown tables. Additional information that is provided in `tab_model()`, like residual standard error, or number of observations etc.,  is planned for the [report-package](https://easystats.github.io/report), which may replace `sjPlot::tab_model()` in the future.

**Comment by kambanane** [comment]
Thank you, this was helpful.

**Comment by strengejacke** [comment]
We have added more output options in our [easystats ecosystem](https://easystats.github.io/easystats), so you can now print summary tables as HTML or markdown formart, which both should render nicely to PDF. See examples here:
https://easystats.github.io/parameters/articles/model_parameters_formatting.html

This requires updating the easystats-packages from GitHub, or you wait 2-3 weeks, until we updated all of them on CRAN.

Your approach (in rmarkdown-docs) would be:

```r
library(parameters)
model <- lm(mpg~cyl, data=mtcars)
mp <- model_parameters(model)
print_html(mp)
print_md(mp)
```

**Comment by gorkang** [comment]
In case is useful to someone, I created a [Github repo](https://github.com/gorkang/html2latex/) with a couple functions that can help you convert the sjPlot::tab_model() html files to tex/pdf and showing how to insert the resulting tex file in a Rmd that renders as pdf.

**Comment by kapsner** [comment]
In case someone is interested, I have created the [sjtable2df](https://github.com/kapsner/sjtable2df) R package for converting outputs from `sjPlot::tab_model()` and `sjPlot::tab_xtab()` to R `data.frame`, `data.table` or `knitr::kable()` objects. 
However, as I just saw, there might not be much benefit from `sjtable2df` compared to `parameters` from the easystats ecosystem...
