### ISSUE TITLE
type = "std" argument has no effect on forest plots

### ISSUE THREAD

**Issue by robbwh** [strengejacke/sjPlot#716]
Hello, 

`plot_model(linear_model)`

Yields the exact sample plot as 

`plot_model(linear_model, type = "std")`

It seems like the betas are not being standardized
sjPlot throws no errors when I run either command. Anything obvious that I am missing? 

I am loading libraries in this order

`library(sjstats)`
`library(sjPlot)`
`library(sjmisc)`
`library(ggplot2)`

Thank you

**Comment by strengejacke** [comment]
Can't reproduce, do you have a reproducible example?

``` r
m <- lm(Sepal.Length ~ Sepal.Width + Petal.Length, data = iris)
sjPlot::plot_model(m)
```

![](https://i.imgur.com/BaFiMQP.png)

``` r
sjPlot::plot_model(m, type = "std")
```

![](https://i.imgur.com/xmVfgEL.png)

<sup>Created on 2020-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by robbwh** [comment]
Hello, those set of commands work for me. So that's good.

Here is where it doesn't work for me: 

I think it might be that Sjplot doesn't support when variables defined in the linear model using $ syntax.

`linear_model<-lm(epoch1$bld.c.hgb~epoch1$sex.factor+epoch1$education,na.action = na.omit,data=epoch1)`

`plot_model(linear_model)`

![871d7eb5-11af-4925-8f4d-42b8b660af8f](https://user-images.githubusercontent.com/39274562/102234574-0cd2a200-3eb7-11eb-9228-679d0fde6022.png)


`plot_model(linear_model, std.est = "std")`

![457fd3f7-219d-4972-b31f-3cab6b57606a](https://user-images.githubusercontent.com/39274562/102234640-1956fa80-3eb7-11eb-8892-6344c6e24cdc.png)

**Comment by strengejacke** [comment]
If you provide the data-argument, leave out the `epoch1$` in the formula:

```r
linear_model<-lm(bld.c.hgb~sex.factor+education, na.action = na.omit, data=epoch1)
```

Does this work?

**Comment by robbwh** [comment]
Yes it does, thanks. Doesn't work if I use $ and don't provide the data argument though. Anyway, much appreciated!

**Comment by strengejacke** [comment]
> Doesn't work if I use $ and don't provide the data argument though.

Yes, I opened an issue (https://github.com/easystats/effectsize/issues/238) in the effectsize-repo, which does all the standardization. Maybe we find a solution.
