### ISSUE TITLE
model_plot only provides a subset of predicted values

### ISSUE THREAD

**Issue by rlwelicky** [strengejacke/sjPlot#717]
Hello,

I am using the below model: 
glu2<-glmmTMB(X~ Y+ Z + scale(year) +(1|sites)  + sl, family = "gaussian", data= compiled)
 
All variables are continuous/numeric except site. The model runs without any issues using my full dataset.

When I implement, plot_model(glu2, type = "pred", terms = "year [all]", full.data = TRUE, show.data = TRUE), I only get a plot that provides 13 predicted values, spanning 1950-2010.  My data span 1930-2018 and I want a predicted value per input value. 

I have searched for similar problems via google, but have not come across any solutions. I am unsure if this function is acting correctly and why it would not provide a predicted value per input value. Any help would be greatly appreciated!

**Comment by strengejacke** [comment]
Can you please try:

```r
library(ggeffects)
pr <- ggpredict(glu2, "year [all]")
plot(pr)
as.data.frame(pr)
```

It might be that this is just an issue of labelling the axis, but I can't say for sure without a reproducible example. So please try the above code and look if it is just a label-issue, or a bug.

**Comment by rlwelicky** [comment]
Hi there, thanks for your quick response! 

I used your code and I run into the same issue. The dataframe only includes 13 values spanning 1950-2008. My complete dataset span 1930-2018 and has 43 values/rows.

**Comment by rlwelicky** [comment]
Hi Daniel, I was wondering if you had any thoughts on a work around for this bug or alternate packages or base code to achieve the same plots? Any input would be greatly appreciated. Thank you!

**Comment by strengejacke** [comment]
I think I need a reproducible example here to find a way how to fix this error.
