### ISSUE TITLE
transform = "plogits" not working for plot_models (does work for plot_model singular)

### ISSUE THREAD

**Issue by hjbunting** [strengejacke/sjPlot#719]
I am new to github so hope I am getting this correct... 

I have run a series of logit models that are stored within a list. When coming to plot them, the transform argument doesn't work and it always plots Odds Ratios. However there is no error code. I tried it on a singular model, using plot_model, and the transformation worked. Would be great to have this functionality in plot_models.

(Have not supplied reprex due to no error message, but can do if needed).

**Comment by strengejacke** [comment]
Do you have a reproducible example? Works for me:

``` r
library(sjPlot)
model <- glm(vs ~ wt + mpg, data = mtcars, family = "binomial")
plot_model(model)
```

![](https://i.imgur.com/OJtIQXW.png)

``` r
plot_model(model, transform = "plogis")
```

![](https://i.imgur.com/nCSdHVp.png)

<sup>Created on 2021-01-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
