### ISSUE TITLE
tab_model argument p.val not working with "ml1" and "betwithin" in a glmer model

### ISSUE THREAD

**Issue by gorkang** [strengejacke/sjPlot#723]
Dear @strengejacke , tab_model in a glmer model works when p.val is set to "wald" but does not work when set to "ml1" or "betwithin". See reprex below.

The error is:

> Error in match.arg(df_method, choices = c("wald", "ml1", "betwithin", : 'arg' should be one of "wald", "ml1", "betwithin", "satterthwaite", "kenward"

This may be related to #621 ?

Thanks for the help.

``` r
# remotes::install_github("strengejacke/sjPlot")

library(lme4)
#> Loading required package: Matrix

model1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
                data = cbpp, family = binomial)


sjPlot::tab_model(model1, p.val = "wald")
```

<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
cbind(incidence,size-incidence)
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Odds Ratios
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.25
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.16 – 0.39
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
period \[2\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.37
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.20 – 0.67
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
period \[3\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.32
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.17 – 0.61
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
period \[4\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.21
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.09 – 0.47
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td colspan="4" style="font-weight:bold; text-align:left; padding-top:.8em;">
Random Effects
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
σ<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
3.29
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
τ<sub>00</sub> <sub>herd</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.41
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
ICC
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.11
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
N <sub>herd</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
15
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
56
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
Marginal R<sup>2</sup> / Conditional R<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.085 / 0.187
</td>
</tr>
</table>

``` r
sjPlot::tab_model(model1, p.val = "ml1")
#> Error in match.arg(df_method, choices = c("wald", "ml1", "betwithin", : 'arg' should be one of "wald", "ml1", "betwithin", "satterthwaite", "kenward"
sjPlot::tab_model(model1, p.val = "betwithin")
#> Error in match.arg(df_method, choices = c("wald", "ml1", "betwithin", : 'arg' should be one of "wald", "ml1", "betwithin", "satterthwaite", "kenward"
sjPlot::tab_model(model1, p.val = "satterthwaite")
#> Warning: 'satterthwaite'-degrees of freedoms are only available for linear mixed
#> models.
```

<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
cbind(incidence,size-incidence)
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Odds Ratios
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.25
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.16 – 0.39
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
period \[2\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.37
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.20 – 0.67
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
period \[3\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.32
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.17 – 0.61
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
period \[4\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.21
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.09 – 0.47
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td colspan="4" style="font-weight:bold; text-align:left; padding-top:.8em;">
Random Effects
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
σ<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
3.29
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
τ<sub>00</sub> <sub>herd</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.41
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
ICC
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.11
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
N <sub>herd</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
15
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
56
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
Marginal R<sup>2</sup> / Conditional R<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.085 / 0.187
</td>
</tr>
</table>
<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.3 (2020-10-10)
#>  os       Ubuntu 20.04.1 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Atlantic/Canary             
#>  date     2021-01-04                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package      * version date       lib source        
#>  assertthat     0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
#>  backports      1.2.1   2020-12-09 [1] CRAN (R 4.0.3)
#>  bayestestR     0.8.0   2020-12-05 [1] CRAN (R 4.0.3)
#>  boot           1.3-25  2020-04-26 [4] CRAN (R 4.0.0)
#>  broom          0.7.3   2020-12-16 [1] CRAN (R 4.0.3)
#>  callr          3.5.1   2020-10-13 [1] CRAN (R 4.0.3)
#>  cli            2.2.0   2020-11-20 [1] CRAN (R 4.0.3)
#>  coda           0.19-4  2020-09-30 [1] CRAN (R 4.0.2)
#>  codetools      0.2-18  2020-11-04 [4] CRAN (R 4.0.3)
#>  colorspace     2.0-0   2020-11-11 [1] CRAN (R 4.0.3)
#>  crayon         1.3.4   2017-09-16 [1] CRAN (R 4.0.2)
#>  desc           1.2.0   2018-05-01 [1] CRAN (R 4.0.2)
#>  devtools       2.3.2   2020-09-18 [1] CRAN (R 4.0.2)
#>  digest         0.6.27  2020-10-24 [1] CRAN (R 4.0.3)
#>  dplyr          1.0.2   2020-08-18 [1] CRAN (R 4.0.2)
#>  effectsize     0.4.1   2020-12-07 [1] CRAN (R 4.0.3)
#>  ellipsis       0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
#>  emmeans        1.5.3   2020-12-09 [1] CRAN (R 4.0.3)
#>  estimability   1.3     2018-02-11 [1] CRAN (R 4.0.2)
#>  evaluate       0.14    2019-05-28 [1] CRAN (R 4.0.2)
#>  fansi          0.4.1   2020-01-08 [1] CRAN (R 4.0.2)
#>  fs             1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
#>  generics       0.1.0   2020-10-31 [1] CRAN (R 4.0.3)
#>  ggeffects      1.0.1   2020-12-14 [1] CRAN (R 4.0.3)
#>  ggplot2        3.3.3   2020-12-30 [1] CRAN (R 4.0.3)
#>  glue           1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
#>  gtable         0.3.0   2019-03-25 [1] CRAN (R 4.0.2)
#>  highr          0.8     2019-03-20 [1] CRAN (R 4.0.2)
#>  htmltools      0.5.0   2020-06-16 [1] CRAN (R 4.0.2)
#>  insight        0.11.1  2020-12-08 [1] CRAN (R 4.0.3)
#>  knitr          1.30    2020-09-22 [1] CRAN (R 4.0.2)
#>  lattice        0.20-41 2020-04-02 [4] CRAN (R 4.0.0)
#>  lifecycle      0.2.0   2020-03-06 [1] CRAN (R 4.0.2)
#>  lme4         * 1.1-26  2020-12-01 [1] CRAN (R 4.0.3)
#>  magrittr       2.0.1   2020-11-17 [1] CRAN (R 4.0.3)
#>  MASS           7.3-53  2020-09-09 [4] CRAN (R 4.0.2)
#>  Matrix       * 1.3-0   2020-12-22 [4] CRAN (R 4.0.3)
#>  memoise        1.1.0   2017-04-21 [1] CRAN (R 4.0.2)
#>  minqa          1.2.4   2014-10-09 [1] CRAN (R 4.0.2)
#>  modelr         0.1.8   2020-05-19 [1] CRAN (R 4.0.2)
#>  multcomp       1.4-15  2020-11-14 [1] CRAN (R 4.0.3)
#>  munsell        0.5.0   2018-06-12 [1] CRAN (R 4.0.2)
#>  mvtnorm        1.1-1   2020-06-09 [1] CRAN (R 4.0.2)
#>  nlme           3.1-151 2020-12-10 [4] CRAN (R 4.0.3)
#>  nloptr         1.2.2.2 2020-07-02 [1] CRAN (R 4.0.2)
#>  parameters     0.10.1  2020-12-08 [1] CRAN (R 4.0.3)
#>  performance    0.6.1   2020-12-09 [1] CRAN (R 4.0.3)
#>  pillar         1.4.7   2020-11-20 [1] CRAN (R 4.0.3)
#>  pkgbuild       1.2.0   2020-12-15 [1] CRAN (R 4.0.3)
#>  pkgconfig      2.0.3   2019-09-22 [1] CRAN (R 4.0.2)
#>  pkgload        1.1.0   2020-05-29 [1] CRAN (R 4.0.2)
#>  prettyunits    1.1.1   2020-01-24 [1] CRAN (R 4.0.2)
#>  processx       3.4.5   2020-11-30 [1] CRAN (R 4.0.3)
#>  ps             1.5.0   2020-12-05 [1] CRAN (R 4.0.3)
#>  purrr          0.3.4   2020-04-17 [1] CRAN (R 4.0.2)
#>  R6             2.5.0   2020-10-28 [1] CRAN (R 4.0.3)
#>  Rcpp           1.0.5   2020-07-06 [1] CRAN (R 4.0.2)
#>  remotes        2.2.0   2020-07-21 [1] CRAN (R 4.0.2)
#>  rlang          0.4.10  2020-12-30 [1] CRAN (R 4.0.3)
#>  rmarkdown      2.6     2020-12-14 [1] CRAN (R 4.0.3)
#>  rprojroot      2.0.2   2020-11-15 [1] CRAN (R 4.0.3)
#>  sandwich       3.0-0   2020-10-02 [1] CRAN (R 4.0.2)
#>  scales         1.1.1   2020-05-11 [1] CRAN (R 4.0.2)
#>  sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
#>  sjlabelled     1.1.7   2020-09-24 [1] CRAN (R 4.0.2)
#>  sjmisc         2.8.5   2020-05-28 [1] CRAN (R 4.0.2)
#>  sjPlot         2.8.6   2020-10-28 [1] CRAN (R 4.0.3)
#>  sjstats        0.18.0  2020-05-06 [1] CRAN (R 4.0.2)
#>  snakecase      0.11.0  2019-05-25 [1] CRAN (R 4.0.2)
#>  statmod        1.4.35  2020-10-19 [1] CRAN (R 4.0.3)
#>  stringi        1.5.3   2020-09-09 [1] CRAN (R 4.0.2)
#>  stringr        1.4.0   2019-02-10 [1] CRAN (R 4.0.2)
#>  survival       3.2-7   2020-09-28 [4] CRAN (R 4.0.2)
#>  testthat       3.0.1   2020-12-17 [1] CRAN (R 4.0.3)
#>  TH.data        1.0-10  2019-01-21 [1] CRAN (R 4.0.2)
#>  tibble         3.0.4   2020-10-12 [1] CRAN (R 4.0.3)
#>  tidyr          1.1.2   2020-08-27 [1] CRAN (R 4.0.2)
#>  tidyselect     1.1.0   2020-05-11 [1] CRAN (R 4.0.2)
#>  usethis        2.0.0   2020-12-10 [1] CRAN (R 4.0.3)
#>  vctrs          0.3.6   2020-12-17 [1] CRAN (R 4.0.3)
#>  withr          2.3.0   2020-09-22 [1] CRAN (R 4.0.2)
#>  xfun           0.19    2020-10-30 [1] CRAN (R 4.0.3)
#>  xtable         1.8-4   2019-04-21 [1] CRAN (R 4.0.2)
#>  yaml           2.2.1   2020-02-01 [1] CRAN (R 4.0.2)
#>  zoo            1.8-8   2020-05-02 [1] CRAN (R 4.0.2)
#> 
#> [1] /home/emrys/R/x86_64-pc-linux-gnu-library/4.0
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

**Comment by strengejacke** [comment]
Thanks, should be fixed.
