### ISSUE TITLE
if (fam.info$is_linear) transform <- NULL else transform <- "exp" error

### ISSUE THREAD

**Issue by kambanane** [strengejacke/sjPlot#733]
I am trying to use this code:

library(tidyverse)  # data manipulation and visualization
library(modelr)     # provides easy pipeline modeling functions
library(broom)      # helps to tidy up model outputs

(default <- as_tibble(ISLR::Default))

fit1 <- glm(student ~ balance, data=default, family = "binomial")
fit2 <- glm(student ~ balance +income, data=default, family = "binomial")

tab_model(fit1, fit2, type="latex")

and get this error:

" if (fam.info$is_linear) transform <- NULL else transform <- "exp"  errorー: "

any ideas?

**Comment by strengejacke** [comment]
Yes, there's no `type`-argument, as only HTML is produced. Just omit that argument and it should work. That said, we have a similar function now in the _parameters_ package, called [`compare_parameters()`](https://easystats.github.io/parameters/reference/compare_parameters.html), which has several "templates" for the table layouts, and which produces tables in text, markdown or HTML format. Hence, this should render well for PDF documents when using rmarkdown. See examples [here](https://easystats.github.io/parameters/articles/model_parameters_formatting.html).
