### ISSUE TITLE
No variable labels for predictors 

### ISSUE THREAD

**Issue by SilMerAl** [strengejacke/sjPlot#736]
sjPlot and tab_model retrieve the labels for outcome variables, and for factor levels. However the names of the predictor variables are in it's raw form despite having a variable label (confirmed by the fact that get_label() and arsenal::taleby() do retrieve these labels). I am using lme4::glmer() and lmer()to create the models.

**Comment by strengejacke** [comment]
Not sure what you mean, can you give an example?

Here in the vignette, variable and value labels are shown:
https://strengejacke.github.io/sjPlot/articles/tab_model_estimates.html

**Comment by SilMerAl** [comment]
In trying to make a reproducible example, I discovered that my problem was assigning labels before converting character variables to factors. When reversing the order of these, the labels work beautifully. 

Thank you for all your great work, it is very much appreciated!

**Comment by strengejacke** [comment]
Great, glad to hear it works!
