### ISSUE TITLE
tab_model: get "Error: 'is_effectsize_name' is not an exported object from 'namespace:effectsize'"

### ISSUE THREAD

**Issue by saaralonbarkat** [strengejacke/sjPlot#741]
When I try to create any regression table using tab_model, I receive the following error: 

Error: 'is_effectsize_name' is not an exported object from 'namespace:effectsize'

see example below: 

```{r}
m1 <- lm(barthtot ~ c160age + c12hour + c161sex + c172code, data = efc)
m2 <- lm(neg_c_7 ~ c160age + c12hour + c161sex + e17age, data = efc)
tab_model(m1)
```

I have tried updating lots of packages but still didn't solve this issue. Any idea of why it is happening?

Thanks, 

Saar

**Comment by strengejacke** [comment]
You can try to update following packages, than this issue _should_ be resolved:

- sjPlot (to 2.8.7)
- insight (to 0.13.1)
- parameters (to 0.12.0)
- effectsize (to 0.4.3)

**Comment by saaralonbarkat** [comment]
Thank you very much. You made my day!

The issue was with `effectsize` package.
