### ISSUE TITLE
How are df determined in tab_model when you set p.val = "wald"?

### ISSUE THREAD

**Issue by hj1032** [strengejacke/sjPlot#750]
I created a multilevel model using lmer and displayed the results using tab_model. 

In tab_model, if you use the Wald method, how exactly are the df determined?  I can't seem to find this information anywhere.  In the documentation it only says "Use df.method = "wald" for a faster, but less precise computation."

**Comment by strengejacke** [comment]
Thanks, I have revised the docs:

Use `df.method = "wald"` for a faster, but less precise computation. This will use the residual degrees of freedom (as returned by `df.residual()`) for linear mixed models, and `Inf` degrees if freedom for all other model families.
