### ISSUE TITLE
Error in match.arg(rotation) : 'arg' should be one of “promax”, “varimax”

### ISSUE THREAD

**Issue by AriFarugie** [strengejacke/sjPlot#752]
I got following error message, when I conduct a factor analysis with `tab_fa()` and using the rotation "oblimin".

My code looks like this:

`library(GPArotation)`

`tab_fa(df,  nmbr.fctr = 3, fctr.load.tlrn = .3, method = "pa", rotation = "oblimin")`

When I conduct this, I get this error message : Error in match.arg(rotation) : 'arg' should be one of “promax”, “varimax”

It would be nice to know what I am doing wrong.

Thank you in advance!

**Comment by strengejacke** [comment]
Should be possible now, but I recommend the [_parameters_](https://easystats.github.io/parameters/reference/principal_components.html) package, since it offers more utilities and options. `tab_fa()` and `tab_pca()` did not gain much attention from me the last time...

**Comment by strengejacke** [comment]
(It's not that those return "incorrect" results, rather they offer less options than the functions in the parameters package).

**Comment by AriFarugie** [comment]
THANK YOU A LOT!
