### ISSUE TITLE
New error in calling library(sjPlot)

### ISSUE THREAD

**Issue by teindor** [strengejacke/sjPlot#769]
Hello,
I'm using sjPlot quite often (especially tab_model). Yesterday I tried to load the package using library(sjPlot) and got this message: 
Error: package or namespace load failed for ‘sjPlot’:
 object ‘data_partition’ is not exported by 'namespace:parameters'

I tied to reinstall it from GitHub and the regular install.packages and I get a message stating that the package has non-zero exit status

Please advise
Great package!
Tsachi

**Comment by strengejacke** [comment]
Hi Tsachi, sorry for responding so late. If you update all packages from CRAN, using `install.packages(..., dependencies = TRUE)`, that should fix the error.

**Comment by joachimstarck** [comment]
Hi, 
I also have this problem - 
**library(sjPlot)
Error: package or namespace load failed for ‘sjPlot’:
 object ‘parameters_table’ is not exported by 'namespace:insight'**

I've tried re-install as above and re-installing "insight". I'm very fund of your tab_model and plot_model so I really would like this to work.

**Comment by strengejacke** [comment]
I suggest following steps:

1. `install.packages("easystats", dependencies = TRUE)`
2. `easystats::install_latest()`
3. `install.packages("sjPlot", dependencies = TRUE)`

That should resolve these issues.
