### ISSUE TITLE
SjPlot: tab_model() Don't show quadratic/polynomial terms 

### ISSUE THREAD

**Issue by ClemensHut** [strengejacke/sjPlot#776]
Hi all, 
is there any way to hide the quadratic/polynomial terms in the regression output? 
It seems to show them by default which adds tons of rows, obviously. 
Thanks so much! 
Best
Clemens

**Comment by HeatherUrry** [comment]
@ClemensHut did you try using the terms or rm.terms argument? 

```
library(sjPlot)

# load mtcars data
data(mtcars)

# factorize cyl variable
mtcars$cyl.f <- factor(mtcars$cyl, ordered=TRUE)

# set polynomial contrast for factorized cyl
contrasts(mtcars$cyl.f) = contr.poly(3)

# run linear regression model
lm <- lm(mpg ~ cyl.f, data=mtcars)

# default table with all terms
tab_model(lm)

# table that removes the quadratic term
tab_model(lm, rm.terms="cyl.f.Q")
```

**Comment by strengejacke** [comment]
The next update will include `keep` and `drop` arguments, that are a bit more flexible and allow you to define regular expression patterns like this:

```r
library(sjPlot)

# load mtcars data
data(mtcars)

# factorize cyl variable
mtcars$cyl.f <- factor(mtcars$cyl, ordered=TRUE)

# set polynomial contrast for factorized cyl
contrasts(mtcars$cyl.f) = contr.poly(3)

# run linear regression model
m <- lm(mpg ~ cyl.f, data=mtcars)

# include all polynomials
tab_model(m, keep ="\\.f")

# remove all polynomials
tab_model(m, drop ="\\.f")
```

**Comment by munoztd0** [comment]
I get this error when running this exact snippet:

![image](https://user-images.githubusercontent.com/43644805/146425482-e0f73c45-adec-4a5c-a576-41f45a7af1cd.png)

**Comment by strengejacke** [comment]
Are all packages updated? This should include latest versions of sjPlot, parameters and insight (all from CRAN).

**Comment by munoztd0** [comment]
Updating actually removed the errors (thanks for that!) but now it just outputs the same table with keep or drop .. ?

**Comment by strengejacke** [comment]
hm... this works for me (tables are rendered properly outside this reprex):

``` r
library(sjPlot)
#> Install package "strengejacke" from GitHub (`devtools::install_github("strengejacke/strengejacke")`) to load all sj-packages at once!

# load mtcars data
data(mtcars)

# factorize cyl variable
mtcars$cyl.f <- factor(mtcars$cyl, ordered=TRUE)

# set polynomial contrast for factorized cyl
contrasts(mtcars$cyl.f) = contr.poly(3)

# run linear regression model
m <- lm(mpg ~ cyl.f, data=mtcars)

# include all polynomials
tab_model(m, keep ="\\.f")
```

<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
mpg
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
cyl f \[linear\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-8.18
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-10.05 – -6.30
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>\<0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
cyl f \[quadratic\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.93
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.38 – 3.24
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.416
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
32
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.732 / 0.714
</td>
</tr>
</table>

``` r
# remove all polynomials
tab_model(m, drop ="\\.f")
```

<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
mpg
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
20.50
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
19.29 – 21.72
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>\<0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
32
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.732 / 0.714
</td>
</tr>
</table>

<sup>Created on 2021-12-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


Can you post your session info?

**Comment by munoztd0** [comment]
Thanks for the help here you have

``` r
# Install package "strengejacke" from GitHub (`devtools::install_github("strengejacke/strengejacke")`) to load all sj-packages at once!
#   
library(strengejacke)
#> # Attaching packages
#> ✔ ggeffects  1.1.1    ✔ sjlabelled 1.1.8 
#> ✔ sjmisc     2.8.9    ✔ sjstats    0.18.1
#> ✔ sjPlot     2.8.10   ✔ esc        0.5.1
  
# load mtcars data
  
data(mtcars)



# factorize cyl variable

mtcars$cyl.f <- factor(mtcars$cyl, ordered=TRUE)



# set polynomial contrast for factorized cyl

contrasts(mtcars$cyl.f) = contr.poly(3)



# run linear regression model

m <- lm(mpg ~ cyl.f, data=mtcars)



# include all polynomials

tab_model(m, keep ="\\.f")
```

<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
mpg
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
20.50
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
19.29 – 21.72
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
cyl.f \[linear\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-8.18
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-10.05 – -6.30
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
cyl.f \[quadratic\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.93
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.38 – 3.24
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.416
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
32
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.732 / 0.714
</td>
</tr>
</table>

``` r

tab_model(m, drop ="\\.f", file = "drop")
```

<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
mpg
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
20.50
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
19.29 – 21.72
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
cyl.f \[linear\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-8.18
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-10.05 – -6.30
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
cyl.f \[quadratic\]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.93
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.38 – 3.24
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.416
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
32
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.732 / 0.714
</td>
</tr>
</table>

<sup>Created on 2021-12-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

> R version 4.0.1 (2020-06-06)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Pop!_OS 21.04
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.13.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=fr_CH.UTF-8       
>  [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=fr_CH.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=fr_CH.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
> [10] LC_TELEPHONE=C             LC_MEASUREMENT=fr_CH.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] esc_0.5.1          sjPlot_2.8.10      sjstats_0.18.1     sjmisc_2.8.9       sjlabelled_1.1.8  
> [6] ggeffects_1.1.1    strengejacke_0.5.0
> 
> loaded via a namespace (and not attached):
>  [1] httr_1.4.2        pkgload_1.2.1     tidyr_1.1.3       splines_4.0.1     modelr_0.1.8     
>  [6] datawizard_0.2.1  assertthat_0.2.1  remotes_2.4.2     bayestestR_0.11.5 sessioninfo_1.1.1
> [11] pillar_1.6.1      backports_1.4.1   lattice_0.20-41   glue_1.6.0        snakecase_0.11.0 
> [16] rvest_1.0.0       minqa_1.2.4       colorspace_2.0-2  sandwich_3.0-1    Matrix_1.2-18    
> [21] pkgconfig_2.0.3   devtools_2.4.2    broom_0.7.10      purrr_0.3.4       xtable_1.8-4     
> [26] mvtnorm_1.1-3     scales_1.1.1      processx_3.5.2    lme4_1.1-27       emmeans_1.7.1-1  
> [31] tibble_3.1.2      ggplot2_3.3.3     generics_0.1.1    usethis_2.0.1     ellipsis_0.3.2   
> [36] TH.data_1.1-0     cachem_1.0.6      withr_2.4.3       cli_3.1.0         survival_3.1-12  
> [41] magrittr_2.0.1    crayon_1.4.2      effectsize_0.4.5  memoise_2.0.0     estimability_1.3 
> [46] ps_1.6.0          fs_1.5.2          fansi_0.5.0       nlme_3.1-148      MASS_7.3-51.6    
> [51] xml2_1.3.3        pkgbuild_1.2.0    tools_4.0.1       prettyunits_1.1.1 lifecycle_1.0.0  
> [56] multcomp_1.4-17   stringr_1.4.0     munsell_0.5.0     callr_3.7.0       compiler_4.0.1   
> [61] rlang_0.4.12      grid_4.0.1        nloptr_1.2.2.3    parameters_0.14.0 rstudioapi_0.13  
> [66] boot_1.3-25       testthat_3.0.2    gtable_0.3.0      codetools_0.2-16  DBI_1.1.2        
> [71] curl_4.3.2        R6_2.5.1          zoo_1.8-9         knitr_1.37        dplyr_1.0.6      
> [76] performance_0.7.2 fastmap_1.1.0     utf8_1.2.2        rprojroot_2.0.2   insight_0.14.5   
> [81] desc_1.4.0        stringi_1.7.6     Rcpp_1.0.7        vctrs_0.3.8       xfun_0.29        
> [86] tidyselect_1.1.1  coda_0.19-4

**Comment by strengejacke** [comment]
ok, looks like you need to update your packages. some of them (like _parameters_) are not up to date, that seems to be the reason why it doesn't work.

**Comment by munoztd0** [comment]
Hello, I updated all my packages: 

Rerun the snippet (with parameters_0.15.0)... and I get the same thing still..

Maybe a Linux rleated bug ?

`R version 4.0.1 (2020-06-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 21.04

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.13.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=fr_CH.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=fr_CH.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=fr_CH.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_CH.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] esc_0.5.1          sjPlot_2.8.10      sjstats_0.18.1     sjmisc_2.8.9       sjlabelled_1.1.8   ggeffects_1.1.1    strengejacke_0.5.0

loaded via a namespace (and not attached):
 [1] httr_1.4.2        pkgload_1.2.4     tidyr_1.1.4       splines_4.0.1     modelr_0.1.8      datawizard_0.2.1  assertthat_0.2.1  remotes_2.4.2    
 [9] bayestestR_0.11.5 sessioninfo_1.2.2 pillar_1.6.4      backports_1.4.1   lattice_0.20-41   glue_1.6.0        snakecase_0.11.0  rvest_1.0.2      
[17] minqa_1.2.4       colorspace_2.0-2  sandwich_3.0-1    Matrix_1.2-18     pkgconfig_2.0.3   devtools_2.4.3    broom_0.7.10      purrr_0.3.4      
[25] xtable_1.8-4      mvtnorm_1.1-3     scales_1.1.1      processx_3.5.2    lme4_1.1-27.1     emmeans_1.7.1-1   tibble_3.1.6      generics_0.1.1   
[33] ggplot2_3.3.5     usethis_2.1.5     ellipsis_0.3.2    TH.data_1.1-0     cachem_1.0.6      withr_2.4.3       cli_3.1.0         survival_3.1-12  
[41] magrittr_2.0.1    crayon_1.4.2      effectsize_0.5    memoise_2.0.1     estimability_1.3  ps_1.6.0          fs_1.5.2          fansi_0.5.0      
[49] nlme_3.1-148      MASS_7.3-51.6     xml2_1.3.3        pkgbuild_1.3.1    tools_4.0.1       prettyunits_1.1.1 lifecycle_1.0.1   multcomp_1.4-17  
[57] stringr_1.4.0     munsell_0.5.0     callr_3.7.0       packrat_0.7.0     compiler_4.0.1    rlang_0.4.12      grid_4.0.1        nloptr_1.2.2.3   
[65] parameters_0.15.0 boot_1.3-25       testthat_3.1.1    gtable_0.3.0      codetools_0.2-16  curl_4.3.2        DBI_1.1.2         R6_2.5.1         
[73] zoo_1.8-9         knitr_1.37        dplyr_1.0.7       performance_0.8.0 fastmap_1.1.0     utf8_1.2.2        rprojroot_2.0.2   insight_0.14.5   
[81] desc_1.4.0        stringi_1.7.6     Rcpp_1.0.7        vctrs_0.3.8       xfun_0.29         tidyselect_1.1.1  coda_0.19-4  `
