### ISSUE TITLE
tab_model: missing closing </tr> tag

### ISSUE THREAD

**Issue by babayoshihiko** [strengejacke/sjPlot#777]
I am using sjPlot 2.8.8.

The closing `</tr>` is missing when I build a bookdown with tab_model. This is treated well by browsers, but not by epub readers.

The output (http://babayoshihiko.ddns.net/RStudioCloud/%E3%83%A9%E3%83%B3%E3%83%80%E3%83%A0%E5%8C%96%E6%AF%94%E8%BC%83%E8%A9%A6%E9%A8%93.html) produces:

```
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
ICC
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.93
</td>
<tr>
```

**Comment by babayoshihiko** [comment]
Does this code cause the issue?

html_print.R: 482-484

    s_css <- "tdata leftalign summary"
    page.content <- paste0(page.content, sprintf("\n  <tr>\n    <td class=\"%s\">&sigma;<sup>2</sup></td>\n", s_css))
    s_css <- summary.css

**Comment by strengejacke** [comment]
Yes, looks like that could be the issue. I have added a `</tr>` now, I hope this fixes this issue.
