### ISSUE TITLE
plot_model() Asymmetrical CI levels

### ISSUE THREAD

**Issue by LauFernanda** [strengejacke/sjPlot#778]
I'm using plot_model() to plot the Average Marginal Effects in a model with interactions, but for some reason, it plots asymmetrical CI. I would like to understand how the functions calculates CI, and thereby why they are asymmetrical. Below I paste an example of the plots I'm creating:

![image](https://user-images.githubusercontent.com/11415242/131905200-2cdbfa0f-0daa-4e8f-bc32-ced53294161f.png)

**Comment by strengejacke** [comment]
For percentages on the y-axis, an increase from 10% to 20% is the same as a decrease from 10% to 5% (double versus half, i.e. 2:1 vs. 1:2). If you use `log = TRUE`, you get symmetrical error bars, see examples here:
https://strengejacke.github.io/ggeffects/articles/introduction_plotmethod.html#control-y-axis-appearance-1
