### ISSUE TITLE
p-values of tab_model don't match summary output?

### ISSUE THREAD

**Issue by Ribbontree** [strengejacke/sjPlot#779]
Hey everyone =)
Sorry to bother but I can't wrap my head around why the rounded values given in tab_model do not exactly match the output of my summary function. I am running linear mixed effects models with lme4 and I get p-values with lmerTest. While estimates, standard errors and the like are exactly the same, as you can see here, for PBFW, for example, tab_model gives me .081 but the summary output gives me .082. I am using sjPlot version 2.8.9.

Right now, I am wondering whether tab_model calculates its own p-values instead of grapping those of the model object since that is the only explanation I could have so far. If that is the case though, I am wondering which p-values to "trust". Sorry if these are idiotic questions and I missed something obvious!

Thank you for your great package!
Cheers,
Lara

![Screenshot 2021-09-06 at 09-33-53 Male Cycle Awareness Mate Retention - Preregistered Analyses](https://user-images.githubusercontent.com/43512234/132178020-37adbaac-a7c4-4d39-adba-1635e16d573a.png)
![Screenshot 2021-09-06 at 09-33-18 Male Cycle Awareness Mate Retention - Preregistered Analyses](https://user-images.githubusercontent.com/43512234/132178028-360ecddf-abf9-4ba5-b73d-5cb98c5ae734.png)

**Comment by Ribbontree** [comment]
Finally found it that indeed, the methods for dfs are likely just different =)

**Comment by strengejacke** [comment]
Hi Lara, yes, it depends on the degrees of freedom, which affects the test-statistic, CI and p-values. You can use the `df.method` argument to change the method to compute degrees of freedom.

**Comment by Ribbontree** [comment]
Thank you for confirming that and for your advice! Hope you can enjoy the late summer =)
