### ISSUE TITLE
plot_model() uses conditional averages rather than full averages from MuMin model-averaged object

### ISSUE THREAD

**Issue by shan-e-s** [strengejacke/sjPlot#780]
plot_model() can generate plots using averaged models from MuMin but only using the conditional averages rather than the full averages, as far as i can tell.

sjPlot is the only package i have come across that can handle the model average objects from MuMin and has been great so far. Is it possible to choose between the full and conditional averages when plotting?

Related to the following issue: https://github.com/strengejacke/sjPlot/issues/692

**Comment by strengejacke** [comment]
I think this is not yet implemented in `plot_model()`. Meanwhile, you can try [`parameters::model_parameters()`](https://easystats.github.io/parameters/reference/model_parameters.averaging.html), and the related [`plot()`-method](https://easystats.github.io/see/articles/parameters.html) as a workaround.

**Comment by shan-e-s** [comment]
Great thanks, that workaround functions as needed.
