### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by montgomerie** [strengejacke/sjPlot#783]
I am getting the following error message as of June 2021 after years of no problem with sjPlot and sjstats

Error: package or namespace load failed for ‘sjPlot’:
 object ‘check_heterogeneity’ is not exported by 'namespace:parameters'

I really love these packages and would like to continue using them. I have tried uninstalling and reinstalling

**Comment by montgomerie** [comment]
On getting no response I completely deleted an reinstalled R and now sjPlot and sjstats work again

**Comment by strengejacke** [comment]
I think that was an issue with packages (dependencies) that were not up to date.
