### ISSUE TITLE
sjt.glmer() not working

### ISSUE THREAD

**Issue by davidcanarte** [strengejacke/sjPlot#784]
Hi Daniel. 
I have several hierarchical logistic regression models (glmer objects) that I want to summarize using sjt.glmer() function but R is giving me the error below. Moreover, I just updated sjlabelled, sjmisc, and sjPlot to their latest variobs (1.18, 2.8.7 and 2.8.9, respectively) just in case... What can I do? 

sjt.glmer(my_model, show.aic = TRUE, show.ci = TRUE,
           show.se = TRUE, p.numeric = FALSE)
Error in sjt.glmer(m5_instrumental_lat, show.aic = TRUE, show.ci = TRUE,  : 
  could not find function "sjt.glmer"

**Comment by strengejacke** [comment]
The function is now the generic `tab_model()`, see also https://strengejacke.github.io/sjPlot/articles/tab_mixed.html.
