### ISSUE TITLE
What happened to sjt.fa? 

### ISSUE THREAD

**Issue by DeFilippis** [strengejacke/sjPlot#799]
I'm trying to use `sjt.fa`, but I keep getting the error:

> could not find function "sjt.fa"

I couldn't find the function anywhere in the current codebase, either, but I found the reference to the function here: http://www.strengejacke.de/sjPlot/reference/sjt.fa.html.

Is this a deprecated function? What happened to it?

**Comment by strengejacke** [comment]
`sjt._*` functions have been renamed to `tab_*`: https://strengejacke.github.io/sjPlot/reference/tab_fa.html
