### ISSUE TITLE
How can I view summary statistics?

### ISSUE THREAD

**Issue by ehsong** [strengejacke/sjPlot#802]
I really like this package since I am using MS word, but I can't find a way to obtain a descriptive statistic table or a summary statistics table. Is there a way to print this?

**Comment by jrcalabrese** [comment]
Hi, would this work for your data? You can create descriptive statistics using `psych::describe()`, print it using `tab_df`, and export it as a `.doc`.

```{r}
library(tidyverse)
library(sjPlot)
library(psych)

data(airquality)

airquality %>%
  psych::describe() %>%
  tab_df(
    title = "here is my table",
    show.rownames = TRUE,
    file = "~/Documents/mytable.doc")
```

**Comment by ehsong** [comment]
@jrcalabrese Thank you! I ended up using gtsummary and flextable to export the table to .doc, but I will try the psych library as well.

**Comment by strengejacke** [comment]
You could also use [`sjmisc::descr()`](https://strengejacke.github.io/sjmisc/reference/descr.html) and set argument `out = "browser"`, and then copy/paste to word. Or you use [`datawizard::describe_distribution()`](https://easystats.github.io/datawizard/reference/describe_distribution.html) and then use `print_html()` to print to HTML.
