### ISSUE TITLE
sjt.lmer not available ?

### ISSUE THREAD

**Issue by laramarieke** [strengejacke/sjPlot#827]
When trying to use this function, I get these Error messages :

Error in sjt.lmer(lm.update4) : could not find function "sjt.lmer"

or

Error: 'sjt.lmer' is not an exported object from 'namespace:sjPlot'

I'm confused ; is the function not available anymore ?

Thank you,

Lara

**Comment by strengejacke** [comment]
Hi Lara, the function is replaced by [`tab_model()`](https://strengejacke.github.io/sjPlot/articles/tab_mixed.html).
