### ISSUE TITLE
question about tab_model

### ISSUE THREAD

**Issue by aexaa21** [strengejacke/sjPlot#830]
Hello, 

Many thanks for your help Daniel @strengejacke 

I have a question about tab_model in Sjplot. Is there anyway I could get the actual coefficient value printed in R, and not the Odds Ratio or the Incidence Rate Ratios?

Many thanks in advance for your help,

Aziz

**Comment by aexaa21** [comment]
Hi, sorry one more thing, 

if there is a function in tab_model that will get me the standard deviation of Random Effect variance, I would very much appreciate it.

**Comment by strengejacke** [comment]
Yes, use the argument `transform = NULL` to avoid transformation of estimates. Currently, sjPlot only returns random effects parameters as shown in these examples: https://strengejacke.github.io/sjPlot/articles/tab_mixed.html

If you want a result closer to the `summary()`, I suggest using the _parameters_ package (which is internally used by sjPlot), see examples for [`parameters::model_parameters()`](https://easystats.github.io/parameters/articles/model_parameters.html). There are also ways to format the table (see [here](https://easystats.github.io/parameters/articles/model_parameters_formatting.html) and [here](https://easystats.github.io/parameters/articles/model_parameters_print.html)), or if you want more flexibility, you may look at the [modelsummary](https://vincentarelbundock.github.io/modelsummary/) package, an alternative to _sjPlot_, which also relies on the parameters package (and thus should cover a similar range of models).

**Comment by aexaa21** [comment]
Many thanks @strengejacke  for your help and support. That was so helpful, and it is greatly appreciated.
