### ISSUE TITLE
Plotting FE model coefficients - standardized within or between units?

### ISSUE THREAD

**Issue by MariusBug** [strengejacke/sjPlot#838]
Hello,

I am using sjPlot to visualize the standardized coefficients of a two-way fixed effects model, i.e., I am using the options 

`pred.type = c("fe"), type = "std"`

However, I am unsure whether sjPlot considers within-unit (as desired for panel models) or between-unit variation for the standardized coefficients here, which is essential for the interpretation of the plot. 

So, which type of variation is used? And if it is _between_ units, is there a way to switch it to within?

Thanks!

**Comment by strengejacke** [comment]
It's a "simple" standardization of coefficients that is carried out here, see https://easystats.github.io/parameters/articles/standardize_parameters_effsize.html

You can demean your data using [`datawizard::demean()`](https://easystats.github.io/datawizard/reference/demean.html) before you fit the model. See also [this vignette](https://easystats.github.io/parameters/articles/demean.html).
