### ISSUE TITLE
tab_model

### ISSUE THREAD

**Issue by ringeck56** [strengejacke/sjPlot#844]
I am getting the following message:

Error: 'is_empty_object' is not an exported object from 'namespace:insight'

when I apply the tab_model function to any model name, such as for example:

mod2 <- lm(Petal.Length ~ Species + Petal.Width, data=iris) 
sjPlot::tab_model(mod2, file = "~/Desktop/model2.doc")

What does that error message mean?

**Comment by strengejacke** [comment]
Have you updated all your packages?

**Comment by Elen91** [comment]
I have the same issue. I've updated all my packages, but the problem still remains.

**Comment by strengejacke** [comment]
See https://github.com/strengejacke/sjPlot/issues/769#issuecomment-1491384638
