### ISSUE TITLE
Not able to load sjPlot

### ISSUE THREAD

**Issue by peterhedmark** [strengejacke/sjPlot#853]
For some reason, I cannot load and use sjPlot. When I try to install the library before making a plot of my model predictions I get the following message: "> library(sjPlot)
Error in library(sjPlot) : there is no package called ‘sjPlot’".

**Comment by strengejacke** [comment]
Have you already installed that package?

**Comment by peterhedmark** [comment]
I got it to work, Thanks for responding!

**Comment by strengejacke** [comment]
Great!
