### ISSUE TITLE
Error: object ‘standard_error_robust’ is not exported by 'namespace:parameters'

### ISSUE THREAD

**Issue by andreoulios** [strengejacke/sjPlot#866]
Can not import sjPlot after installing easystats.
Conflict with package parameters.

Removed and reinstalled both packages, have updated to the latest using easystats::install_latest and the problem remains.

sjPlot was first installed in system library from c2d4u repo. Installing from rstudio stucks with the same error.

**Comment by strengejacke** [comment]
I think you need the latest versions from CRAN to successfully install all packages

**Comment by yuryzablotski** [comment]
Had the same issue, updating everything solved the problem! Thanks, Daniel!

**Comment by andreoulios** [comment]
> 

I tried installing first easystats then sjplot and loading with the same order... the error remains

i tried loading first sjplot (user library) the same error happens.

i tried loading first sjplot (system library) then easystats  and this error happens:

`Error: package or namespace load failed for ‘easystats’:
 .onAttach failed in attachNamespace() for 'easystats', details:
  call: value[[3L]](cond)
  error: Package ‘insight’ version 0.18.6 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘insight’ is imported by ‘effectsize’, ‘datawizard’, ‘sjPlot’, ‘performance’, ‘sjlabelled’, ‘sjmisc’, ‘bayestestR’, ‘sjstats’, ‘parameters’ so cannot be unloaded`


of course i did easystats::install_latest

I dont know what else to do if you can point me in the right direction

**Comment by strengejacke** [comment]
I would try:

- Restart R (or RStudio, or whatever you're using)
- If RStudio, also press `Shift + F10`
- Run `easystats::install_latest()`
- Run `install.packages(c("sjstats", "sjPlot"))`

That _should_ in theory work.

**Comment by andreoulios** [comment]
Thank you very much this worked :D
