### ISSUE TITLE
Problem with  object ‘standard_error_robust’ is not exported by 'namespace:parameters'

### ISSUE THREAD

**Issue by TillMK** [strengejacke/sjPlot#886]
Dear all, getting  object ‘standard_error_robust’ is not exported by 'namespace:parameters'. Even if reinstalling sjPlot and parameters. Cant use or even call sjPlot anymore. Is this issue known to anyone? Same issue with earlier versions
Also no success with detaching. Please help, absolutely need sjPlot for current scripts.

Cheers
TK

**Comment by strengejacke** [comment]
Please install package _easystats_, if you haven't done yet:

```r
install.packages("easystats")
```

Then run

```r
easystats::install_latest()`
```

Then it should work. If not, some of the packages _sjPlot_, _sjmisc_ or _sjstats_ are not up to date.

**Comment by TillMK** [comment]
Thank you, reinstalling them all together after reinstalling easystats did it for me
install.packages("easystats")
easystats::install_latest()
install.packages(c("sjPlot", "sjmisc" , "sjstats"))

**Comment by strengejacke** [comment]
great, good to know it works now!
