### ISSUE TITLE
sjPlot showing extra regression line

### ISSUE THREAD

**Issue by aaldoh** [strengejacke/sjPlot#908]
Hello! I'm trying to visualise an interaction using terciles or quartiles and whenever I try to do so, I get an extra regression line. For example:

test_mod <- lm(hp ~ drat*wt, mtcars)
plot_model(test_mod,type = "eff", terms = c("drat","wt [terciles]"))

![image](https://github.com/strengejacke/sjPlot/assets/55540402/44c7ab73-15d1-43e3-b004-1ea5b15cc0b5)

Any idea how to make them 3? I also tried with quart instead of terciles and I ended up with 5 plotted lines.

**Comment by aaldoh** [comment]
Ah brilliant! Thank you. I now see that there are options excluding the minimum and maximum. I couldn't see it in the documentation for plot_model "mdrt.values" column but the linked page clears it all up.

**Comment by strengejacke** [comment]
Yes, I mainly work on the _ggeffects_ package, and _sjPlot_ just wraps `ggeffects::ggpredict()`, so I somewhat neglect updating _sjPlot_ a bit ;-)
