### ISSUE TITLE
sjt.pca() function

### ISSUE THREAD

**Issue by varelasebastian** [strengejacke/sjPlot#922]
Hello! thanks for this excellent package.
When I try to use the sjt.pca() function it says _could not find function "sjt.pca"_
Is the function avaible currently? 
I used the 2.8.15 version of sjPlot.

**Comment by strengejacke** [comment]
That function was renamed. It's `tab_pca()`. All `sjt.` prefixes were renamed into `tab_`, and all `sjp.` prefixes into `plot_`.

See reference list here: https://strengejacke.github.io/sjPlot/reference/index.html
