### ISSUE TITLE
support for a quantile regression

### ISSUE THREAD

**Issue by yuryzablotski** [strengejacke/sjPlot#925]
**Describe the solution you'd like**
I would like to be able to plot predictions of quantile regression similarly, like it's currently possible for OLS / GLM. A single quantile would be great, all quantiles at once would be terrific! 

It works with only plot_model(model), but doesn't work with plot_model(model, type = "eff", terms = "predictor")

By the way, the emmeans guys (almost, some bugs are still there) made it work with quantile regression and I can use the emmip for plotting. But I prefer your package.

**How could we do it?**
Should be very similar to OLS with the use of "tau" argument, where tau is the quantile. A list of taus is of couarse a much better choice, a compared to a single tau.

**Code example**

library(ISLR) 
library(quantreg) 

lr   <- lm(wage ~ jobclass + age, Wage)
qr10 <- rq(wage ~ jobclass + age, Wage, tau = 0.1)
qr50 <- rq(wage ~ jobclass + age, Wage, tau = 0.5)
qr90 <- rq(wage ~ jobclass + age, Wage, tau = 0.9)

qr_all <- rq(wage ~ jobclass + age, Wage, 
             tau  = seq(.05, .95, by = 0.05))

summary(qr_all) %>% plot()

**Comment by strengejacke** [comment]
_sjPlot_ internally uses the [ggeffects-package](https://strengejacke.github.io/ggeffects). I suggest using that package directly, which is as easy as sjPlot, but more flexible, if desired.


``` r
library(ISLR)
library(quantreg)
#> Loading required package: SparseM
library(ggeffects)

qr_all <- rq(wage ~ jobclass + age, Wage, tau = seq(0.1, 0.9, by = 0.1))
#> Warning in rq.fit.br(x, y, tau = tau, ...): Solution may be nonunique

predict_response(qr_all, terms = "jobclass")
#> # Predicted values of wage
#> 
#> tau: 0.1
#> 
#> jobclass       | Predicted |         95% CI
#> -------------------------------------------
#> 1. Industrial  |     68.02 |  66.35,  69.69
#> 2. Information |     75.18 |  72.30,  78.06
#> 
#> tau: 0.2
#> 
#> jobclass       | Predicted |         95% CI
#> -------------------------------------------
#> 1. Industrial  |     77.87 |  76.35,  79.40
#> 2. Information |     86.74 |  84.79,  88.69
#> 
#> tau: 0.3
#> 
#> jobclass       | Predicted |         95% CI
#> -------------------------------------------
#> 1. Industrial  |     85.38 |  84.01,  86.76
#> 2. Information |     96.21 |  93.83,  98.58
#> 
#> tau: 0.4
#> 
#> jobclass       | Predicted |         95% CI
#> -------------------------------------------
#> 1. Industrial  |     92.10 |  90.56,  93.64
#> 2. Information |    104.58 | 102.77, 106.40
#> 
#> tau: 0.5
#> 
#> jobclass       | Predicted |         95% CI
#> -------------------------------------------
#> 1. Industrial  |     99.06 |  97.50, 100.61
#> 2. Information |    111.72 | 109.69, 113.75
#> 
#> tau: 0.6
#> 
#> jobclass       | Predicted |         95% CI
#> -------------------------------------------
#> 1. Industrial  |    106.82 | 104.71, 108.92
#> 2. Information |    119.82 | 117.41, 122.22
#> 
#> tau: 0.7
#> 
#> jobclass       | Predicted |         95% CI
#> -------------------------------------------
#> 1. Industrial  |    115.49 | 113.30, 117.67
#> 2. Information |    130.04 | 126.60, 133.47
#> 
#> tau: 0.8
#> 
#> jobclass       | Predicted |         95% CI
#> -------------------------------------------
#> 1. Industrial  |    126.37 | 122.78, 129.96
#> 2. Information |    143.81 | 137.45, 150.18
#> 
#> tau: 0.9
#> 
#> jobclass       | Predicted |         95% CI
#> -------------------------------------------
#> 1. Industrial  |    143.63 | 135.46, 151.80
#> 2. Information |    168.44 | 144.07, 192.82
#> 
#> Adjusted for:
#> * age = 42.00
predict_response(qr_all, terms = "jobclass") |> plot()
```

![](https://i.imgur.com/NNkXGg9.png)

<sup>Created on 2024-11-25 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by yuryzablotski** [comment]
thanks a lot Daniel! that worked well, not with too many taus, but with 10 it worked perfectly. 10 taus are more then enough!
sorry for late replay, your email got a bit lost in my post-box. kind regards from Munich!
