### ISSUE TITLE
I installed the sjPlot package successfully but when I opened it with library I got that it called the estimability package

### ISSUE THREAD

**Issue by leo23ps** [strengejacke/sjPlot#936]
Error: package or namespace load failed for ‘sjPlot’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘estimability’
In addition: Warning message:
package ‘sjPlot’ was built under R version 4.2.3

How could I solve this please

**Comment by strengejacke** [comment]
Which R version are you using? Package _estimability_ requires R 4.3

**Comment by leo23ps** [comment]
> ¿Qué versión de R estás usando? _La estimación_ del paquete requiere R 4.3
Thank you very much, it worked, but I got another query, I want to use the sjt.pca() function but it seems to me that it is in the sjPlot 2.4.1.9 version. I want to make a pca, how can I use this function? I turn to your support very gratefully

**Comment by strengejacke** [comment]
Some of the functions have been improved and re-implemented in other packages, mainly the new _easystats_ project, where I'm also involved. The relevant functions are:

- https://easystats.github.io/parameters/reference/principal_components.html
- https://easystats.github.io/parameters/reference/n_factors.html
- https://easystats.github.io/performance/reference/check_itemscale.html

`plot()` methods are available, too:
- https://easystats.github.io/see/articles/parameters.html#principal-component-analysis

**Comment by strengejacke** [comment]
In sjPlot, you have:

- https://strengejacke.github.io/sjPlot/reference/tab_itemscale.html
- https://strengejacke.github.io/sjPlot/reference/tab_pca.html

**Comment by leo23ps** [comment]
thank you so much
