### ISSUE TITLE
Problem with sjPlot

### ISSUE THREAD

**Issue by peterhedmark** [strengejacke/sjPlot#937]
I keep getting this message when I try to use sjPlot:
> library(sjPlot)
Error: package or namespace load failed for ‘sjPlot’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘xfun’ 0.42 is being loaded, but >= 0.43 is required
In addition: Warning message:
package ‘sjPlot’ was built under R version 4.2.3

**Comment by strengejacke** [comment]
Looks like you need to update the _xfun_ package?

**Comment by peterhedmark** [comment]
Excellent! It works. Thanks so much.
