### ISSUE TITLE
tab_model displaying incorrect estimates with glm() objects 

### ISSUE THREAD

**Issue by dpmoriarity** [strengejacke/sjPlot#944]
the tab_model function is working fine for lm() and lmer() objects, but generalized models seem to be bugged

head(iris)

test<-glm(Sepal.Length~Petal.Length, family = Gamma(link="log"), 
                                 data = iris)

summary(test) 
tab_model(test) #statistcs don't match summary output

**Comment by strengejacke** [comment]
`tab_model()` exponentiates coefficients by default, for easier interpretation.

``` r
test<-glm(Sepal.Length~Petal.Length, family = Gamma(link="log"), data = iris)

summary(test)
#> 
#> Call:
#> glm(formula = Sepal.Length ~ Petal.Length, family = Gamma(link = "log"), 
#>     data = iris)
#> 
#> Coefficients:
#>              Estimate Std. Error t value Pr(>|t|)    
#> (Intercept)  1.493970   0.013011  114.82   <2e-16 ***
#> Petal.Length 0.070164   0.003136   22.38   <2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> (Dispersion parameter for Gamma family taken to be 0.00456538)
#> 
#>     Null deviance: 2.97256  on 149  degrees of freedom
#> Residual deviance: 0.67623  on 148  degrees of freedom
#> AIC: 148.13
#> 
#> Number of Fisher Scoring iterations: 3

parameters::model_parameters(test)
#> Parameter    | Log-Prevalence |       SE |       95% CI | t(148) |      p
#> -------------------------------------------------------------------------
#> (Intercept)  |           1.49 |     0.01 | [1.47, 1.52] | 114.82 | < .001
#> Petal Length |           0.07 | 3.14e-03 | [0.06, 0.08] |  22.38 | < .001
#> 
#> Uncertainty intervals (profile-likelihood) and p-values (two-tailed)
#>   computed using a Wald t-distribution approximation.
#> 
#> The model has a log- or logit-link. Consider using `exponentiate =
#>   TRUE` to interpret coefficients as ratios.

parameters::model_parameters(test, exponentiate = TRUE)
#> Parameter    | Prevalence Ratio |       SE |       95% CI | t(148) |      p
#> ---------------------------------------------------------------------------
#> (Intercept)  |             4.45 |     0.06 | [4.34, 4.57] | 114.82 | < .001
#> Petal Length |             1.07 | 3.36e-03 | [1.07, 1.08] |  22.38 | < .001
#> 
#> Uncertainty intervals (profile-likelihood) and p-values (two-tailed)
#>   computed using a Wald t-distribution approximation.
```

<sup>Created on 2024-07-09 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by dpmoriarity** [comment]
this makes a lot of sense, thanks for pointing this out, missed the incorporation of the parameters package here.

Just in case reviewers ask to see both the coefficient and the ratio, am I correct there is no way to turn off the exponentiation in the tab_model command?

**Comment by dpmoriarity** [comment]
or, alternatively, to specify other commands (e.g., ci_method = "satterthwaite") from the parameters package within the tab_model command to ensure compatibility with lmer() models?

**Comment by strengejacke** [comment]
You can use `transform = NULL`. There are plenty of options in the function, which makes it difficult to keep an overview. You can use `df.method` to use, e.g., Satterthwaite approximation.

**Comment by dpmoriarity** [comment]
thank you so much! sorry I was unable to find these before, mostly self-taught in R and trying to branch out is pushing my fluency a bit.

I hope you have a great rest of your week, thanks for your work with all these amazing tools

**Comment by dpmoriarity** [comment]
Hello again,

Sorry to bother but I found a couple of models, specifically those using heteroscedasticity-corrected SEs, and the p-values are slightly off compared to the coeftest output. Is there another modification I can't find that I need to add to make the tables compatible with the output? Also, if there is a better place to put these trouble-shooting inquiries than this github page, please let me know, I'm just getting used to the github ecosystem.

head(iris)
test<-glm(Sepal.Length~Petal.Length+Species+Sepal.Width+Petal.Width, family = Gamma(link="log"),
          data = iris)

coeftest(test, vcov = vcovHC(test)) 

tab_model(test,
          df.method="wald",transform = NULL,vcov.fun = vcovHC(test)) #p-values don't match coeftest summary output

**Comment by dpmoriarity** [comment]
(one thing I forgot to note, when I rerun the same models as a lm() object this discrepancy no-longer occurs)

head(iris)
test2<-lm(Sepal.Length~Petal.Length+Species+Sepal.Width+Petal.Width,
          data = iris)

coeftest(test2, vcov = vcovHC(test2)) #uniformity is good (similar to issue of normality in lm models), heteroscedasticity seems somewhat better but not great, posterior predictive check improved

tab_model(test2,
          df.method="wald",transform = NULL,vcov.fun = vcovHC(test2)) #statistcs don't match summary output

model_parameters(test2, vcov = vcovHC(test2))

**Comment by dpmoriarity** [comment]
realizing now that these don't actually matter now that I switched to gamma regression, since homogeneity of variance isn't an assumption of gamma regression, so I'll close this as the rest of the models are squared away- have a great day!
