### ISSUE TITLE
plot_model not changing confidence intervals with ci.lvl function

### ISSUE THREAD

**Issue by gonzalofranetovic** [strengejacke/sjPlot#947]
Hi! 
I just report a problem with the ci.lvl option of plot_model. It does not change the confidence intervals of some plots. I would appreciate help. Thank you. 

#Example

```
library(sjPlot)

#Model
M1 = lm(mpg  ~ cyl*disp, data = mtcars)

#Working
plot_model(M1, ci.lvl = 0.95) 
plot_model(M1, ci.lvl = 0.90) 

#Not working
plot_model(M1, type = "pred", ci.lvl = 0.95, terms = "disp") 
plot_model(M1, type = "pred", ci.lvl = 0.90, terms = "disp") 

#Not working
plot_model(M1, type = "int", ci.lvl = 0.95) 
plot_model(M1, type = "int", ci.lvl = 0.90) 
```

**Comment by strengejacke** [comment]
Thanks!
This is related to renaming arguments in the [ggeffects-package](https://strengejacke.github.io/ggeffects), which is internally used by *sjPlot*. As a workaround, I suggest using the *ggeffects* package directly for predictions and effects plots:

``` r
library(ggeffects)
M1 = lm(mpg  ~ cyl, data = mtcars)
predict_response(M1, terms = "cyl", ci_level = 0.55) |> plot()
```

![](https://i.imgur.com/VTm3zZt.png)

``` r
predict_response(M1, terms = "cyl", ci_level = 0.90) |> plot()
```

![](https://i.imgur.com/K6lSDaG.png)

<sup>Created on 2024-08-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
