### ISSUE TITLE
Mixed effect hurdle model fitted with glmmTMB not working with plot_model

### ISSUE THREAD

**Issue by fmcarrier** [strengejacke/sjPlot#957]
Hi,

### Hurdle

I estimated a model with glmmTMB using the family "truncated_nbinom2" and a rcs term (from RMS package).

_mod_hurdle_rcs <- glmmTMB(nbr_bp_periop ~ rcs(MELD_na,3) + (1 | site), data=data_mod, ziformula=~., family=truncated_nbinom2)_

I wanted to create a plot of the effetc of "MELD_na" using the following command: 

_plot_model(mod_hurdle_rcs, type="eff", terms="MELD_na [all]")._ 

However, I received the following message:

> **Can't compute adjusted predictions, `effects::Effect()` returned an error.**

### Zero-inflated

When using a zero-inflated model as following:

_mod_zi_rcs <- glmmTMB(nbr_bp_periop ~ rcs(MELD_na,3) + (1 | site), data=data_mod, ziformula=~., family=nbinom2)_

and using plot_model:

_plot_model(mod_zi_rcs, type="eff", terms="MELD_na [all]")_

I receive the following message:

> **Error in if ((model_info$is_zero_inflated || model_info$is_hurdle) &&  : 
>   missing value where TRUE/FALSE needed**

**The same happens even without a rcs term.** 

### "pred" versus "eff"

When using "pred" instead of "eff", it works. 

Is it a bug or `effects::Effect()` does not support zi and hurdle models for the "'effect" estimation ?

Thank you.

**Comment by fmcarrier** [comment]
A model as simple as this one also returns the same error.

mod_test <- glmmTMB(nbr_bp_periop ~ MELD_na + (1 | site), data=data_mod, ziformula=~., family=truncated_nbinom2)

plot_model(mod_test, type="eff", terms="MELD_na")

**Comment by strengejacke** [comment]
Do you have a reproducible example? Else, try `effects::Effect()` with your model and report it it works.

**Comment by fmcarrier** [comment]
Here is a reproductible example that fits the distribution of my variables. 

library(glmmTMB)

#Data frame
set.seed(12345)
x <- round(rnorm(800, mean=20, sd=10.5),0)
x[x<6] <- 6
x[x>40] <- 40
set.seed(12345)
y <- rnbinom(800, mu=10.6, size=1.4)
set.seed(12345)
y[floor(runif(n=140, min=1, max=800))] <- 0
site <- c(rep("A",25), rep("B",50), rep("C", 75), rep("D",100), rep("E",150), rep("F",200), rep("G",200))
example <- data.frame(cbind(x,y,site))
example$x <- as.integer(example$x)
example$y <- as.integer(example$y)

mod_test <- glmmTMB(y ~ x + (1 | site), data=example, ziformula=~., family=truncated_nbinom2)
plot_model(mod_test, type="eff", terms="x")

> Can't compute adjusted predictions, `effects::Effect()` returned an error.
> 
> Reason: non-numeric argument to mathematical function
> You may try `ggpredict()` or `ggemmeans()`.
> 
> NULL

I am not used to use the effects package, but I tried this example command and it did not work:

effects::Effect(mod=mod_test, term="x", focal.predictors="x")

> Error in log(mu) : non-numeric argument to mathematical function
> 
> In addition: Warning message:
> In Effect.glmmTMB(mod = mod_test, term = "x", focal.predictors = "x") :
> overriding variance function for effects/dev.resids: computed variances may be incorrect

**Comment by fmcarrier** [comment]
I just posted one.

François

De : Daniel ***@***.***>
Date : lundi, 2 décembre 2024 à 09:11
À : strengejacke/sjPlot ***@***.***>
Cc : Francois Carrier ***@***.***>, Author ***@***.***>
Objet : Re: [strengejacke/sjPlot] Mixed effect hurdle model fitted with glmmTMB not working with plot_model (Issue #957)

Do you have a reproducible example? Else, try effects::Effect() with your model and report it it works.

**Comment by strengejacke** [comment]
It's indeed a bug in the `glmmTMB.Effect()` method, I opened an issue at their repo.

**Comment by strengejacke** [comment]
In general, I suggest using the [*ggeffects* package](https://strengejacke.github.io/ggeffects), which is more flexible and as easy to use. Furthermore, you may switch to other prediction-types that rely on `predict()` or the *emmeans* package, see example below:

``` r
library(glmmTMB)

#Data frame
set.seed(12345)
x <- round(rnorm(800, mean=20, sd=10.5),0)
x[x<6] <- 6
x[x>40] <- 40
set.seed(12345)
y <- rnbinom(800, mu=10.6, size=1.4)
set.seed(12345)
y[floor(runif(n=140, min=1, max=800))] <- 0
site <- c(rep("A",25), rep("B",50), rep("C", 75), rep("D",100), rep("E",150), rep("F",200), rep("G",200))
example <- data.frame(cbind(x,y,site))
example$x <- as.integer(example$x)
example$y <- as.integer(example$y)

mod_test <- glmmTMB(y ~ x + (1 | site), data=example, ziformula=~., family=truncated_nbinom2)

ggeffects::predict_response(mod_test, "x")
#> You are calculating adjusted predictions on the population-level (i.e.
#>   `type = "fixed"`) for a *generalized* linear mixed model.
#>   This may produce biased estimates due to Jensen's inequality. Consider
#>   setting `bias_correction = TRUE` to correct for this bias.
#>   See also the documentation of the `bias_correction` argument.
#> # Predicted (conditional) counts of y
#> 
#>  x | Predicted |      95% CI
#> ----------------------------
#>  6 |     10.59 | 9.26, 12.12
#> 10 |     10.57 | 9.47, 11.81
#> 14 |     10.56 | 9.65, 11.55
#> 18 |     10.54 | 9.77, 11.37
#> 24 |     10.51 | 9.74, 11.35
#> 28 |     10.49 | 9.58, 11.49
#> 32 |     10.47 | 9.37, 11.71
#> 40 |     10.44 | 8.87, 12.28
#> 
#> Adjusted for:
#> * site = NA (population-level)
#> 
#> Not all rows are shown in the output. Use `print(..., n = Inf)` to show
#>   all rows.
ggeffects::predict_response(mod_test, "x", margin = "marginalmeans")
#> # Predicted (conditional) counts of y
#> 
#>  x | Predicted |      95% CI
#> ----------------------------
#>  6 |     10.59 | 9.26, 12.12
#> 10 |     10.57 | 9.47, 11.81
#> 14 |     10.56 | 9.65, 11.55
#> 18 |     10.54 | 9.77, 11.37
#> 24 |     10.51 | 9.74, 11.35
#> 28 |     10.49 | 9.58, 11.49
#> 32 |     10.47 | 9.37, 11.71
#> 40 |     10.44 | 8.87, 12.28
#> 
#> Not all rows are shown in the output. Use `print(..., n = Inf)` to show
#>   all rows.
```

<sup>Created on 2024-12-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Oh, and plotting:

``` r
pr <- ggeffects::predict_response(mod_test, "x")
plot(pr)
```

![](https://i.imgur.com/Ac9lJox.png)

<sup>Created on 2024-12-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by fmcarrier** [comment]
When 'plot_model' calls ggeffects with the argument "eff", does it call it with the argument margin='marginalmeans' or not ?

I cannot find this information in the ggeffects vignette.

Thanks

**Comment by strengejacke** [comment]
- "eff" calls `ggeffect()` (no equivalent in `predict_response()`)
- "pred" calls `ggpredict()` (equivalent to `predict_response()`)
- "emm" calls `ggemmeans()` (equivalent to `predict_response(margin = "marginalmeans")`)

**Comment by fmcarrier** [comment]
Thank you very much.

**Comment by fmcarrier** [comment]
However, when I use ggeffect(mod_test, terms="x"), I still have the error.

Since “eff” has no equivalent in predict_response, the only solution that is similar to “eff” is the use of “marginalmeans” ?

I used the “eff” argument for other models, so I wanted to be consistent on the way I computed the means of non-focal predictors when marginalizing.

François

De : Daniel ***@***.***>
Date : lundi, 2 décembre 2024 à 10:31
À : strengejacke/sjPlot ***@***.***>
Cc : Francois Carrier ***@***.***>, Author ***@***.***>
Objet : Re: [strengejacke/sjPlot] Mixed effect hurdle model fitted with glmmTMB not working with plot_model (Issue #957)

  *   "eff" calls ggeffect() (no equivalent in predict_response())
  *   "pred" calls ggpredict() (equivalent to predict_response())
  *   "emm" calls ggemmeans() (equivalent to predict_response(margin = "marginalmeans"))

**Comment by fmcarrier** [comment]
Since “eff” has no equivalent in predict_response, the only solution that is similar to “eff” is the use of “marginalmeans” ?

No solution to reproduce the output obtained with the "eff" argument ?

**Comment by strengejacke** [comment]
- `plot_model(type = "eff")` calls `ggeffect()`, which internally calls `effects::Effect()`
- `plot_model(type = "pred")` calls `ggpredict()`, which internally calls `stats::predict()`
- `plot_model(type = "emm")` calls `ggemmeans()`, which internally calls `emmeans::emmeans()`

That's why `ggeffect()` doesn't work, because it relies on the (failing) `Effect()` method.

Since I think it's confusing to approach predictions (and their different results) via _function names_, I thought it is clearer to think about it as "how are non-focal terms held constant?". Thus, there is a `predict_response()` function that internally calls one of the above three methods, based on the _margin_ argument (read more about it [here](https://strengejacke.github.io/ggeffects/)).

The question is not: I want predictions, which package to use? But rather: I want predictions, which (research) questions do I want to answer? And this depends on how you marginalize over non-focal terms, thus the `margin` argument. Technically, `predict()`, `emmeans()` or `Effect()` (and `avg_predictions()` from a fourth package) all marginalize differently over non-focal terms, leading to different predictions, resulting in different interpretations. But I think it's less intuitive to think in terms of "packages", but rather in terms of "which question do I want to answer?"

But emmeans and Effect usually return same results, thus you can safely switch to `ggemmeans()` (or: `predict_response(margin = "marginalmeans")`.

**Comment by fmcarrier** [comment]
Thank you very much for this detailed and complete answer. 

I agree that the package is not important but rather what we want to do. I expressed myself by "package terms" to be consistent with the bug I observed and the previous discussion.

Let's say that the "effects" vignette is not as clear as the "predict_response" vignette about how non-focal terms are averaged for prediction in 'Effect()'. My confusion came from the fact that I cannot clearly understand what the difference is between 'effect()' and 'emmeans()' and 'avg_comparison()' on the way non-focal terms are held constant. 

François

**Comment by strengejacke** [comment]
If you look here at the docs for `margin`:

https://strengejacke.github.io/ggeffects/#adjusted-predictions-at-marginalizing-over-non-focal-predictors

You see what `predict()`, `emmeans()` and `avg_predictions()` (from package _marginaleffects_) do. If you really want to dig into technical details, see this vignette: https://strengejacke.github.io/ggeffects/articles/technical_differencepredictemmeans.html

**Comment by strengejacke** [comment]
The _effects_ package and the _emmeans_ package seem to handle non-focal terms in the same way, that's why you should get identical results.

**Comment by fmcarrier** [comment]
Thank you very much for your time and help.

I have been reading the first vignette for some days now to get my head around. It is the most well-written one. It is less clear to me how it fits with the way ‘marginaleffects’ handle non-focal terms when it estimates contrasts.

I am estimating contrasts with marginaleffects and want to produce graph for non-linear terms. I try to be consistent on what I report and how non-focal terms are handled in either process.

Based on the second vignette, my understanding is that 'avg_prediction()' and 'avg_comparison()' from 'marginaleffects' use the same process as the one implemented in 'margin="empirical"' in 'predict_response' based on counterfactual theory and simulation.  

Thank you very much.

**Comment by strengejacke** [comment]
"marginaleffects" has no unique handling of non-focal terms, it can mimic predict(), emmeans() or it can return counterfactual predictions (this is what `ggaverage()` does). Often, it is not important for contrasts or pairwise comparisons, because the _point estimate_ of predictions differs, but not the difference between predictions (which is used for contrasts and comparisons).

You can easily use `test_predictions()` for that, see https://strengejacke.github.io/ggeffects/articles/introduction_comparisons_1.html.

Again, here I described more technically how _contrasts_ and _comparisons_ differ between packages: https://strengejacke.github.io/ggeffects/articles/introduction_comparisons_5.html

**Comment by fmcarrier** [comment]
I get it. Thank you very much
