### ISSUE TITLE
t-values in sjt.lm

### ISSUE THREAD

**Issue by sjPlot** [strengejacke/sjPlot#98]
See https://github.com/sjPlot/sjmisc/issues/17

**Comment by methodds** [comment]
Would be nice. You can access them by calling ``coef()`` on a ``lm summary``:

```
data(efc)
fit1 <- lm(neg_c_7 ~ c160age, data = efc)
coef(summary(fit1))[, "t value"] 

(Intercept)     c160age 
  18.614510    3.866733 
```
It might be necessary to also include this in ``robust()`` though, such that this option works properly for ``sjt.lm()```.

**Comment by sjPlot** [comment]
accessing the t-value is not the problem - re-writing the code to add another optional column in an HTML-table is. ;-)

**Comment by strengejacke** [comment]
Implemented in the current draft of `tab_model()`.
